[quote.epigraph, , Prov. 4:18-19]
____
But the path of the just is like the shining sun,
that shines ever brighter unto the perfect day.
The way of the wicked is like darkness;
they do not know what makes them stumble.
____

== Journal of John Griffith

It has been much upon my mind to write something by way of a journal of my life, travels,
and experiences in the gracious and merciful dealings of the
Lord with me through the course of my pilgrimage in this world.
And as the Lord shall be pleased to open my understanding,
it may also afford profitable way-marks to some weary
travelers who are seeking a city that has foundations,
whose builder and maker is God.

I was born on the 21st day of the fifth month, 1713, in Radnorshire, South Wales,
being favored with parents who had the substance of true religion in themselves,
and were conscientiously concerned to train up their children in the fear of God.
I was favored with the heart-melting visitations of God`'s love,
I think when about seven or eight years old,
and frequently experienced His name to be in the assemblies of His
people "`as precious ointment poured forth,`" whereby my desires were
greatly raised to attend meetings for divine worship.
For although, like Samuel of old, I was as yet unacquainted with the voice of God,
and did not clearly understand the Source of that precious consolation which I felt,
yet I well remember something working powerfully in my tender, weak mind,
by way of opposition to that sweet heavenly enjoyment, in order to deprive me of it.
This opposing power would often present to my view some transitory delight,
and fill my mind with vain, unprofitable, and sometimes wicked and blasphemous thoughts,
which were a very great affliction to me.
Then he who was a liar from the beginning would suggest
that the only way to get over such uneasiness,
was to give way to these thoughts,
and to be utterly regardless of what passed through my mind.
I found the flesh wanted ease, and to save itself,
willingly joined with the temptations of Satan.
In this way, I obtained a kind of present ease,
but it was by such gratifications as tended to heap up wrath for the day of wrath,
and the revelation of the righteous judgments of God.

Notwithstanding the false ease contrived by my soul`'s enemy,
as I grew up I did often sensibly feel this peace disturbed and broken by a
sense of God`'s wrath revealed from heaven against my unrighteousness,
and I was often in great bitterness of spirit when the
chastening of the Lord was upon me for sin.
At such times I would enter into covenant with the Lord, promising amendment of my ways;
but as these promises were made very much in my own will, they were soon broken,
and this increased the weight of my horror and distress.
But the Lord, in infinite mercy, was pleased to find me out,
and to plead with me as in the valley of decision.

In writing this,
my mind is greatly moved with pity and compassion towards inconsiderate youth who,
for the sake of trifling vanities, disregard the Lord`'s mercy to them,
and so become subjected to great distress of mind.
The case is still worse,
when by repeated disobedience and rebellion against God`'s unmerited grace,
they have almost stifled His divine witness in their own hearts, and go on with impunity.
Alas, an awakening time will come, sooner or later,
which must strike all such hearts with horror and amazement.
May it be in mercy!

My godly parents were very careful to prevent my falling into evil company.
Nevertheless, without their knowledge I frequently found it,
and joined in those vanities which are incident to youth,
not falling a bit behind any of my companions in folly.
Yet in the cool of the day, I would often feel sharply reproved; yes,
sometimes even in the midst of my vanity.
But, by this time I wanted to silence the pure witness against evil in my heart.
Oh, I have often since then, with deep reverence,
thankfully admired the long-suffering of a gracious God,
in that He did not cut me off when I willfully resisted the reproofs
of His instruction (which are the way to life) because I wanted to
live in the vain pleasures of this perishing world.

When I was about thirteen years old, a Friend who had lived some time in Pennsylvania,
being in our area, and frequently at our house,
gave a very pleasing account of that country.
And because I already had two uncles and an aunt there,
some of whom had before written to encourage our moving to Pennsylvania,
my inclination to go grew very strong.
My parents (especially my father) were at first very much against the idea,
but I became immovably bent upon going.
So when my parents saw this, and that my elder brother also inclined to go with me,
they at length consented, and procured a certificate of our being in unity with Friends.
There was another family of Friends also going over in the same ship,
and we were given over to their care.
So in the year 1726, we embarked at Milford-haven,
on board the Constantine Galley of Bristol,
and had a passage of about eight weeks from land to land.
We were about eighty or ninety passengers, generally healthy,
amongst whom three children were born while on board, and none were removed by death.
My uncle, John Morgan, who lived about twelve miles from the city of Philadelphia,
hearing of our arrival, came on board and conducted us to his house,
where I continued for some time.
And my brother, being a weaver, settled at my aunt Mary Pennel`'s and followed his trade.

Removing from under my parents`' watchful care furnished me with great opportunities
to gratify a vain mind in the foolish amusements of a transitory world,
towards which I had too great an inclination.
But I have this to say,
in order that parents may be encouraged to exert their godly endeavors for the
preservation of their children--that I do steadfastly believe that the religious
care of my parents over me in my youth impressed so great an awe upon my mind,
that (through the blessing of divine providence) it was
a great means of my preservation from gross evils,
despite having many opportunities of being swallowed up by them after I left home.
I hope always to retain a grateful and thankful remembrance of those
gracious preservations when I consider how narrowly I have escaped
those rocks upon which many have been shipwrecked and ruined.

After my arrival in America, I was sometimes visited by the Lord,
and to a degree awakened to a sense of my undone condition without a Savior,
though this happened not so frequently as when I was younger.
For having often (oh, very often!) knowingly withstood Him,
my taste for worldly pleasures had now grown stronger,
and I was very unwilling to give up to the call of Christ.
I could plead an abundance of excuses, insisting, among other things,
that I was still young, and might live a great many years.
I reasoned that, even if I lived loosely for a few years,
I might still become religious sooner than many others
had done who had become exemplary men in their day.
So to make myself more easy for a time,
I would fully determine to become a very religious and good man at one time or other;
but it must not be yet.

Thus, through the gross darkness which had covered my mind,
I was prevailed upon by the subtlety of Satan to run the
dreadful hazard of future repentance and amendment of life,
having no certainty of seeing the light of one day more.
And so I became even worse and more hardened in evil,
though I was still preserved out of what are commonly esteemed the grossest pollutions.
For I was afraid to tell a lie,
except to embellish or exaggerate a pleasant or merry tale or story,
thinking it no great crime to tell a lie in jest.
I do not remember ever to have sworn an oath, or uttered a curse.
Nor was I prevailed upon, in my customary conversation,
to depart from the rules of my education respecting the plain language,
_thee_ and _thou_ to one person, and _you_ to more than one person.^
footnote:[See Introduction, pg. 10-11]
All this time I preserved a pretty fair character among men,
for none could charge me with anything accounted as scandalous.
I retained much love and regard for those I thought to be truly religious,
especially those weighty, substantial ministers of the everlasting Gospel.
I believe I had a better sense of their spirits
and labors than some of my companions had,
and was therefore afraid to despise or speak contemptuously of them,
as some of my associates did.
In this carnal, degenerate state, I commonly (in a customary way),
attended first-day meetings,
and sometimes attended meetings on other days of the week whenever
any ministers from distant parts came to visit Abington meeting,
to which I belonged.
But alas, such meetings were to little or no good purpose,
for the labor bestowed upon me (by ministry or
otherwise) was like water spilled upon a stone,
which immediately runs off again without any entrance.
I was indeed for some time
"`like the shrub in the desert, not knowing when good came`" (Jer. 17:6).
And if at anytime the Seed of God`'s kingdom fell upon my heart,
which was like the highway ground, it was soon taken away,
and I very quickly lost its savor.

When I had arrived at about nineteen years of age, I was
(through infinite mercy, never to be forgotten)
visited by the Lord in an extraordinary manner.
And since this was the happy means by which He, in a good degree,
turned my mind from the perishing vanities of an
uncertain world to the God of all sure mercies,
I intend to be somewhat particular.
One evening, being with several of my companions in vanity,
and under no restraint because the heads of the family were not at home,
we carried our frothy, vain conversation and foolish,
rude actions to a higher degree of wicked madness than I ever was guilty of before,
in which I suppose I acted as something of a ringleader.
Because of this, I felt some sharp lashes of conscience as I went to bed that night,
and the thought took hold of my mind that we did not
have a being in this world for such a purpose,
or to spend our time as above mentioned.
I gave some hint of these sentiments to my roommate,
yet this conviction did not sink so deep, for I pretty soon fell to sleep.

I had not slept long before a messenger alarmed me with the account
that one of my jolly companions--who was then in the house with us,
and who, I think, had behaved the best of us--was dying.
He desired me to go immediately to him, which I did,
and I was exceedingly struck with horror of mind at the thoughts of
the manner in which we had spent the evening before,
and the sudden stroke that followed upon this poor man.
But when I came to his bedside and saw the dreadful agony he was in,
my horror increased beyond all expression,
for none of us expected he could live many hours.
For my part, I was so deeply plunged into anxiety of mind,
that it seemed as if the pains and terrors of hell had laid hold of me already.
I was then in full expectation that there was no deliverance for me,
and that I should surely die before morning with
the weight of the distress which was upon me.
This happened on a seventh-day night, and though the young man in time recovered,
yet he was not fit to be left the following day,
which hindered me from going to meeting.

Oh, I was exceedingly desirous to go to meeting,
for by this time I was pretty thoroughly awakened to a sense of my duty!
But it was a week before the like opportunity presented itself again,
and it seemed the longest week I had ever known.
Oh how I longed to present myself before the Lord in the assemblies of His people,
that I might pour forth my inward cries before Him in a
state of sincere repentance and deep contrition of soul!
For, through the effectual operation of His power in my heart,
I was then in a condition to do so.
Now I clearly saw that repentance is the gift of God, and that His love,
(with which He has loved us in Christ Jesus our Lord) leads sinners thereto.
My fleshly will was for the present overcome and silenced,
and there was now a giving up with all readiness of mind to the Lord`'s requirings.
Indeed, there was not anything too near to part with for the real and
substantial enjoyment of the Beloved of my soul;
for I was brought in degree to experience that He came "`for judgment into this world,
that those who see not might see; and that those who see might be made blind.`"
I could no longer look upon my former delights with any satisfaction.
Instead, I had a glorious view of the beautiful situation of mount Zion,
and my face was turned to it.
For the joy which was set before me, I was made willing to endure
"`the cross of Christ, and to despise the shame;`" and though I became a
wonder and a gazing stock to my former companions,
I did not much regard it, knowing I had just cause so to be.
My great change struck them with some awe,
for I observed they did not have the boldness to mock or deride me before my face.

The young man who was the instrument in the divine hand for my awakening,
together with his brother,
were both greatly reached and deeply affected by
the above-mentioned wonderful visitation,
and there was a very visible change in them for a time.
But like the seed that fell upon the stony ground,
they withered away and did not become fruitful to God.

When first-day came, I greatly rejoiced that I could go to meeting,
which proved indeed to be a memorable one.
There were two public Friends,^
footnote:[The term "`public Friend`" was used by the early Quakers to
refer to those members of the Society who were frequently engaged in
traveling and public ministry among the various established meetings.
These ministers never received money for their services in the Lord`'s body,
being convinced that they should freely give what they had freely received.]
strangers, who seemed to me to be sent there on my account,
for most of what they had to deliver appeared applicable to my state.
Now I did, in some degree,
experience the substance of what was intended by the
"`baptism of water unto repentance,`"
"`the washing of water by the Word,`"
and being "`born of water and the spirit,`"
all of which would be fully seen and clearly understood by the
professors of Christianity were they rightly acquainted with the
"`gospel of Christ, which is the power of God unto salvation.`"
This power, inwardly revealed, is alone able to work that change in them,
without which (our Lord says) none shall so much as see the kingdom of God.
But alas, being carnal in their minds, a spiritual religion does not suit them!
For even as the Scripture says,
"`The natural man receives not the things of the Spirit of God,
for they are foolishness unto him; neither can he know them,
because they are spiritually discerned.`"
So it is that the professors of the Christian name hold tightly to signs and shadows,
while the substance is neglected.
They plead for the continuance of types, when the antitype is but little regarded.
But where this substance is experienced, all shadows and types vanish and come to an end,
as did the types and figures of the law, when Christ, the antitype,
came and introduced His dispensation, which is altogether of a spiritual nature.

This administration of water by the Word continued upon
me in a remarkable manner for about three months,
in which I found great satisfaction; for it was accompanied by a heavenly sweetness,
like healing balm to my wounded spirit,
and my heart was melted before the Lord as wax is melted before a fire.
Great was my delight in reading the holy Scriptures and other good books,
and I was favored at that time to receive much comfort and improvement thereby.
But this easy,
melting dispensation had to give way to a more powerful one--even the baptism with
the Holy Spirit and fire--that the floor might be thoroughly purged.
And then the former dispensation of the Lord to my soul seemed much
to resemble John`'s baptism with water unto repentance
(being the substance signified by it)
in order to prepare the way of the Lord.

Under this fiery dispensation I was, for a time,
exceedingly distressed under a sense of the great alteration in the state of my mind;
for indeed I felt myself forsaken of the Lord,
and attributed the cause to something in myself.
All the former tenderness was gone, and I became like the parched ground.
Yes, my agonies were so great that when it was day I wished for night,
and when it was night I wished for day.
In meetings for worship, where I had formerly enjoyed the most satisfaction,
I was now under the greatest weight of pain and distress,
even to such a degree that at times I could scarcely forbear crying aloud for mere agony.
When meeting was over, I would sometimes walk a considerable way into the woods, so that,
unheard by any mortal,
I might give vent to my greatly distressed soul in mournful cries.

In this dejected state of mind,
the grand adversary was permitted to pour forth floods of temptations.
I was almost constantly beset with evil thoughts, which exceedingly grieved me.
And though I was too much enlightened to willingly
allow or join with these wicked and corrupt thoughts,
yet I often judged myself not earnest enough in resisting these and other temptations.
Oh, what a dark and distressed condition my mind was in!
Indeed, I was exceedingly weak in those days, and I am persuaded that the Lord,
in gracious condescension, looked mercifully at the sincerity of my intention,
not marking all my failings,
or I could never have stood before Him in any degree of acceptance.
Very great were my temptations, and very deep was my distress of mind for about a year,
during which time I was like a little child in understanding
the way and work of God upon me for my redemption.
Yet, He who will
"`not break the bruised reed, nor quench the smoking flax,
until He sends forth judgment unto victory,`"
by His invisible power lifted up my head above the raging waves of temptation,
so that the enemy found he could not overwhelm me.
The Lord taught my hands to war, and my fingers to fight under His banner,
and through His blessing and assistance,
I found some degree of victory over the beast--that is,
that part in man which has its life in fleshly gratifications.

Then the false prophet began to work with signs and lying wonders in
order to deceive my weak and unskillful understanding.
It is written, "`Satan transforms himself into an angel of light,`"
and so I found him, at least in appearance.
For perceiving that I was too much enlightened
from above to be easily drawn into sensuality,
the enemy of my soul (who goes about seeking whom he may devour)
craftily attempted my destruction another way--by setting himself up,
undiscovered then by me, as a guide in the way of mortification.
For I was then resolved, through divine assistance, to carefully carry my cross,
and to deny myself in all things which appeared inconsistent with the divine will.
But this subtle transformer,
taking advantage of the ardency of my mind to press forward in this necessary concern,
suggested that it would be much easier to obtain a complete victory over evil,
were I to refrain for a time from some of the necessaries of life,
particularly from eating and taking my natural rest in sleep,
except just as much as would preserve life.
He furthermore suggested that I must constantly keep my hands employed in business,
as idleness is the nursery of vice; and he was not slow to bring Scriptures,
and passages from other religious books, to confirm these requirings.
At that time I really believed it was the voice
of Christ in my mind commanding these things,
and therefore endeavored to be faithful therein,
even though my natural strength abated and my body grew much weaker.
I was greatly distressed when at any time I fell short
of what I apprehended to be my duty in these respects.
And I found that he who required this service was a hard master;
for though he had power to deceive,
yet he could not give me faith that I should ever overcome.

My views in those days were indeed very discouraging,
and my poor afflicted soul was almost sunk into despair.
My friends took notice that I was in uncommon distress.
The family with which I then lived could not help but take
notice of my wandering about in the fields at night,
and of my much refraining from food,
and of the deep distress which was legibly imprinted on my countenance,
though I concealed it as much as I could.
They feared (as I afterwards understood) that I
should be tempted to lay violent hands on myself.
And I had forbidden myself to speak of my condition to any,
as I felt that would be seeking relief from without--a very improper and unworthy thing.

Notwithstanding all this,
the God of all grace (who permitted this uncommon affliction to fall upon me for a trial,
and not for my destruction) was pleased, in wonderful kindness,
to move upon the heart of a minister belonging to our meeting to visit me,
and to open a way for my deliverance.
He carefully inquired concerning my inward condition,
informing me that Friends were much concerned about me,
as it was very obvious I was under some uncommon temptation.
At first I was very unwilling to open my state to him,
but at length he prevailed and took the opportunity to
show me that I was under a gross delusion of Satan.
By this means, through the Lord`'s mercy,
I was delivered from the wicked design of my enemy,
which undoubtedly was to destroy both soul and body.
And so, in reverent thankfulness, I rejoiced in His salvation.
And I then clearly saw that Satan must also be
carefully guarded against in his religious appearances;
for nothing in religion can be acceptable to God except
for the genuine product of His unerring Spirit,
distinctly heard and understood by the ear of the soul and the renewed understanding.
"`My sheep,`" said Christ, "`hear My voice;`"
which I now began to experience fulfilled.
Blessed be the Lord forever!

About this time, I had many precious openings into the divine mysteries,
and when I read the holy Scriptures,
they were opened to my understanding far beyond what they had ever been before.
Indeed I had very great comfort,
and my hope was revived and my faith much strengthened
by those things that were written beforehand.
I am well assured, by certain experience,
that the mysteries couched in those holy writings cannot be rightly
understood except by the same Spirit which inspired the penmen of them.
It is therefore vain presumption for fallen and unregenerate man,
by his earthly wisdom and human learning, to attempt unfolding heavenly mysteries.
The lip of truth Himself has signified that they are hidden from the
wise and prudent of this world and revealed unto the humble,
dependent babes and sucklings--that is,
those who sensibly experience their sufficiency for every good
word and work to proceed immediately from God,
so that Christ
"`is made unto them, wisdom and righteousness, sanctification and redemption.`"
The lack of this inward, living sense has been the cause of, and has opened the way for,
the great apostasy, darkness, and error, which have overspread Christendom, so called.
There is no way for its recovery,
except by humbly submitting to Christ inwardly revealed,
and learning the nature of true religion from Him, the great Author thereof.
I am well assured that the forward, active, and inventing self must be denied, abased,
and laid in the dust forever, and the Lord alone exalted in our hearts,
before we can rise up in the several duties of true religion with divine approbation.

I saw that the divine light which began to shine out of my darkness,
and which separated me from it,
was the greater light which was to rule the Day of God`'s salvation,
and that all the saved of the Lord must carefully walk in this light,
wherein there is no occasion of stumbling.
I also saw that when it pleased the Lord in His wisdom,
for a trial of my faith and patience, to withdraw this holy light,
so that there was a sitting in darkness,
and in the region of the shadow of death for a time,
where I had no distinct knowledge what to do--that it was then my
indispensable duty to stand still and wait for my sure unerring Guide.
And when, during these times, self would arise and be uneasy,
it must be brought to the cross, there to be slain.
By such experience, I found I was nothing,
and that God was all things necessary for soul and body,
and that if I would be brought into a state of perfect reconciliation with Him,
I must know all things made new.

About this time I had a distant view of being called into the work of the ministry.
My mind was at times wonderfully overshadowed with the universal love
of God to mankind in the glorious gospel of His Son,
to such a degree that I thought I could (in the strength of His love)
give up to spend and to be spent for the gathering of souls to Him,
the great Shepherd of Israel.
Indeed, at times I felt I could lift up my voice like a
trumpet to awaken the inhabitants of the earth.
But I soon found that all this was only preparation for this important work,
and that I had not yet received a commission to engage therein.
A fear and care were upon my mind that I not presume to
enter upon this solemn undertaking without a right call;
for it appeared to me exceedingly dangerous to speak in the name of the Lord
without a clear evidence in the mind that He required it of me,
which I then fully believed He would give in His own time,
if I would give up to wait for it.

From this time, until I was really called into the work,
I frequently had
(especially in religious meetings)
openings of Scripture passages,
with lively operations of the divine power in my mind.
Sometimes these came with so much energy that I was
almost ready to offer to others what I had upon my mind.
But because of a holy awe which dwelt upon my heart,
I endeavored to weigh my offering in the unerring balance of the sanctuary,
and I found it was too light to be offered.
Then I was thankful to the Lord for His merciful preservation,
in that I had been enabled to avoid offering the sacrifice of fools.
But when the time really came that it was divinely required of me to speak,
the evidence was so indisputably clear that there was not the least room for doubt.
Nevertheless, through fear and human frailty I put it off,
and did not give way to the Lord`'s requiring.
Then oh, how was I condemned in myself!
The divine sweetness which had covered my mind in the meeting was withdrawn,
and I was left in a very poor, disconsolate state!
I was ready to beg forgiveness,
and to covenant with the Lord that if He would
be pleased to favor me again in like manner,
I would give up to His requiring.
At the next first-day meeting,
the heavenly power again overshadowed me in a wonderful manner,
in which it was required of me to kneel down in supplication to the Lord in a few words.
I gave way this time in the dread of His power, with fear and trembling,
and afterwards my soul was filled with peace and joy in the Holy Spirit,
and I could sing and make sweet melody in my heart to the Lord.
As near as I remember,
I was twenty-one years of age the day I first entered
into this great and solemn work of the ministry,
which was the 21st of the fifth month, 1734.

I have found my mind engaged to be somewhat particular concerning the
manner of my entering into the work of the ministry,
so that it may stand by way of caution and proper encouragement to others.
For in the course of my observation,
I have had cause to fear that some have taken the work
of preparation (as before hinted) for the thing itself,
and so have proceeded very far to their own great wounding, and the hurt of others.
Such as these bring forth untimely fruit,
which is exceedingly dangerous and should be carefully avoided.
Nothing is a sufficient guard to preserve from this but keeping the
eye single to the Lord (through the divine blessing),
and fearfully considering what a great thing it is for
dust and ashes to speak as the apostle Peter directs,
namely: "`As each one has received a gift,
even so minister it one to another as good stewards of the manifold grace of God.
If anyone speaks, let him speak as the oracles of God; if anyone ministers,
let him do it as with the ability which God supplies.`"
The author to the Hebrews says,
"`No man takes this honor to himself, but he that is called of God, just as Aaron was.`"
So that regardless of what some may pretend to, or intrude themselves into,
unless they are really called of God they have no share
in that honor which comes from God alone.

The church of Christ has had its share of trouble from false ministers,
both in the primitive times, and in ours.
That excellent gospel liberty--wherein all who feel themselves
inspired (whether male or female) may speak or prophecy,
one by one--has been, and still is, abused by false pretenders to divine inspiration.
Nevertheless, this liberty ought to be carefully preserved,
and other means found to remedy the abuses in this regard; which would not be difficult,
were the members in a general way more spiritually minded,
rightly savoring the things that are of God.
Presumptuous and unsanctified appearances in ministry would then be easily
contained and suppressed so as not to disturb the peace of the church.
But alas, the case is often otherwise, as I have observed in many places.
And such barren ministry is often little minded,
so long as the words and doctrines are sound, and there is nothing to blame in conduct.
But here the main thing is disregarded,
which is the powerful demonstration of the Holy Spirit.
And the few who are deeply pained at heart with such lifeless
ministry find it exceedingly difficult to correct,
for lack of strength, especially when they perceive what strength there is against them.
For the formal professors of Christianity love to have it so,
rather than to sit in silence.
I have observed such pretenders to be all mouth or tongue,
having no ear to receive instruction; they are fond of teaching others,
but very unteachable themselves.
I pray God to quicken His people,
and to raise our Society into a more lively sense of that
blessed power which first gathered us to be a people.
Otherwise, I fear this great evil will prove to be a growing one among us, namely:
profession without possession.

I was not quite free to omit a remark on this subject,
as I am fully persuaded the living members of the church of Christ groan
under a painful sense of this sorrowful token of a declined society.
May the Lord of Hosts hear their cries, and regard the anguish of their souls in secret,
so as to work by His invisible power for His own name`'s sake, and for their enlargement.
And may He turn His hand again upon our Zion to purge away her dross,
and to take away her tin and reprobate silver,
that her judges may be restored as at the first, and her counselors as at the beginning.
And oh, that many, having their feet shod with the preparation of the gospel of peace,
may yet appear beautiful upon the mountains!
So be it, says my soul!

I have given some hints how it was with me during the time of
preparation for the great and important work of the ministry,
and also the danger of my being misled, even sometimes when I had right openings,
and felt the sweet, efficacious virtue of the love of God,
through Jesus Christ to mankind (which, no doubt,
is at times the sensible experience and enjoyment of every faithful
follower of Christ who is never called to the work of the ministry).
I was apprehensive in those days of the danger of being
led out into ministry through the wrong door,
and I have since more clearly seen the danger of this and other by-paths which
would have led me to give away to others what I was meant to live upon myself.
Indeed, many are the by-paths that lead out of the humble,
dependent state (in which alone there is safety), to have a will and a way of our own,
that we might be furnished and enriched with much treasure.
But in sincerity of heart, and an earnest endeavor to preserve the eye single,
and through the watchful care of divine providence over me,
the Day of the Lord shone upon all of these dangers, and I came clearly to see,
and experientially to know, that my sufficiency was of God.
I saw that there must be a steady dependence upon the Lord to be immediately
fitted and supplied every time I was to engage in this solemn service.

I ardently desire that all who have the least apprehension of
being called into the work of the ministry,
may dwell in a holy dread of the divine presence,
and know their own wills wholly subjected to the divine will,
waiting for a distinct and clear certainty of the Lord`'s requirings,
not only in entering upon this at first, but also at all other times.
And as self comes to be laid in the dust,
they will receive undeniable evidence in their
own minds of the certainty of their mission,
and will not lack a confirming testimony from the witness for God in
the consciences of those amongst whom they are sent to minister.
True ministers will be a savor of life to those living in the Truth,
and of death to those who are in a state of death.
Let it be ever remembered, that nothing of, or belonging to man,
can possibly add any luster or dignity to the divine gift.
Neither can the best and most perfectly adapted words or doctrines (though they be
ever so truly and consistently delivered) be any more than as sounding brass,
or as a tinkling cymbal, without the power, light,
and demonstration of the Spirit of Christ.
And allow me to add--there is no need for those who regard the Lord`'s
power as the substance of their ministry to be anxious about words,
as the lowest and most simple are really beautiful when
fitly spoken under that holy influence.

Having entered upon the solemn and weighty service of the ministry, I gave up,
for the most part, to utter a few words in a broken manner, with fear and trembling,
as I found the requirings of Truth
(through its own divine power and efficacy)
moving upon my heart and subjecting my will.
The Lord was exceedingly merciful to me,
like a tender father taking me by the hand and making me willing by
His mighty power to be counted a fool for His sake and the gospel`'s.

The meeting I then belonged to was large, and in it there was a body of valuable,
weighty Friends.
As far as I could observe by their carriage,
these did acknowledge and approve of my weak and low appearances in the ministry.
Nevertheless, they used Christian prudence,
"`not laying hands on me quickly,`" but giving
me full opportunity to make proof of my ministry,
and to feel my feet therein.

About this time a fine spring of ministry was
opened within the compass of our Yearly Meeting,
for about one hundred persons had their mouths opened
in public testimony in a little more than a year.
Several of these became powerful, able ministers,
but some of them withered away like unripe fruit.
Within that time,
about ten appeared in the particular meeting of Abington to which I belonged.

As I was enabled to wait on my ministry,
I experienced a considerable growth and enlargement;
and in the faithful discharge of my duty therein,
great peace and heavenly consolation flowed into
my soul like a pleasant refreshing stream.
I also found that this was a means of engaging the minds of
Friends in a sweet and comfortable nearness of unity with me,
which I had never before so largely and livingly felt.

Many well-minded young people, and some others of little experience,
seemed to admire my gift, and would sometimes speak highly of it,
which they did not always forbear doing in my hearing.
But oh, how dangerous this is, if delighted in by ministers!
It may be justly compared to a poison which will soon destroy the pure innocent life.
My judgment was against it,
yet I found something in me that seemed rather inclined to hearken to it,
though not with full approbation.
The same thing in me would want to know what such and such persons
(those who were in most esteem for experience and wisdom)
thought of me.
I sometimes imagined that such looked apprehensively upon me, which would cast me down.
But all of this, being from a root of self, I found to be for judgment,
and I knew it must die upon the cross before I was fit
to be trusted with any great store of gospel treasure.

I began also to take too much delight in my gift; and if divine goodness had not,
in mercy, prevented it (by a deep and distressing baptism,^
footnote:[He uses the word baptism figuratively,
as speaking of being dipped down into the fiery trials, testings,
and judgments by which the Lord thoroughly "`purges His threshing floor.`"])
this might have opened a door for spiritual pride,
which is the worst kind of pride, to enter in for my ruin.
I have reason to think that solid Friends, observing my large growth at the top,
with spreading branches, were in fear of my downfall in case of a storm.
But, in the midst of my lofty career,
the Lord was pleased for a time to take away from me the gift of the ministry,
along with all sensible comforts of His Spirit,
so that I was left (as I thought) in total darkness,
even in the region and shadow of death.
In this dejected state of mind, I was grievously beset and tempted by the false prophet,
the transformer,
to keep up my credit in the ministry by continuing my public appearances.
It might well be said of him that he can
"`cause fire to come down from heaven in the sight of men, in order to deceive them;`"
for so I found it to be.
Oh, it is hard to imagine how near a resemblance the enemy can make,
or how exact an imitation he can form of the things of God!
And indeed, with the state of mind I was then in, I was at times ready to say,
"`Ah, I see and feel the fire of the Lord coming down to prepare the offering!`"
And I have been almost ready to give up to this prompting, and to speak on God`'s behalf,
when a godly fear would seize my mind, along with a desire to test it again.
By this means, my strong delusion has been discovered, the false fire has been rejected,
and my soul has been plunged into deeper anxiety than I was in before.

No tongue or pen can fully set forth the almost constant anguish of
soul that was upon me for about the space of four or five months.
With regard to my friends,
it fared with me in some degree as it did with Job--some
conjecturing one thing to be the cause of this fall,
and some another thing; though, through mercy,
they could not charge me with any evil conduct as the cause thereof.
The most probable reason for my alteration, in the mind of many,
was that I had been too much set up by others, and so had lost my gift.
And indeed, this came the nearest to the truth of the case.
Yet it was not so far lost, but that when my gracious Helper saw my suffering was enough,
He restored it again, and appeared to my soul as a clear morning without clouds.
Everlasting praises to His holy name!
My mind was deeply bowed in humble thankfulness under a sense of the great
favor of being again counted worthy to be entrusted with so precious a gift.
I was therefore careful to exercise it in great fear and awe,
and in an even greater cross to my own will than before.

In the course of my religious experience,
I have very often had cause to admire and adore divine wisdom in His
dealings with me for my preservation in the way of peace.
I am well assured that He will so work for all mankind
who are entirely given up in heart to Him,
so that it will not be possible for these to miss everlasting happiness.
For truly,
none are able to pluck out of His almighty hand
those who do not first incline to leave Him.

After I had appeared in public ministry somewhat more than two years,
I found some drawings of gospel love (as I apprehended) to
visit the meetings of Friends in some parts of New Jersey.
Being but young in the ministry,
I was at times in great fear lest I should be mistaken
in what I thought to be the divine requiring.
I much dreaded running when and where the Lord did not send me,
lest I should bring dishonor to His blessed name,
and expose myself to wise and discerning Friends to be without
proper qualifications for so great an undertaking.
Great indeed was my distress, night and day, crying to the Lord for greater confirmation.
These cries He graciously heard, and was pleased, by a dream or night vision,
to afford me such full satisfaction that I do not
remember having any doubts afterwards concerning it.

I entered upon this journey the 7th of the eighth month, 1736,
having a companion who was much older than myself.
We visited the following meetings: namely, Pilesgrove, Salem, Alloways Creek,
and Cohansey, where my companion left me and returned home,
being under some discouragement about the journey in his own mind.
But as I found the Lord by His blessed power near--opening my mouth and
enlarging my heart abundantly in His work--I was encouraged to proceed,
being joined in travel by an innocent Friend belonging to Alloways Creek meeting,
who had a few words to speak in meetings.
We went from Cohansey, through a wilderness for about forty miles without inhabitants,
to Cape May, where we had a meeting.
From there we moved on to Great and Little Egg-harbor and had meetings,
and then through the wilderness to the Yearly Meeting at Shrewsbury,
which was large and much favored with the divine presence.
Various ministering Friends from Pennsylvania were there, namely, Thomas Chalkley,
Robert Jordan, John and Evan Evans, Margaret Preston, and others.

It neither suited my growth in the ministry, nor my inclination,
to take up much time in those large meetings.
I therefore, for the most part, gave way to those who were better qualified for the work,
and in my esteem worthy of double honor.
I had a great regard in my mind for all who I thought to be pillars in the house of God,
whether ministers or elders.
And I really think that if any of these had given it as
their sense that I was wrong in any of my offerings,
at any time,
I would have been more likely to depend upon their judgment than upon my own.
I looked upon myself, for many years, as a child in experience every way,
and therefore thought a subjection was due from me to
those who were fathers and mothers in Israel.
And I never, that I remember, manifested any disregard to them,
which is now a great satisfaction to my mind.

I confess, I have at times since had cause to marvel at the forwardness of some,
who though but children in ministry
(if rightly children at all)
have undertaken the work of men,
hardly demonstrating a willingness to give the preference to any.
And when these have been admonished by those of much more experience than themselves,
they have been apt to dispute, or to plead a divine commission,
and that it is right to obey God rather than man,
as if they had the sole right of speaking and judging in the body.
But I had many times seen the great danger of
being deceived and misled by the transformer,
and was therefore afraid of being confident of my own sight,
and looked upon it to be safest for me to stand quite open to instruction,
let it come from whoever it would;
for there was nothing more desirable to me than to be right.

This large meeting at Shrewsbury ended well and sweetly;
praises to the Lord over all forever!
From there I went to meetings at Chesterfield, Trenton, Bordentown, Mansfield,
Upper Springfield, Old Springfield, Burlington, Bristol, the Falls, Ancocas, Mount Holly,
Evesham, Chester, Haddonfield and Woodbury Creek, after which I returned home.
The Lord made my journey prosperous, and was to me at times as a fountain unsealed,
supplying daily for the work He had engaged me in,
and wonderfully condescending to my weak state, giving both wisdom and utterance,
as it is written,
"`Out of the mouths of babes and sucklings You have ordained strength.`"
Praises to His holy name forever!

But though the Lord had committed to me a dispensation of the gospel,
and was pleased to reward my sincere labors therein with the
sweet incomes of peace and joy in the Holy Spirit,
and with the unity of the brethren in a comfortable degree;
yet great were my temptations,
and various were the combats I had with my soul`'s enemies for some years after.
Oh, how hard I found it to keep from being defiled (in one degree or another) by the
polluting floods which almost continually poured out of the dragon`'s mouth.
Indeed, he sought to carry away my imagination into various unlawful delights,
and from these I did not always wholly escape.
Sometimes I was prevailed upon to set bounds for myself,
and though I would not directly fall into the evil I was tempted to do,
yet I would take some delight and satisfaction in
approaching as near to it as I thought was lawful.
In this way,
for lack of a watchful care
(not only to shun that which I knew to be really evil, but also every appearance of evil),
I sometimes brought great anguish and deep distress upon my mind.
And when I had gone but a little out of the right way,
I then found that many (oh many!) weary steps and painful heart-aches were
necessary before I was received again into the way and favor of my heavenly Father.

I have often since been humbly thankful for His preservation, even out of gross evils,
considering how I sometimes dangerously tampered with these in my imagination.
How can weak mortals determine to what length
they will go when any ground is given to evil?
Most certain it is,
that man works greatly to his own hurt by taking any
pleasure at all in the thoughts of forbidden things.
I have found by woeful experience, that when the least way is given to the enemy,
he then gains advantage over us, and we are greatly enfeebled thereby.
And so,
instead of growing as "`willows by the water-courses,`" there is
danger of withering and becoming one of those that draw back,
in whom the Lord has no pleasure.
I have found it the first subtle working of Satan to draw me
off from a constant care of bringing all my thoughts,
words, and actions, to be tried by the light of Christ in my own heart;
and instead of this, to examine them by my biased reasoning part.
Here many things really evil in their nature or tendency, or both,
may carry the appearance of indifference;
and the mind then pleads that there is no harm in this, that, or the other thing.
And though there be doubts in the mind,
these can be reasoned away
(not duly considering that, "`he who doubts, is condemned if he receive`").
So then (alas!),
when the true Judge of all has been pleased to arise,
there He has found me with my fig-leaf covering on,
having in a great measure lost the garment of innocence and a
holy confidence towards God by giving way to wrong things.
Oh, how my neglect has occasioned the furnace to be made hot,
that all dross might be done away!

Thus it was with me,
until the many chastenings of the heavenly Father brought me into more fear, care,
and subjection.
I could not omit giving these hints of my many weaknesses and failings,
that others may learn thereby to be aware.
And I also apprehend this to be the chief reason for which God has transmitted to
us the failings and miscarriages of His people in the Holy Scriptures.
O you traveler Zionward, look forward to the joy set before you,
not allowing your eyes to wander about you,
lest they convey such delight to your heart as
may infect your soul with deadly distempers,
by which you will be rendered unable to proceed on your journey towards the holy city.
Beware you do not load yourself with the seemingly
pleasant fruit of that country through which you travel.
Though it may appear to hang plentifully on each side,
it will neither be of any use to you in that heavenly country where you are going,
nor serve for true refreshment on the way there.
If you desire that your own way be prosperous, look steadily forward,
with a single eye to the recompense of reward.
Bring every motion towards seeking satisfaction
in forbidden places immediately to the cross,
and you will much sooner find the yoke of Christ made easy and His burden light.
Indeed you will find all His ways pleasant, and His paths peace.
This is abundantly better than that uneasy,
in-and-out way of traveling--sinning and repent­ing, repenting and sinning again,
which lays a foundation for murmuring, labor, and toil.
Such as these cry out (some all their lives) that there is no
complete victory to be obtained over sin on this side of the grave.
"`Miserable sinners we must remain,`" they say,
when the cause thereof is wholly in themselves--because they will not come into,
and abide in, the help of the Lord against the mighty enemies of their soul`'s happiness,
which is altogether sufficient to give a complete victory over them.
Indeed, He is able to give power to triumph and to say,
"`We are made more than conquerors through Him that has loved us.`"

[.asterism]
'''

[.emphasized]
John Griffith was a minister between 1734 and 1776,
around one hundred years after the great outpouring of light
and power that gave rise to the Society of Friends.
Though the Society continued to grow in number through much of the 1700`'s,
and a living remnant survived even into the 1800`'s,
there was nevertheless a sad and steady decline in true life and
godliness after the initial fifty years of prosperity and purity.
John Griffith spent his entire life laboring among a waning church,
warning them not to lose their first love,
and insisting upon the need for the Spirit`'s leading, light, and power in all things.
In one of many similar expressions found in his complete journal, he writes,
"`It is but about a century since the Lord, by an outstretched arm,
gathered our Society from the barren mountains and desolate hills of empty profession;
choosing them for His own peculiar flock and family,
as does fully appear by many evident tokens of His love and
mighty protection--even when the powers of the earth,
like the raging waves of the sea, rose up against them,
with full purpose to scatter and lay waste.
It may be justly queried, '`What could the Lord have done for us that He has not done?`'
Notwithstanding which, what indifference,
lukewarmness and insensibility as to the life of religion are
now to be found amongst numbers under our name!
Nay, in some places, this painful lethargy has become almost general.`"

[.emphasized]
John Griffith, together with a faithful minority in his generation,
poured out their lives for the truths of the gospel, for the purity of the church,
and for the glory of the Lord in the earth.
He died from complications with asthma in 1776, at 63 years of age.
