== Preface

Were it not apprehended by me to be a duty to offer to your serious
perusal the following plain and experiential observations,
the reader would not have heard from me in this way.

I have often, with many brethren and sisters in the Truth,
been deeply affected in viewing the great danger to which
Christian professors are exposed through indifference of mind.
When a lethargic stupefaction has gained the ascendency in the heart,
religion in notion and fruitless speculation satisfy a mind so depraved.
Thus a true renovation of heart (without which
none can be truly religious) is not sought after;
and men, being pleased with the shell or form only,
are not sensible that they lack the substance.

When the subtle adversary finds men in this kind of sleep or stupefaction,
it is then his opportunity for sowing the tares amongst the wheat; and by this means,
the field of the Christian church, in process of time, became covered therewith.
That which came nearest to my heart and most earnestly
engaged my attention towards this present undertaking,
not without ardent desires for the lasting advantage of Christians of all denominations,
was, that the descendants of a people, who a little above a century ago,
were marvelously brought out of, and redeemed from,
all lifeless shadows and empty forms of religion,
to enjoy and be grounded in the blessed power and life thereof,
might be preserved truly sensible of the way and means whereby our
worthy predecessors obtained a firm establishment in the Truth,
as it is in Christ Jesus; for it is evident where the means are neglected,
the end cannot be attained.

That many of the descendants of the early Society of Friends,
in this day of outward peace and plenty, inclining to false liberty and ease,
shun the cross of Christ which would crucify them to the world,
is a mournful truth too obvious to be denied.
And it is in consideration of this,
I found a concern to throw a few observations before them,
suited to the present state of things; endeavoring, in some degree,
to offer to the view of the present and succeeding generations,
the means by which our worthy predecessors became a living honorable body of people,
in hope that the necessity may fully appear of the same
blessed power operating upon their hearts and minds,
in order to qualify all to rightly succeed those
valiants in maintaining the cause of God.

The objection which cast some discouragement in my way may also occur to some readers,
namely, that the subjects treated of in this small tract have been
many times judiciously written before by different authors.
But this is no more than may be said of most religious subjects.
Divine wisdom and goodness has seen fit to revive the same truths,
by different instruments, from generation to generation;
the Lord's servants speaking the same thing, as with one mouth.
Herein God's gracious condescension to human frailty is very conspicuous,
causing those excellent truths, so essential to be received that man's soul may be saved,
to be frequently revived and inculcated,
seeing man is so liable to forget God and his reasonable duty to Him.

I shall only add my earnest prayer to the God and Father of all sure mercies,
that these truths, which I have cast into the treasury, may meet the serious reader,
of whatever denomination, with the divine blessing!
If such a blessing graciously attends,
though what is here offered may be justly accounted as mere barley-loaves,
the hungry soul may receive some strength and refreshment thereby.

[.signed-section-signature]
John Griffith

[.signed-section-context-close]
30th of Eighth month, 1764.
