[#section-1, short="Counsel to Parents and Children"]
== Section I

[.chapter-subtitle--blurb]
Containing Tender Advice, Caution, and Counsel to Parents and Children

=== First to parents.

Very much depends upon the right education of children.
I therefore find it in my mind to make a few observations upon this subject,
as it shall please the Lord to open my understanding,
without whose assistance and blessing upon our labors, they prove altogether fruitless.

The people of Israel were strictly enjoined to make the
training up of their children in the law of God,
their constant care: "`Hear, O Israel, the Lord our God is one Lord;
and you shall love the Lord your God with all your heart, and with all your soul,
and with all your might.
And these words which I command you this day, shall be in your heart,
and you shall teach them diligently unto your children,
and shall talk of them when you sit in your house, and when you walk by the way,
and when you lie down, and when you rise up.`"

Exceedingly great is the trust reposed in parents and the heads of families.
It is certainly their indispensable duty, as much as they can,
both by precept and example, to form the tender minds of their offspring to virtue,
as says the apostle, "`And you fathers, provoke not your children to wrath;
but bring them up in the nurture and admonition of the Lord.`"
And, "`Train up a child in the way he should go; and when he is old,
he will not depart from it.`"

Parents must first be acquainted with the way of Truth,
and the nurture and admonition of the Lord themselves,
before they can train up their children therein.
That which is likely to have the greatest influence upon their tender minds is a steady,
circumspect example, in a self-denying conduct before them;
which will beget reverence and honorable thoughts in children
concerning those whom Providence has placed over them.

Great care should dwell upon the minds of parents,
to make it fully evident to their children that they are much more
desirous they should possess a heavenly than an earthly inheritance;
and are more concerned that their souls be adorned with the graces of the Holy Spirit,
than that their bodies should appear decked with outward ornaments.

Children will be very likely to value that which they see is preferred by their parents,
whether it be the things of the world, or the things of God.
If this is the case (which I think will be conceded by all thoughtful persons),
O then! how much depends upon them for the promotion of
truth and righteousness on the earth,
both in regard to the present time, and the generations to come.
This fully appears by the Lord`'s testimony concerning Abraham;
"`And the Lord said, Shall I hide from Abraham that thing which I do?
seeing that Abraham shall surely become a great and mighty nation,
and all the nations of the earth shall be blessed in him.
For I know him, that he will command his children, and his household after him,
and they shall keep the way of the Lord, to do justice and judgment;
that the Lord may bring upon Abraham that which He has spoken of him.`"
Abraham`'s godly concern appears earnest, even for the child of the bond-woman;
where he said unto the Lord, "`Oh! that Ishmael might live before You.`"

Constant and faithful endeavors,
with secret cries to God that His blessing may attend them,
may prove effectual to the preservation of children.
This care should begin very early,
even as soon as they are capable of distinguishing what
pleases and displeases their parents.
A self-willed, contrary disposition may soon be discovered in children,
which is very earnest to have its own way,
before they can judge what is best for themselves.
This should constantly be subjected to those who are to judge for them.
Children should never be allowed to prevail by a demanding and fretful temper,
not even when what they crave is suitable for them to receive,
were they in a submissive disposition.
By this they will quickly and clearly see,
that it is more to their benefit and comfort to
yield an entire subjection to their providers,
and that nothing is to be obtained by a fretful self-willed temper.
This should be done by a firm and steady hand,
which will make the work of parents abundantly
easier in the government of their children,
and may prove a great benefit to them, perhaps through the whole course of their lives;
since by crushing their willfulness in its first buddings, it may thus die away,
so as never more to gain the pre-eminence.
This would be a great blessing,
and they would owe their watchful parents far more for
suppressing this and other pernicious buds in them,
than for the reception of a large outward inheritance.
Indeed, everything of an evil nature should be kept down
in children by a careful and steady means.
Oh! what a hopeful generation of youths should we have,
were parents in general to exercise this prudent care in all things!
I verily believe that,
instead of sober virtuous youths being as speckled birds amongst the rest,
the rebellious, disobedient and obstinate, would be so;
and this would bring judgment upon them.

A conscientious discharge of this great duty,
would bring an ample reward to such parents as have no greater
joy than to see their children walking in the Truth.
And even if parents should prove unsuccessful, as it sometimes has happened,
they will be clear of their children`'s blood in God`'s sight, which is a very great thing;
so that though the rebellion and evil conduct of their offspring may be their sorrow,
it will not be their sin.

I have sometimes been much grieved,
when I have seen youth in a path of being ruined through the imprudent
indulgence of their parents (especially mothers) making themselves and
others mere slaves to the perverse desires of their children.
These take great pains to extinguish the flame of their children`'s
troublesome tempers by such means as add fuel to the fire;
inverting the order of nature, in becoming subject to those who should submit to them.
And by answering their unreasonable cravings, they make themselves more work,
and that of a very disagreeable nature.
Parents who are so very imprudent,
have little reason to reflect upon their children for being self-willed,
and not subject to them when they grow up, because they themselves have cherished, fed,
and supported that selfish disposition in them from their cradles.
And unless the Spirit of God is permitted to lay deep hold of them,
and change the state of their minds,
they are unfit to be a comfort either to themselves or others,
not being formed for good servants, husbands, wives, or members of society.

Alas! when I take a view of the world,
and reflect how it wallows in abundance of wickedness and corruption--which
mankind possesses in a sort of succession from parents to children,
like outward inheritances--I have no words sufficient
to set forth to the full so deplorable a case.
How sorrowful it is to observe even children, by the power of example,
become like grown men in wickedness and hardness of heart!
Custom and general practice have so changed the common opinion of some gross evils,
that there appears very little remorse in the almost constant practice of them.
Many children are brought up, like their parents,
much strangers to their duty both to God and man.
This almost universal infection of evil, forgetfulness of God,
and wallowing in the pollutions of this world, are very alarming,
and call loudly for a reformation,
lest the Lord break forth in judgment upon the nations as the breach of waters.
It is indeed a painful task for godly parents, amidst so general a depravity,
to raise their children without receiving some stain from this pollution,
which runs down in our day like a strong torrent.
The safest way is, with great strictness and steadfastness,
to keep them out of such company,
though an inconvenience may attend this in various outward respects.
But oh! the soul is the most precious part of them, and parents,
above all other considerations,
ought to be concerned to preserve it untainted with the defilements of this world.

There is no better rule to act by in this important task,
than perfect submission to the Spirit of Truth,
who is promised to lead us into all truth.
If we mind this,
we shall not indulge our children in anything
which the Spirit testifies against in ourselves.
And we shall be far from pleading that because they are young,
some greater liberties may be allowed them in this or that thing.
Rather, we shall feel that as they are a part of ourselves,
the same divine law should be a rule for both them and us.

I have taken notice, that some parents, who seem to have learned, in degree,
the lesson of humility and self-denial,
as far as could be discovered by their outward appearance,
yet seem to have no aversion to their children`'s making a different appearance;
but will even introduce them into vane and worldly things while very young,
plainly manifesting they have a pride in seeing them so.
Such parents, notwithstanding their outward show, exhibit great unsoundness,
and that they themselves are not what they would pass for.
I sincerely wish that parents,
who indulge wrong liberties in their children by allowing them to deviate from that
pure simplicity and self-denial into which Truth leads all who follow it,
would consider the injury their children sustain thereby,
being placed in a variety of difficult and
dangerous situations with respect to temptations.
Indeed, inconsiderate tender youth,
through their aptness to crave the glittering things of the world,
and their imprudent parents indulging them therein, are, as it were, prepared for ruin,
unless divine mercy interpose.
Some parents have been pierced through with much sorrow by this means,
and have had great cause to repent when it was too late;
and there has been reason to fear that the blood of
their children will be required at their hands.

Some perhaps may think I am very sharp and severe upon parents,
insisting that it is not always their fault when children pursue wrong things.
This I have already granted,
and it is true that they are frequently very self-willed and ungovernable.
Such an argument has merit when children are of an age to become their own rulers,
and have ability to clothe and provide for themselves.
But I think it has little weight while their parents provide for them,
who not only have power to advise and persuade, but also to command and restrain.
Here a parent certainly may and ought to maintain absolute authority,
most especially in cases where the testimony of Truth is in danger of suffering.

It is very observable that Eli was greatly blamed for not restraining his wicked sons,
even though it plainly appears he much disapproved of their practices,
reasoned with them on that account,
and laid before them the deadly consequences of their evil conduct.
How very affecting it is, to consider the fearful calamities which came upon that house,
and also upon Israel, probably in some measure upon the same account.

The neglect and imprudent indulgence of parents in training up
their children is also a painful loss to the church,
as the consequence thereof tends greatly to obstruct the progress of Truth,
by standing as a stumbling-block in the way of serious inquirers.
When people of the world see that the undue liberties which they are called out of,
are indulged in amongst us, they are offended.
Oh! that parents, children, and all who are unfaithful,
and who easily allow the various branches of our Christian testimony to fall,
would deeply consider the mournful consequence
thereof in retarding the progress of Truth,
and grievously eclipsing the beauty of Zion!
Then I greatly hope a more living zeal and holy ardor would prevail,
and that the careless sons and daughters would arise,
shake themselves from the dust of the earth,
and put on the beautiful garment of holiness and Truth,
that she might become more and more a praise in the earth.

=== Now to Children

Having offered a few remarks concerning the important duty of parents,
it now remains to do the same respecting the indispensable
duty of children to honor and obey their parents in the Lord,
which is strongly enjoined in the holy Scriptures,
and is of lasting and indispensable obligation.

The command is, "`Honor your father and your mother,
that your days may be long upon the land which the Lord your God gives you.`"
Read Matt. 15:4. Mark 8:10. Luke 18:20. Eph. 6:2-3.
In those things which are consistent with the law of God,
no child can stand acquitted before the supreme
Judge for disobeying or dishonoring its parents.
This obedience and honor not only extend to yielding to what they command or direct,
but also to the preservation of a reverent awe and honorable esteem in the heart,
arising from love, which would on all just occasions cherish and protect them.
It is a sin of great weight to disregard and slight parents,
as appears by Duet. 27:16:
"`Cursed is the one who treats his father or his mother with contempt;`"
and Prov. 30:17: "`The eye that mocks at his father, and refuses to obey his mother,
the ravens of the valley shall pick it out, and the young eagles shall eat it.`"
Chap, 23:22: "`Hearken unto your father, and despise not your mother when she is old,`" etc.

On the other hand,
very notable is the kind and watchful Providence that attended those who feared the Lord,
and those who loved, honored and obeyed their parents; as Jacob, Joseph, Ruth,
Samuel and David; also the Rechabites (Jer. 35).
It would far exceed the bounds of my intention to particularize all
those excellent patterns and examples we are favored with the account of,
which are wonderfully adapted to instruct, encourage and improve the youth,
as well as others.

It is a very commendable, as well as a very profitable thing,
to be familiar with those sacred writings.
Remember what Paul said of his beloved son Timothy:
"`From a child you have known the holy Scriptures,
which are able to make you wise unto salvation, through faith which is in Christ Jesus.
All Scripture is given by inspiration of God, and is profitable for doctrine,
for reproof, for correction, for instruction in righteousness;
that the man of God may be perfect, thoroughly furnished unto all good works.`"
But let all duly consider, that profiting unto salvation by the sacred writings,
depends entirely upon the holy, living, powerful faith of Christ, which works by love,
purifying the heart.
It is by this that we come to see Him who is invisible,
and consequently to understand the precious mysteries of His kingdom,
as far as is proper and necessary for us to know them (which
is all that is lawful for us to desire).
There are many other good and profitable books,
but none in which is contained such a storehouse
of rich treasure and sublime heavenly mysteries,
wonderfully wrapped up and concealed from earthly wisdom and carnal understanding.
For none can know the things of God, without the assistance of His Spirit,
as appears by 1 Cor. 2:10-15, and many other texts.

Great has been the concern of the spiritually-living in the church (as
appears by frequent and very pressing affectionate advice,
caution, and counsel to the youth),
both to read the holy Scriptures and other profitable books,
and to carefully refrain from all other books which have the
least tendency to draw the mind out from the holy fear of God,
and from a sober, virtuous course of life, or those which are solely for amusement,
being entirely unprofitable.
Time is very precious, short, and uncertain;
it should therefore be carefully improved to the soul`'s everlasting advantage.
Moreover, youth should learn early to yield strict and
careful obedience to the divine Monitor within,
as well as to their parents and all who have the rule over them,
carefully shunning the vain and unprofitable amusements,
as well as the corrupt conduct of the world.
I earnestly advise all to avoid everything in both dress and address,
which might have the least tendency to draw them into a league or
friendship with "`the children of the land,`" or with the depraved
degenerate world that wallows in pollution and great defilements,
lest they should be drawn aside and defiled, as Dinah was,
by going out to see the daughters of the land (see Genesis 34),
and as the children of Israel were,
by their woful intimacy with the daughters of Moab and Midian.
And do not forget the dreadful fall of Solomon, the wisest king, who,
by contracting an intimacy with those who were strangers to God and His holy covenant,
had his heart drawn away from the living and true God,
and so greatly debased himself as to bow down to their paltry dumb idols.
Time would fail to recapitulate the mournful instances recorded in the holy Scriptures,
and other authentic accounts,
concerning the hurtful consequences of God`'s people mixing and joining with the nations.
It is their safety to be separate and to dwell alone, for He says,
"`Come out from among them and be separate.
Do not touch what is unclean, and I will receive you.`" (2 Cor. 7:17)

Our youth^
footnote:[He means the youth within the Society of Friends]
have been highly favored with a living, powerful ministry,
which has often reached the witness of God in their hearts.
What a great favor this is when we consider that the greatest part of Christendom,
almost ever since the apostles`' days,
have deprived themselves of this by substituting human wisdom and learning in its place.
Thus the panting,
thirsty souls among them could meet with little more
from their ministers than the muddy waters of Babylon.
Indeed, such ministers could not direct seeking hearts to the pastures of Christ`'s flock;
but instead darkened counsel by a multitude of words without knowledge,
and made void the commandments of God by the precepts, inventions and traditions of men.
In what a blessed time has your lot been cast,
even when evangelical light and truth has manifested itself in perfect purity!
Oh! that our youth would consider and deeply ponder in their hearts,
that notwithstanding the great and earnest labors bestowed in godly love and zeal
for the preservation of the Society in the way of truth and righteousness,
yet very sorrowful and obvious has been the declension in practice of many amongst us.
A mournful flood of undue liberties has flowed in;
many have made grievous advances in those corrupt,
perishing pleasures and trifling amusements,
which our truly pious predecessors wholly denied and turned their backs upon,
having left us large and living testimonies, by way of warning and caution,
to carefully avoid being entangled with such yokes of bondage.
These things have prevailed for lack of abiding in the fear of God,
and not duly considering that He is ever present, beholding all our words and actions,
be they ever so much concealed from the view of mortals.
When the mind is turned to His pure witness in the heart, we find reproof,
correction and judgment, for giving way to wrong things;
and as the youth abide in subjection to this,
they will be afraid to transgress its pure law in the heart,
which they will find to agree exactly with the precepts and
injunctions recorded in Scripture respecting their duty to God,
their parents, and all mankind.

The reason why many who see their duty, fail in the performance of it,
is their departing from "`the perfect law of liberty,`"
or the "`law of the Spirit of life`" in their hearts.
They may be informed concerning their duty by outward means and laws,
but the ability to perform is only to be found arising from the inward law,
agreeably to Rom. 8:2; "`For the law of the Spirit of life in Christ Jesus,
has made me free from the law of sin and death.`"
In obedience and humble subjection to this holy law, youth would enjoy that pure peace,
heavenly serenity and sweet consolation of soul,
which infinitely surpass all the treasures and pleasures of the earth,
and would have a well-grounded hope of a happy eternity.
It is the adversary who leads to hardness of heart and a self-willed,
rebellious state of mind.
This is sadly observable in some of the youth, who, by their uncontrollable dispositions,
administer great sorrow and anxiety to their parents and friends,
being puffed up with the vain conceit that they are more capable of judging
for themselves than those of far greater wisdom and experience.
In this way, many, it is to be feared, have rushed on to the ruin of both body and soul.

Very great is the danger when the young and inexperienced are proud and opinionated.
This naturally raises them above instruction,
putting them out of the way of being truly profitable, either to themselves or others.
Such, unless their hearts are mercifully turned by a supernatural power,
are never likely to be fit for governing families,
or to act as members in the church of God.
For it often appears that, unless their unmortified wills and tempers are bowed to,
however unreasonable,
they will break the peace of Society and violate its wholesome order,
being like the unsubjected "`bulls of Bashan.`"
And when any of these assume the outward form of religion,
and take upon themselves to be active members, without a change of heart,
they prove a painful burden to the living members of the body.

I do therefore, in much affection and desire for the welfare of tender youth,
caution and warn them to carefully avoid the company and conversation of all who,
though under the same profession of Christianity,
disregard their parents and those who have the rule over them,
or who slight or speak contemptuously of their superiors, both natural and spiritual.

The fear of the Lord is the beginning of wisdom,
and it is this which makes and keeps the heart clean.
Learn it in a tender age,
and by it you will be taught to remember your Creator in the days of your youth; and,
agreeably to the injunction of our blessed Lord,
you will find that in seeking first the kingdom of God and His righteousness,
all things necessary will be added.
Divine wisdom, as it is sought for and obeyed,
will direct your steps in the course of this short pilgrimage,
in the choice of a proper helpmate, and in all other affairs of importance.
Watchful Providence will indeed be over you in care, guidance, and protection,
if you look to Him and live in His fear.

It greatly behooves you to look diligently to the footsteps of Christ`'s companions,
who walked with Him through many tribulations,
having washed their robes and made them white in the blood of the Lamb.
Be truly contented with that low, humble, self-denying way which you see they walked in;
you can never revise or improve it.
If you seek more liberty than this path allows, it will only bring darkness,
pain and vexation of spirit upon you.
Read the writings of Friends in early times,
and observe how wonderfully the power and love of God was with them,
and how marvelously they were protected amidst the raging,
foaming waves of earthly powers, combined to lay waste the heritage of God.
What encouraging and excellent accounts left upon record for us,
concerning the powerful overshadowing of heavenly love
and life in their religious assemblies,
and the glory of God shining forth amongst them!
This glory and power, through the mercy of God, is not yet departed;^
footnote:[This was written in 1764]
though there have been some withdrawings of it.

Dearly beloved youth, lay to heart the great slackness of zeal which appears in too many;
the dimness, flatness, and painful gloominess,
which has spread over our assemblies in this day.
This is indeed hard to break through,
and it many times deprives us of experiencing
the heavenly places in Christ Jesus our Lord!
It is not of Him that we are in this condition, but it certainly is our own fault,
because wrong things are allowed to prevail.
Oh, that our youth may be stirred up in a godly zeal
to cry out fervently with the prophet Elisha,
"`Where is the Lord God of Elijah?`"
and be vigilant in ardent endeavors to be endued with the same Spirit,
and to succeed those honorable worthies who are now
removed from works to receive a blessed reward.
Consider that the business of your day is to come up in a faithful succession,
maintaining the cause and testimony of God, left with you by your ancestors.
Stand fast, therefore,
in the liberty purchased for you by great sufferings and the shedding of innocent blood.
Be afraid to trample upon it,
which all certainly do who turn away from the Truth as it was received,
held forth and maintained by them.
May Truth be very precious in your eyes from generation to generation,
until time shall be no more!
Those who lightly esteem it, turning their backs upon it,
violating its blessed testimony in its several branches,
will (unless they repent) surely be rejected and cast off,
as being unworthy of so great an honor as that of holding
forth a standard of truth and righteousness to the nations;
and others will be called and chosen for that great and glorious work.
The Lord is able to raise up those who may be compared to stones,
and to make them Abraham`'s children, by doing his works;
while those who might have been the children of the kingdom, may, by disobedience,
provoke Him to exclude them.

I shall conclude this affectionate address to our youth with the words of Christ,
by His faithful servant John, to the church in Philadelphia, "`Behold I come quickly;
hold that fast which you have, that no man take your crown.
Him that overcomes, I will make a pillar in the temple of My God,
and he shall go no more out; and I will write upon him the name of My God,
and the name of the city of My God, which is New Jerusalem,
which comes down out of heaven from My God: and I will write upon him My new name.`"
