[#section-2, short="The Nature and Necessity of New Birth"]
== Section 2

[.chapter-subtitle--blurb]
Observations Concerning the Nature and Necessity of the New Birth

The doctrine preached by our Lord Jesus Christ to Nicodemus,
of the necessity of being born again, John 3:3-8.,
and what is delivered by John the Baptist concerning
the baptism of Christ with the Holy Spirit and fire,
being the same in substance as what is set forth by the prophet Malachi,
under the lively metaphors of a refiner`'s fire, a purifier of silver, and fuller`'s soap,
with many other similar passages of the holy Scriptures,
although of the utmost importance to be rightly understood and deeply pondered by all,
is by the generality of professing Christians much overlooked and neglected.
That which alone can lay a sure foundation for happiness, both in time and eternity,
is hardly thought of by many, at least not with desire,
or with any degree of seriousness,
unless it is to shun and evade the force of that power which would
separate them from their beloved lusts and fleshly gratifications.

Many and exceedingly absurd have been the conjectures
and dreams of mankind on this subject,
but all are to the same purpose: to shun the cross, so that the corrupt self,
with all its seeming treasures and adornments, might be saved.
This self, in many, has been more fond of a religious kind of ornament and treasure,
than any other sort;
and the subtle transforming spirit has not been lacking
to plentifully furnish with temptations to it,
any whose minds have a religious inclination.
Antichrist, as an eminent author observes,^
footnote:[i.e. Isaac Penington]
can bring forth in his church a likeness or imitation
of everything that is to be found in Zion.
O then! how greatly it behooves mankind to press after true certainty,
since nothing can possibly land the soul in a more deplorable state,
than a mistake of this kind in the great work of salvation.

But some are apt to doubt whether such a thing as an
infallible evidence of our adoption is attainable here;
though so fully asserted in the holy Scriptures.
This is not to be wondered at, with respect to those who are in the natural,
unrenewed state; seeing that the natural man, according to Paul`'s doctrine,
"`understands not the things of the Spirit of God, neither indeed can he know them,
because they are spiritually discerned.`"
But I am persuaded that none who have really experienced the new birth brought forth,
remain doubtful or unsettled concerning this important truth.
It seems to me unreasonable to suppose Infinite Goodness,
who knows the fallibility and great weakness of His creature man,
should leave any whose hearts are fully devoted to yield obedience to His will,
under a mistake with regard to these things, or ignorant of His divine approbation,
upon a careful discharge of their duty to Him.
This holy evidence in faithful souls is indeed the white stone,
and in it a new name is written which none know save those who receive it.
Here, indeed, there is an assurance that their names are written in heaven,
from which arises a joy which is unspeakable and full of glory.

A sense of the wrath of God against evil,
often makes deep impressions upon the minds of many,
so that in painful remorse they are ready to cry
out for mercy and forgiveness of their sins.
This conviction upon the mind of man, that he has displeased his Creator,
neither does nor can proceed from anything in man besides the
pure witness of God which He has placed there.
It is therefore quite reasonable to conclude that this same divine Witness,
upon our faithfully discharging the duty we owe
to God (according as it is made manifest to us),
will impress our minds with a sweet sense of divine approbation,
agreeably to Rom. 8:16;
"`The Spirit Himself bears witness with our spirit, that we are the children of God.`"
With many other passages in Scripture of like import.

When any are really disposed to follow Christ,
great care should be taken in their first setting out.
Many have been marred upon the wheel, for lack of patience to endure proper tempering;
endeavoring to be formed into useful vessels before
they have passed through the necessary operation.
This has been for lack of thoroughly knowing themselves.
Everything that appertains to the creaturely will,
and a forwardness of desire to choose and act for itself, must die upon the cross,
and there must be a remaining as without form and void, under the Lord`'s dispensations,
until the effective Word says, "`Let there be light!`"
This, by His own power, makes a perfect separation between the light and darkness in man,
even as He did in the visible world.
Until this is really experienced,
man is not in a condition to be placed upon the
wheel to be formed into a vessel of honor;
and there must also be a time for drying, and enduring the furnace.

These wonderful operations, which I have only just touched upon in an allegorical way,
make very deep and lasting impressions upon all who have experienced the
nature of that regeneration without which none can see the kingdom of God.
When any have come thus far,
there will be no occasion to make use of dreams and uncertain
conjectures in forming a judgment concerning their adoption.
The divine birth which is raised in them, naturally cries, Abba, Father!
And when He is pleased to appear (for which they are taught to wait in the patience),
they have no room to doubt of having passed from death unto life,
or being translated from under the power of darkness
into the kingdom of the Lord Jesus Christ,
which consists in "`righteousness, and peace, and joy in the Holy Spirit.`"

The great danger of man`'s being deceived, lies in the mysterious workings of Satan,
who has a stronghold in those who, upon their first awakening by the call of Christ,
have not allowed His power so far to prevail as to make
them willing to part with all for His sake.
There is something exceedingly reluctant in the strong
spirit and will of man to fall into nothingness of self,
and to be wholly given up to be guided and upheld by another.
This in part arises from the excellency of his created frame,
and the nobility of his understanding,
finding in himself natural abilities capable of effecting great things,
and thus he assumes (till his eyes are opened and enlightened from above) that he
is equally capable of comprehending what relates to the world to come.
Therefore, instead of wholly ceasing from his own will,
and relying altogether upon the guidance of the Holy Spirit, he is very apt to be active,
imagining that God will be pleased with his diligence in the
performance of what he apprehends to be religious duties;
such as praying, singing, preaching, or seeking to join others in those performances;
often telling his experiences, and hearing those of others.
However, it would be abundantly more pleasing to the Almighty, and profitable to himself,
to lay his mouth in the dust, silently commune with his own heart, and be still,
until it pleased the Lord to send forth His light and His Truth,
that the poor helpless creature may move and act in a truly spiritual sense,
with his understanding informed by God.
For everything that is done in religion and
worship without the guidance of the Holy Spirit,
is will-worship and idolatry;
for if the Spirit of Christ does not move and actuate us in all religious performances,
we are susceptible to the influences of the spirit of antichrist.

Some perhaps, by way of excusing themselves,
are ready to call it "`enthusiasm`" and "`presumption`" in those who assert
the necessity of being influenced by the Spirit of Truth in their religion,
insisting that there is no such thing in our time,
though they readily acknowledge it was so in the apostles`' days.
But these can give no good reason why the divine power and
efficacy of the Holy Spirit should forsake the true church,
since mankind is most certainly in the same need of it,
and the nature of God`'s dispensation is now the same as it was then.

Common prudence teaches us to examine carefully into the
clearness and validity of our titles to earthly estates,
that we may be fully satisfied we are not deceived or
imposed upon by false glosses and misleading claims.
Shall we be less concerned about that which is of infinitely greater importance; namely,
our title to an everlasting inheritance?
Man should be very watchful over his own heart,
which is always apt to be partial towards itself,
and through the transformations of Satan,
to soothe and flatter into an apprehension that
he is in the way to everlasting happiness,
when in reality it is quite otherwise.
The criterion by which he forms a judgment of
himself may be the same as that of the pharisee,
who went up to the temple to pray,
or rather to recapitulate his own supposed excellencies.
He perhaps measures himself by himself,
or by comparing his principles and conduct in life with those of others.
But nothing should be received as a standard in this very important case,
but the stamp of divine approbation sealed upon the heart by the Holy Spirit;
agreeably to Rom. 8:14-16;
"`For as many as are led by the Spirit of God, they are the sons of God.
For you have not received the spirit of bondage again to fear;
but you have received the spirit of adoption, whereby we cry, Abba, Father.
The Spirit itself bears witness with our spirit, that we are the children of God.`"

Having offered these hints by way of caution,
that all into whose hands they come may examine themselves without partiality,
lest they fall inadvertently into an irretrievable
mistake respecting the salvation of their own souls,
I shall now endeavor to set forth, from my own experience,
a little of the nature of that new birth without which none can see the kingdom of God,
and consequently none can be true members of His church.
For, it cannot be supposed,
that a person wholly unregenerate is properly qualified for the
performance of any religious duty or service in that kingdom,
which he does not so much as see.

I have, by experience from my childhood,
found two spirits or seeds striving in me for mastery or rule.
I have discovered them to be irreconcilable enemies one to the other;
and that I could not serve them both at the same time.
I had an understanding given to me,
whereby I knew one of those seeds was a manifestation
of the all-powerful inexhaustible source of Goodness;
and the other, which had in a manner leavened the whole lump,
was of a wicked and diabolical nature.
By means of this corrupt leaven, I had a strong bias to evil of many kinds; nevertheless,
I often found the good Spirit striking at the evil, as an axe laid to the root thereof,
agreeably to Matt. 3:10,
in order to destroy that which deprived the Heir of all things of His inheritance.
I was long in a kind of suspense, unresolved with which to join;
yet saw all depended upon my determination, and that I had full power of choice.
On the one hand, when the awakening visitations of God`'s Spirit were upon me,
it appeared very dreadful to provoke an omnipotent Being of unmerited
kindness and mercy to cast my soul into everlasting perdition.
On the other hand (especially when those heavenly impressions had somewhat worn off),
it was next to death itself to yield up all my sensual gratifications,
and to expose myself to the scorn and contempt of the world.
However, in process of time, the Lord in gracious condescension broke in upon my soul,
by His judgments mixed with mercy, in such a powerful manner,
that I was made willing to yield to Him, come life or death.
Indeed I looked for nothing else at that time,
but expected my frail body would sink under the weight
of the unspeakable distress which was upon me,
and that my sinful soul must be centered in a state of everlasting misery.
Then my cry was, like that of Saul, with trembling and astonishment,
"`Lord! what will You have me to do?`"
Then there was no holding back or secret reserve,
but whatever was called for was given up with readiness, this being all I could do.
As to performing truly religious duties, I had them all to learn,
though I had been trained up from my infancy in a strict religious way by godly parents.
But the very best outward helps, and the most consistent set of religious principles,
when only professed, cannot at all enrich the soul with heavenly grace.

By carefully inquiring of the Lord,
I clearly perceived my business was to watch and pray continually;
to commune with my own heart, or the Witness of God there,
that I might receive fresh instruction and help as I had need.
Self-denial and taking up the cross daily was to be my constant employment;
in doing which, I had much inward peace and comfort,
and a well-grounded hope that I should thereby find (in
the Lord`'s time) the body of sin so weakened,
that the yoke of Christ would become easy, and His burden light.

In order for a happy progress in the life of religion, it is necessary,
by abiding in the divine light,
to preserve a clear and distinguishing sensibility between the flesh and the Spirit.
This cannot be done without great care and a steady waiting upon the divine gift.
If the eye turns from this, it is blinded by the darkness,
and then man is liable to be misled by a counterfeit light,
and the various resemblances which Satan will
cast in his way for guidance and instruction,
persuading him all is well and right.
To be so misled and therein established, is a truly deplorable state;
for it is very unlikely that such a person will
ever be persuaded to believe they are mistaken,
as they often deride whatever appears doubtful concerning their own religion and worship.
This was evidently the case with a set of professors of uncommon outward
sanctity and punctual exactness in the exterior of their religion,
in the time of our Savior`'s personal appearance upon earth; notwithstanding which,
these very people were manifestly the most
inveterate enemies Christ had amongst mankind.

Seeing therefore, that frail mortals are liable to such dangerous mistakes,
how exceedingly circumspect and watchful ought all to be!
And what frequent and strict scrutiny ought they
to make into the state of their own hearts,
which can be known in no other way but as the Lord is
pleased to send forth His heart-searching light!
This is a great favor, which none receive but those who are turned from the darkness,
and are fervently concerned to put away all of its works.
Very gross is the deception of those who imagine the
whole work of regeneration to be instantaneous.
This can be nothing else than a delusion of Satan,
to settle people at rest in a state of self-security as soon as he can.
Oh! what a length of time it takes to work out that rebellious, stiff-necked,
backsliding nature, which was born in Egypt,
before the new generation is raised up that is fit to enter the promised land!

From what is before hinted, it may be understood, that the good Seed or Holy Spirit,
arising into ascendency in us over the evil seed,
and leavening the soul into its own nature,
is essentially a "`being born again with water and the Spirit,`" or
being "`baptized with the Holy Ghost and fire,`" or man`'s enduring
the operation of the "`refiner`'s fire and fuller`'s soap,`" and being
purified as silver.
All of these metaphors signify, in a very instructive manner,
the different operations of the Holy Spirit, which, to the willing soul,
is sometimes like water, to wash and bathe in, and also freely to drink of;
and at other times like a refiner`'s fire, to purge away the filth and dross,
that man may be as pure gold,
prepared to receive the image and superscription of the King of heaven; that so,
wherever he goes, or whatever he does, all who have their eyes opened,
may see whose subject he is.

It is very observable that the prophet Malachi,
when he had set forth the nature of the new birth,
breaks out in the fourth verse of the third chapter in this way;
"`Then shall the offerings of Judah and Jerusalem be pleasant unto the Lord,
as in the days of old, and as in former years;`"
which clearly implies man`'s unacceptable
state with his Maker in religious performances until he has known the
cleansing and refining operations before mentioned.
What then will become of those who have intruded themselves into religious services,
and amongst His faithful followers, without having on the wedding garment!
These would gladly pass for His people,
but they have not trodden the path of regeneration,
or passed through the pangs of the new birth.

When man has, through the powerful prevalence of the Holy Spirit,
obtained victory in a good degree over evil,
his soul abounds with evidence and tokens of his
happy attainments through the Lord Jesus Christ,
to whom, with the Father, through the influence of the Holy Spirit, praise,
adoration and thanksgiving are offered up as incense with acceptance.
Such a one enjoys an abundant flow of heavenly love towards
those who are begotten of the same everlasting Father,
agreeably to 1 John 3:14;
"`We know that we have passed from death unto life, because we love the brethren.`"
It is then become his food and drink to do the will of God.
He looks with indifference upon worldly enjoyments when
compared with the joys and concerns of spiritual things.
His body, soul, and outward substance are offered up to the great Giver,
being given up to spend and be spent for the promotion of Truth,
according to the Lord`'s requirings.
These particulars, and much more than I can set forth,
are the result of a humble and steadfast obedience to
the heart-changing power of the Spirit of Christ,
which produces great peace and heavenly solace,
whereby the true disciple is encouraged to persevere.

Oh, that mankind would come clearly to see the necessity of
both beginning in the Spirit and walking therein,
according to the advice and practice of the primitive Christians!
Then they would no longer fulfill the lusts of the flesh,
for the spirit that lusts to envy, and seeks vengeance, would be slain.
Outward wars and fightings would cease in due course; for when the cause is taken away,
the effect would be no more.
A selfish, covetous spirit,
which seeks undue advantage to the injury of others would be purged out,
and here we would have power to love our neighbors as ourselves,
and to do unto all as we desire them to do unto us.
All of these and many more good fruits,
would spring up naturally from the new creation in Christ Jesus our Lord.
But those who have not experienced this groundwork in themselves,
and lack the virtues of the Holy Spirit which are set forth in the Scriptures of Truth,
are blind and cannot see that it is just as possible now to attain
those exalted Christian virtues as it was in the apostles`' days.
So it is that imaginations, dreams,
and conjectures abound amongst carnal Christians concerning the means of
obtaining that salvation which is only to be known by being born from above.
Some say, Lo! here is Christ!
Others say, Lo! he is there!
But alas, they still evade the cross.
Indeed, were the cross not in the way, they would surely embrace the right thing,
for it is so clearly set forth and described in the holy Scriptures.

The views of many, both Catholics and Protestants, concerning the nature of salvation,
are exceedingly obscure and carnal,
making the sprinkling of infants with a little water
(which they call baptism) essential thereto.
The manner of their expressing themselves on this subject in their confession of faith,
seems to make this ceremony all, or the chief thing,
that is intended by being born from above;
or at least that the operations of the Spirit to that
end are infallibly connected to the sprinkling of water.
Catholics say,
"`We must believe that Jesus Christ has instituted in His church seven sacraments,
or mysterious signs and instrumental causes of divine grace in the soul: baptism,
by way of a new birth, by which we are made children of God and washed from sin:
confirmation,
by which we receive the Holy Spirit by the imposition
of the hands of the successors of the apostles,`" etc.^
footnote:[Catholic Manual of Spiritual Exercises, page 4.]
The Protestant church of England, in their confession of faith, says,
"`In my baptism,`" by which they mean the sprinkling of infants,
"`wherein I was made a member of Christ, a child of God,
and an inheritor of the kingdom of heaven,`" etc.
After an infant is sprinkled, the priest says, "`Seeing now, dearly beloved brethren,
that this child is by baptism regenerate and grafted into the body of Christ`'s church,
let us give thanks,`" etc.
And again, "`We yield You most hearty thanks, most merciful Father,
that it has pleased You to regenerate this infant with Your Holy Spirit,
to receive him for Your own child by adoption,
and to incorporate him into Your holy church,`" etc.^
footnote:[Catechism and public baptism of the Church of England.]

These are clearly mere evasions.
Man hates death to self,
and had rather look in any direction but that which is
likely to strip him of all his beloved treasure.
However, if he were not so very blind and ignorant concerning his true interest,
he would easily see that his supposed loss would make way for his greatest gain.
This unhappy reluctance to the true way,
has put man upon straining and inventing to find an easier way to the kingdom of God;
a way that includes becoming heir of two kingdoms, and serving both God and mammon,
though we are assured by our Savior that this is impossible.

Many would eagerly imagine that man may be saved merely by the
imperceptible imputation of Christ`'s righteousness;
which, if it were true, would be a very palatable doctrine to a multitude of self-lovers.
Some, who do not agree with this opinion, but believe that men must repent,
and experience the evil purged out by the Spirit of judgment and burning,
do yet put off this great work,
resting in a kind of hope that they shall thereby be fitted
for everlasting happiness some time before they die.
These lean much upon the great mercy and long-suffering of the Almighty,
catching eagerly at the sudden conversion of Paul and of the thief upon the cross.
But oh, how exceedingly inconsiderate are such delays!
A saying of Chrysostom is worthy to be noted: "`God promises mercy to penitent sinners,
but He does not promise them that they shall have so
much time as tomorrow for their repentance!`"

There are others who imagine that their regeneration is effected in an instant;
and in order that their deception may be effectual,
the false prophet causes fire (so to speak) to come down from heaven in their sight;
and he that is prince in the airy region,
raises vehement heats and convulsions in their passions.
This they call the workings of the Spirit upon them for their conversion;
immediately after which a kind of false heaven is formed,
in which they take their rest with a seeming security,
erroneously supposing that their calling and election are now made entirely sure,
and that they can never fall from saving grace.
Oh! how dangerous is such a security!

Much more might be written concerning the many false rests and
visionary heavens which poor mortals
(through the subtlety of Satan and their own inattention)
are deluded to sit down in;
all of which might be happily prevented were
they to enter into the sheep-fold by Christ,
the only true door and way to the everlasting kingdom,
which is opened and prepared for the soul to
travel in by submitting to His inward appearance.
He will certainly count all thieves and robbers,
who come into His church by any other way.

What an abundance of robbery is found in you O Christendom!
Oh how you steal the name of Christ, and the former experiences of God`'s people,
to live upon, and also to feed one another!
What a multitude of unwholesome and barren pastors, with poor, lean, starved flocks,
amongst most or all societies of Christian professors!
Yes, it is their poor,
low condition (with respect to religion) that
induces them to put forth their hands to steal.
Can the God of justice and truth delight in a stolen burnt-offering?
No, such sacrifices are an abomination to Him.
His regenerate ones, though often tried with great poverty of spirit, dare not steal,
for they know that nothing will find acceptance with Infinite Goodness,
but that which is of His own immediate begetting.
Yes, this will be a sweet savor to Him, though it be but a sigh or a groan;
which may be compared with the acceptable offering of the poor under the law,
of a pair of turtle doves, or two young pigeons;
or to the widow`'s two mites cast into the treasury.
And those poor, humble, dependent ones,
who are made perfectly honest by the just and upright Seed prevailing in them,
and waiting the Lord`'s time, are often furnished with larger offerings,
and do greatly increase with the increase that comes from God.

To conclude this subject, I shall thus sum up the matter--that man`'s great business,
upon his first awakening out of the sleep or stupefaction of sin,
is passively to yield himself into the hands of his faithful Creator,
that He may be pleased to work in and upon him
both to will and to do of His own good pleasure.
He must, with the utmost care,
endeavor to abide in that which enables incessantly to pray,
"`Your kingdom come, and Your will be done on earth as it is done in heaven.`"
When this is the bent of his heart,
the grace of God is a sufficient guard or defense against all
the subtle attempts of Satan to beguile and deceive.
The most crafty devices of the adversary can never
prevail to pluck such a one out of the Almighty`'s hand;
and by abiding therein, he is created anew in Christ Jesus unto good works,
having spiritual senses given,
that he may continually exercise them in discerning between good and evil.
His heart being made pure, in a good degree,
by the sprinkling of the most precious blood of Christ,
His constant care (through divine assistance) is to preserve it so,
that the Lord may be pleased to tabernacle with him, and be made unto him wisdom,
righteousness, sanctification and redemption.
These passive,
upright souls receive from Him those qualifications
which enable them to co-work with the Spirit,
and to perfectly understand the proper business of their day,
both as strangers and pilgrims in the world,
and as living members of the body of Christ.
