[#section-3, short="The Nature of True Worship"]
== Section 3

[.chapter-subtitle--blurb]
Relating to the Nature of True Worship;
with Some Remarks on the State of the Society of Friends,
both in Early Times, and Now

The nature of acceptable worship is set forth by our Lord and
Savior Jesus Christ in a manner well adapted to the subject,
namely, that it is to be performed in spirit and in truth.
The reason is given, "`because God is a Spirit;`" and therefore,
"`they that worship Him, must worship Him in spirit and in truth.`"
This is not the ceremonial, shadowy, and typical worship of the Jews,
which was dispensed to them because of weakness,
but rather the more excellent worship of the Gospel dispensation,
whereby man has a "`better hope,`" nearer access to the Divinity,
and a better knowledge of himself.
Here such a brightness of heavenly glory appears, as to cause all signs, figures,
and types to vanish away, and worship is to be performed in the truth,
and real substance of all that was typified and
prefigured by the ceremonial law of Moses;
for the righteousness of that law is fulfilled
in those who walk and worship in the Spirit.

The soul must bow in perfect sincerity, humble prostration,
and a deep inward sense of its own frailty, lack, and unworthiness,
being at the same time deeply impressed with a living
sense of the Lord`'s adorable greatness and goodness.
From this sensibility renewed upon the mind by Him who is the sole object of worship,
thanksgiving and praises ascend for the multitude of His mercies received,
along with reverent prayer (either mental or vocal,
according as the mind feels itself influenced or directed by the holy anointing)
for the continuance of His gracious preservation in the way of righteousness;
agreeably to Eph. 6:18. "`Praying always with all supplication in the Spirit,
and watching thereunto with all perseverance and supplication for all saints.`"

It is clearly to be understood by what our Lord
said to the woman of Samaria in John chapter 4,
that acceptable worship is not confined to any particular place, mode, form, or ceremony;
which was a deception that mankind had generally
fallen into and greatly needed to be drawn from,
being then, as well as now,
apt to please himself and rest satisfied with exterior performances.
Although some of these outward shadows were
indeed dispensed to the Jews in condescension,
these were never given with the intention of substituting spiritual worship,
nor were they at all acceptable without a humble, bowing of the soul.
But here our Lord clearly shows that the outward worship was to be laid aside,
and not to continue any longer in His glorious spiritual dispensation.
But it could hardly be expected that so great a mass of
outward observations could be all cast off at once;
yet in the course of the apostles`' days,
the church was progressively brought out of them,
as appears by the very few requirements laid upon the Gentiles (see Acts 15:22-29).
But alas! the Christian church (so called),
instead of leaving all and becoming purely spiritual,
gradually decayed as to life and power,
and increased in ceremonies and outward observations,
until she became as full of them as ever the Jewish church was.
Then she got full possession of the outward court,
having nothing to enjoy but her own inventions, and nothing to glory in but Babylon,
which she had built instead of Zion, until her measure should be filled up,
and her determined overthrow take place.

Paul says to the Philippians, "`For we are the circumcision,
who worship God in the Spirit, and rejoice in Christ Jesus,
and have no confidence in the flesh.`"
Which circumcision is here intended, appears from Rom. 2:28-29 and Col. 2:11,
namely, "`the circumcision made without hands by putting of the body of the flesh.`"
That the generality of Christian professors, of every denomination,
have lamentably deviated from this kind of worship,
requires not much insight to discover.
And though the great Author of the Christian religion has so fully
expressed His will and pleasure in this most important point,
yet many will not be satisfied without a kind of
worship in which the fleshly part can be active,
and which has something in it to amuse the outward senses.
These would worship the Most High with human abilities or the work of men`'s hands,
and by an unjustifiable reverence for old mass houses and other places of worship,
calling them churches, houses of God, holy places, etc.
But such professors of Christianity maintain a doctrine quite
contrary to the testimony of that holy martyr Stephen;
who said "`However, the Most High dwells not in temples made with hands,`"
and that of the great apostle of the Gentiles,
who told the Athenians, "`God, who made the world and everything in it,
since He is Lord of heaven and earth,
does not dwell in temples made with hands.
Nor is He worshiped with men`'s hands,
as though He needed anything, since He gives to all life, breath, and all things.`"

Most Protestants, though they have cast off much Catholic superstition,
still retain some outward ceremonies and observations which are very
unsuitable to the spirituality of the Gospel dispensation.
In support of these things they have no divine authority or warrant,
except what is patched together from the example of some in the primitive church, which,
being at that time just arising out of a load of outward ceremonies,
was not wholly weaned from everything of that kind at once;
and therefore a few shadowy things were for a time condescended to.
For although the new covenant church had a very glorious beginning,
and abounded with heavenly power in order to make her way in the world,
yet this was but the morning of the Gospel day;
and as the Sun of Righteousness
(who rules the everlasting day of God`'s salvation)
rose higher and higher,
she was to put on all her beautiful garments to make herself ready for the bridegroom,
and by a gradual increase of clear discoveries,
was to grow into a maturity of wisdom and ripeness of judgment.

Our Lord clearly intimates the great danger of tacking anything of
the old ceremonial dispensation to the new Gospel dispensation,
showing they would by no means agree,
or safely subsist together (See  Matthew 9:17).
This the experience of many generations fully declares.
Oh, what rents and schisms there have been by means of clinging to
and pleading for some patches of the old garment!

Yet there has been a godly travail and an ardent labor preserved by the true church,
even through the darkest ages of superstition
and idolatry (though hidden from carnal eyes),
that she might cast off this heavy, eclipsing mass of outward observations.
There were many who, through divine power, rose up against it,
especially in opposition to the grossest and most grievous errors and superstitions.
But the most extraordinary of these reformations,
as to its consistency with the unmixed purity of the Gospel,
was about the middle of the last century +++[+++beginning in the 1650s],
when evangelical light and truth broke forth without
the blending of ceremonies and outward observations.
And when the Lord, by His overruling power,
had erected this blessed standard of simple truth and pure
righteousness +++[+++through the early Society of Friends],
many thousands flocked to it, and spoke the language set forth in Song of Solomon 6:10;
"`Who is she that looks forth as the morning, fair as the moon, clear as the sun,
and terrible as an army with banners?`"
Terrible indeed they were to the man of sin, the son of perdition,
being mighty instruments in the Lord`'s hand to reveal him.
Yes, they were a great annoyance to the merchants of Babylon,
and to those who enriched themselves by her superstitious merchandise which
multitudes had purchased because of her witchcraft and enchantments.
These sons and daughters of light endured a great fight of affliction; but through all,
with patient but undaunted firmness, maintained their ground,
and were made victorious through sufferings, as was the Captain of their salvation.
The everlasting Gospel was preached by them in
demonstration of the Spirit and with great power;
in substance as it was to be preached after the apostasy, "`Fear God,
and give glory to Him; for the hour of His judgment is come:
and worship Him that made heaven and earth,
and the sea, and the fountains of water.`" (Rev. 14:7)

This was indeed a coming to the substance,
after men had wearied themselves with an abundance of toil,
catching nothing but vanity and vexation of spirit.
And with those who receive this Gospel,
as it is preached according to its true intent and meaning,
there is no room to evade the cross of Christ, which is the power of God unto salvation.
There is no liberty here to retain a few ceremonies for decency`'s sake,
but all are compelled to embrace the substance,
not daring any more to touch the beggarly elements,
which were so prostituted and defiled during the long night of apostasy.
The virgin daughter of Zion is well assured that the Bridegroom of her soul
will never more appear to her in these uncertain and polluted things,
which have been, and yet will be more and more terribly shaken,
and eventually pass away as a scroll; that those things which can never be shaken,
may remain, agreeably to Rev. 21:1; "`And I saw a new heaven, and a new earth;
for the first heaven and the first earth were passed away; and there was no more sea.`"
There was no more sea; nothing unstable, fluctuating and uncertain;
nothing of that element from which the beast arises,
and therefore no danger of a beast rising from there any more.
The second, third and fourth verses of the same chapter,
wonderfully set forth the glory of the New Jerusalem coming down from above,
the tabernacle of God being with men, and God`'s dwelling with them.
Here the Lord wipes away all tears from their eyes, and there shall be no more crying,
sorrow and pain, because the former things are passed away.
There was no more sea;
all is purged away which was the cause of those dreadful
calamities and miseries set forth in this divine revelation,
by opening the seven seals, sounding the seven trumpets,
and pouring out the seven vials full of the wrath of God, who lives forever and ever.
The fifth verse says,
"`And He that sat upon the throne said, '`Behold, I will make all things new!`'`"
Now there is nothing of the old garment, nor any old wine,
to tear and break to pieces the new garment and the new wineskins.
Oh! glorious Gospel time!
May the Lord of hosts hasten it more generally in the kingdoms of the earth!

Having offered a few general observations upon the state of things,
it now remains to make some further remarks concerning
that people who were so remarkably raised,
as before hinted, in the last century, in this land.
Their beginning and first progress was here in England,
though many other lands were also sharers in the brightness of Truth`'s arising in them;
and it may without vanity be said, that through them a light has extended,
or at least glanced,
over a great part of Christendom (so called) which has uncovered the
hidden mystery of the false church more clearly than before,
and given a great shake to the long continued kingdom of anti-christ.

These have been, through divine wisdom, established into a compact body,
amongst whom subsists the handsome order of the Gospel,
which acts as a hedge for their safety and preservation from the destroyer,
and keeps out of the polluting defilements of a greatly corrupted world.
Notwithstanding which, their preservation depends upon their diligently seeking unto,
and waiting singly and carefully for, a daily renewing of strength and wisdom from above,
whereby alone all things must be directed and ordered for their safety and perseverance.

I have often accounted it a great favor and blessing,
that my lot was cast in a time when primitive Christianity,
in its power and purity, is restored in the world;
and that I was so happy as to have my birth and
education amongst the before-mentioned people.
For though this did not make me a real and living member of their body,
yet it happily put me more in the way of being so,
than if my lot had fallen in some of the foregoing dark ages,
and it afforded me greater means of restoration than if I had
been educated amongst superstitious and prejudiced persons.
And truly, for this favor, enjoyed by me and many others,
there must be proportionate returns of thankfulness and obedience,
or it will surely add to our condemnation; for where much is given,
much will be required.

Before I had quite arrived to man`'s state, I was,
through merciful goodness operating upon my soul, brought into a better knowledge of,
and a nearer intimacy and fellowship with these people, in a spiritual sense,
to my unutterable consolation;
for I found that the glorious Lord was their king and law-giver,
and that He had indeed become to them a place of broad rivers and streams,
as it is written:
"`For the Lord is our judge, the Lord is our law-giver, the Lord is our king, He will save us.`"
This was the blessed language that sounded within their borders.
My spirit has many times been reverently bowed
and prostrated in great awe before the Lord,
in beholding the beautiful situation and safety of these His people;
in a humble sense whereof I have been ready to say,
"`Happy are you, O Israel! who is like unto you, O people saved of the Lord!
For He is the shield of your help, and the sword of your excellency!
Your enemies shall be found liars before you,
and you shall tread upon their high places!`"

It may be objected that the foregoing contains high accolades for a people,
amongst whom we cannot discover these excellencies, but have looked upon them as a low,
contemptible body, who affect a kind of awkward singularity.
Moreover, we observe many amongst this people to be as eager after the world,
and who love it as well as any people whatever;
and there are others who take fleshly liberties,
are as deeply involved in the pleasures and festivities of life,
and are as much strangers to self-denial as people of other persuasions.
And it is further to be noted, that when we go to their places of worship,
and observe the manner of their sitting in silence,
a Laodicean lukewarmness is very apparent in many of them, by the easy,
careless condition they seem to sit in,
at the same time they profess to be waiting in silence of body
and stillness of soul for the descending of the Holy Spirit,
that their spiritual strength may be renewed.
Surely, this must be a mockery and deception of the most contemptible
and provoking nature in the sight of the all-seeing eye.

Now, in order to open a little the state of the case,
and to answer the foregoing objections,
I shall now make some observations upon the defection
in practice that is to be found amongst us as a people,
especially of later years,
which has caused an abundance of pain and heart-aching
distress to the living members of the body,
who fervently travail that Christ may be formed in those who are
members of our Society by natural and not spiritual birthright.

As to the first part of the objection,
I may say that this people have always been viewed by carnal
professors of Christianity as a low and contemptible people,
even from their first rise,
which manifests the same undistinguishing blindness that has
ever deprived the children of this world from seeing any
beauty or comeliness in the children of light.
I have before noted, that though educated in the same religious society,
I did not see that the Lord was amongst them, until He was pleased to open my eyes,
agreeably to Matt. 16:16-17, where our Lord pronounces Peter blessed,
in that the Father had revealed the Son to him.
He elsewhere said to His disciples,
"`Blessed are your eyes, for they see; and your ears, for they hear.`"
And it is through the same blessing that my eyes are yet preserved open to see,
that notwithstanding the great declension which prevails over many of us,
the glory has not departed from amongst us.
Indeed, the King is known by the upright hearted to be still reigning in His beauty.
Princes do yet rule in the Spirit of judgment given to them by God.
My faith is, at times,
greatly strengthened to believe that it will never cease to be so amongst this people,
but that they will be preserved by the Almighty power, through all generations,
a living body; and that the principles of Truth, as held by them,
will yet spread far and wide in the kingdoms of the earth.
This, I believe,
was the blessed end for which they were first raised and marvelously supported.
This glorious work has been in degree going on,
though very much impeded by the unfaithfulness of many amongst us, who,
like the foolish woman in Proverbs 14,
are in some measure pulling down what the wise woman has built up.
Oh! that all who take upon themselves our holy profession of the unchangeable Truth,
would deeply consider the weight of obligation which they take upon themselves!

Because of their disregarding or lightly esteeming this weighty responsibility,
and resting in the bare profession of truth, we find many under our name more insensible,
and harder to be reached and awakened by a living powerful ministry,
than people of other religious persuasions.
This may seem strange to some, but I know it to be lamentably true,
having frequently felt it in my Gospel labors.
To me, this is not hard to account for,
when it is considered that amongst us there have been dispensed greater spiritual favors,
of various kinds,
than amongst any society of people that I know of--which has not proceeded
from any partiality in the Almighty towards us more than others,
but only to enable us to keep our covenant with Him in the
discharge of that great work to which He has called us.
Where any are so inconsiderate as to disregard and neglect
such opportunities of lasting benefit and improvement,
they become more hardened and impenitent than those who have
had less opportunity to receive heavenly impressions.
The portion of such, unless they in time embrace the gift of repentance, is very dismal,
as in Prov. 29:1; "`He who is often rebuked, and hardens his neck,
will suddenly be destroyed, and that without remedy.`"
And Heb. 6:7-8;
"`For the earth which drinks in the rain that often comes upon it,
and bears herbs useful for those by whom it is cultivated, receives blessing from God;
but if it bears thorns and briers, it is rejected and near to being cursed,
whose end is to be burned.`"

Great indeed has been the bounty of heaven to us as a people, both immediately,
by the solacing influences and guidance of the Holy Spirit to all that would receive it,
and also by the abundant flowing of a truly evangelical ministry,
raised up and continued for the greatest part of this last hundred years.
But now the Society is much stripped of a living skillful ministry; though it is not yet,
and I hope never will be, wholly destitute.
This, through the divine blessing,
has been a means of our being gathered and preserved a people.
But many amongst us have leaned and depended too
much upon the outward ministry of others,
and therefore it may be consistent with divine Wisdom,
to try how the Society will stand without so much outward help in that way.
It looks, at times,
as if the Lord desires to make His people still more inward and spiritual,
showing them plainly, that Gospel worship does not depend upon outward means.

It is quite obvious that abundant preaching, praying and singing,
do not bring a great part of mankind any nearer to heaven,
nor more acquainted with God and themselves, than they would be without it.
Thus it may be truly said, and indeed lamented,
that these spend their money for that which is not bread,
and bestow much labor without real profit to themselves.
With respect to us, the approved ministry has abounded with heavenly bread,
and refreshing streams of living water have flowed
through the conduits to the plantation of God;
and although many have not improved thereby, yet some have indeed grown and flourished.
But the Lord of the vineyard cannot be confined to any
particular means for the help and preservation of His church,
not even such as He has made use of in time past.
Yet upon the whole,
it appears to me something like a chastisement that so
many worthy valiants have been removed by death,
and few have raised up in the ministry to succeed them with equal brightness.
This may prove a great trial, which, to discerning eyes,
may fully distinguish between the bare professor
and the true possessor of the Christian religion.

A holy, awful,
silent waiting before God is the way that spiritual Israel abides in her tent,
where no divination nor enchantment can prevail against her.
This is exceedingly beautiful, reaching,
and convincing to all whose spiritual eyes are in degree opened;
as is set forth Numbers 24:5-7;
"`How lovely are your tents, O Jacob! Your dwellings, O Israel!
Like valleys that stretch out, like gardens by the riverside,
like aloes planted by the Lord, like cedars beside the waters.
He shall pour water from His buckets, and His seed shall be in many waters.`"
Oh! what encouragement do the Lord`'s chosen people have to
abide faithful in that station wherein He has placed them,
whether in silence or speaking, in doing or suffering, in prosperity or adversity.
There is not the least occasion to be ashamed of silent worship,
unless we are so naked as to be void of a right sense of what true worship is.
Then indeed it is exceedingly contemptible,
and cannot fail to render us even more despicable in
the eyes of mankind than those who have an outward form,
decorated with man`'s curious inventions and adorning.
This state of insensibility to the nature of true
worship in those who profess to be spiritually-minded,
is set forth by our Lord under the metaphor of "`Salt that has lost its savor,
which is then good for nothing, but to be cast out and trodden under the feet of men.`"
Therefore all professors of spiritual worship should greatly
fear being found in this dreadful state--holding the outward
form which Truth leads into _without_ the life and power.

In my travels for the promotion of Truth,
which I have been engaged in through most parts of our Society,
I have seen and painfully felt much of this sorrowful idleness and insensibility,
which has caused me many days and nights of mourning with sackcloth, as it were,
underneath.
I have seen that this proceeds from various causes,
but principally from an over anxiousness in seeking
after earthly things which are lawful in themselves,
but the pursuit of which is idolatry when they have the chief place in the heart,
and are made the heart`'s principal treasure--which they certainly are,
when they are most delighted in and thought upon.
Can it be supposed that idolaters can worship the true
and living God in any way besides a mere form?
With such as these,
the several branches of our Christian testimony are regarded
for no other reason than for outward decency`'s sake,
to keep up the form and appearance in the sight of men.
There is a dead form and an insipid fruitless
preaching which can never truly beget unto God,
though perhaps it may sometimes beget into the form.
But this brings no increase to the Lord`'s people, except of pain and distress.
Visible disorders and immoral practices in particular things
have indeed wounded us and hurt the cause of Truth,
but not in such a dangerous manner as a lifeless ministry; because,
wherever sound judgment and the spirit of wholesome discipline have been preserved,
sin and disorder have been quickly judged and cast out of the camp.
But the greatest wounds we have received have been in the house of our seeming friends,
by their unsanctified endeavors to maintain our worship, ministry,
and discipline (or at least what they have liked of them) in the outward form only.
Anti-christ has always made more havoc on the church by
transforming himself into something plausible,
than by any direct violence and opposition.

Let it be ever remembered what Paul says,
"`For he is not a Jew who is one outwardly,
nor is circumcision that which is outward in the flesh;
but he is a Jew who is one inwardly; and circumcision is that of the heart,
in the Spirit, not in the letter; whose praise is not from men but from God.`"
None, I think,
will deny that it would be equally true if the word
Christian were substituted in place of the word Jew.
If so, we are warned that the form,
appearance and character may be attained without the heart work.
Indeed, we read of some who "`had the form of godliness, yet denied the power.`"
These perhaps did not deny the power in their words, but, to me,
the most emphatic denial of the power of God is to live and act in the form without it.
Such as these declare to mankind by their practice
(which speaks louder than words) that there is no need of the power,
seeing they can do without it.
And most certain it is, that all who inordinately love this world and the things of it,
will not know the power of godliness while they remain in that state;
as the apostle says, "`Love not the world, neither the things that are in the world.
If any man love the world, the love of the Father is not in him.`"

I do earnestly entreat all, into whose hands these remarks shall come,
to seriously pause and examine their own hearts without partiality,
that they may see (before it is too late) what state they are in.
If, by a narrow and strict scrutiny they should find that the religious structure,
which some have been building for many years,
was not erected by the ordering and direction of divine Wisdom,
it would be much more safe and prudent to have it all pulled down,
that not one stone is left upon another;
and so lay the foundation of repentance from dead works,
and of living and powerful faith towards God and our Lord Jesus Christ,
in a conscience purified by His blood.

These lines are principally intended by way of an alarm and warning to the careless,
lukewarm, and formal professors of Christianity.
As for the sincere, upright, humble seekers and worshippers of God,
they will be established upon the Rock of ages,
which the gates of hell shall not prevail against,
and shall reap the blessed fruits of the painful travail of their souls.
And in due time, if they faint not, their parched ground will become a pool,
and their thirsty land springs of water.
Yes, through generations to come, they will enlarge and become as a fountain of gardens,
wells of living water and streams from Lebanon.
The beloved of their souls will call, saying,
"`Awake, O north wind! and come you south, blow upon my garden, that its spices may flow out.`"
Then will they say, "`Let my Beloved come into His garden, and eat His pleasant fruits.`"
