[#section-4, short="Remarks Upon True and False Ministry"]
== Section 4

[.chapter-subtitle--blurb]
Remarks Upon True and False Ministry

The prophet Joel, in a remarkable and excellent manner,
sets forth the true spring of Gospel ministry in these words:
"`And it shall come to pass afterward, I will pour out my Spirit upon all flesh,
and your sons and your daughters shall prophesy.`"
What sort of prophesying is here intended is clearly expressed in 1 Cor. 14:3;
"`He that prophesies, speaks unto men to edification, and exhortation, and comfort.`"
Indeed,
a great part of this chapter is excellently employed in setting forth Gospel ministry,
and that Christian liberty in which all may operate,
according as they are rightly called thereto.
But let it be observed,
that the daughters were to be engaged in this ministry as well as the sons,
by Gospel law and rule;
which was accordingly allowed and practiced in the primitive church.
But where the learning and wisdom of man have been
introduced in the place of true Gospel ministry,
it has (directly contrary to this Christian liberty) wholly excluded women therefrom.
What pride and arrogance must men have who exclude all from the ministry but themselves,
often for the sake of filthy profit, assuming the name clergy,
and calling others laity--a distinction to which the true
church and the holy Scriptures are entirely strangers.
For the Scriptures say,
"`As each one has received a gift, minister it to one another,
as good stewards of the manifold grace of God. If anyone speaks,
let him speak as the oracles of God.
If anyone ministers, let him do it as with the ability which God supplies,
that in all things God may be glorified through Jesus Christ.`"

Here is the precious and comfortable language of truth indeed,
and the perfect Gospel liberty which excludes none who have received a gift; that is,
none who are immediately called of God thereto, as Aaron was.
Exodus 28:1 and 1 Chronicles 23:13 show at large how Aaron was called, and how he,
together with his posterity, were separated by the immediate appointment of God Himself.
The manner of their qualification,
and how they should conduct themselves in the priest's office during that dispensation,
are also recorded with that exact clearness and punctuality
which was always used by the Almighty towards His poor,
dependent creature man,
when He was pleased to require the observance of any law or ordinance.
Therefore no man ought to receive anything as an ordinance of God,
unless it appears indisputably clear that God has indeed commanded it;
nor should any receive such men as have taken a ministry upon themselves,
unless they appear to have better authority for their undertaking
than being taught by human means at schools and colleges.

But, alas! the powers of the earth allow many such ministers to take the fleece,
whether or not they truly feed the flock; and having learned this trade,
they appear as eager as any others to make the most of it.
Their great unhappiness seems to result from
allowing personal interest to blind their eyes,
making them believe it is much to their outward advantage to keep mankind
from receiving the "`true Light which enlightens every man that comes into
the world,`" lest their trade should be endangered by this Light's arising.
Here the blind lead the blind, which exposes both to the utmost hazard.
Nevertheless, such leaders frequently despise and deride those who,
from the constraining power and love of God, testify against their blindness.
To these, the answer of our Lord to the learned rabbis may not be inapplicable:
"`And some of the pharisees which were with Him heard these words, and said unto Him,
'Are we blind also?'
Jesus said unto them, 'If you were blind, you should have no sin: but now you say we see;
therefore your sin remains.'`"

Wherever men have allowed themselves to be swayed by personal
interest to embrace a profitable craft whereby they get wealth,
they have frequently been found very hot and fierce in supporting it,
and in endeavoring to suppress whatever rises up against it.
Thus the experience of many generations can testify,
that ever since preaching became a gainful trade,
by which to get money and worldly honor,
the clergy (so called) have always been the
greatest stirrers up of force upon conscience,
and persecution against any who differ from them in matters of religion;
for which they have not the least shadow of example or
precept either from Christ or His apostles.
All that Christ's ministers were allowed to do,
with respect to those who would not receive them and their doctrine,
was to shake off the dust from their feet, as a testimony against them.
These had received the gift of the ministry from Christ,
and they had it without money and without price; for His command to them was,
"`Freely you have received, freely give.`"
But mercenary preachers do not receive their ministry freely;
alleging that it was costly to become properly qualified for it,
and so now they must make a gain of it, or they should be great losers.
The plain truth is, these do not receive their ministry from Jesus Christ;
neither can they produce any evidence to prove that they have
received divine commission for what they take upon themselves.
Their using the words of Christ and His apostles affords them no authority from Him;
for the very worst of men, yes the devils themselves, may do the same.
Oh! what a pity it is they should pretend to be sent of God,
as ambassadors of Christ or as the apostles' successors,
when they are so manifestly unlike Him and them,
bearing the marks of the false prophets and
hirelings we read about in the holy Scriptures.

Let us take notice what Paul, the great apostle of the Gentiles, says upon this subject;
"`Not that we are sufficient of ourselves to
think of anything as being from ourselves,
but our sufficiency is from God,
who also made us sufficient as ministers of the new covenant,
not of the letter but of the Spirit; for the letter kills, but the Spirit gives life.`"
This plainly shows,
that ministers in the Gospel times are to minister in
the quickening Spirit of living and heavenly virtue,
agreeably to Matt. 28:19-20;
"`Go therefore and make disciples of all the nations,
baptizing them in +++[+++literally _into_]
the name of the Father and of the Son and of the Holy Spirit... and lo,
I am with you always, even to the end of the age.`"
That this baptizing teaching with the Holy Spirit was
the kind practiced in the primitive church,
appears by many passages in Scripture; particularly Acts 10:44;
"`While Peter was still speaking these words,
the Holy Spirit fell upon all those who heard the word.;`" also 11:15-16;
"`And, said Peter, as I began to speak, the Holy Spirit fell upon them,
as upon us at the beginning.
Then I remembered the word of the Lord, how He said, 'John indeed baptized with water,
but you shall be baptized with the Holy Spirit.'`"
And seeing that the dispensation of God to man is the very same now as it was then,
and that mankind is as much involved in sin and estranged from God as they were then,
and that the Lord has graciously promised to be with
His ministers always to the end of the world,
no good reason can possibly be given why the same powerful,
efficacious means are not now as essentially necessary for man's recovery,
as at that time.
Indeed, there can be no ground for a denial of this truth.
And though there is a consciousness in many that they do not
have the assistance of the Spirit in their ministry,
yet it seems to their interest, and for the maintaining of their credit,
to persuade mankind that there is no such thing to be attained now.
This, with many other instances which might be adduced,
plainly shows these to be no other than ministers of the letter; and that, we read,
only kills, whenever the life-giving Spirit does not accompany their preaching.

Very judicious are the distinctions made between ministers of
the letter and ministers of the Spirit by William Dell,
in his book, _Trial of Spirits both in Teachers and Hearers;_
he being himself a man of literature,
and well acquainted with the nature of university education,
as he was master of Gonville and Gaius college in Cambridge.
I shall make a few quotations from him, and recommend this tract,
and his treatise on baptism to the reader's serious perusal.

[quote]
____
"`And first, let me note an objection.
Some will object here, if a man preach the word in the letter, even good,
sound and orthodox doctrine, there is no doubt but that such a man is to be heard,
and he may do much good in the church, though he lack Christ's spirit.
This I have heard from very many who have thought they have said something.
But to this I answer, that they who lack Christ's Spirit,
which is the Spirit of prophesy, though they preach the exact letter of the word,
yet are false prophets, and not to be heard by the sheep.
Again, they that preach only the outward letter of the word without the Spirit,
make all things outward in the church;
whereas in the true kingdom of Christ all things are inward and spiritual,
and all the true religion of Christ is written in the
soul and spirit of man by the Spirit of God;
and the believer is the only book in which God Himself writes His New Covenant.`"
____

[.no-indent]
He further says,

[quote]
____
"`They that preach the outward letter without the Spirit, can, notwithstanding that,
both live themselves in all the inward evils of corrupted nature,
and allow others to do so too.
Wherefore, to conclude, let us understand that that church that has the word,
if it lacks the Spirit, is antichrist's church;
and that ministry that uses the word and lacks the Spirit, is antichrist's ministry;
and that all works, duties, praying, preaching, fasting, thanksgiving, etc.,
without Christ's Spirit, are nothing but the very kingdom of anti-christ,
and the abomination of desolation.`"
____

Of what importance it is for mankind, of every denomination of Christianity,
ours as well as others, to deeply ponder these weighty observations in their hearts,
especially the last.
And upon that statement of Paul in Rom. 10:15;
"`How shall they preach, except they be sent?`"
Dell further observes thus: "`So that true preaching, comes from a true sending,
and this comes from the grace of God.`"
It is not, I say, from the sending of universities, bishops, presbyters,
or any other man or set of men whatsoever,
or from man's intruding himself into ministry in his own will without a proper call;
but from the constraining power of the everlasting Word
of God laying a necessity upon the individual,
as Paul expressed, "`For if I preach the gospel, I have nothing to boast of,
for necessity is laid upon me; yes,
woe is me if I do not preach the gospel!`" 1 Cor. 9:16

It is of the utmost consequence,
towards promoting truth and righteousness upon the earth,
that the ministry be preserved according to its original institution, namely,
under the immediate direction of the eternal Word of God, speaking as the oracles of God.
Ministry is properly God's speaking by His instruments to the children of men,
such things as He (the Searcher of hearts) knows they stand in need of;
and at the same time opening their hearts to receive the truth.
Nothing but the unparalleled love and power of Christ
can bring forth and support such a ministry.
It is impossible, in the very nature of things,
that those who are rightly exercised in such a ministry can
have sinister views of making temporal gains thereby.
Wherever this appears, we may be assured that the Lord has not sent them;
and they therefore cannot profit the people at all.
And even though a person may feel good-will to mankind
flowing from the love of God shed abroad in the heart,
in which strong desires may arise to do good, free from lucrative goals of all kinds,
and though much beautiful Gospel doctrine may open to their view,
which is thought suitable to help and edify his or her fellow-mortals,
yet all this is not sufficient ground upon which to proceed,
without the call and real gift in this weighty undertaking; for indeed,
this may be no more than the natural consequence
of the operation of pure love in a saint's mind,
even in those who have never had a call to the ministry.

Yet to some, these blessed operations, influences and openings,
may be given in order to prepare them for that work,
and they should wait patiently under the forming
hand of the Potter until the full time comes.
This will be clearly seen, as the eye is kept single to Him.
But there is great cause to believe that some have launched out in
their public ministry before a true foundation was settled,
when still under the preparing hand of the Lord,
whereby they have (in a sorrowful manner) brought darkness upon themselves,
and sometimes upon others.
These too prove only ministers of the letter,
though perhaps they pretend much to have the impulses of the Spirit,
and so have been instruments of much anxiety and distress to the true church,
who can savor nothing with delight,
except that which comes from the power of the Word of life.
It may be difficult to bring true judgment over such ministers as these,
in the present low state of our society,
especially when they have a fair outward appearance,
and nothing to blame in their morals.
But it sometimes has happened,
that something has been permitted to manifest their unsoundness,
and thereby to relieve the painful sufferers who
sit under the blasting wind of their ministry.

Inconsiderate, weak persons have intruded themselves into this great work; who,
not duly waiting for the Lord's judgment to try their
spirits and all that presents to their minds,
have been beguiled by the enemy to run out in a false heat,
without the holy dread and fear of God upon their hearts.
These have taken advantage of the Gospel liberty
again restored among us (which must be preserved,
lest the Holy Spirit be quenched), namely,
that all who are called to the work of the ministry, whether male or female,
may prophesy or preach one by one, that all may be edified.

It has been a painful, suffering case to the living members in some places,
when they have seen that both the matter and manner of some
could have no other tendency than to display themselves,
and to burden the religious society that allowed such to
assume an office for which they were in no way qualified.
Certainly the church has power to order and regulate her own members;
and doubtless she has the right to wholly refuse and reject a ministry which,
upon trial, she has no unity with.
Moreover, substantial members of the church, who have stood their ground well,
and have large experience of the Lord's dealings, whether ministers or others,
ought to have great weight with such who have not yet made full proof of their ministry,
nor given satisfaction to the body in general, though they may to themselves,
and perhaps to a few others of little judgment.
Neither should any go abroad to exercise their ministry,
until they know there is a general satisfaction with it at home.
Some such have been very confident and resolute, hard to convince of their mistakes,
and critical of those of deeper experience,
much evincing that sign of depravity set forth by Isaiah 3:5;
"`The child shall behave himself proudly against the ancient,
and the base against the honorable.`"

Good order and decency are to be preserved in the church of God,
especially among the leading members, as way-marks to all.
The reason and nature of the thing demands a proper regard and preference to age, gifts,
growth and experience;
which will always be carefully observed and paid by those of a right spirit.
When this is not the case, it is a sure token of a false birth,
and a proof that pernicious self is not yet slain.
And where self predominates, it cannot fail of mixing with all religious services.

Now, that the hearers have a right to judge, appears from 1 Cor. 14:29;
"`Let two or three prophets speak, and let the others judge.`"
It is therefore very presumptuous for any to take upon
themselves the sole right of speaking and judging too;
or to impose something upon an auditory or church by which they are not edified,
believing it does not proceed from the right spring.
For the word preached does not profit, unless it is mixed with faith in those that hear.
Heb. 4:2

I know of no way to evade the force and weight of what is above mentioned,
unless it be by supposing that the auditors in
general are so void of spiritual understanding,
as not to be capable of judging; which would be very uncharitable,
and savor much of arrogance.
I am fully persuaded,
if ministry does not reach the divine Witness in the hearts of the hearers,
and cause them to assent to it in some measure, it will never profit them.
The right ministers have a witness to the truth of
their ministry in the hearts of even the rebellious;
how much more so then in the honest-hearted.

The danger which arises from the low, languid, unskilful state of many in our Society,
has induced me (feeling my mind in degree moved thereto),
to write the more strongly concerning the nature
and pernicious consequences of a false ministry;
being fully persuaded that the more formal and superficial we become as a people,
the more danger there is of such a ministry rising,
and finding encouragement to grow and prevail.
For the lifeless,
formal professors of Christianity had rather have
almost any kind of ministry than all silence.
On the other hand, a right ministry cannot have a free course, nor be exalted,
where there is nothing but worldly spirits, clothed with a form of religion.
Here true ministers must be like the holy prophet Ezekiel, where it is said;
"`I will make your tongue cling to the roof of your mouth,
so that you shall be mute and not be one to rebuke them,
for they are a rebellious house.`"
And, "`Therefore the prudent keep silent at that time, for it is an evil time.`"
Amo. 5:13

These remarks upon the false, as well as the presumptuous and unskilful ministry,
though plain and strong,
I hope will administer no hurt or discouragement to any
who are rightly concerned in this important work;
and these comments may, if duly observed,
be lessons of caution and instruction to those for whom they are intended.
I hope these observations will also prove an encouragement to those
who are painfully burdened by unskilful intruders into the work of
the ministry (whether because of weakness or willfulness),
that they may not be slack in their endeavors to regulate such things by plain dealing,
yet with true judgment, love and tenderness,
justly applied wherever it may be called for.
This task may sometimes be heavy and discouraging,
as it is hard to turn those who have taken a wrong course,
and who imagine themselves right, when it is really quite otherwise.
Sadly, these have been observed to be the most confident of
all in their pretended sight and sense.
Nevertheless, let the weight of truth, which is the strongest of all,
be laid upon them from time to time,
that the church may not suffer hurt and loss by
any omission on the part of the living members.
I know it is those who are alive in the Truth,
of good understanding and judgment therein, and no others,
that are qualified to help and direct such as have missed their way in a spiritual sense;
agreeably to Gal. 6:1; "`Brethren, if a man be overtaken in a fault,
you who are spiritual restore such a one in the spirit of meekness; considering yourself,
lest you also be tempted.`"
It is not the censorious, critical, or worldly-wise that can restore a brother;
for these have nothing to do in the church of Christ until
they are first subjected to and taught of the Lord themselves.

The main issue, in my apprehension,
is to be able to form a true judgment of the
source or spring from which ministry proceeds.
If it is found to be right in the ground, originating from the true Fountain,
then a great deal of tenderness is to be used,
and much childishness or weakness is to be patiently borne with.
For although some through fear,
and a deep sense of the weight of so important an undertaking, may, at first,
speak very stammeringly, and with considerable awkwardness,
yet the sweet efficacy of the quickening powerful Spirit,
which is felt with them in their service by those who are circumcised in heart and ear,
far exceeds the finest eloquence without it.
Such should be prudently encouraged, yet allowed time to find their own feet.
There are but few children, however hopeful, that can bear much recognition and applause.
Great hurt has been done by the forward, affectionate part of some,
laboring to bring forth ministers before the right time, and pushing others on too fast,
who in their beginning were living and very hopeful.
Oh then, what caution and care should be exercised,
to clearly see in the true light what to lay hold of,
and what to discourage in this important respect.

I intend to conclude this subject with some plain, honest hints,
which have arisen from my own experience and observation, concerning the true ministry,
as it has been restored again, through divine mercy, for about this last hundred years,
in greater simplicity and purity than has been known, as I apprehend,
since the apostles' days.
This ministry has not been conducted with the enticing words of man's wisdom,
but in such a demonstration of the Spirit and power of God,
as has (though much despised by the learned rabbis)
been a great blessing to this and other nations.
Indeed,
many thousands having been thereby turned to Christ their true and saving teacher,
whom they embraced joyfully as the only beloved of their souls,
and a great number of churches have been gathered to sit down
as under the shadow of the wings of the Prince of peace.
Great was the Lord God in the midst of us, in the beginning of this society.
Our ministers were clothed with salvation,
and their feet shod with the preparation of the Gospel of peace.
Many then ran to and fro, and the true knowledge of God increased.
The Lord gave the word, and many, both male and female, were mighty publishers of it.
And through divine mercy it may yet be said that,
though the declension in practice is great in many,
there is still a considerable body preserved to bear the ark
of the testimony of the Lord their God as upon their shoulders,
in the sight of the people, with their feet standing in the bottom of Jordan;
and a living, powerful ministry is yet continued,
though far short of the number formerly engaged in that work.
For many have grown up amongst us,
who have become more superficial and easy about possessing the
substance of religion than their ancestors were.
These have relied too much on the outward ministry,
and have not truly profited in religion thereby.
Instead, they have greatly declined in practice, under abundant favors of this kind,
the ministry becoming to many as a pleasant song.
They hear the words with pleasure, but do them not;
their hearts still following after covetousness of one kind or another.
Therefore the Lord has seen fit to strip our Society very much in this respect;
and also to engage many of those who are true ministers, frequently to lead the people,
by example, into silence.
O blessed will all those servants be, who are preserved in discernment and true judgment,
administering proper food in due season, whether in silence or in words,
in doing or in suffering with and for Christ!
This doubtless all will do, who look with a single eye to God's honor above all things,
attending upon the measure of their gift received,
which in its operations and requirings is self-evident.
None that wait aright upon God will ever be confounded;
but peace and infallible certainty will be known through all the borders of Zion.
Everyone who knows Jerusalem to be a quiet habitation,
is at no loss to understand his proper allotment of service therein,
unless he falls into conferring with flesh and blood.
Then he comes to confusion and uncertainty, in which he may fret and toil in vain.
But in the holy,
diligent waiting upon God in a sanctified heart (which
is the temple wherein Christ dwells,
and our house of prayer), satan can never come to deceive us, or endanger our safety.
