[#section-5, short="The Nature and Usefulness of Christian Discipline"]
== Section 5

[.chapter-subtitle--blurb]
On the Nature and Usefulness of Christian Discipline

[quote.scripture, , Isa. 4:5]
____
And the LORD will create upon every dwelling place of mount Zion,
and upon her assemblies, a cloud and smoke by day,
and the shining of a flaming fire by night: for upon all the glory shall be a defense.
____

That God intended to establish an excellent government, order,
and discipline in the church under the Gospel dispensation,
appears from several passages of the prophets in the Old Testament,
who saw into and wonderfully described the Christian state.
I shall instance just a few:
"`Behold a king shall reign in righteousness, and princes shall rule in judgment.`"
(Isa. 32:1)
"`The Lord is exalted; for He dwells on high,
He has filled Zion with judgment and righteousness;
and wisdom and knowledge shall be the stability of your times,
and strength of salvation.`"
(Isa. 33:5-6)
"`In that day shall the Lord of hosts be for a crown of glory,
and for a diadem of beauty unto the remnant of His people:
and for a spirit of judgment to him that sits in judgment,
and for strength to them that turn the battle to the gate.`"
(Isa. 28:5)

Our Lord and Savior Jesus Christ, in Matt. 18:15-18,
clearly directs His followers how to proceed in
the exercise of discipline and good order,
both with respect to individuals and to the church.
He assured them that whatsoever of this kind is done under divine direction upon earth,
shall be ratified and confirmed in heaven, chap.
19:28, and promises such who have followed Him in the regeneration,
that they shall be exalted in His kingdom,
sitting upon thrones to judge and govern His people.
We find among the eminent gifts of the Spirit, Paul mentions helps in government, 1 Cor. 12:28.
In chap. 5, he blames that church very strongly for their neglect
of practicing sound judgment in the way of discipline,
showing them the necessity of putting those who were
guilty of corrupt practices out of the community,
lest as a leaven they should affect the whole lump.
In verse 11, he points out how unsafe it is for the Lord`'s people to
have any society with the workers of iniquity.
In verse 12 and 13, he shows that it is the church`'s duty to judge those that are within,
that is, her own members, leaving the judging of those that are without to God.
In chap. 6, he blames them sharply for going to law one with another before the unjust,
showing that it would have been better they had allowed themselves to be defrauded,
and that every matter of difference or controversy
should be judged and determined by the church,
in regard to its own members.

A Christian society, gathered by God`'s power,
having received diversities of gifts and qualifications,
is considered as a body properly constrained by its holy Head (who is perfect in wisdom),
that it may peacefully exist according to pure laws, rules and comely orders,
both within and without.
For the maintaining of this state,
every member has its proper office and station wherein he or she is to act,
yet only by the guidance of the holy Head, who is ever known to preside over His humble,
dependent people, as a present help in the needful time,
supplying all their needs as they wait His time.
Pertinent to this is Eph. 4:15-16; "`But speaking the truth in love,
may grow up into Him in all things who is the head, even Christ,
from whom the whole body fitly joined together,
and compacted by that which every joint supplies,
according to the effectual working in the measure of every part,
makes increase of the body, unto the edifying of itself in love.`"

The apostle, in 1 Cor. 12,
with great strength of reason and perspicuity, shows the diversities of gifts,
differences of administrations and operations, all by the same Spirit,
who works in all as He will.
He further shows that, notwithstanding this variety, all, and of all sorts,
are baptized into one body, and made to drink into one Spirit; he says,
"`For the body is not one member, but many;`"
and shows they are all useful to and dependent upon one another,
so that none have a right to claim such a self-
sufficiency as to be independent of other members.
Indeed, those members of the body which seem to be more feeble, are truly useful.
The near union, harmony and sympathy of this glorious body, is set forth in verse 26;
"`And if one member suffers, all the members suffer with it.
If one member is honored, all the members rejoice with it.`"

For brevity`'s sake, I forbear at present making more quotations on this subject.
These are sufficient to demonstrate fully the strong
obligation which all spiritually-baptized members are
under to rightly understand their places in the body,
and to come forth in a faithful discharge of their duty as in the sight of God,
to whom they must be accountable.
It likewise appears that every member
(having become such by his or her voluntary consent)
is strictly bound to keep and maintain the established rules of that body;
the breach of which not only renders him or her guilty in God`'s sight,
but also accountable to the body.
It also behoves this body, immediately upon the transgression of its rules and orders,
to exert itself in dealing with transgressors,
and to administer sound judgment in order to restore them; or,
on failure of success in that, to disown or refuse to have unity with such,
letting the world know they are not of their body,
so that its reputation may be preserved amongst those who are without,
as well as for its own peace and safety within.
By a neglect of this, not only may others be infected by the corrupt member,
and his evil may spread in the body like a leprosy,
but the Lord may also be provoked to withdraw from that body
which neglects the exercise of true judgment against evil;
as in the case of Achan, Joshua 7, and also that of the tribe of Benjamin, Judges 19-20.

It is too obvious to be denied, that the professors of Christianity,
by losing the power and life of religion,
also lost the true spirit of discipline and good order in their churches.
In the place of this, they have substituted rules, orders,
and canons of their own invention,
principally calculated to support that power by
which the clergy (so called) got their wealth.
The present state of church government appears to be truly deplorable
amongst most of the different sects of Christian professors that I know of.
Consequently, they are in a very corrupted state,
greatly lacking that judgment and righteousness which was to fill Zion,
and the wisdom and knowledge which was predicted would be the stability of her times.

Cave and King, in their book _Primitive Christianity,_ clearly show,
from the writings of many of the ancients,
particularly for the first three hundred years after Christ,
that much care and zeal were maintained to preserve the
church clean and pure by a wholesome discipline.
King shows, that not only the teachers,
but the whole church were concerned and active in dealing with,
receiving satisfaction from, or finally censuring people;
and also that no teachers were set over the church,
but only such as the whole unanimously agreed to receive.
Moreover, it is demonstrated that the common people, generally called laity,
were equally concerned with others in deposing and censuring ministers,
when they ceased to have unity with them
(see pages 22 to 25, 112, and 116).
Both he and Cave, citing Tertullian,
show that the manner of the primitives in giving
judgment on such accounts was very weighty and solemn.
"`As amongst those that are sure that God beholds what they do,`" says Tertullian,
"`this is one of the highest forerunners of the judgment to come,
when the delinquent is banished from the communion,`" page 120.

Athenagoras told the emperors, that no Christian could be a bad man,
unless he was a hypocrite; and Tertullian openly declared,
that when men depart from the discipline of the Gospel,
they so far cease amongst us to be accounted Christians.
Cave, page 95.

When at any time invited to public solemnities, such as marriages and the like,
the prudence of the church thought fit to lay restraints upon their members,
forbidding light and foolish actions, such as leaping and dancing;
insisting they should eat and drink with modesty and gravity,
as is fitting for Christians; for which he quotes a council of Laodicea, second part,
page 73.

They took notice of all offenses against the Christian law,
any vice or immorality that was either public in itself,
or made known on good authority to the church.
For, says Cave,
the holy and good Christians of those times were
careful to keep the honor of their religion unspotted,
to stifle every sin in its birth, and by bringing offenders to public shame and penalty,
kept them from propagating the malignant influence of a bad example.
For this reason they watched over one another,
told them privately of their faults and failures, and when that would not do,
brought them before the attention of the church (third part,
page 406). Agreeably to the nature and constitution of the church--which,
as it transacts only in spiritual matters,
so it could inflict no other than spiritual censures and chastisements--the
common and standing penalty they made use of was excommunication,
or suspension from communion with the church;
cutting off and casting out an offending person, an infected member,
until by repentance and wholesome discipline he was cured and restored;
and then he was re-admitted into church society (page 410). Penitents,
before they were received into unity, made open confession of their faults;
this being accounted the very spring of repentance,
and without which they concluded it could not be real.
Without true repentance and amendment of life,
neither riches nor honor would procure any admission into the church.

Professors of Christianity have been, and still are,
very forward and active in heaping up offerings,
by performing what they call religious duties,
while true virtue has been shamefully neglected.
Multitudes professing faith in Christ, and who are accounted members of His church,
are allowed to remain in various sins and pollutions without any control or rebuke,
to the great scandal of the Christian name.
Indeed,
it may now be said that iniquity runs down like a mighty stream or torrent among many,
carrying all in its path.
What painful apprehensions must fill the minds of
thoughtful parents respecting their offspring,
when, morally speaking,
no other can be expected than that they will be carried
away by this torrent into everlasting destruction!
Oh that it were rightly considered by all Christian professors,
that obedience is better than sacrifices or offerings,
and to hearken unto the voice of God,
in putting away the evil of their doings from before His eyes,
is better than the fat of rams.
To what purpose is the multitude of their sacrifices or offerings,
while the most weighty matters of the law of God are neglected?--namely: judgment, mercy,
and faith; even that faith which produces good works.
Let them carefully ponder in their hearts what the Lord has declared by His prophet,
"`I hate, I despise your feast days,
and I do not savor your sacred assemblies.
Though you offer Me burnt offerings and your grain offerings, I will not accept them,
nor will I regard your fattened peace offerings. Take away from Me the noise of your songs,
for I will not hear the melody of your stringed instruments.
But let judgment run down like water, and righteousness like a mighty stream`"
Amos 5:21-24.

Man is apt to begin at the wrong end, or where he should finish,
presuming to perform worship and service to his Maker
before he is in a fit condition to be accepted;
but a being of infinite purity will not so much as look towards him in that regard,
while a man has any fellowship with the unfruitful works of darkness,
either in himself or in others.
Indeed, the Lord will be sanctified by all them that come near Him.
He is of purer eyes than to behold iniquity with any assent or approbation;
and this being true concerning the acceptance or non-acceptance of individuals,
it is also true, and will hold good, in regard to churches and countries or nations.
Oh, then! how greatly it behoves all who desire to stand approved in God`'s sight,
to exert their utmost care and diligence in judging,
condemning and suppressing evil of all kinds, first in themselves,
and then in every branch of the community, as far as it lies in their power.

I shall now proceed to show,
that when the Lord was pleased to restore Christianity in its primitive purity and power,
which was in the middle of last century +++[+++1600`'s], church-government, good order,
and wholesome discipline were also restored amongst a humble, self-denying people,
who were, as God`'s people in all ages have been, much despised, reviled and persecuted.
Yet through all the heathenish rage of their adversaries,
the rising up of the rulers of the earth against them,
and the people imagining vain things concerning them, their bands were not broken,
nor were their cords cast away.
They saw that holiness was the Lord`'s delight,
and they promoted it with all diligence amongst mankind in general,
but more especially amongst themselves.
The Lord, who at first raised up chosen instruments,
and sent them forth into the world (which was as a briery thorny wilderness),
wonderfully blessed their ardent labors with increase,
so that in a few years a large number of churches were planted,
even amidst all the rage and fury before mentioned,
and were quietly settled and established under
the teachings of His Spirit in their hearts.
Hereby they grew up in wisdom and stature, and in process of time clearly saw,
in the divine light, that they must form themselves into an orderly body,
to be governed under such regulations as would put them in the best capacity,
as a religious society, of glorifying God, and being most useful to one another,
as members of the same body; and that also,
by being embodied and disciplined as an army with banners,
they might make a firm stand against every appearance of evil,
with their united strength, under the Captain of their salvation.

Divine wisdom was wonderfully with those worthies first
sent out and engaged in this blessed work,
directing their steps with true judgment,
as well as opening the minds of a numerous people of various growths,
to receive the manner and form of government and order,
which those of the clearest sight discovered, in the light of Truth,
to be best adapted to promote the glory of God,
and the preservation of His church and people.
Yet there were some opposers, as in the primitive times,
even within their own body or society--men of perverse spirits,
who troubled the church for a time with quarrelsome complaints, and corrupt disputations.
But the Lord,
who knows how to put a stop to the rage and cunning devices of the enemies of His church,
brought a blast upon them,
which has exposed the names of the leaders to ages and generations to come.
Thus the faithful were enabled to carry on this great work,
designed for the defense and preservation of God`'s people,
in defiance of all those Sanballats, Tobiahs and Geshems,
(see Nehemiah chapter 2, 4, and 6)
who were permitted to rise up against them and their godly undertaking.

Great wisdom may be discerned by those eyes which the Lord has opened,
in His thus ordering and placing His people in such a way that
the strong bear and help the infirmities of the weak,
supporting one another in that which is good,
and judging down all that is of a contrary nature to it, in every rank and station;
and where none dare to be above correction,
but rather esteem it a mark of love and sincere regard that others extend care over them;
agreeably to 1 Thess. 5: 12-14;
"`And we urge you, brethren,
to recognize those who labor among you,
and are over you in the Lord and admonish you,
and to esteem them very highly in love for their work`'s sake.
Be at peace among yourselves.
Now we exhort you, brethren, warn those who are unruly, comfort the fainthearted,
uphold the weak, be patient with all.`"

What an inexpressible favor it is to be even one of the least members of this body,
or branch of the heavenly Father`'s family,
where help and edification may be received from those
of greater growth and maturity than ourselves.
On the other hand, what satisfaction it affords the fathers and mothers in Israel,
to see the children and weaklings of the flock of a teachable disposition,
carefully endeavoring to walk according to the Truth.
Some are made by God to be as "`saviors upon mount Zion,`" (Obad. 1:21)
and as watchmen upon her walls,
anointed and appointed by the Holy Spirit to watch over the flock of Christ,
as those that must give an account.
Such excellent service may justly entitle them to the application of that language
whereby Job sets forth what he had done in the time of his prosperity,
Job 29: 13-16; "`The blessing of him that was ready to perish came upon me;
and I caused the widow`'s heart to sing for joy.
I put on righteousness, and it clothed me; my judgment was as a robe and a diadem.
I was eyes to the blind, and feet to the lame.
I was a father to the poor; and the cause which I knew not I searched out.`"

Elders who rule in this way in the church are indeed worthy of double honor,
whether they minister in word and doctrine or not;
being such as (agreeable to Peter`'s advice, 1 Pet. 5:2-4):
"`Shepherd the flock of God which is among you, serving as overseers,
not by compulsion but willingly, not for dishonest gain but eagerly;
nor as being lords over those entrusted to you, but being examples to the flock;
and when the Chief Shepherd appears,
you will receive the crown of glory that does not fade away.`"

It is of the utmost importance that the members who constitute the church of Christ,
be thoroughly acquainted with the true Spring of action in the Lord`'s body,
lest any should presumptuously imagine that,
since church government deals with outward and civil concerns,
human abilities (natural or acquired) are sufficient to manage it.
If any fall into such a dangerous error,
it must be for lack of duly considering the nature of the work to be engaged in;
it being no other than what appertains to the spiritual kingdom of Christ and its
promotion in the earth--which kingdom man by nature cannot either see or understand.
It is written,
"`the world by wisdom knew not God,`" and they certainly cannot know His kingdom,
nor how to act properly therein under the Supreme Head, when they know Him not.

To be capable of acting rightly in the discipline of the church,
man must be born of the Spirit (or born from above),
and receive a qualification from the Holy Spirit for that work.
Such as these are the only qualified persons for maintaining good order in the churches,
whether young, old, or middle aged, male or female,
and should be regarded as those who are set over others in the Lord.
These are highly esteemed and loved for the work`'
s sake by the discerning ones in the church.
Indeed, those who are alive in the Truth can savor the things of God
that are conveyed to them through these favored instruments;
and these can also reject the things which are of men,
whenever man intrudes into the work of God;
for the innocent life raised up in them is burdened and grieved therewith.

Nothing can more afflict the souls of the spiritually living than to hear
the darkening of counsel by a multitude of words without knowledge.
None were properly qualified to judge and govern in outward Israel,
unless they were gifted of God for that purpose.
We find that they were to have God for their king,
and those whom He raised up by His immediate power to be their judges under Him,
(this being a perfect pattern of the Christian church).
However, they impiously rejected this government that they might be more like other nations,
that is, left more to their own power and policy, and to be less dependent upon God.
While they looked to the Lord for judgment, aid, and protection,
how wonderfully did He provide for them a Moses, an Aaron, and a Miriam in Egypt,
through the Red Sea, and in the wilderness.
And for the help of these, the Lord also raised up a large number of inferior judges,
upon whom He put His Spirit as an essential qualification.

It would be needless to be very particular in showing
how the Lord was pleased to raise up many,
and to put His spirit upon them,
under whose blessed influence and strength they wrought wonders for the reformation,
deliverance, and protection of His people; such as Joshua, Othniel, Deborah and Barak,
Gideon, Jephthah, Samuel, David, Solomon, Nehemiah, etc.
And when the people perceived that the Spirit of God was upon these leaders,
they eagerly joined them in God`'s work,
out of faithful subjection to the Spirit of God in and upon them,
and not unto them as men.

Very remarkable is the humility and the honest, upright petition of Solomon,
which amply demonstrates the state of mind which all must be brought into,
who are favored with ability to judge and govern in the church of Christ.
"`In Gibeon the Lord appeared to Solomon in a dream by night, and God said,
'`Ask what I shall give you.`'
He said, '`O Lord my God You have made Your servant king instead of David my father;
and I am but a little child; I know not how to go out or come in.
Give therefore Your servant an understanding heart to judge Your people,
that I may discern between good and bad;
for who is able to judge this great a people of Yours?`"

I might draw much more from the precious doctrine and
experience of God`'s people recorded in the holy Scriptures,
demonstrating the outward order, government, and beautiful discipline of the church,
which is the kingdom of Christ,
wherein the truly sanctified of God act as subordinate kings and priests.
But this is expressed in Daniel 7: 21-22, "`I beheld,
and the same horn made war with the saints,
(i.e. the power of anti-christ in the form of a church, with its orders and rules)
and prevailed against them, until the Ancient of days came,
and judgment was given to the saints of the Most High,
and the time came that the saints possessed the kingdom.`"
Oh!
How long has this wicked horn had the rule and government where the saints should reign;
so that there has been little or nothing seen of the nature of that
excellent government which is found in the kingdom of Christ.
There has been no true vision from the prophets; the law has perished from the priests,
and counsel from the ancients, Ezek. 7:26.
And the glorious kingdom of the Messiah has
for many ages been as it were banished from the earth,
or at least hidden from mankind, as in a wilderness,
whereinto the true church fled (see Rev. 12:6).

But the Lord has been pleased, in a good degree,
to restore again the excellent order of His house amongst a despised people;
concerning whom I shall now endeavor to give some account of what my eyes have seen,
my ears heard,
and what I have tasted and handled of the good Word of life in their assemblies;
particularly respecting those called meetings for discipline,
and for church order and government.
These meetings I have attended with diligence
(as I thought it my indispensable duty),
for about thirty years;
the first ten of which I was for the most part a highly pleased and
comforted spectator of the sweet harmony and handsome order of God`'s house.
Indeed, I beheld the love, the sympathy, and the care extended in each branch thereof,
one towards another, in silent seeking the assistance of the holy Head,
that the entire body might edify itself in love,
and the King of saints be known to rule all that was within us.
When we become members of Christ`'s body,
we cease to consider ourselves as individuals only,
but also as members deeply interested in the welfare of the body.
Here is a united labor and travail, being all in one common interest.

I have often beheld the awesome Majesty of the divine power amongst these people,
and could say in humble admiration, at least in my heart, "`Cry out and shout,
you inhabitant of Zion, for great is the holy One of Israel in the midst of you!`"
There has been no lack of any good thing in the camp of God,
"`For the Lord was our judge, the Lord was our lawgiver,
the Lord was our king`" (Isa. 33:22),
and therefore all the splendid art and invention
of man in religion was wholly laid aside,
as Saul`'s armor was by David, and all were concerned to go as David did, in the name,
that is, in the power and dread of the Most High.
When I thus stood still, looking upon Zion, viewing her beauty and excellency,
I saw great things done by lowly instruments,
going forth against their enemies in the name of the Lord only; and truly,
this has caused me to be knit to them, and to love them as my own soul.
The sight and sense of such things made me exceedingly watchful in my mind,
afraid to speak and act,
unless I found a well-grounded assurance that the Lord required it of me;
by feeling the weight of His divine power upon my spirit,
opening my understanding and guiding my judgment, that I might clearly know what, when,
and how to speak in the fearful presence of God, and before the princes of His people,
whose words I observed, "`were as goads,
and as nails fastened by the master of our assemblies,
which are given from one Shepherd`" (Ecc. 12:11).

The words of Solomon in Ecclesiastes 5:1-3 are
very pertinent to what I am now touching upon,
and ought to make a deep impression upon all those concerned:
"`Walk prudently when you go to the house of God;
and draw near to hear rather than to give the sacrifice of fools,
for they do not know that they do evil.
Do not be rash with your mouth, and let not your heart utter anything hastily before God.
For God is in heaven, and you on earth;
therefore let your words be few.
For a dream comes through much activity, and a fool`'s voice is known by his many words.`"

It is plain from what is before-noted, and from much more in holy Writ,
that all the power and wisdom of man, until they are subjected, sanctified,
and properly influenced by a supernatural life,
are wholly excluded and shut out of the church of God.
Although these abilities are sufficient for the things of a man,
i.e. the concerns of this life;
yet the things of God no man can know (nor rightly act in), except by His Spirit.
This also appears in part from the words of Elihu in Job 32:7-9: "`I said,
'`Age should speak, and multitude of years should teach wisdom.`'
But there is a spirit in man, and the breath of the Almighty gives him understanding.
Great men are not always wise, nor do the aged always understand judgment.`"

Very great has been, and still is,
man`'s loss for lack of understanding this important point.
Giving liberty to human abilities in religion, and in spiritual concerns,
has opened the door wide for anti-christ to become almost a universal monarch.
In this way he has gotten great footing amongst all the divisions of professing
Christians--our Society in a sorrowful manner (with respect to many individuals),
as well as others.
Nevertheless, a living body is yet preserved among us; and these,
through the divine blessing, have prevented his taking possession of our society,
as he has done with some.
The eyes and the cry of these are to the Lord,
whom they know to be their only sufficiency;
and that unless He ordains salvation as walls and bulwarks to keep our city,
in vain are all human endeavors.

When I have considered the low, indifferent,
languid state of those under our name in many places, both in this and other nations,
chiefly occasioned by an inordinate love of the world and the things thereof,
my soul has been deeply humbled in awful prostration before the Lord--
contemplating His wonderful condescension in still shining forth upon us,
as from between the cherubim of His glory,
waiting to be gracious by turning again the captivity of many of His Israel,
and seeking to rebuild her waste places, and thereby to revive her ancient beauty.
He has been pleased to preserve unto us some judges as at the first,
and counsellors as at the beginning, though but few in number when compared to the rest.
May the great Lord of the harvest raise many more faithful laborers,
and send them into His harvest,
even such as are described by the evangelical prophet Isaiah,
"`The sinners in Zion are afraid, fearfulness has surprised the hypocrites.
Who among us shall dwell with the devouring fire?
who among us shall dwell with everlasting burnings?
He that walks righteously, and speaks uprightly, he that despises the gain of oppression,
that shakes his hands from the holding of bribes,
that stops his ears from hearing of blood, and shuts his eyes from seeing evil:
he shall dwell on high; his place of defense shall be the munitions of rocks,
bread shall be given him, his waters shall be sure.`"
(Isa. 33:14-16)

Oh! how sorrowful it is, in this and other nations,
to view the great prevalence of unfaithfulness in large numbers,
in most branches of our Christian testimony,
much of which is greatly owing to negligence in discipline.
Those who should have been, above all other considerations,
waiting for fresh and renewed ability from God to build His house,
have been principally endeavoring to build themselves and
their posterity temporal houses for earthly inheritances;
living at ease in their paneled houses,
while the ark of the testimony of God has been exposed to peril.

Dreadful is the account such will have to render to God,
who have hidden their Lord`'s talent in the earth, having wrapped it in a napkin,
i.e. in a decent _form_ of religion.
The Lord has opened eyes that see through these fig-
leaf covering in most or all the ranks of His people;
though it is much to be feared that many have closed their own eyes,
except towards the world.
Yes, in the world they desire to be clear-sighted, for it is their kingdom.
Some of these may presume, from their having long professed the Christian religion,
and having taken care (as far as appears to man`'s eye) to
preserve a reputation free from outward spots or blemishes,
to be on safe ground.
But having given themselves to the pursuit of wealth,
these may not only have dried up the tender plant of Life in themselves,
but also have laid a foundation for the ruin of their children,
or those who inherit their great stock of possessions; notwithstanding which,
some of these may take upon themselves to be
active members in the meetings where they belong.
Oh lamentable indeed is the state of meetings, managed by such unsanctified spirits!
The King of Zion is banished from their councils;
and her precious sons and daughters are but as suffering witnesses for God,
clothed as in sackcloth; and the Seed of God,
which should have dominion in all our meetings, is
"`pressed down under them, as a cart is pressed when full of sheaves`" (Amo. 2:13).

I sincerely wish there were no cause for these strong remarks;
but a caution of this kind may be necessary.
When this spirit gets in amongst us, in any part of the Society,
it cannot fail to lay waste.
Therefore, let all consider what spirit rules in them; for where such a spirit prevails,
it is not the wise woman who builds the house,
but the foolish woman who pulls it down with her own hand. (Prov. 14:1)

It is a mournful truth, that among the many thousands of Israel,
there are but few in comparison who really stand upright, as pillars in God`'s house;
who cannot be at all warped by fear, personal interest, favor, or affection,
but look beyond all with a single eye to truth and righteousness.
Oh, what sad acquiescing, stooping,
and hesitating are to be found in some!
"`It is my son, my daughter, a near relation,
or friend, whom I am unwilling to offend,
lest I should suffer in my interest or reputation,
or gain their disapproval or resentment.`"
This cowardly spirit will never dwell on high,
but must have its portion amongst the fearful and the unbelieving;
and unless such repent, they will be ranked with those who deny Christ before men.
They may read of their portion in Luke 12:9,
"`He who denies Me before men will be denied before the angels of God.`"
True zeal and sound judgment are often rejected by this sort,
whether it comes from individuals or from the church,
whenever they do not find it to agree with their unsanctified understandings.

It may be further observed,
that those whose principal aim is only to maintain the
form or outward character in religion,
feel very little or no pain on account of the
disorderly practices of their fellow-members.
These, therefore, can easily plaster with untempered mortar, smoothing things over,
and crying "`peace, peace,`" before judgment has laid hold of the transgressing nature;
and all this is done under the deceptive pretense of charity and Christian tenderness.
Yet when any are constrained in godly zeal to point out the
deadly consequences of "`healing the wounds of the daughter of Zion deceitfully,`"
some of these soon manifest that they are
still great strangers to true charity,
for they stand opposed to sound judgment,
and to those who are engaged to search to the bottom of the church`'s wounds.
Here something of a persecuting spirit appears,
and the bitter leaven of the pharisee is uncovered that strikes at the life of religion.
But, agreeably to the usual craft of anti-christ,
they must call all godly concerns and labors by a contrary name,
or they could not attack them with any semblance of reason.
Such honest laborers have sometimes been represented as enthusiasts or extremists,
too hot in their zeal, and disturbers of the church`'s peace, etc.
But when there is peace with wrong things in the church,
it is much better broken than kept.
I believe it was in this sense that our Lord said,
"`I came not to send peace on earth, but a sword.`"
It was a sad and dangerous kind of peace,
when Israel became so reconciled to the inhabitants of the land,
that they allowed them to dwell therein, contrary to the express command of God!

When the upright in heart cannot, for Zion`'s sake, hold their peace,
their spirits being truly enlightened to search Jerusalem,
it is very dangerous for any to obstruct, oppose,
or even to discourage them in such a godly undertaking.
The voice of their Almighty helper says,
"`Touch not My anointed;`" and He will certainly vindicate His own cause in their hands,
and will recompense any injury done to it, or them, as if done to Himself;
so that all have need to know well what they do, and what spirit bears rule within them.

In concluding this subject, I am free to express an ardent prayer,
which has filled my heart at times for a considerable number of years,
that the Lord may be graciously pleased to
greatly increase the number of those amongst us,
who are made willing to leave all, and to follow the gentle leadings of His Spirit,
wheresoever He is pleased to lead them.
May He raise up more who prefer the welfare, peace,
and prosperity of the city of God to their chiefest joy;
that truth and righteousness may be so exalted in every part of the body,
as to make all the sinners in Zion afraid indeed.
For these cannot stand in judgment when the Lord arises in majesty among His saints,
nor in the congregations of the righteous;
but in shame will cast away their idols of silver and
gold which they have made for themselves to worship,
to the moles and bats. (Isa. 2:20).

The substance of what is here signified,
has doubtless been the fervent travail of many brethren and sisters,
who are deeply affected with the present lethargy which prevails,
yet in the midst of which are comforted in observing a great revival of concern,
in most places, for stirring up and provoking one another to love and to good works,
particularly in promoting good discipline.
If this prospers, as I believe it will, truth and righteousness will prevail thereby,
and Zion will enlarge her borders, her cords will be lengthened,
and her stakes strengthened.
She will yet break forth on the right hand and on the left,
and her seed will inherit places which are now desolate.
Therefore let the true travailers for her prosperity be encouraged;
for I believe some of them will see the fruits of their painful exercise,
and be satisfied.
May all such keep their habitations in the holy Head, whether in suffering or rejoicing,
prosperity or adversity; for, as says the apostle, If we suffer with Christ,
we shall reign with Him, being glorified together.
