[quote.epigraph, , Prov. 4:18-19]
____
But the path of the just is like the shining sun,
that shines ever brighter unto the perfect day.
The way of the wicked is like darkness;
they do not know what makes them stumble.
____

== Chapter 1

[.chapter-synopsis]
* Birth
* character of his parents
* early visitations of Divine grace
* removal to America
* conversion
* true baptism
* regeneration
* His various exercises and view of being called to the ministry
* first appearance in that weighty work
* remarks on the nature of Gospel ministry.

It has been much upon my mind to write something by way of journal, of my life,
travels and experience in the gracious and merciful dealings of the Lord with me,
through the course of my pilgrimage in this world;
together with some remarks on the state of our Society in my time,
interspersed with observations relating to our conduct in various stations of life,
but chiefly in a religious sense; to remain, when my body is laid in the dust,
a lasting memorial and testimony to the Truth.
And as the Lord shall be pleased to open my understanding,
it may also afford profitable way-marks to some weary travelers,
who are seeking a city that has foundations, whose builder and maker is God.

I was born on the 21st day of the fifth month, 1713, in Radnorshire, South Wales;
being favored with parents who had the substance of religion in themselves,
and were conscientiously concerned to train up their children in the fear of God.
The names of my parents were John and Amy Griffith;
my mother was educated in society with the people called Quakers, and was a steady,
valuable Friend; having at times, a few words by way of testimony,
tenderly to drop in religious meetings, which were acceptable to Friends.
My father, as I have heard him relate,
was convinced of the blessed Truth after he had arrived to man`'s estate,
and found it a great cross to join with the despised Quakers;
he being the only one of the family, which was pretty large,
who joined in society with that people.
But the Lord making hard things easy to him,
he gave up in earnest to the heavenly discoveries, and in process of time,
had a dispensation of the Gospel of peace and salvation committed to him;
wherein he labored in the parts where he lived,
with remarkable sincerity and uprightness;
being a truly living minister and a heavenly-minded man, as I well remember,
though I left him when I was young, and never saw him again.
He finished his course in this world, on the 24th of the second month, in the year 1745;
and it is added in the register of the Monthly Meeting to which he belonged,
"`He was a minister many years, and left a good report behind him among all sorts of people.`"
He was a serviceable instrument in the Lord`'s hand against undue liberties,
which were then creeping in;
and was very deeply affected with the declining state of the church in those parts,
many having removed to America, which since his decease has become almost a desolation.

[.offset]
Having thus paid a small tribute, which I thought due to the memory of my worthy parents,
I shall proceed to give an account of myself.

I was favored with the heart-melting visitations of God`'s love, I think,
when about seven or eight years old;
and frequently experienced his name to be in the assemblies of
his people as precious ointment poured forth;
whereby my desires were greatly raised to attend meetings for Divine worship.
For although, like Samuel of old, I was as yet unacquainted with the voice of God,
neither did I clearly understand from where that precious consolation which I felt, came;
yet I well remember something working powerfully in my tender, weak mind,
by way of opposition to that sweet heavenly enjoyment, in order to deprive me thereof,
by presenting to my view some transitory delight, and filling my mind with vain,
unprofitable and sometimes wicked and blasphemous thoughts,
which were a very great affliction to me.
Then he who was a liar from the beginning,
would suggest that the only way to get over such uneasiness,
was to give way to those thoughts,
and to be utterly regardless of what passed through my mind.
I found the flesh wanted ease, and to save itself,
willingly joined with the temptations of Satan, whereby I got a kind of present ease;
but it was by such gratifications as tended to heap up wrath against the day of wrath,
and the revelation of the righteous judgments of God.
Notwithstanding the false ease contrived by my soul`'s enemy,
I did at times very sensibly feel as I grew up,
this peace disturbed and broken by a sense of God`'s wrath,
revealed from heaven against my unrighteousness;
and I was often in great bitterness of spirit,
when the chastening of the Lord was upon me for sin.
I would at such times enter into covenant with the Lord, promising amendment;
but as those promises were made much in my own will, they were soon broken,
and that increased the weight of my horror and distress; the Lord in infinite mercy,
being pleased to find me out, and to plead with me as in the valley of decision.
In writing this,
my mind is greatly moved with pity and compassion towards inconsiderate youth,
who for the sake of trifling vanities, slight their own mercies,
and are subjected to distress of mind.
The case is still worse,
when by repeated disobedience and rebellion against God`'s unmerited grace,
they have almost stifled his Divine witness in their own hearts, and go on with impunity;
for an awakening time will come, soon or late,
which must strike all such with horror and amazement.
May it be in mercy!

My godly parents were very careful to prevent my falling into evil company;
notwithstanding which, without their knowledge, I frequently found such,
and joined them in those vanities which are incident to youth,
and perhaps was not a whit behind any of them therein.
Yet in the cool of the day, I was sharply reproved, no sometimes,
in the very midst of my folly.
But by this time I wanted to silence the pure witness against evil in my heart.
Oh! I have often since, with deep reverence,
thankfully admired the long suffering of a gracious God, in that he did not cut me off,
when I willfully resisted the reproofs of his instruction, which is the way to life,
because I wanted to live in the vain pleasures of this perishing world.

When I was about the age of thirteen years,
a Friend who had lived some time in Pennsylvania, being in our parts,
and frequently at our house, gave a very pleasing account of that country.
I having two uncles and an aunt there,
some of whom had before written to encourage our going over there,
my inclination grew very strong to go; though my parents, especially my father,
was at first very much against it.
But I was as one immoveably bent upon going; which when my parents saw,
and that an elder brother inclined to go with me, they at length consented,
and procured a certificate of our being in unity with Friends.
There being a family of Friends, out of the compass of our Monthly Meeting,
also going over in the same ship, we were delivered under their care,
and in the year 1726, we embarked at Milford-haven,
on board the Constantine galley of Bristol, Edward Foy, master.
We had a passage of about eight weeks from land to land.
We were about eighty or ninety passengers, generally healthy; among whom,
three children were born while on board, and none removed by death.
My uncle John Morgan, who lived about twelve miles from the city of Philadelphia,
hearing of our arrival, came on board and conducted us to his house,
where I continued for some time.
My brother being a weaver, settled at my aunt Mary Pennel`'s, following his trade.

Removing from under my parents`' watchful care over me for my good,
furnished me with great opportunity to gratify a vain mind,
in the foolish amusements of a transitory world,
towards which I had too great an inclination.
But I have this to say,
in order that parents may be encouraged to exert their
godly endeavors for the preservation of their children,
that I do steadfastly believe, the religious care of my parents over me in my youth,
impressed so great an awe upon my mind, that through the blessing of Divine Providence,
it was a great means of my preservation from gross enormities;
though I had great opportunity of being plunged therein, after I left them.
I hope ever to retain a grateful and thankful
remembrance of those gracious preservations,
when I consider how narrowly I have escaped those rocks,
upon which many have been shipwrecked and ruined.

I was sometimes visited,
and in degree awakened to a sense of my undone condition without a Savior,
after my arrival in America, though not so frequently as when I was younger.
As I had often, oh, very often! knowingly withstood it,
my taste for worldly pleasures being now grown stronger,
I was very unwilling to give up to the call of Christ.
I could plead abundance of excuses, concluding among other things, that I was but young,
and might live a great many years; that if I did take my swing a few years,
I might become religious sooner than many others had done,
who were brave men in their day.
I would, however, to make myself more easy for that time,
fully determine to be a very religious good man at one time or other;
but it must not be yet.
Thus, through the gross darkness which had covered my mind, I,
who had no certainty of seeing the light of one day more,
was prevailed upon by the subtlety of Satan,
to run the dreadful hazard of future repentance and amendment of life;
and so I became worse and more hardened in evil,
though still preserved out of gross pollutions, or what are commonly so esteemed.
I was afraid to tell a lie,
except to embellish or set off a pleasant or merry tale or story;
apprehending it no great crime to tell a lie in jest.
I do not remember ever to have sworn an oath, or uttered a curse.
Nor was I prevailed upon, in my customary conduct,
to depart from the rules of my education, respecting the plain language,
thee and thou to one, and you to more than one;
all this time preserving a pretty fair character among men,
as none could charge me with any thing accounted scandalous.
I retained much love and regard for those I thought truly religious,
especially weighty substantial ministers of the everlasting Gospel;
and I believe had a better sense of their spirits and labors,
than some of my companions had,
and therefore was afraid to despise or speak contemptuously of such,
as some of my associates did.
In this carnal degenerate state, I commonly in a customary way,
attended first-day meetings,
and mostly had the liberty of going on other days of the week,
when any ministers from distant parts came to visit Abington meeting,
to which I belonged: but alas! it was to little or no good purpose,
as the labor bestowed upon me, by ministry or otherwise,
was like water spilt upon a stone, that soon runs off again without any entrance.
I was indeed for some time, like the heath in the desert, not knowing when good came;
and if at anytime, the seed of God`'s kingdom fell upon my heart,
which was like the highway ground, it was soon taken away,
and I presently lost the savor thereof.

When I had arrived to upwards of nineteen years of age, I was, through infinite mercy,
never to be forgotten, visited in an extraordinary manner; concerning which,
as it was the happy means of turning my mind, in a good degree,
from the perishing vanities of an uncertain world, to the God of all sure mercies,
I intend to be somewhat particular.
One evening being with several of my companions in vanity, and under no restraint,
as the heads of the family were not at home,
we carried our frothy vain conversation and foolish rude actions,
to a higher degree of wicked madness than I ever was guilty of before,
in which I suppose I was as a ringleader.
On this account, I felt some sharp lashes of conscience as I went to bed that night;
and a thoughtfulness took hold of my mind,
that we had not a being in this world for such a purpose,
or to spend our time as above mentioned, of which I gave some hint to my bed-fellow;
yet (his conviction did not sink so deep, but that I pretty soon got to sleep.
I had not slept long,
before a messenger alarmed me with an account that one of my jolly companions,
who was then in the house, and who, I think, had been the best of us, was dying,
desiring me to go immediately to him, which I did.
I was exceedingly struck with horror of mind,
at the thoughts of the manner in which we had spent the evening before,
and the sudden stroke that followed upon this poor man.
But when I came to his bedside and saw the dreadful agony he was in,
my horror was increased beyond all expression,
as none of us expected he could live many hours.
For my part, I was so deeply plunged into anxiety of mind,
that it seemed as if the pains and terrors of hell had laid hold of me already;
and I was then in full expectation there was no deliverance for me therefrom;
but that I should die before morning, with the weight of the distress which was upon me.
This happened on a seventh-day night, and though the young man in time recovered,
yet he was not fit to be left next day, which hindered me from going to meeting,
where I was exceedingly desirous to go;
for by this time I was pretty thoroughly awakened to a sense of duty;
and it being a week before the like opportunity presented to me again,
it seemed the longest week I had ever known.
O how did I long to present myself before the Lord in the assemblies
of his people! that I might pour forth my inward cries before him,
in a state of sincere repentance and deep contrition of soul; which,
through the effectual operation of his power in my heart,
I was then in a condition to do.
Now I clearly saw, that repentance is the gift of God, and that his love,
wherewith he has loved us in Christ Jesus our Lord, leads sinners thereinto.
The fleshly will being for the present overcome and silenced,
there was a giving up with all readiness of mind, to the Lord`'s requirings.
There was not any thing then too near to part with for the
real and substantial enjoyment of the Beloved of my soul;
for I was brought in degree to experience, that he came "`for judgment into this world,
that they which see not might see; and that they which see might be made blind.`"
I could no longer look upon my former delights with any satisfaction,
but instead thereof, had a glorious view of the beautiful situation of mount Zion,
and my face was turned thitherward, and for the joy which was set before me,
I was made willing to endure "`the cross of Christ, and to despise the shame;`"
and though I became a wonder and a gazing stock to my former companions,
I did not much regard it, knowing I had just cause so to be.
My great change struck them with some awe,
for I observed they had not the boldness to mock or deride me before my face.

The young man, who was an instrument in the Divine hand for my awakening,
and his brother, were both greatly reached and deeply affected for the present,
by the above mentioned wonderful visitation,
and there was a very visible change in them for a time;
but like the seed that fell on the stony ground,
they withered away and did not become fruitful to God.

I greatly rejoiced when first-day came, that I might go to meeting;
which proved to me indeed a memorable one, there being two public Friends, strangers,
sent there as I thought on my account; for most of what they had to deliver,
appeared to me applicable to my state.
Now did I in some degree,
experience the substance of what was intended by the "`baptism of water unto repentance;
the washing of water by the word; and being born of water and the spirit.`"
All which would be fully seen and clearly understood by the professors of Christianity,
were they rightly acquainted with the
"`Gospel of Christ; which is the power of God unto salvation.`"
This power inwardly revealed, is alone able to work that change in them, without which,
our Lord says, none shall so much as see the kingdom of God.
But alas! being carnal in their minds, a spiritual religion does not suit them;
for as says the Scripture,
"`the natural man receives not the things of the Spirit of God,
for they are foolishness unto him; neither can he know them,
because they are spiritually discerned.`"
Hence it is, that the professors of the Christian name, retain signs and shadows,
while the substance is neglected; pleading for the continuance of types,
when the antitype is but little regarded.
Where this latter is experienced, all shadows and types vanish and come to an end;
as did the legal types, when Christ the antitype, came and introduced his dispensation,
which is altogether of a spiritual nature.
And what is yet more wonderful, and an evidence of great ignorance, is,
to find those happy and blessed effects,
which are only produced by the baptism of Christ with the Holy Ghost,
attributed or annexed to the ceremony of sprinkling a
little water by a priest in a child`'s face:
for when that is done, the priest prays "`that old Adam in the child may be buried;
that the new man may be raised up in him; that all carnal affections may die in him;
and that all things belonging to the spirit may live and grow in him.`"
Then he prays, that the element of water may be sanctified to the washing away of sin.
The child is then said to be received into the congregation of Christ`'s flock,
and is signed with the sign of the cross: when this is done,
they acknowledge the child to be regenerate,
and grafted into the body of Christ`'s church, and return thanks to God,
in that he has been pleased to regenerate; that infant with his Holy Spirit,
and to receive him for his own by adoption.
Concerning a child sprinkled, they say,
"`who being born in original sin and the wrath of God,
is now by the laver of regeneration in baptism,
received into the number of the children of God, and heirs of everlasting life.`"
They say, by baptism, that is, sprinkling infants, that they have put on Christ,
and that they are made children of God and of the light.
They hold children baptized, dying before they commit actual sin, are undoubtedly saved;
which seems to imply that others are not.
Being weary of reciting these palpable errors,
I shall proceed with the account of my own progress,
in the real experience of this great work of regeneration, or the new birth, which,
I well know, is not obtained at so easy a rate as above mentioned.

This administration of water by the Word, continued in a remarkable manner upon me,
for about three months, in which I found great satisfaction,
as it was accompanied with a heavenly sweetness,
like healing balsam to my wounded spirit; my heart being melted before the Lord,
as wax is melted before the fire.
Great was my delight in reading the Holy Scriptures and other good books;
being favored at that time, to receive much comfort and improvement thereby.
But this easy melting dispensation, was to give way to a more powerful one,
that the floor might be thoroughly purged, even the baptism with the Holy Ghost and fire.
For the former dispensation of the Lord to my soul,
seemed much to resemble John`'s baptism with water unto repentance,
as being the real thing signified thereby, in order to prepare the way of the Lord.

Under this fiery dispensation I was for a time exceedingly distressed,
in a sense of the great alteration I found in the state of my mind;
attributing it to some cause given by me, that I was thus, as I thought, forsaken.
All the former tenderness was gone, and I was as the parched ground.
My agonies were so great, that when it was day I wished for night;
and when it was night I wished for day.
In meetings for worship, where I had enjoyed most satisfaction,
I now was under the greatest weight of pain and distress, even to that degree, at times,
that I could scarcely forbear crying aloud for mere agony.

When meeting was over, I would sometimes walk a considerable way into the woods, that,
unheard by any mortal, I might, in mournful accents,
give vent to my greatly distressed soul.
In this doleful state of mind,
the grand adversary was permitted to pour forth floods of temptations.
I was almost constantly beset with evil thoughts, which exceedingly grieved me;
for though I was in such a dark, distressed condition, my mind was, by this time,
too much enlightened to allow of, or join with, wicked and corrupt thoughts:
yet I often judged myself, and I believe at times not without cause, being apprehensive,
I was not earnest enough in resisting those evil thoughts and temptations.
But, oh!
I was exceedingly weak in those days; and I am persuaded the Lord,
in gracious condescension, looked mercifully at the sincerity of my intention,
not marking all my failings,
or I could not have stood before him in any degree of acceptance.

Very great were my temptations, and deep my distress of mind, for about a year;
in which time I was but as a little child in
understanding the way and work of God upon me,
for my redemption.
Yet, He who will not break the bruised reed, nor quench the smoking flax,
until he sends forth judgment unto victory, by his invisible power,
bore up my head above the raging waves of temptation,
so that the enemy found he could not overwhelm me therewith.
The Lord taught my hands to war, and my fingers to fight under his banner,
through whose blessing and assistance, I found some degree of victory over the beast,
that is, that part which has its life in fleshly gratifications.
Then began the false prophet to work with signs and lying wonders,
in order to deceive my weak and unskillful understanding: as it is written,
"`Satan is transformed into an angel of light;`"
so I found him, at least in appearance.
He that goes about seeking whom he may devour,
perceiving that I was too much enlightened from above,
to be easily drawn into sensuality, craftily attempted my destruction another way,
namely, by setting himself up, undiscovered then by me,
for a guide in the way of mortification, which I was resolved, through Divine assistance,
carefully to walk in,
by denying myself in all things which appeared inconsistent with the Divine will.
This subtle transformer,
taking advantage of the ardency of my mind to press forward in this necessary concern,
suggested that my work would be much easier in obtaining a complete victory over evil,
were I to refrain for a time from some of the necessaries of life,
particularly from eating and taking my natural rest in sleep,
except just as much as would preserve life;
and that I must constantly keep my hands employed in business,
as idleness is the nursery of vice; neither was he wanting to bring Scripture,
and passages out of other religious books, to confirm these requirings.
I then really believed it was the voice of Christ in my mind commanding these things,
and therefore endeavored to be faithful therein,
till my natural strength abated and my body grew much weaker.
Greatly distressed I was,
when at any time I fell short of what I apprehended to be my duty in these respects,
he that required this service being a hard master; though he had power to deceive,
yet he could not give me faith that I should overcome.
My views in those days were indeed very discouraging,
my poor afflicted soul being almost sunk into despair.
My friends took notice that I was in uncommon distress.
The family in which I then lived, could not be altogether ignorant,
though I concealed it as much as I could, of my wandering about in the fields, etc.,
at nights, and much refraining from food;
my deep distress being also very legibly imprinted on my countenance, and they feared,
as I afterwards understood, lest I should be tempted to lay violent hands on myself.
I was forbidden in myself to tell my condition to any,
as that would be seeking relief from without; a very improper and unworthy thing.

Notwithstanding which, the God of all grace,
who permitted this uncommon affliction to fall upon me for a trial,
and not for my destruction, was pleased, in wonderful kindness,
to move upon the heart of a minister belonging to our meeting, to visit me,
and to open a way for my deliverance.
He strictly inquired concerning my inward condition,
informing me that Friends were much concerned about me,
as it was very obvious I was under some uncommon temptation.
I was at first very unwilling to open my state to him; however he at length prevailed,
and took the opportunity to show me that I was under a gross delusion of Satan.
Being thus, through the Lord`'s mercy, delivered from the wicked design of my enemy,
which undoubtedly was to destroy both soul and body, I had, in reverent thankfulness,
to rejoice in his salvation.
I then clearly saw, that Satan in his religious appearances,
is also carefully to be guarded against; as nothing in religion can be acceptable to God,
but the genuine product of his unerring Spirit,
distinctly heard and understood by the ear of the soul, and the renewed understanding.
"`My sheep,`" said Christ, "`hear my voice;`"
which I now began to experience fulfilled;
blessed be the Lord forever!
I had many precious openings into the divine mysteries about this time;
and when I read the Holy Scriptures, they were opened to my understanding,
far beyond what they had ever been before, so that I had very great comfort;
my hope being revived and my faith much strengthened,
by those things that were written aforetime.
I am well assured, by certain experience,
that the mysteries couched in those holy writings, cannot be rightly understood,
but by the same spirit which inspired the penmen of them:
therefore it is vain presumption, for fallen and unregenerate man,
by his earthly wisdom and human learning, to attempt unfolding heavenly mysteries.
The lip of truth has signified,
that they are hidden from the wise and prudent of this world,
and revealed unto the humble dependent babes and sucklings;
those who sensibly experience their sufficiency for every good word and work,
to proceed immediately from God; and that Christ "`is made unto them,
wisdom and righteousness, sanctification and redemption.`"
The lack of this inward living sense, has been the cause of, and has opened the way for,
the great apostasy, darkness and error, which have overspread Christendom, so called.
There is no way for its recovery, but by humbly submitting to Christ inwardly revealed,
and learning the nature of true religion of him, the great author thereof.
I am well assured that forward, active and inventing self must be denied,
abased and laid in the dust forever, and the Lord alone exalted in our hearts,
before we can come up in the several duties of religion, with Divine approbation.
I saw that the Divine light which began to shine out of my darkness,
and separated me therefrom,
was the greater light which was to rule the day of God`'s salvation,
and that all the saved of the Lord must carefully walk in this light,
wherein there is no occasion of stumbling.
I also saw, that when it pleased the Lord in wisdom,
for a trial of my faith and patience, to withdraw this holy light,
and there was a sitting in darkness,
and as in the region of the shadow of death for a time,
so that I had no distinct knowledge therefrom what to do;
that it was my indispensable duty to stand still, and wait for my sure unerring guide;
if at those times, self would arise and be uneasy, it must be brought to the cross,
there to be slain.
By such experience, I found I was nothing,
and that God was all things necessary for soul and body;
and that if I was brought into a state of perfect reconciliation with him,
I must know all things made new.

About this time I had a distant view of being called into the work of the ministry;
my mind being at times wonderfully overshadowed
with the universal love of God to mankind,
in the glorious Gospel of his Son, to such a degree, that I thought I could,
in the strength thereof, give up to spend and to be spent,
for the gathering of souls to him, the great Shepherd of Israel;
and that I could lift up my voice like a trumpet, to awaken the inhabitants of the earth.
But I found all this was only by way of preparation for this important work,
and that I had not yet received a commission to engage therein.
A fear and care were upon my mind,
lest I should presume to enter upon this solemn undertaking without a right call;
it appearing to me exceedingly dangerous to speak in the name of the Lord,
without a clear evidence in the mind, that he required it of me;
which I then fully believed he would do in his own time, which was to be waited for.
From this time, until I was really called into the work, I frequently had,
but especially in religious meetings, openings of Scripture passages,
with lively operations of the Divine power in my mind; and sometimes with so much energy,
that I have been almost ready to offer what I had upon my mind, to others.
But as, through a holy awe which dwelt upon my heart,
I endeavored to try my offering in the unerring balance of the sanctuary,
I found it was too light to be offered,
and was thankful to the Lord for his merciful preservation,
in that I had been enabled to avoid offering the sacrifice of fools.
But when the time really came that it was divinely required of me,
the evidence was so indisputably clear, that there was not the least room to doubt;
yet through fear and human frailty, I put it off, and did not give way thereto.
But oh! how was I condemned in myself!
The divine sweetness which had covered my mind in the meeting was withdrawn,
and I was left in a very poor disconsolate state, wherein I was ready to beg forgiveness,
and to covenant with the Lord,
that if he would be pleased to favor me again in like manner,
I would give up to his requiring.
At the next first-day meeting, the heavenly power overshadowed me in a wonderful manner,
in which it was required of me to kneel down in supplication to the Lord in a few words.
I gave way thereto, in the dread of his power, with fear and trembling.
After which, my soul was filled with peace and joy in the Holy Ghost, and I could sing,
and make sweet melody in my heart to the Lord.
As near as I remember, I was twenty-one years of age,
the very day I first entered into this great and awful work of the ministry;
which was the 21st of the fifth month, old stile, 1734.

I have found my mind engaged to be somewhat particular concerning
the manner of my entering into the work of the ministry,
to stand by way of caution and proper encouragement to others, who may peruse the same;
having in the course of my observation,
had cause to fear that some have taken the work of preparation, as before hinted,
for the thing itself; and so have proceeded very far, to their own great wounding,
and the hurt of others, in bringing forth untimely fruit, which is exceedingly dangerous,
and carefully to be avoided.
Nothing is a sufficient guard to preserve therefrom, but keeping a single eye,
through the divine blessing,
awfully considering what a great thing it is for dust
and ashes to speak as the apostle Peter directs,
"`As every man has received the gift, even so minister the same one to another,
as good stewards of the manifold grace of God.
If any man speak, let him speak as the oracles of God; if any man minister,
let him do it as of the ability which God giveth.`"
The author to the Hebrews says, that
"`no man takes this honor to himself, but he that is called of God, as was Aaron.`"
So that whatever some may pretend to, and intrude themselves into,
unless they are really called of God,
they have no share in that honor that comes from God only.

The church of Christ has not been without its trouble from false ministers,
neither in the primitive times, nor in ours.
That excellent Gospel liberty in which all who feel themselves inspired thereunto,
whether male or female, may speak or prophecy, one by one, has been, and still is,
abused by false pretenders to divine inspiration;
yet the liberty ought to be preserved inviolable,
and other means found out to remedy this great inconvenience;
which would not be difficult, were the members in a general way spiritually minded,
rightly savoring the things that be of God.
Forward and unsanctified appearances, by way of ministry,
would then be easily awed and suppressed, so as not to disturb the peace of the church.
The case has been otherwise, as I have observed in some places; but was little minded,
if the words and doctrine were sound, and nothing to blame in the conduct.
Here the main thing, which is the powerful demonstration of the Holy Spirit,
is disregarded; and if a few are deeply pained at heart with such lifeless ministry,
they find it exceedingly difficult to lay hands thereon, for lack of more strength;
especially when they perceive what strength there is against them;
for formal professors love to have it so, rather than to sit in silence.
I have observed such pretenders to be all mouth or tongue,
having no ears to receive instruction; fond of teaching others,
but very unteachable themselves.
I pray God to quicken his people,
and raise the Society into a more lively sense of that
blessed power which gathered us to be a people;
or I fear the great evil above hinted at will prove a growing one;
profession without possession,
being the proper element for such a ministry to flourish in.
I am not quite free to omit a remark on this head,
as I am fully persuaded the living members of the church of Christ,
groan under a painful sense of this sorrowful token of a declined society.
May the Lord of sabbath hear their cries,
and regard the anguish of their souls in secret,
so as to work by his invisible power for his own name`'s sake, and their enlargement,
by turning his hand again upon our Zion, to purge away her dross,
and to take away her tin and reprobate silver,
that her judges may be restored as at the first, and her counsellors as at the beginning;
that many, having their feet shod with the preparation of the Gospel of peace,
may yet appear beautiful upon the mountains!
So be it, says my soul!

I have given some hints how it was with me,
by way of preparation for the great and important work of the ministry,
and the danger of my being misled, even sometimes when I had right openings,
and felt the sweet efficacious virtue of the love of God, through Jesus Christ,
to mankind; which, doubtless,
is at times the sensible experience and enjoyment of every faithful follower of Christ,
who never was called to the work of the ministry.
I was in those days apprehensive of some danger of being led out at that door;
but I have since more fully seen the danger of this and other by-paths,
which would have led me to give that away to others, which I was to live upon myself;
and out of the humble, dependent state, in which only there is safety,
to have a will and way of my own,
that I might be furnished and enriched with much treasure.
But sincerity of heart, and my endeavors to preserve the single eye,
through the watchful care of Divine Providence over me,
brought the day of the Lord upon it all; so that I came clearly to see,
and experimentally to know, that my sufficiency was of God;
that there must be a steady dependance on the Lord,
to be immediately fitted and supplied, every time I was to engage in this solemn service.
I ardently desire,
that all who have the least apprehension of being called into the work of the ministry,
may dwell in a holy dread of the Divine presence,
and know their own wills wholly subjected to the divine will,
waiting for a distinct and clear certainty of the Lord`'s requirings,
not only in entering upon it at first, but also at all other times.
And as self comes to be laid in the dust,
they will receive undeniable evidence in their
own minds of the certainty of their mission;
and they will not be without a testimony thereof,
from the witness for God in the consciences of
those among whom they are sent to minister.
They will be a savor of life to the living in the Truth,
and of death to those who are in a state of death.
Let it ever be remembered, that nothing of or belonging to man,
can possibly add any luster or dignity to the divine gift.
Neither will the best and most curiously adapted words or doctrine,
ever so truly and consistently delivered, be any more than as sounding brass,
or as a tinkling cymbal, without the power,
light and demonstration of the spirit of Christ.

There is no occasion for those who regard his power as the substance of their ministry,
to be solicitous about words; as the lowest and most simple are really beautiful,
when fitly spoken under that holy influence.

Having entered upon the solemn and awful service of the ministry,
I gave up for the most part, as I found the requirings of Truth,
through the divine power and efficacy thereof,
moving upon my heart and subjecting my will, to utter a few words in a broken manner,
with fear and trembling; the Lord being exceedingly merciful to me, as a tender father,
taking me by the hand, and making me willing by his mighty power,
to be counted a fool for his sake and the gospel`'s.

The meeting I then belonged to was large, and a body of valuable weighty Friends therein;
who, as far as I could observe by their carriage,
did own and approve of my weak and low appearances in this service:
yet they used Christian prudence, not to lay hands suddenly,
but gave me full opportunity to make proof of my ministry, and to feel my feet therein.

About this time a fine spring of ministry was
opened within the compass of our Yearly Meeting;
there having, by account, about one hundred opened their mouths in public testimony,
in little more than a year; several of whom became powerful, able ministers,
and some of them withered away like unripe fruit.
About ten appeared within that time, in the particular meeting of Abington,
to which I belonged.

As I was enabled to wait on my ministry,
I experienced a considerable growth and enlargement; and,
in a faithful discharge of duty therein, great peace and heavenly consolation,
like a pleasant refreshing stream, flowed into my soul.
I also found, that it was a means of engaging the minds of Friends,
in a sweet and comfortable nearness of unity with me,
which I had never before so largely and livingly felt.
Many well-minded young people, and some others of little experience,
seemed to admire my gift, and would sometimes speak highly of it,
which they did not always forbear in my hearing.
But oh, how dangerous this is, if delighted in by ministers!
It may be justly compared to poison, which will soon destroy the pure innocent life.
My judgment was against it; yet I found something in me,
that seemed to have no aversion thereto, but rather inclined to hearken to it,
yet not with full approbation.
The same thing in me would want to know, what such and such,
who were in most esteem for experience and wisdom, thought of me.
I sometimes imagined such looked shy upon me, which would cast me down; all which,
being from a root of self, I found was for judgment, and must die upon the cross,
before I was fit to be trusted with any great store of gospel treasure.
I began also to take rather too much delight myself in the gift;
and had not Divine goodness in mercy, by a deep and distressing baptism,
kindly prevented, this might have opened a door for spiritual pride,
which is the worst kind of pride, to enter in, to my ruin.
I have reason to think, that solid Friends observing my large growth in the top,
with spreading branches, were in fear of my downfall, in case of a storm.
But, in the midst of my high career, the Lord was pleased to take away from me,
for a time, the gift of the ministry, and with it all sensible comforts of the Spirit;
so that I was, as I thought, in total darkness; even in the region and shadow of death.
In this doleful state of mind, I was grievously beset and tempted by the false prophet,
the transformer, to keep up my credit in the ministry,
by continuing my public appearances.
It might well be said of him, that he would
"`cause fire to come down from heaven, in the sight of men, to deceive them;`"
for so I found it.
It is hard to imagine, how near a resemblance he could make,
how exact an imitation he could form, of the very thing itself,
to the state of mind I was then in; even to that degree,
that I have at times been ready to say,
"`Ah! I see and feel the fire of the Lord coming down to prepare the offering;`"
and have been almost ready to give up thereto,
when a godly fear would seize my mind, and a desire to try it again; by which means,
the strong delusion has been discovered, the false fire rejected,
and my soul been plunged into deeper anxiety, by this false heat, than I was in before.
No tongue or pen can set forth to the full, the almost constant anguish of my soul,
for about the space of four or five months;
being as nearly as I can remember the time this sore affliction was upon me.
It fared with me in some degree, respecting my friends, as it did with Job;
some conjecturing one thing and some another thing, to be the cause of this fall,
as it was apprehended; though,
through mercy they could not charge me with any evil conduct as the cause thereof.
The most probable reason to them, of this alteration was,
that I had been too much set up by others, and so had lost my gift; and this, I think,
came the nearest to the truth of the case.
Yet it was not so lost, but that when my gracious helper saw my suffering was enough,
he restored it again, and appeared to my soul as a clear morning without clouds:
everlasting praises to his holy name!
My mind was deeply bowed in humble thankfulness,
under a sense of the great favor of being again counted
worthy to be entrusted with so precious a gift;
therefore I was careful to exercise it in great fear and aw fulness,
and more in a cross to my own will than before;
as that which was likely to deck itself therewith, was, for the present at least,
in a good degree slain.
I have very often in the course of my religious experience,
had cause to admire and adore Divine wisdom,
in his dealings with me for my preservation in the way of peace;
being well assured that he will so work for mankind,
if they are entirely given up in heart to him,
that it will not be possible for them to miss of everlasting happiness;
for none are able to pluck those out of his almighty hand,
who do not first incline to leave him.
