== Chapter 2

[.chapter-synopsis]
* His first religious visit
* Further exercises respecting his appearances as a minister
* Visit to some meetings in East-Jersey
* Marriage and settlement at Darby
* Visits New England in the work of the Gospel
* Makes a similar visit to meetings in New York
* also to meetings in Chester county, Pennsylvania then to West Jersey, to Maryland and Delaware
* and in Bucks County
* Death of his daughter and wife.

After I had appeared in public somewhat more than two years,
I found some drawings of Gospel-love, as I apprehended,
to visit the meetings of Friends in some parts of NewJersey;
and being but young in the ministry, I was in great fear, at times,
lest I should be mistaken,
in that which at other times I thought to be the Divine requiring.
I much dreaded running when and where the Lord did not send me,
lest I should bring dishonor to his blessed name,
and expose myself without proper qualifications for so great an undertaking,
to wise and discerning Friends.
Great indeed was my distress, night and day, crying to the Lord for greater confirmation;
which he graciously heard, and was pleased, by a dream or night vision,
to afford me such full satisfaction,
that I do not remember I had any doubt afterwards concerning it.

I entered upon the journey on the 7th of the eighth month, 1736;
having a companion much older than myself.
We visited the following meetings, Pilesgrove, Salem, Alloways-creek, and Cohansey,
where my companion left me, and returned home,
being under some discouragement about the journey in his own mind.
But as I found the Lord by his blessed power near,
opening my mouth and enlarging my heart abundantly in his work,
I was encouraged to proceed,
being joined in travel by an innocent Friend belonging to Alloways-creek meeting,
who had a few words to speak in meetings.
We went from Cohansey, through a wilderness for about forty miles, without inhabitants,
to Cape May, where we had a meeting.
From there to Great and Little Egg-harbour and had meetings, then through the wilderness,
to the Yearly Meeting at Shrewsbury,
which was large and much favored with the Divine presence;
several ministering Friends from Pennsylvania being there, namely, Thomas Chalkley,
Robert Jordan, John and Evan Evans, Margaret Preston, and others.

It neither suited my growth in the ministry, nor my inclination,
to take up much time in these large meetings.
I therefore, for the most part, gave way to such as were better qualified for the work,
and in my esteem worthy of double honor.
I had a great regard in my mind for those whom I thought pillars in the house of God,
whether ministers or elders; and really think, if such had given it as their sense,
that I was wrong in my offerings, at any time,
I should have been more likely to depend on their judgment than on my own.
I looked upon myself, for many years, as a child in experience every way;
and therefore thought a subjection was due from me,
to those who were fathers and mothers in Israel, and never, that I remember,
manifested any disregard to them; which is now a satisfaction to my mind.
I confess, I have at times since had cause to marvel at the forwardness of some,
who though but children, if rightly children at all, have undertaken the work of men,
hardly discovering a willingness to give the preference to any;
and when they have been admonished by those of much more experience than themselves,
they have been apt to retort, or to plead a Divine commission,
and that it is right to obey God rather than man;
as if they had the sole right of speaking and judging too.
I had several times seen the great danger of
being deceived and misled by the transformer,
and therefore was afraid of being confident of my own sight,
and looked upon it to be safest for me to stand quite open to instruction,
let it come from what quarter it would;
there being nothing more desired by me than to be right.

This large meeting ended well and sweetly.
Praises to the Lord over all forever!
From there I went to meetings at Chesterfield, Trenton, Bordentown, Mansfield,
Upper Springfield, Old Springfield, Burlington, Bristol, the Falls, Ancocas, Mount-Holly,
Evesham, Chester, Haddonfield and Woodbury creek; from where I returned home.
The Lord made my journey prosperous, and was to me at times, as a fountain unsealed,
furnishing daily for the work he had engaged me in;
being in wonderful condescension to my weak estate, both wisdom and utterance;
as it is written,
"`Out of the mouths of babes and sucklings you have ordained strength.`"
Praises to his holy name forever!

Notwithstanding the Lord had committed to me a dispensation of the Gospel,
and was pleased to reward my sincere labors therein,
with the sweet incomes of peace and joy in the Holy Ghost,
and with the unity of the brethren in a comfortable degree;
yet great were my temptations, and various the combats I had for some years after,
with my soul's enemies.
Oh! how hard I found it to keep from being defiled, more or less,
with the polluting floods,
which were almost continually poured out of the dragon's mouth,
in order to carry away my imagination into unlawful delights,
from which I did not always wholly escape;
being sometimes prevailed upon to set bounds to myself,
that though I would not directly fall into the evil I was tempted to,
yet I might take some delight and satisfaction in
approaching as near thereto as I thought was lawful.
Thus, for lack of a watchful care, not only to shun that which I knew to be really evil,
but also every appearance of evil,
I sometimes brought great anguish and deep distress upon my mind;
and when I had gone but a little out of the right way, I found many,
oh! many weary steps and painful heart-achings necessary,
before I was received again into the way and favor of my heavenly Father.
I have often since been humbly thankful for his preservation, even out of gross evils,
considering my dangerous tampering therewith at times in the imagination.
How can weak mortals determine what length they will go, when any way is given?
Most certain it is, they go out greatly to their hurt,
who take any pleasure at all in the thoughts of forbidden things.
I have found by woful experience, that when the least way is given to the enemy,
he gains advantage over us, and we are greatly enfeebled thereby;
so that instead of growing as willows by the water-courses,
there is danger of withering and becoming of those that draw back,
in whom the Lord has no pleasure.
I found it the first subtle working of satan,
to draw me off from a constant care of bringing all my thoughts, words and actions,
to be tried by the light of Christ in my own heart; and instead thereof,
to examine them by my partial reasoning part.
Here many things really evil in their nature or tendency, or both,
would carry the appearance of indifference; the pleading would then be,
there is no harm in this, that or the other thing;
yet there has been a doubt perhaps in the mind to reason away, not duly considering,
that he who doubts, is condemned if he receive.
So have I many times found it, when the Judge of all has been pleased to arise,
and to find me out, with my fig-leaf covering on; having, by giving way to wrong things,
in a great measure lost the garment of innocence, and a holy confidence towards God.
Oh! how very hot has my neglect occasioned the furnace to be made,
that so the dross might be done away.

Thus it was with me,
until the many chastenings of the heavenly Father brought me into more fear,
care and subjection.
I could not be quite easy to omit giving these hints of my many weaknesses and failings,
that others may learn thereby to be aware.
This I apprehend to be the chief reason of our having the failings and
miscarriages of God's people transmitted to us in the Holy Scriptures.
You traveler Zionward, look forward to the joy set before you,
not allowing your eyes to wander about you, lest they convey such delight to your heart,
as may infect your soul with pernicious distempers,
by which you may be rendered unable to proceed on your journey towards the holy city;
and through the defect occasioned thereby to your sight, you may, in a great measure,
lose the glorious prospect of its beautiful situation and the splendor of its structures.
Beware you do not load yourself with the seemingly
pleasant fruit of that country through which you travel.
Although it may appear to hang plentifully on each hand,
it will neither be of any use to you in that heavenly country where you are going,
nor for refreshment on the way there.
If you have a mind that your own way should be prosperous, look steadily forward,
with a single eye to the recompense of reward.
Bring every motion towards seeking satisfaction in forbidden places,
immediately to the cross,
and you will much sooner find the yoke of Christ made easy and his burden light,
all his ways pleasant and his paths peace.
This is abundantly better than that uneasy in and out way of traveling,
sinning and repenting, repenting and sinning again,
which lays a foundation for murmuring, labor and toil; crying out,
as some do all their days,
there is no complete victory to be obtained over sin on this side of the grave;
miserable sinners we must remain; when the cause thereof is wholly in themselves;
because they will not come into and abide in the help of the Lord,
against the mighty enemies of their soul's happiness,
which is altogether sufficient to give a complete victory over them; yes,
to give power to triumph, and say,
"`We are made more than conquerors through him that has loved us.`"

In the eighth month, 1737, I set out in order to visit some meetings in East-Jersey;
having Richard French, an ancient Friend to bear me company.
We had meetings at Stonybrook, Bethlehem, Lebanon,
and at a Baptist's house near Black-river.
None of our Society were thereabouts, but there were some Ranters of Rogers's followers,
who had taken upon them the name of Quakers,
to the great scandal of Friends in that remote place: they came to the meeting,
being mostly women.
Their impatient restless spirits would not allow them to let us hold our meeting quietly;
yet they did not seem inclinable to contend, but rather to flatter and applaud us.
Some of them stood up, after we had each delivered what we had upon our minds,
to signify their unity with our doctrine,
pretending it to be the same they held forth to the people,
though not enough regarded by them.
But we were not free to receive their testimony,
any more than Paul and Silas could that of the
maid who was possessed with an evil spirit;
but rebuked them openly, and publicly declared our disunity with them,
desiring the people not to look upon them as belonging
to the Society of the people called Quakers,
as we could assure the meeting it was not so;
and that we had no more unity with those pretenders, than they had.
I thought the chief service we had at that place,
was to testify against those wild frantic people, who by being accounted Quakers,
had caused the way of Truth to be evilly spoken of.
This unexpected opposition raised their flighty spirits,
so that they became very troublesome, being full of words,
and asking frivolous questions.
Whereupon the words of Paul to some such women in the Corinthian church,
came freshly into my mind.
I therefore called out aloud,
"`Let your women be silent in the church;`" and opened to them,
that it was such women as they were, whom the apostle rebuked and commanded to be silent;
who not experiencing their spirits to be truly subjected,
that they might know how to speak concerning the
things of God with a right understanding,
ought to learn in silence: not meaning to exclude those of my own sex in the like case;
the same thing being as necessary for them.
We left them as full of themselves as we found them, and went from there to Whippany,
where we had a precious meeting in a Friend's house.
The greater number being of other societies, the testimony of Truth flowed forth freely;
they appearing to be much tendered and affected therewith.
After meeting some of them took us by the hand,
and in an affectionate manner expressed their satisfaction with our labors amongst them.
From there we went to Plainfield and Woodbridge, where we had meetings,
and then returned home;
having been favored to accomplish this little journey to my own satisfaction.

Sometime before I entered upon the before mentioned journey,
I found my mind pretty strongly drawn to enter into the marriage
state with a young woman belonging to the same meeting,
within the compass of which I had lately taken a farm,
and to which I was then joined by certificate.
Her name was Rebecca, the daughter of Josiah and Sarah Fearn,
and grand-daughter of John Blunston: she being a valuable branch of a good stock.
By the death of her brother,
she was possessed of that part of her said grandfather's estate,
where he had lived and entertained Friends from
almost the first settlement of Pennsylvania,
until his death; which afterwards was continued by his widow many years,
but of late had been laid aside.
It was in Lower Darby, about seven miles from Philadelphia, near a large meeting;
the meeting-house being built on some of that tract of land.
The reason of my being so particular in this account,
is to show the Lord's kindness and gracious condescension to me,
in so fully answering what I had often desired, namely,
that in case I ever married and settled,
I might be so circumstanced as to entertain the Lord's
servants and messengers in an agreeable manner;
on which account,
as well as that he was pleased to give me an affectionate virtuous wife,
I have great cause of humble thankfulness.
We took each other in marriage the 30th of the tenth month, 1737,
at a large and solemn meeting, held in the meeting-house before mentioned,
under the precious overshadowing of the power of divine love,
I think to a larger degree than I had often known before;
which was no small confirmation of our being rightly joined together;
it being that alone which can enable to make and keep covenant rightly with each other.

After my marriage I constantly attended our particular meeting,
both on first and other days of the week;
also the Quarterly and Yearly Meetings as they fell in course,
and frequently visited adjacent meetings.
I visited Friends in the county of Bucks twice, but have no account of the exact time.
I signified to my wife some time after we were married, that I expected in a few years,
I should find a concern to leave her for a longer time than I yet had done,
and gave her a hint what time I thought it would be; which fell out accordingly;
having then a distant view of visiting New England.

When the time for undertaking that journey appeared clear to me, I gave up thereto,
in humble resignation and faith in the sufficiency of the divine power of Him, who,
I believed, required it of me;
yet not without some intervals of discouragement and reasoning in myself,
what would become of my family and outward concerns.
Neither did I then know of any companion to join me in this great undertaking,
but at times believed I should be favored with one, if I gave up thereto.
I laid my concern before the Monthly Meeting to which I belonged,
requesting their concurrence and certificate, if upon a weighty consideration thereof,
they had unity with my concern.
A certificate was prepared, whereby I was left to my liberty to proceed;
but I had not yet heard of a companion, and greatly feared going without.
Our Quarterly Meeting falling quickly after, I went to it,
where I made inquiry of my much esteemed friend, John Churchman,
whether he knew of any suitable companion for me.
He readily told me that his brother-in-law, William Brown,
had procured a certificate in order for the same journey,
and did not then know of any companion, but believed one would be provided for him.
This was very acceptable to me.
William Brown and I had an opportunity of conferring together the same day,
and we found our concerns and views so exactly to agree,
and our spirits so closely united for the service,
that our hearts bowed in thankfulness to the Lord, for his care and providence over us;
believing what we were about to engage in, was agreeable to his will and in his counsel.
It being the meeting for ministers and elders that day,
we laid bur concern before that meeting, where it appeared to be well approved,
which was no small strength to us.
I did then, and hope I ever shall, greatly love and value the unity of the brethren;
having found it no small strength and encouragement to me, in low and trying times,
which are necessary and unavoidable in that solemn engagement of visiting the churches;
especially now in their low declined state.
It is indisputably clear to my understanding
that it is altogether impossible to administer,
in a feeling effectual manner to people's several states,
unless we are baptized thereinto.
Well adapted words and sound doctrine, as to the external appearance, may,
without much difficulty be attained;
seeing we have the holy Scriptures and many other good books,
containing the principles of Truth and the Christian experience of the Lord's people;
yet all this delivered with the tongue of men or angels, will prove an empty,
fruitless sound, without the power and demonstration of the Spirit of Christ,
who enables his upright-hearted ministers to search all things, yes,
the hidden mystery of iniquity, as well as the deep things of God,
even as he led his prophet Ezekiel to look through the hole in the wall,
that the most secret abomination may be brought to light and testified against.

I took leave of my dear wife,
and set out with my companion the 5th of the seventh month, 1741.
Passing through New-Jersey, we had a meeting at Chesterfield,
crossed Staten Island and came to an arm of the sea, called the Narrows,
which separates the before mentioned island from Long Island.
The wind blowing very strong and the sea running exceedingly high,
we were obliged to wait some time;
the ferrymen being afraid to run the hazard of carrying us and others who were there,
also waiting, over.
Towards evening the wind abating, they appeared willing to venture, if we would;
and we being desirous to proceed, agreed to go.
I think we had eight or nine horses, besides people, in the boat.
They set the horses heads to the wind, which proved of singular service,
in bearing up the boat against it;
otherwise it did not seem altogether improbable
that she would have been laid on her side.
We ran over in about ten minutes,
the distance being accounted at least two miles and a half.
We were thankful for preservation; as I believe most, or all of us,
when we were on the water, apprehended considerable danger.
We made but little stay on Long Island, only taking Newtown meeting in our way,
and crossing the water to the main land in New-York government,
had meetings at Mamaroneck, Longreach and the Purchase.
From there, having a guide provided for us, we set out for our journey,
about two hundred miles through the colony of Connecticut, to Rhode Island.
We met with a kind reception and entertainment for our money, at a very low rate,
amongst the Presbyterians of this colony: the case was very different formerly,
when our Friends were banished from there by a law.
I remarked as I passed along, that very good order was observed in their inns;
and as far as could be discovered,
the people in general appeared to be sober and religious in their way;
far from being so vitiated and corrupt as I found those in the mother country,
as they call it.
We were several times attacked by some of them on religious subjects,
but through divine favor, were enabled to answer them in such a manner,
that I hope neither we nor the Truth professed by us, suffered thereby.
I can say with thankfulness,
I never was at a loss in giving answers to those
who asked a reason of the hope that was in me,
when my chief dependence was on the Lord, to be furnished immediately by him,
without leaning to my own understanding.
We were kindly received by Friends at Newport, on Rhode Island,
where there is a large body;
some of whom we found much hurt by differences and parties about government affairs;
which caused hard close work for us, in their meetings.
From Rhode Island we went to the island of Nantucket, where is.
also a large body of Friends, amongst whom we had good satisfaction.
We then returned to the main land, visiting meetings at Sandwich, Yarmouth, Suckanesset,
and a Quarterly Meeting at Pembroke, where we met our friend Samuel Plopwood,
who had arrived at Boston, from England, a few days before,
in company with Moses Aldrich, on a religious visit.
We went to Boston, where we had a meeting,
there being a small number of Friends in the town, but Truth never prospered much there:
it seemed to me that something of the same spirit was yet alive and to be felt,
that formerly would have wholly extirpated our Friends, and Truth as held by them,
from the face of the earth,
and prevailed to inflict cruel sufferings on many of the Lord's servants,
four of whom they put to death, as is related at large in a book entitled,
"`New England Judged,`" written by George Bishop,
and in "`Sewel's History of the people called Quakers.`"
Happening to walk into the prison yard, I observed a very ancient building,
which I judged by its appearance,
might have been the same in which our Friends had formerly suffered very great hardships.
Upon which I asked some present,
if that was the prison their forefathers put our Friends into?
A woman answered, Yes; and added,
"`It was a very wicked thing of the rulers of that time,
and the land has suffered for it ever since;`" or to that import.
A Friend of Boston related to me,
what he said he had from an ancient inhabitant of the town,
who had seen that wicked act of putting to death the four Friends as above hinted,
namely, that he could well remember fine wheat growing about and near Boston,
and never knew or heard of any wheat blasted, or peas eaten by bugs,
until they put the Quakers to death;
and that they never could raise either wheat or peas near that town since,
perhaps not within fifteen or twenty miles.
I suppose the inhabitants were so often disappointed formerly,
that they have not attempted to raise any lately,
the land being generally turned to grazing, and for raising Indian corn.
They seem sensible of the extraordinary alteration;
but I suppose few of them are willing to attribute it to that cause.
I had some discourse with one of the inhabitants, as we were riding together near Boston,
concerning the above mentioned event.
He pretended to argue a natural cause for it; but I endeavored to show him,
that according to my apprehension,
those very reasons which he advanced to prove a natural cause for the change,
if they proved any thing, proved directly the contrary of what he intended, for he urged,
that clearing away the woods might so change the nature of the air,
as to produce a blasting quality therein.
But if the air any wise resembles water,
the freer its course and the less the obstruction it meets with,
the more it purifies itself,
and is therefore less capable of producing hurtful
consequences either to vegetables or animals.

We passed on and had meetings at Lynn, Salem, Cachechy, Dover, Hampton, Haverhill,
Amesbury, Newbury, Taunton, Acoakset, and to Dartmouth Yearly Meeting,
which was held there and at Acushnef, four days: it was large.
After which we had meetings at Rochester, Freetown, Swanzey, Leicester, Smithfield,
Providence Woods, at one Harris's, Greenwich, South Kingston, Conanicut Island,
Portsmouth, Tiverton, Little Compton, and so to Newport again:
several of which were large.
The Lord was graciously pleased to furnish us according to the occasion,
to labor amongst the professors of Truth in those parts,
many of whom appeared to us ignorant in a sorrowful degree,
of the life and nature of true religion.
Our spirits were often very deeply baptized on their account, in great travail,
that Christ might be formed in them.
It was a very exercising laborious journey, but the Lord mercifully made all up to us,
by the comfortable enjoyment of his love and peace flowing into our hearts.
Glory to his name forever!

From Newport we set our faces homeward, taking Westerly meeting in our way,
and proceeded through the colony of Connecticut to Long Island;
upon which we had meetings at Cowneck, Joseph Lealham's, Jericho, Westbury, Matinicock,
and were at the Quarterly Meeting at Flushing.
From there we crossed the water to Westchester on the main;
got there some time before the hour appointed for the meeting,
and staid a while at an inn in the town.
The landlady coming into our room in a pleasant manner, said,
"`I suppose you are traveling Friends?`"
My answer was, "`We are travelers and we are Friends;
therefore we are traveling Friends;`" "`But I suppose,`" said she,
"`you are preachers;`" and added, "`I like your way very well,
as you come up to the command of Christ, in traveling about as you do,
more fully than our ministers: but there is something lacking with you.`"
"`What is that, said I?`" "`Why, said she, you should baptize as well as preach.`"
I then asked her what we should baptize withal.
She replied,
"`With water to be sure; for it is not in the power of man to baptize with any thing else.`"
Upon which, I showed her from the holy Scriptures,
that the primitive ministers of Christ were so gifted,
as to be able to baptize believers into the name or power, of the Father,
Son and Holy Ghost; instancing, in particular,
that passage of Peter at the house of Cornelius; "`And as I began to speak,
the Holy Ghost fell on them, as on us at the beginning.
Then remembered I the word of the Lord, how that he said,
John indeed baptized with water; but you shall be baptized with the Holy Ghost.`"
It is evident from this account, that by the effectual preaching of Peter,
the gentiles were baptized with the Holy Ghost;
and as the dispensation of God to man is the same now as it was then,
and he has graciously promised to be with his ministers always to the end of the world,
and man, by nature in a fallen degenerate estate,
is as much involved in sin and a stranger to God as he was then;
no good reason can be given,
why the same powerful efficacious means are not as necessary for his recovery,
by a reconciliation with his Maker, as they were at that time.
The woman was very attentive to what was said on the occasion, and seemed affected,
being quite silenced as to that subject.
We invited her to our meeting; she told us she intended to go, and if she could,
to prevail with her husband to go too, but doubted being successful therein.
She and her husband were both at the meeting,
and the Lord was graciously pleased to give us a precious opportunity together,
wherein I am persuaded she was made in some degree sensible of that baptizing power,
which in a comfortable degree, accompanied the ministry that day.
She was tendered, and at parting, with tears desired us to remember her and pray for her.

After this meeting we proceeded homewards,
taking meetings in the Jerseys as they fell in our way, at Elizabethtown, Woodbridge,
and Stonybrook.
I got home the 7th of the tenth month, and found my dear wife and family well,
which was cause of mutual thankfulness; having performed nearly as much,
in about three months, as was usually done in about four.
It is very necessary to avoid both extremes in traveling on Truth's account,
neither to be over hasty, nor too dilatory;
yet I have always found great satisfaction and peace in
being as diligent and expeditious therein,
as sits easy on the mind, and the constitution of body will bear;
that all may have cause to be fully convinced we travel not for outward pleasure,
but from a necessity laid upon us;
which will certainly add considerable weight to our service, and greatly tend,
in the eyes of mankind,
to maintain the credit of that truly disinterested Gospel ministry,
which the Lord has been pleased to raise up amongst us as a people.

Having staid at home some time, to make necessary provision for an increasing family,
I found a concern upon my mind to visit Friends a second time
on Long-Island and the main land in New-York government,
and set out the 27th of the eighth month, 1743;
being accompanied by my well esteemed friend, John Sykes.
The first meeting we attended on the island, was a Yearly Meeting,
which was held on a first-day at Matinicock.
It was a large precious meeting; many not of our Society being there,
and the Lord was pleased to open the doctrine of his kingdom largely,
and his glorious Truth was over all; to whom alone be the praise forever!
Notice was given at this meeting,
of our intending to be on the next first-day at Westbury, not far from this place;
and that week we had meetings at Brook-haven, Islip, Bethpage, Rockaway, Henry Willis's,
and so to the before-mentioned meeting on first-day.
Friends came to it from several parts of the island,
and also many people of other societies, so that it was very large.
Their expectation was greatly after words,
which the master of our assemblies did not see fit to gratify;
for we were almost wholly shut up as to ministry;
which I hope proved a profitable lesson to many.
After this meeting we crossed the water, and had meetings at Westchester, Mamaroneck,
Longreach, and Ryewoods; we then returned to the island, and had meetings at Flushing,
Oyster-bay, Cowneck, Flushing again, and Newtown.
Having finished our service we traveled homewards,
taking meetings as we passed along in East-Jersey, at Rahway, Plainfield, and Woodbridge,
and in West-Jersey at Upper Springfield,
and attended the Quarterly Meeting at Crosswicks; after which I returned home,
and have to say with thankfulness, that in this little journey,
the Lord was to me strength in weakness and riches in the time of poverty;
and was pleased to conduct me safely to my dear wife and family in peace.

About the latter end of the year 1744,
I found my mind drawn to visit Friends in the western part of our county;
and had meetings at East and West Nottingham, DeerCreek, New-Garden, London-Grove,
Hockesson, Kennet, and Concord.
The Lord enabled me, both to do and suffer, in this little journey,
as the same appeared to be my duty.
At Hockesson I was quite shut up as to words, yet had peace,
believing it was my business, as it has been many times since,
in order as I apprehend to lead others into silence by example;
as being the most profitable state they or I can possibly arrive at in mutability,
in order to attain a right understanding of our religious duties.

Soon after my return home, I went into West-Jersey,
to visit the following meetings as I found my mind drawn thereto, namely, Haddonfield,
Chester, Evesham, Mount-Holly, Ancocas, Old-Springfield, Trenton,
and Burlington Quarterly Meeting, in which I had good satisfaction.

I think it was about this time,
I went in company with my well-beloved friend Michael Lightfoot,
to the Yearly Meetings at Cecil, and Thirdhaven in Maryland,
wherein we were greatly favored.
He returned homewards from Maryland,
but I went to some meetings in the lower counties of Kent and New-Castle,
had a meeting at Duck-Creek, and went to the Yearly Meeting at LittleCreek,
which was a very precious season, Divine goodness greatly overshadowing the same,
to the tendering of many hearts.
From there I went to George's-Creek, and NewCastle, and returned home.

I have no account by me, of any other journey in the service of Truth,
until the second month, 1746,
when I went in company with our worthy friend
before-mentioned to the Yearly Meeting at Salem,
in West-Jersey; and visited Cohansey, and Pilesgrove meetings.
In the third month of the same year, I went to Chesterfield Quarterly-Meeting in Jersey,
and had meetings at Stony-Brook, Burlington, and Haddonfield.

In the fifth month of the same year I visited the county of Bucks,
and had meetings at Middletown, Bristol, the Falls, Wrightstown, Buckingham,
and Plurnstead; taking North-Wales meeting in my return home.
The Lord was my sure helper and sufficiency in all these journeys,
affording the comfortable enjoyment of sweet peace in my return; to whom the praise,
if any service was done, I hope ever will be freely offered up;
for he alone is worthy thereof forever.

Soon after my return home,
great and inexpressible afflictions were permitted to befall me and my afflicted family,
most of whom were seized with the dysentery;
of which distemper I buried a daughter between four and five years old,
and was taken very ill myself of the same disorder.
In this time, my dear wife was confined,
and for a week or ten days after appeared hopeful to do well and recover;
but being taken with the before-mentioned disease, was in a short time removed by death,
leaving me three small children, the youngest about two weeks and three days old.
I found the Lord near to support my drooping spirit under this great affliction.
I well remember, when my dear wife lay with symptoms of death upon her,
having also sometimes, as I thought, intervals of being better,
my mind was in a painful suspense between hope and fear.
It seemed to me then impossible to give her up,
and to be wholly separated from so valuable a companion; but the Lord,
who formerly rebuked the winds and allayed the raging of the sea, was pleased,
as in an instant, to bring a holy calmness over my mind,
in which there was an entire resignation to his divine will; so that I could say,
with Job of old, "`The Lord gives, and the Lord takes away, blessed be his name.`"
I did not, from that time, look upon her as any more mine,
but gave her up into his hands who had kindly bestowed her upon me.
I write this by way of encouragement to others, that they may live in the fear of God,
and give up in steady obedience to his requirings; and then, I am well assured,
they may lean upon him in all their afflictions, and will find to their comfort,
that those things which appear impossible with man, are possible with God;
who will make hard things easy and bitter things sweet to his humble followers.
She departed this life the 22nd of the seventh month, 1746;
we having lived together nearly nine years.

I have this short testimony to give concerning her;
that she made it her early care to lead a sober and virtuous life;
and a godly concern remained upon her mind, to keep a conscience void of offense,
both towards God and man; being engaged, according to the ability received,
for the promotion of the blessed Truth,
and gladly entertained the Lord's faithful laborers;
esteeming it a blessing to be favored with their company.
When I found a concern to travel abroad in the service of Truth,
she freely gave me up thereto; having, with great satisfaction,
to acknowledge the Lord's goodness,
in favoring her with true peace and contentment in my absence;
and also in a steady trust and dependence on his providence,
for our support every way in a faithful discharge of duty.

In her last illness,
she was favored with great calmness and resignation to the Divine will,
either to live or die; signifying, that she did not find any thing in the way; and that,
if it pleased the Lord to remove her out of this world,
she hoped it would be a glorious change, and that she should go to her innocent babes,
who were gone before her;
often confessing the Lord's goodness in giving her so much ease both of body and mind.
She was very loving to those who visited her in her illness, and said,
she had nothing but love and good-will to all.
She took leave of our children in a very tender and affectionate manner,
committing them to divine Providence, and expressing her belief that his.
watchful care would be over them when she was gone.
The apprentice and servant boys were called at her request; she took them by the hand,
and in a loving tender manner, gave them good advice;
a heavenly sweetness accompanying her words, which much affected those present.
She discovered great nearness of affection to me, almost to the last,
and departed this life in sweet peace, of which I was favored, after her removal,
with a certain evidence, to my unspeakable satisfaction;
whereby I plainly saw my great loss was her everlasting gain,
and was enabled to bow in humble acquiescence to the Divine will, who knows what is best,
and orders all things in perfect wisdom.

Being apprehensive that I should be concerned to travel
pretty much abroad in the service of Truth,
for some years; I thought it my duty to go out of business,
and as soon as I conveniently could,
to place my children where they might be trained up in the way of Truth.
This view had been gradually coming upon my mind for a considerable time;
but now the weight of it much increased; the time also of entering thereupon,
appeared pretty clear to me; having found it my incumbent duty,
not only to wait for a full confirmation of a right
call to travel abroad in the work of the ministry,
but also to know the acceptable time for engaging therein;
all which will be fully discovered by those who, with a single eye to God's glory,
desire above all things to be found faithful.
