== Chapter 3

[.chapter-synopsis]
* His second visit to New England
* interview with collegians at New Haven
* religious concern to visit the churches of Great Britain
* embarks for Europe
* captured by a privateer and carried into Spain, and then to France
* is liberated
* lands in England and proceeds to London.

The first journey I entered upon, was a second visit to Friends in New England.
I set out the 23rd of the third month, 1747,
and was at two meetings in Burlington next day.
From there I went to a Quarterly Meeting at Chesterfield, and got to Flushing,
on Long Island, the 27th. Next day I attended their week-day meeting.
The Yearly Meeting for that province then came on, which held four days.
It was large,
and the Divine presence appeared therein to our mutual comfort and strength.

The 2nd of the fourth month, being four in number, we set out for Rhode Island:
passing through the colony of Connecticut, we met with civil, courteous usage, as before,
when I traveled through that country.
I felt great love in my heart toward the people, in which I had a strong persuasion,
if not something of a foresight, that Truth, in the Lord`'s time,
will break forth and spread in that colony.
For though I believe superstition and bigotry are very predominant amongst them,
yet they appeared to me in general, a cleaner people in their morals,
than in many other places where I have traveled.
At New Haven in that colony,
they have a college in order to train up their ministers, etc.
I found an inclination to go amongst the collegians, who gathered about me,
carrying themselves civilly and respectfully.
I had much discourse and reasoning with them concerning our principles:
they appearing desirous of information, I answered their questions in a concise manner;
referring them to Robert Barclay`'s _Apology,_ which I supposed they had in their library,
for a further explanation thereof.
I could not help remarking, with pleasure,
the becoming order they observed in their questions and answers: one at once,
without the least flout, jeer, or any thing like mockery.
I found work also amongst them,
to remove the prejudice some had imbibed against us as a people,
on account of the wicked and frantic behavior of one Rogers and his followers,
who I think dwelt about New-London, in that province, calling themselves Quakers;
and as there were none of the right sort, that people might see the difference,
they were ready to conclude, that all the people called Quakers were such,
to the great reproach of our Society.
I declared to them, that their actions were as much abhorred by us,
as they could be by any people whatever;
that Rogers and his company of ranters were no
more of our Society than they were of theirs;
that it would be very hard and unjust, if we, as a people,
should be defamed by means of a crew, whom we had nothing further to do with,
than to let the world know our abhorrence of their practices,
and that they took our name upon them, in all probability,
as a cloak to cover their wickedness.
The students readily admitted what I said to be very just and reasonable.
I believe this opportunity tended to the reputation of our Society,
and am sure it was to my comfort and satisfaction;
feeling the love of God flow in my heart towards those young men,
some of whom I did not think far from the kingdom.
I called again to see them on my return, and gave them some books, namely,
two letters written by Samuel Crisp,
giving reasons why he joined with the people called Quakers;
a Treatise on Baptism, by William Dell;
and I think some others, which they received very kindly,
still carrying themselves respectfully to me.

I cannot well omit taking notice of the great difference observed by me since,
at the two great universities of England, in the behavior of the students,
whom they pretend to be training up for Gospel-ministers,
and for other employments to get a living by.
Oh! what floutings, jeerings, mocking and deriding of that which is serious and humble,
like true religion! as though to work out our salvation with fear and trembling,
were not now the way to the kingdom of God;
but that a sufficient assurance to scoff at and ridicule what
in the primitive church and by the people of God in all ages,
was accounted religious,
were now the distinguishing mark of true Christians and ministers of the Gospel.
How have they frequently broken in upon our peaceable, quiet meetings,
like the raging foaming waves of a troubled sea, casting up mire and dirt!
Such conduct gives sober, discerning people,
cause to look upon them as a nest of unclean birds; who,
instead of promoting true religion, may be instrumental to subvert it.
I have often wondered, seeing the conduct of many of these pretended Gospel-ministers,
is obviously so very bad, not only while they are learning the trade of preaching,
but also in their following the same for a livelihood;
how it comes to pass that the people bear them.
One reason appears to be, that the laws of the land are much in their favor;
but the principal reason is, that people, in almost a general way,
are strangers to the life and power of true religion;
being satisfied with a profession thereof, and having itching ears,
heap to themselves teachers;
erroneously supposing the principal part of religion to
consist in performing what they call religious duties;
as hearing sermons, prayers, and singing psalms, etc.,
some of the hearers being so dark as to say, such a one is a good teacher,
though perhaps a drunkard, a swearer, or guilty of other evils.
It is plain that the strength and security of such ministers,
is in the darkness and ignorance of people`'s minds.
We do not read in the Revelations, of the locusts coming upon the earth,
until the smoke arose out of the bottomless pit and darkened the sun and air;
and whenever the children of men shall, in a general way,
turn to the light of the Sun of Righteousness in their own hearts,
mystery Babylon the mother of harlots must fall,
and these her merchants will be wholly rejected.
All their abominable craft will be fully discovered.
Great will be their torment, fear and distress, in that day!
The Lord Almighty hasten the time for his own name`'s sake, when all craft,
violence and shedding of human blood, may be at an end;
and righteousness cover the earth, as water covers the sea!

Some of the inhabitants of New Haven signified their
desire that we should appoint a meeting there,
but we did not find sufficient strength and courage to answer their request;
so proceeded on our journey,
and got to Newport on Rhode Island the 8th of the seventh month.
Here we were kindly received by Friends, and attended their Yearly Meeting,
which began at Portsmouth, where it held only one day, being a meeting for worship;
after which the meetings for worship and business were held four days at Newport.
They were very large and divinely favored,
so that those who depended on the Lord alone for wisdom and strength,
were enabled to come up in the discharge of their respective duties,
to their peace and comfort.
When this great meeting was over, I had meetings at Tiverton, Little Compton, Acoakeset,
and Aponyganset, and was at their Monthly Meeting on second-day.
Next morning about eight o`'clock,
I went on board a vessel bound to the island of Nantucket, John Hanes master,
where we arrived about one o`'clock next morning.
I stayed upon this island about six days, and was at their Yearly and Monthly Meetings;
having good satisfaction therein.
I returned in the same vessel, and landed on the continent in about six hours;
had a meeting at Falmouth, and went to their Monthly Meeting at Sandwich,
and attended the Quarterly Meeting held there.
Here I met with several Friends from our parts, who were on the service of Truth.
We had very close, searching, laborious service amongst them,
as things were very low and much out of order;
in part owing to the neglect of some members whose
minds had been too much taken up with earthly things,
to watch over the flock as those who must give an account.
We endeavored to lay the weight of things more closely upon the active members,
and left them to the Lord`'s dealings; knowing,
"`that although Paul may plant, and Apollos may water, it is he alone that can give the increase.`"

I went from there to Pembroke, where I had a meeting; and through Boston to Lynn,
where I had a meeting also; from there to Salem Monthly Meeting, and returned to Boston,
and had two meetings there, being first-day.
From there I went directly to Rhode Island, and had meetings at Portsmouth and Newport,
to good satisfaction: the Lord giving power and dominion,
by the blessed efficacy of his pure word of life,
over all of a contrary nature to itself, whereby I was enabled to clear my mind,
to my great ease and comfort.
I then returned homewards with much satisfaction and peace of mind;
taking meetings in my way at Conanicut-Island, and South Kingston;
so proceeded on my journey through Connecticut, and lodged at New Haven.
I spent part of a day in conversation and reasoning with some well disposed people,
to satisfaction.
I also visited the students as before hinted;
after which I proceeded on my journey to Longreach, where I had a meeting,
and went to the Yearly Meeting at West Chester.
From there I traveled homewards,
having cause to be humbly thankful to the Fountain of all goodness, who was near to help,
as my eye was single to him, in all proving times, whether in heights or depths;
and as he was waited upon, gave wisdom and utterance.
I desire he alone may have the praise and glory, if any good is done;
as there is no good but what proceeds from him.

I had not been long returned from the before mentioned journey,
when I laid before the Monthly Meeting I belonged to,
a concern which had been upon my mind some years,
to visit the churches in several parts of Great Britain and Ireland;
desiring their concurrence and certificate, if upon weighty deliberation,
they found unity with my proposal; intimating,
that the period for entering upon this solemn undertaking had
appeared to me for some time to be drawing near,
and that I should look out for a passage before the end of the year.
A certificate was prepared, setting forth their unity with my service in the ministry,
and with my intended journey;
desiring my labors therein might tend to the
edification of the churches where my lot should be cast,
and my return to them again in peace;
also expressing that I had settled my outward affairs to satisfaction;
for I had acquainted Friends how I had settled them,
as I thought it concerned them to be satisfied in that as well as other things;
it being my earnest desire to have the full concurrence
of my brethren in so great an undertaking.

I took some little journeys in visiting adjacent meetings;
and before the Yearly Meeting came on, I went to North Wales meeting,
and about twenty miles further up the country to Richland,
in order to take my leave of some Friends and relations,
as well as to visit that meeting.
In my return homewards I was taken very ill of what is there called the yellow fever;
because the patient is turned as yellow as if he had the jaundice.
I reached the house of my worthy friend, Thomas Foulke, who, with his wife and children,
were as affectionately kind to me as if I had been one of their nearest relations.
But this malignant fever greatly increased upon me.
My sister was sent for, and several doctors were employed.
Those who saw me, concluded all was over, and that I must depart out of this life.
I took little notice of any thing; yet I think I was for the most part sensible,
and could perceive I was given up for death, by those who had the care of me.
Once they thought I was near drawing my last breath;
they therefore drew a pillow from under my head and unbuttoned the neckband of my shirt,
out of kindness, to make the last struggle between life and death the easier.
For my part, I could not see how it would go with me; but had not much,
if any apprehension of being taken away by death at that time.
This sore illness happening in the Yearly Meeting time,
which was held that year at Philadelphia,
I requested the certificate I had obtained of the Monthly Meeting,
for my intended journey into England, etc.,
might be laid before the Yearly Meeting of ministers and elders`',
as is usual in such cases, for the concurrence of Friends;
and if they found freedom and unity therewith,
to signify the same to the brethren in England, by an endorsement thereon.
It was laid before the said meeting by my good friend Michael Lightfoot,
and the meeting`'s free concurrence being obtained,
it was signed by a very great number of Friends.
This was done when many thought there would be no occasion for a certificate,
as they fully expected it was nearly over with me, as to this world.
But I was not easy to miss so good an opportunity of having a concern of so
great importance solidly weighed by such a substantial body of Friends;
as I was not likely to have another like opportunity,
if the Lord should be pleased to raise me up again.
This illness brought me very low indeed, so that when the fever abated,
and I was fit to be helped out of bed, I could not stand alone;
yet I recovered to admiration; being able, in about a week, to ride home in a chaise,
about twenty-six miles; which I bore very well.
On my return home, my friends and neighbors came to see me,
greatly rejoicing at my recovery,
which they did not expect from what some had seen and others had heard;
for several of them visited me in my illness.
This was a time of deep probation to me both inwardly and outwardly; being tried,
as I sometimes have been when in great weakness of body,
with distressing poverty of spirit;
not having distinct satisfaction and clearness in my
own mind how it was with me as to my inward condition,
judging that an evidence of peace and comfort from the Holy Spirit
would be a great support at such times of bodily affliction;
and I have found it so, when it has pleased the Lord to favor me therewith.
But he knows what is best and most suitable for us; and I find by experience,
it is the safest way to resign our wills to his holy will; as we must, for the most part,
while in this militant state, walk by faith and not by sight.
I am fully persuaded such trying dispensations of divine Providence,
are greatly profitable for our growth in the way that is well pleasing to him;
and if patiently borne, will, in his time,
be a means to work for us a far more exceeding and eternal weight of glory.

Soon after my health was restored, an ancient Friend whose name was Peter Davis,
from New England, came to Philadelphia in order to take a passage for England,
and our friend Thomas Gawthrop having performed a
religious visit to Friends on the continent of America,
intending to embark shortly for the same, with Isaac Greenleaf, a Friend on trade,
I joined them; all agreeing to take our passage in a new ship bound for London.

One thing I would remark, that some Friends, and, as I understood, some others also,
taking notice how providentially public Friends had been preserved
during the war which was then carrying on with France and Spain,
so that none of them had been taken by the enemy, presumed thereon; and would say,
There is no need to insure goods in that ship,
as so many public Friends are going in her, she will doubtless go safe.
I much disliked this unjustifiable confidence,
seeing the judgments of the Lord are a great deep, being unsearchable,
and his ways past finding out.
It becomes us, in all our undertakings,
to commit ourselves and all we have into his hands,
in humble resignation to do or suffer whatever his
wisdom may point out or permit to fall upon us,
for the trial of our faith and patience; as his mercy, power and goodness,
are as conspicuous in preserving, defending and carrying us through great probations,
to his glory, consequently to our own advantage in the end,
as in wholly exempting us from them.
Even Job had no cause to complain of his unparalleled afflictions, when they were over,
and he saw how greatly he had profited thereby.
A Friend said to me before we embarked,
he did not pretend to determine whether we should be taken or not;
but however that might happen, he did believe some Friends in our station would be taken;
not only to check that unwarrantable confidence in some, both Friends and others,
but he also apprehended,
a service might arise from such being cast amongst those dark people,
though against their will.
I did not pretend to any assurance in my own mind,
of preservation out of the enemies`' hands; but was made willing to commit my soul, body,
and all that I had unto the Lord, as into the hands of a faithful Creator,
not doubting the sufficiency of his power for preservation in every condition of life.

On the 30th of the ninth month, 1747, the before mentioned Friends,
who were to be my companions upon the mighty ocean,
set out from Philadelphia in order to embark at Chester, in company with many Friends,
and called for me at my house in Darby, being the direct road.
I joined them, as well as a considerable number of friends and neighbors,
and proceeded to Chester that night; where,
at the house of our ancient friend Grace Lloyd, we had a solemn meeting.
Next day, being the 1st of the tenth month, about two o`'clock in the afternoon,
we took leave of Friends in great love and tenderness, and went on board the ship,
which fell down the river that evening a little below Newcastle.
Next day in the evening, we came to anchor near Reedy Island,
where we were detained by a great storm of wind and rain until the 5th in the morning,
when we set sail with a fair wind,
taking our departure from the capes of the Delaware about six o`'clock the same evening.
The wind continued fair for the most part, though very strong,
and a following sea running very high, until the 18th; when,
according to their calculation, we had run about two-thirds of our passage;
seldom having more than a foresail set, and that sometimes reefed,
and at other times double reefed.
As we had such a high following sea, it was thought the ship was ahead of the reckoning.

From the 18th to the 23rd, the wind continued pretty fair, but more moderate than before.
Then it turned about to the eastward and blew exceedingly hard, with a very high sea,
until the 29th, in which time we lay-to,
and drove about wheresoever the wind and waves would carry us.
We could get very little forward, but were exceedingly tossed.
This was indeed a trying time; the motion of the waves being so violent,
that though she was a strong, new ship,
she was beaten upon with so much force as to make her crack from end to end,
as if she would have been broken to pieces.
I then thought those in my situation had good reason to know well what "`they were about,
and for what they exposed themselves to such dangers;
and had great need to have the mighty Ruler of the sea and land for their friend.
For if he had been pleased to withdraw his protection,
there was only about a two-inch plank between us and eternity,
which was to me very awful to think of;
for I was not without my tossings and combats of mind, during these outward probations.
The 29th proved a fine day; they had a good observation,
and judged we were then about a hundred and
fifty leagues from the land`'s end of England.

Next day, being the 30th of the tenth month,
Thomas Gawthrop having had a very restless painful night, by troublesome dreams, etc.,
had some expectation of our being taken, as he afterwards intimated.
He stepped upon deck about eight o`'clock in the morning,
and immediately espied a sail upon our windward quarter, giving us chase.
He quickly raised the careless captain,
who ought to have been looking out before that time,
and to have watched more narrowly than he did, considering the trust reposed in him.
The captain, when he perceived we were chased, appeared much concerned,
giving the ship up for taken, in his mind, already.
We urged him to put out all the sail he could crowd,
and to exert his utmost endeavor to escape, offering to assist all in our power,
as we often had done before, being very poorly manned;
in part owing to the sailors`' unwillingness to go in ships bound to London,
lest they should be pressed on board men-of-war.
It happened to be a moderate wind,
so that we could have borne all the sail belonging to the ship; but through neglect,
neither topgallant-sails nor steering-sails were in a condition to be set;
neither could the captain be prevailed upon to have a reef taken out of the main-sail.
The vessel was very badly steered, as the French remarked when they had taken us.
The captain ordered her to be close hauled to the wind, vainly hoping, as he intimated,
we should get to the windward of them, being deeply laden.
But this was very ill judged, if really the effect of judgment,
as the way of the ship was thereby much hindered
to what it would have been if she had gone large,
taking the strength of the wind.
Notwithstanding this, we held the privateer in chase about nine hours.
She came up with us about five o`'clock in the evening,
and fired a gun under French colors;
upon which our people lowered their colors and topsail, by way of submitting to them.
They hoisted out a small boat, the sea running high,
in which came the second captain and a lieutenant with seven or eight sailors,
to take possession of a very valuable prize.
She was a snow privateer, belonging to Bayonne, carrying ten carriage guns,
and about one hundred men, commanded by one Peter Garalon.
As the boat was rowing towards us, the people made such a dark,
mean and contemptible appearance,
that our poor sailors cried out in a very affecting manner,
We shall all be used very badly and cruelly, like dogs, for they are a pitiful crew,
and no officer amongst them; but in this they were mistaken.
For my part, the Lord being exceedingly gracious to my soul,
by the blessed support and solacing comfort of his Holy Spirit all that day,
I was quite calm and easy;
all fear of the enemy or whatever I might have to pass through in such a time of trial,
was wholly taken away for the present;
my mind being filled with humble resignation to the divine will; yet was willing,
as I thought it a point of prudence,
to use endeavors for escaping out of their hand if it were practicable.

The before-mentioned second captain of the privateer,
whose name was Andrew De St. Andrew, boarded us with a naked cutlass in his hand,
eight or nine men following him.
He spoke to us in good English very cheerfully, saying to this effect,
"`Your servant, gentlemen; it is the fortune of the war,
although it is ours to day, it may be yours tomorrow;`" and promised good usage.
He then ordered the captain, mate, and sailors, except two,
and us who were cabin passengers, being ten in number, to go on board the privateer;
upon which the boat was loaded and went off.
He took notice that we were of the people called Quakers,
and gave us to understand that he was not altogether a stranger to us as a people.
The chief reason of sending away those on board a prize being for their own security,
lest there might be danger of their rising and recovering the ship again,
we conceived some hopes, from the known peaceable principles we profess,
to be so far indulged as to be allowed to remain on board the prize;
and therefore did not incline to go with the first boat-full;
making use of that space of time in earnest solicitation to remain,
having much better accommodation than we could reasonably expect on board the privateer:
but all the arguments we advanced seemed ineffectual.
When the boat returned,
he still urged the orders he had from the head captain to send us all on board;
upon which I stepped over the side of the vessel, taking hold of the hand-rope,
with a design to go into the boat; when there, it appeared to me exceedingly hazardous,
the sea running very high.
I turned about and looked this French captain full in the face,
and expressed myself in as moving terms as I was capable of,
concerning the danger he was about exposing us to unnecessarily; which,
through divine favor, made such an impression upon him,
that he took me by the hand and drew me into the ship again, saying,
"`You shall stay here to night however.`"
He had before demanded the keys of our chests,
under pretense of preventing their falling into the hands of the common men,
who might plunder them; but the true reason was,
that he and the other officers might first do it themselves;
which they did after we were gone to bed that night, returning our keys next morning,
with large promises of protection and good usage; which, every thing considered,
they in a good degree fulfilled.
We could not help looking upon it as a kind providence,
which made way for our remaining on board the prize;
having there the free use of our private stores,
and being better waited upon than before we were taken,
having two cabin boys for that purpose.
Captain Andrew, to give him his due, carried himself respectfully to us;
frequently filling our plates plentifully,
though he might at times have less left for himself;
and when he wanted any liquors or other provisions out of our chests,
he would ask us for them in a submissive manner, as if he had no authority to demand.
This kind carriage gained upon us, to place some confidence in him,
which in the end he made use of to his own advantage,
by craftily getting from us about two hundred pounds sterling,
the particulars of which would be too tedious to relate.
After the French had got possession of our ship, they put her in a fine trim for sailing,
so that it was plain she could readily outsail the privateer that took her.
Captain Andrew said, that when they took us,
we were about eighty leagues from Cape Clear in Ireland,
and about one hundred and twenty-five leagues from the land`'s end of England.

The next day the chief captain came on board to examine the cargo, etc.
He made Andrew captain of the prize, of which we were glad, as he could speak English,
and from what we saw of him, there was reason to expect favorable usage under his care;
which was also promised us by the head captain.
They found the cargo so valuable that it was
concluded the privateer should keep us company,
in order to convoy us safely to some port of France or Spain.
Having new masters, we had a new course to steer; but the wind set against us,
blowing very hard and stormy.
We lay-to often, and were exceedingly tossed for about two weeks,
and did not in that time think ourselves any nearer Bayonne, than when we were taken.
Our captors wanted more prey, and espied and chased several vessels,
who had the good success to get away from them.
We were once chased by a fine large ship, which they took to be an English man-of-war,
and appeared to be greatly alarmed; but when she came up,
they found her to be a privateer belonging to the town called St. Maloes,
carrying twenty carriage guns, and about three hundred men.
We left the privateer that took us, far behind, during this chase,
our ship being fixed upon at a great distance, for the best booty.

It was the 22nd of the eleventh month, before we saw any land, and when we did,
our captors proved much mistaken,
thinking themselves sixty or seventy leagues
nearer Bayonne than they found to be the case.
We had pleasant sailing near the land on the Spanish coast,
which borders on the bay of Biscay; it being high land,
afforded considerable delight to us,
as we had been long confined to the sight of water only.
The 24th, in the dusk of the evening,
we had nearly entered the port called St. Sebastian,
when the wind chopped in right ahead and drove us out to sea again.
The privateer got into a place called Port-passage, about a league from there,
next morning early.
But we being forced further off by contrary winds,
had great difficulty to get in that day, being for many hours towed by fifteen boats,
in which were one hundred and fifty men laboring at their oars.
They appeared very anxious to get our vessel into port,
as they feared some English ship cruising in the bay, might call them to an account.
We poor captives went on shore the 26th in the morning,
being glad and thankful to have the opportunity of setting our feet again on firm land,
although in an enemy`'s country; for setting aside the great affliction of being taken,
it had been an exceedingly boisterous and trying passage, of about eight weeks.
It was mild spring-like weather there, though about the middle of winter.
We diverted ourselves with walking about in the day and lodged aboard at night,
while we stayed in that place, which was till the 29th,
when horses were provided for us to travel by land, about thirty miles to Bayonne;
the doctor of the privateer being all the guard and guide we had.
There was a very plentiful dinner provided for us at a seaport town in France,
called St. Jean-de-Luz.
I was not at all pleased with the forward, wanton carriage of the women,
such as I had never seen before.
I reproved them, but some by way of excuse said,
the principal thing they intended thereby, was to cheer up our spirits in our captivity;
yet I could hardly believe their design was so innocent.

We had been told by Captain Andrew, that on our arrival at Bayonne,
we that were cabin passengers should immediately have a parole of honor granted us;
but we did not find it so.
Being brought before the commissary, he ordered us to be taken into the castle;
yet we had the liberty there to hire rooms, with beds in them, such as they were,
and to have provisions for our money;
of which we soon found we had need to be well stored,
as they had a knack of getting it from us; for we could not buy any thing ourselves,
but all must come through the hands of such as knew how to make a profit of us.
I never knew any people so thoroughly furnished with artful ways to get money,
as the French.
Their tongues were very much at command,
and they could use them with great wit and address,
in order to gain our good opinion of them, but I perceived that they meant in the main,
advantage to themselves; and therefore,
saw it necessary to be as much as I could on my guard.
We were very much imposed upon on account of provisions, and our money went very fast.
Not being without fear that if they should discover we had sufficient,
some other way might be found out to get it from us,
we made inquiry whether any was willing to supply us with money,
and take our draft upon London, allowing them a premium.
We soon found they were very willing to do it, merely upon the credit of our Society;
such reputation has the possession of Truth gained Friends, far and wide;
but to our sorrow, the bare profession of it, in some mournful instances of late,
has produced the contrary effect; so that there is reason to fear,
the great credit gained by our worthy predecessors for justice and punctuality,
is in danger of being in measure lost to the Society,
by the misconduct of some of their descendants.
They told us that several of the people called Quakers had been amongst them,
but they were not like us; that they looked upon us to be precise stiff Quakers;
but those who had been there before, behaved in a complaisant manner,
not sticking at the punctilio of the hat, etc.
We let them know that our behavior in those respects,
was no other than what is consistent with our principles;
and that we could not answer for those who were hypocrites,
professing one thing and practicing another.
We could discover that upon all occasions,
they seemed to have a greater dependence on our veracity,
than that of the rest of our company; and upon the whole,
they showed us as much if not more kindness.
Our confinement and usage in the castle grew very disagreeable to us;
we therefore took the opportunity when the commissary came,
to lay before him the treatment we met with, and to request our liberty upon parole.
He pretended to make some difficulty of it,
and we found many then in the castle had been
endeavoring some time to procure that liberty,
and could not.
But when we discovered danger of being put off as they had been,
we pressed it upon him with more earnestness.
Hereupon we had a parole of honor granted for upwards of twenty.
The place fixed upon for our residence, was Dax,
an ancient town about forty miles up Bayonne river.
We were sent there by water, and were in the boat all night,
having very disagreeable company, the worst of whom were English and Scotch.
These had laid a scheme to prevent our being admitted into the same boat,
which was very ungrateful in them,
as they knew we had been the principal instruments of procuring that liberty,
especially for some of them.
Without doubt, their reason for that attempt was,
that they might enjoy the intended frolic, without any rebuke or interruption from us.
We bore their obscene discourse and behavior for some time; but at length,
being exceedingly burdened,
Thomas Gawthrop and I were concerned to reprove them very severely,
desiring them to consider,
what the French people in the boat could think
of those who called themselves Protestants.
Some of them seemed at first to retort, but the weight of our spirits came over them;
and we being on Truth`'s side, which is strongest of all,
they were soon overcome and silenced.
From that time we kept them at a distance,
not looking upon them worthy of our notice in a way of intimacy,
so that when we came to Dax, we separated from them, boarding by ourselves.

On our arrival there, we were brought before the governor of the castle;
and our manner of appearing before superiors being different from that of others,
with which we did not expect he was acquainted,
and might probably put an unfavorable construction upon;
we therefore desired our interpreter to inform him,
that we did not stand before him covered in contempt, or in any disrespect,
it being our principle and practice so to appear before our superiors in our own nation.
His answer was to this effect,
"`I am not at all offended with their appearance; I know something of those people.`"
He gave us the liberty of the town and country around; and we got pretty good quarters,
and lived much more to our minds than in Bayonne castle.

This town is now a mean place, but there are still remains of its ancient greatness.
I find by history, it was once the capital of Aquitaine, and was then called Aqua Solis,
from its hot waters.
At one place I found the heat so surprisingly great,
that I could not bear my fingers in the water a quarter of a minute.
This water was enclosed with stone walls of about twenty yards square,
having brass or iron cocks or spouts, to convey water for the use of the inhabitants;
it answering the purpose of boiling water for washing linen, etc.
There arises a steam or smoke therefrom, like a vast furnace or lime-kiln.
We being there in Lent-time, as they call it,
were told the priests were uneasy at our being indulged with flesh,
and that they requested the governor to give orders for preventing it.
We were informed that he turned very short upon them, and said,
"`I will give no such orders.
What have they to do with your lent?
Cannot you be contented to keep it yourselves?`"
He carried himself very civilly to us,
and came once in person to invite us to a bullbaiting, offering, as we were strangers,
to prefer us to the best place for the purpose of seeing,
which was the balcony in the front of his house.
We acknowledged his civility, but at the same time gave him to understand,
we did not allow ourselves to attend such diversions.

There are many worship-houses, and two nunneries in Dax.
Their clergy, of various orders, swarm like locusts, who fleece the people,
so that it may be truly said of much the greater part,
they are in a state of abject poverty and vassalage;
stupidly devoted to follow these blind guides
whithersoever they think proper to lead them,
not daring to judge for themselves in matters of religion.
O happy England!
O land blessed with liberty!
What have you not to answer for, if a right use be not made of so great a privilege.

We went one day to converse with the nuns, which we did through large iron grates,
by an interpreter.
They behaved themselves very civilly, and were courteous and free in discourse.
One of the sisters lay dead in an apartment.
The corpse was laid in a coffin dressed in black,
having twelve wax candles lighted and set in silver candlesticks, six on each side,
and some at her feet, and a black cross fixed between her fingers on her breast,
as if she were looking at it.
Several of the nuns were about her, some kneeling, and others sitting on the floor,
with books in their hands, praying for the departed soul, as we conjectured.
One was ringing a bell, perhaps it was what they call a holy bell,
that at the sound thereof all the evil spirits might be chased
out of the soul`'s way in its flight towards the other world.
We went from this to the other nunnery,
but could not be immediately admitted to see the nuns,
as they were employed in singing psalms or some kind of religious songs,
which we could hear at a considerable distance.
We stood in an open entry before a fine chapel, but did not go into it,
though the door was open;
for indeed I had no freedom to go into any of their idols`' temples,
yet we could see many upon their knees praying, some before one image,
and some before another.
As we waited here, not intending nor expecting to give any offense,
it being an open entry, but I suppose it was hallowed or consecrated, as they call it,
though not discovered to be so by us, there came a monk to us in a great passion,
and talked very fast in French.
We saw he was angry, but did not understand what he said,
and therefore asked the interpreters, having, I think, two with us.
They told us, he said we had polluted that holy place, in keeping our hats on,
inasmuch as the Lord God was there; that if we had no more manners,
they had a way to teach us better.
We then departed, being deprived of the intended visit to the nuns,
but that was no great disappointment.
Their crosses, either of wood or stone, are very numerous,
being erected in all the cross roads,
and also at many places in and about their towns and villages;
on some of which images are fastened, with an imitation of the crown of thorns, the reed,
spear and sponge.
That the people`'s great poverty may more fully appear,
I shall give a short description of the shoes most of them wear, who wear any sort:
they are wholly made of wood, being hollowed out for the feet,
except a piece of leather about three inches broad, across the instep.
They appear very inconvenient to walk in, as they do not yield at all to the feet.
I am persuaded there is not one in sixty, in that part of France,
who wear any other sort of shoes.
Many wagon loads of these shoes are brought to Dax market every week.

The 21st of the twelfth month,
a messenger from Bayonne brought us the agreeable news of a
cartel-ship from England being arrived at Port-passage.
An order came soon after for our return,
and that we might be ready to embark the 24th. We hired a boat for that purpose,
and went to Bayonne, being on the water all night.
It was very cold snowy weather, and I suffered much, taking a cold,
which I did not get over for many days.
What added to our distress, was the commissary`'s receiving us very roughly,
and ordering us into the castle.
I know of no reason he had for being in that ill-natured disposition;
and was ready to imagine it was only to furnish a pretense to
get something into his own pocket by our confinement.
One thing which made me think he had a feeling in the profits,
was his unwillingness to give us and others, a parole.
However, when it appeared that we must go to prison again,
the captain of the cartel-ship being present, demanded our liberty;
which I suppose the commissary dared not deny;
by which means we had the liberty of the town a few days,
until matters were settled for our traveling towards the ship.

One thing I am not willing to omit,
as it will be a specimen of the unaccountable superstition and
idolatry of those people amongst whom our lot was cast.
Thomas Gawthrop and I taking a walk, as we often did, into the fields,
came to a small building, which was in the nature of a conduit,
as there issued out at one end, spouts of water, over which was enclosed in net-work,
an image whose head seemed as if cut off or severed from its body.
It appeared to be a fine spring of water; but that which most attracted our notice was,
to observe so many worshipping this water and beheaded image;
I suppose not less than fifteen on their knees, some nearer to it than others.
We inquired the meaning thereof; but none understood English,
nor did we French enough to converse; so that we remained in the dark,
until by making inquiry in the town, we received the following account, namely,
that it is St. Leon`'s well, who is the titular saint of Bayonne.
That this Leon was the first Gospel missionary sent there in pagan times,
that he was greatly persecuted, and last of all,
beheaded on a hill above that place where the well now is.
That when his head was severed from his body it
rolled down the hill and fell upon this place,
upon which there immediately issued out a spring or fountain of water.
That it is now the constant practice of professors to
send people to do penance at St. Leon`'s well;
who must fix themselves on their knees nearer or
further off according to the nature of their crimes.

When our captain had fully settled with the commissary relative to us,
we proceeded on our way towards the ship as far as the town called St. Jean-de-Luz,
where we abode some time, taking up our quarters at a large inn.
One day when at dinner, we received a visit from two friars,
one of whom being an Irishman, could speak English well;
the other knew very little English.
We understood the design of their coming was to
use endeavors in their pretended catholic spirit,
for our conversion, by bringing us into the bosom of their church, out of which,
they say, there is no salvation.
This Irish friar began to ask questions, which, for a little while, we answered;
but the dispute seemed too promiscuous and was not quite satisfactory;
neither did it appear altogether fair for so many to engage with one;
for the other friar could be of little use in argument, as he had not the language.
Therefore, finding my mind pretty much opened and warmly engaged,
I entered into a close dispute with him, which my companions observing, left it to us.
I soon found that his main support in argument was the
authority and infallibility of their church,
but more especially of the pope.
I told him it was altogether fruitless to support arguments against me,
by an authority I had no faith in;
but seeing he and I both allowed the Holy Scriptures to be of divine authority,
it would be much better for us to back our arguments by that authority only.
It was exceedingly difficult to bring him to this,
as I believe he clearly foresaw I should there be too many for him;
which fell out accordingly, the Lord being near, opening my understanding,
so that the poor man was confounded and knew not what to answer,
nor how to support an argument;
his memory scarcely serving him to quote one Scripture passage truly.
I sometimes helped him, repeating the passages he aimed at,
to see what use he could make of them; but I found him as deficient in applying,
as he was in remembering the Holy Scriptures;
which induced me to think that even their clergy, so called,
find those sacred writings make so little for the support of their religion,
that they do not much regard them.
The dispute continued most of the afternoon;
in which he carried himself with good nature and civility, at least in appearance.
He would sometimes express his wonder at my memory; saying,
he thought I could repeat all the Scriptures by heart from the
beginning of Genesis to the end of the Revelations.
But I knew who graciously helped me; for I did not go against him in my own strength,
the Lord being with me in such a manner,
that I thought I should not have been afraid to engage
with a hundred of their most crafty priests;
and therefore I did,
and do offer thanksgiving and praise to him alone who is eternally worthy!
Towards the conclusion he asked me what I thought of their eucharist.
I felt, as I thought, a snare in his question;
and asked him whether he intended to ensnare me by that question;
which he did not offer to deny.
I was, however, enabled to answer him in such a manner that he could take no advantage,
to bring me into trouble.
I often cried unto the Lord to preserve us in maintaining our testimony,
agreeably to what he knew was right in his sight;
and at the same time to be exceedingly watchful over our own spirits,
lest they should be too much heated and raised in a false zeal,
with indignation against the detestable idolatry
and abominations of those dark countries,
that we might not thereby imprudently put ourselves into their power;
not doubting if the Lord required any service of us amongst them,
he would support us therein, for he has all power in heaven and earth.
The friars took their leave of us in the evening, signifying they would visit us again;
but they never did, and I hardly believe they intended it.

From this place we went into that part of Spain where we first landed,
and stayed there and at Sebastian several weeks, waiting for the ship`'s sailing.
The Spaniards are much more disagreeable to live amongst than the French.
The men appeared to us in a general way, poor, proud and exceedingly lazy;
filled with high conceit of themselves, both in a civil and religious sense.
They sauntered about, walking with their cloaks over their shoulders,
looking upon us with contempt,
as we could bow neither to their pride nor to their religion;
nor could we look upon them in a favorable light,
when we observed what slaves they made of their wives and of the women in general,
who are employed in all or most of the drudgery, even in rowing their boats.
I have seen near the two last mentioned places, in their ferries,
and other business on the water, more than a hundred women thus employed;
and scarcely a man is seen to touch an oar, unless he goes a fishing; and then his wife,
or some woman, must bring his cloak or sword to the water-side against he comes on shore,
and carry the fish home on her head, while he walks in state to the town.
This one of the Friends who were with me assured me he saw.
I am far from envying our English women their happiness;
I think indulgent usage is due to the tenderness of their sex everywhere;
yet I think were they to see even what I have seen, as above hinted,
they would be very thankful to the Author of their
being for casting their lots in the English dominions.

The darkness of popery seems greater here than in France;
although it may be seen and felt there beyond all expression.
Oh the pain and distress of soul I was almost continually under by the muddy rivers
of Babylon in those lands of darkness! the harp being indeed hung upon the willows.
No sweet melody nor song of Zion could be sung, the Lord knows,
under the power of the king of the bottomless pit, who rules in the mystery of iniquity.
Yet so it must remain, until that Almighty Being who cut Rahab and wounded the dragon,
is pleased to arise and put on strength, that he may turn and overturn;
pouring forth the phials of his wrath upon the seat of the beast and false prophet;
that the nations may no more be intoxicated with their abominations.^
footnote:[See Psalm 137, Isaiah 51, and Revelation]
May the Lord, for his oppressed Seed`'s sake, hasten that day,
so that the people and saints of the Most High may obtain the kingdom,
and the earth enjoy her sabbath,
when sweet incense in every place on the Lord`'s
footstool may be offered up to him with acceptance.^
footnote:[Daniel 7]

I took notice at Port-passage that a person went about
the street every evening tinkling a hand-bell,
as if he had something to sell, yet I could not see any thing he had,
which made me ask the reason of it.
I was told, that it was to remind people of the souls in purgatory,
that they might pray for them.
The maid of the house where we boarded, brought a crucifix and desired us to kiss it;
which some of the English then present did, to please her; but upon my refusal,
and withal giving her a gentle rebuke for offering me such an affront,
she alarmed the house with complaints what a bad Christian I was,
for refusing to embrace that piece of brass.
Having soon after to pass through an entry, I found two men,
I suppose lying in wait for me.
One of them came slyly behind my back, laying fast hold of both my arms,
in order to confine me, while the other brought the image to my face; intending,
no doubt, to force me into that which they could not bring me to do voluntarily.
I soon perceived what they were about,
and presently freed myself from their odious design; showing them,
by a stern countenance and some sharp expressions,
that I was much displeased with their uncivil treatment.

I cannot fully account for the cause, but while in Spain, I felt at times,
or at least I thought so, something like snares laid to do us mischief.
However that was, the Lord graciously preserved us,
and gave us ability to maintain our testimony,
as far as he was pleased to require of us in those countries;
which was chiefly in feeling the distressing weight of death and
darkness that covers the holy Seed sown in the hearts of mankind,
and which is pressed down by their superstition, idolatry and wickedness,
"`as a cart is pressed that is full of sheaves.`"
It as surely groans for deliverance as Israel did under Egyptian bondage.
In sympathy therewith, my soul was mostly in deep anxiety; being, as it were,
dumb with silence, and closed up in painful death and darkness; ready at times to say,
Surely I am in the same spirit with them.
But the material difference was this; it was their element,
wherein they lived pleasantly and delighted to breathe;
whereas I could neither live nor breathe therein; so far from it,
that I often looked upon myself in a manner quite dead.
But let everlasting praise ascend to the God of the living, world without end!
He was pleased to bring me through this horrible death and darkness,
to enjoy the glorious day of his salvation again, and to be one of those,
though unworthy,
who have "`the Lamb slain from the foundation of the world,`"
for their light and leader.
Then I saw that even in that day of uncommon trials, both within and without,
my life was sure, though not discerned by me, being hid with Christ in God.

It was some time after my arrival in England before the
thick darkness before-mentioned quite wore off my mind;
yet I was favored at times, with the shining of the Sun of righteousness,
as it were breaking through a thick cloud, to my unspeakable joy and comfort,
and in the work of the Gospel I believe, to the great satisfaction of many others,
to whom I was, through deep suffering, in some degree qualified to speak,
even as deep calls unto deep.

We arrived in England, and came to anchor in Torbay, the 26th of the first month, 1748,
after a passage of five days.
The ship was bound for Plymouth, but the sailors who had been prisoners in France,
being in fear of another confinement by being pressed on board of the men-of-war,
took the command of her from the captain, by something, in appearance at least,
like force.
He told them he had a safe protection from the government,
whereby they would be secured from what they feared by going to Plymouth.
But they did not regard that, neither was he, as we thought, averse to going into Torbay,
as he had the sailors to lay it on;
for we had reason to apprehend he did not keep us waiting in Spain so long for nothing;
so that the bay might suit his purpose better also.
It being the first-day of the week, in the evening, when we came to anchor,
Thomas Gawthrop and I had a mind to go on shore,
that we might endeavor to find a meeting of Friends.

Next day some of the company signifying their intention of going about midnight,
that being the time when I suppose the tide would serve best;
we therefore requested they would call us, which they did.
The ship lay a considerable distance from the town of Bricksham,
where we intended to land.
We had been in the boat but a little while,
when a great storm of wind and rain beat furiously against us,
so that the men at the oars found it hard to keep the boat up against it.
We encouraged them all in our power to work for their own lives and ours,
letting them know, if they would bring us safely to land,
they should be well rewarded for their pains.
The danger of being driven back to sea was very apparent,
and I believe much feared by all in the boat.
The poor men exerted their utmost endeavor, which, through the good providence of God,
proved successful.

This I looked upon as a merciful preservation, having seldom, if ever,
in the course of my life,
apprehended greater danger We were exceedingly wet with the rain,
but having good fires made for us, and other necessary accommodations,
we did not suffer much thereby.
By inquiry,
we found there was a meeting of our Friends held near a place called Newton-Bushel,
about ten miles off, to which we went,
being truly thankful for the great favor of a safe arrival in England,
and the opportunity of sitting down in a meeting of Friends again;
though we held meetings amongst ourselves in our captivity, on first-days,
when it appeared practicable.
This meeting was but small, and the life of religion seemed to me at a low ebb.
I had nothing to deliver by way of testimony.
Friends were very loving to us.
On second-day we proceeded towards London, as far as Exeter,
where Friends entertained us kindly that night.
Next day Thomas Gawthrop, Isaac Greenleaf and myself,
leaving our ancient friend Peter Davis with Friends there,
hired horses as far as Honiton.
There I bought a serviceable mare,
that carried me safely and well through most of
my travels in this journey in England and Wales.
We took Bridport in our way, and lodged with our worthy friend Samuel Bownas, who,
with his house-keeper, entertained us with affectionate kindness.
Now did we begin to enjoy the sweetness of brotherly love again.

The Quarterly Meeting for Dorsetshire was held next day at that place, to which we went.
It was very small, and the power of Truth,
which is the crown of all our religious meetings, as I thought, was very low therein.
We must live in that power at other times,
if we expect its gracious assistance in the weighty affairs of
the church when met for the management thereof;
for that which is born of the flesh is but flesh,
and cannot enter into the kingdom of God, nor so much as see it.
All is certainly of the flesh that has its principal
delight and satisfaction in sublunary things.
So that,
although some may maintain the character of God`'s people as to the outward appearance,
yet if the love of earthly things has the chief room in their hearts,
the love of the Father is not in them;
and therefore such are not qualified to do God`'s work.
Church-government, according to the discipline he in his wisdom has established,
requires our understandings to be divinely enlightened to move rightly therein.
The natural reason and understanding, whereby we manage our outward affairs,
although capable of this, is altogether unfit for the other;
for "`the world by wisdom knows not God;`" and where persons speak and act in this,
in meetings for discipline, they are not likely to understand his work;
but in their pretended endeavors to promote, they mar it,
and frequently darken counsel by a multitude of words without right knowledge.
Instead of raising life in a meeting, they bring death and darkness over it,
to the great pain of the upright-hearted, who are not always ready,
like those above hinted at,
but experimentally knowing their sufficiency for every good word and work to be of God,
they dare not move until it please him, by moving upon their hearts,
to open their understandings and to be a spirit of judgment unto them.
In this only there is a binding and loosing, remitting and retaining,
with divine approbation;
which is livingly known and sealed upon the understandings of the faithful,
by the Holy Spirit of promise.
Our way was quite shut up as to ministry or other public service in that meeting;
after which we pursued our journey for London.
I found constant riding very painful,
not only because I had not rode much for a considerable time, but having,
according to the custom of America, been used to an easy pacer,
my mare now being a trotter, was hard to bear until I was more accustomed to it,
which then proved very agreeable.

Our friend John Hunt and his wife met us on seventh-day at Staines, and being in a coach,
prevailed on me, as I was weary with riding, to go with them in it,
and took me to their house, where I was kindly entertained, not only then,
but also at other times during my travels in this nation.
I continued about two weeks in the city, visiting meetings as they fell in course,
being mostly low and pretty much discouraged in
my mind with a deep sense of my own weakness,
the greatness of the work before me, and the mournful state of the church,
as it appeared to me, in London.
I had but little openness as to ministry,
yet endeavored to wade along as patiently as I could;
it appearing to be my principal business to suffer with the oppressed Seed,
mourning with a sensible remnant, who I could perceive had sackcloth underneath,
because of the prevalence of worldly wisdom and grandeur in that great city;
the lowly meek spirit of Jesus, which by the power of God was exalted amongst us,
in the early time of our being a people,
was in too general a way overlooked and disregarded;
and man`'s will and wisdom taking its place, was grown very high,
and assumed the government, where the wisdom of God formerly bore rule.
But this did not prosper; instead thereof, greater waste and desolation prevailed.
Those who were breathing and panting after heavenly substance were greatly discouraged,
being ready to say, All is gone! the glory is departed from Israel! what can be done now?
but I saw they were to be raised in the Lord`'s time,
as an army to fight his battles against the uncircumcised in heart and ears;
and that the victory over that spirit was to be obtained through sufferings.
Having given a short hint of the afflicting view I had
of the state of our Society in the city of London,
I shall leave it for the present; as I shall, in the course of this journal,
have occasion to make further observations thereon which may tend to explain the above.
