== Chapter 4

[.chapter-synopsis]
* Visit to his mother
* Attends the Yearly Meeting in London
* Meetings in Norfolk, Suffolk, etc.
* Visits Yorkshire, Durham, Lancashire, etc.

I had an ancient mother in Radnorshire, South Wales,
whom I had not seen for about twenty-two years.
I therefore purposed taking meetings in my way there,
and also in my return to London Yearly Meeting.
I set out in order to be at Reading Quarterly Meeting the 16th of the second month,
which I attended to good satisfaction.
After this meeting I took the following in my way, Henley, Warborough, Witney,
Gloucester, and Ross, the Lord being my gracious helper, either to do or suffer,
in which I endeavored to be faithful,
according to the discovery I received of the divine will:
on the 26th I got to my mother`'s house, having sent a messenger a little before,
lest a sudden surprise, although arising from much joy,
might prove too great a shock for my dear ancient
mother to bear without some inconvenience.
I suppose our meeting might somewhat resemble that of Jacob and his son Joseph.
It afforded much comfort to my worthy mother, she being a valuable religious woman,
not only to see me again,
but also that I was come upon a service she so greatly loved and valued.
My honored father had been dead about three years.
I had a brother and sister living with my mother, and another sister married,
who lived not far from her.
I stayed thereabouts somewhat more than two weeks; in which time I had several large,
and some very open precious meetings; many of other societies flocking to them,
who seemed much reached by the testimony of Truth.
But alas!
I found things very low among Friends, which was cause of sorrow to my mind.
Wrong things were creeping in, and very few if any,
had judgment and courage enough to deal plainly with disorderly walkers.
I was at their Monthly Meeting,
and endeavored to stir them up to a more diligent and
zealous exercise of wholesome discipline;
but they appeared weak.
On second-day, the 16th of the third month, I took leave of my dear mother,
brother and sisters, and set out in order to be at the Yearly Meeting in London,
Edward Jones bearing me company.
I took the following meetings in my way, Ammelly, Leominster,
a Quarterly Meeting held at Broomsgrove and Worcester, Evesham and Shipton;
on first-day had two meetings,
at Longcompton in the morning and Chippingnorton in the afternoon; then to High Wickham,
Chesham and Uxbridge.
Several were open satisfactory meetings, and some very trying and afflicting.
The Lord was pleased to be my helper and support,
to whom be humble thanksgivings for his gracious
condescension to the low estate of his poor servants.

I got to London on the seventh-day of the week,
and the day following attended Gracechurch street and Devonshire-House meetings;
but I had very little openness therein.
My spirit was very low and greatly depressed,
so that I seemed near fainting under the weight of my burden.
On second-day the Yearly Meeting began.
The first was a meeting of ministers and elders in the morning.
Many brethren were met from various parts of the nation, among whom,
I looked upon myself as a mere child,
having much fear and reasoning in my mind lest I
should dishonor the great Master`'s cause,
and discover my great weakness, as it appeared in my own view,
to those pillars in the church and experienced servants in the Lord`'s work.
But he in great mercy condescended to my very low estate,
and regarded my humble breathings,
giving me the word of life to preach with demonstration that day,
which much opened my way in the minds of Friends,
and was of considerable advantage to me in my future service;
for very much depends on our having good place in the hearts of the faithful,
and that cannot well be until they know us.
Christian prudence teaches not to lay hands suddenly on any;
therefore such must see and feel the spirits one of another, in some degree,
before they can unite.
Was there not great care and caution in this respect, gross hypocrisy,
by putting on the outward appearance, might be encouraged,
which would be a grievous wound to God`'s cause.
Many Friends after this meeting showed affectionate regard to me;
but none more than that substantial minister of the Gospel Samuel Bownas.
It had a proper effect upon my mind, to strengthen it, and raise,
humble acknowledgments to the Lord for his mercy; it being my fervent prayer,
that whatever I might go through on account of the unfaithful,
my service and labors might be acceptable to the saints,
and that I might be favored with a sense of the unity
and help of their spirits accompanying me therein.
I attended the Yearly Meeting constantly, both the meetings for worship and discipline,
as they fell in course.
The power and virtue of Truth was near,
strengthening and comforting our spirits in a good degree;
but I have known a much fuller enjoyment and overshadowing thereof,
even when all the hills and mountains have been melted, as it were,
before Him who is glorious in holiness and fearful in praises,
working wonders for the help and preservation of his people.
Then we could experimentally say, the Lord`'s awful majesty presided among us,
being a spirit of judgment to them that sit in judgment, and all we stand in need of;
even as a place of broad rivers and streams,
where nothing of man`'s invention could obtain any place.
These were times of rejoicing in the presence of the Lord,
and drinking freely of the wine and milk, without money and without price.
My soul said it is good to be here; having a desire, with Peter, to tabernacle there;
dreading to descend again into this vale of tears,
where I must struggle with my many infirmities, which I did not then much feel.
I do not instance this with design to justify anxious
fears and taking thought for the time to come;
but rather as a mark of my great weakness and lack of growth in the most precious faith,
which is the saints`' victory, whereby, as we grow therein,
strength and patience are received, to endure hardness as good soldiers of Jesus Christ;
not viewing with anxious fear these light afflictions which are but for a moment; seeing,
in due time, if we are properly exercised thereby,
they will work for us a far more exceeding and eternal weight of glory.

On the sixth-day of the next week after the Yearly Meeting,
I set out in order to be at the three eastern Yearly Meetings,
being accompanied by my friends John Hunt and his wife, and Christopher Wilson,
who was to be my companion.
We lodged that night at Brentwood; next morning early we passed on to Chelmsford,
the weather being extremely hot, and breakfasted at my dear friend Frances Wyatt`'s,
who afterwards, through the kind providence of God, became my truly affectionate wife.
Many Friends went forward towards Colchester,
but my companion and I stayed at Chelmsford meeting on first-day.
The weather continuing very hot, I think then equal in heat to our weather in America,
there arose a storm of thunder and rain in the time of the meeting: one clap of thunder,
while I was upon my feet,
so terrified Friends as to take away their attention for the present,
and I expected to be obliged to sit down; but waiting a short time, Friends recovered,
and I went on.
A boy was killed by the lightning as he was playing near Springfield steeple-house,
about a mile from Chelmsford.

We went after meeting to Kelvedon,
and next morning were accompanied by several Friends towards Colchester;
but I was so ill of a fever, that I was obliged to alight at Lexton,
about a mile from the said place.
We mounted our horses again after I had recovered a little;
but before we had proceeded on the way above half a mile,
there came on such terrible thunder, as is seldom known in this part of the world.
The lightning appeared to glide like streams of fire on
the surface of the earth a considerable way,
and there seemed, as I thought, a strong smell of sulphur.
The thunder frightened my mare to such a degree, that I being poorly,
could scarcely sit her; but through mercy, I received no hurt.
I continued ill at Colchester, so that I did not attend many of the meetings.
The Yearly Meeting ended there on fourth-day.
On the sixth-day following, I was so recovered as to ride in a chaise to Maningtree,
and had a meeting there the same day.
On seventh-day we went through Ipswich to Woodbridge,
in order to attend the Yearly and Quarterly Meetings there for the county of Suffolk.
We were at their meeting on first-day;
on second-day was held their meeting for discipline,
wherein the power and virtue of Truth seemed to me low and depressed;
and although I was fully persuaded there were some living, concerned members therein,
who had the cause of Truth at heart, yet they appeared also depressed.
The chief reason whereof I then apprehended, and have more clearly seen since,
was giving too much place to a few busy forward members,
in whom man`'s will and wisdom were too much exalted,
who assumed the rule and government of that meeting;
in which they were too much indulged by the cowardice
of those whose proper business it was to work for God;
that by his blessing and assistance,
they might exalt the weight and authority of Truth over such spirits.
For the dominion and majesty of Truth in a meeting soon foils and overcomes them,
as it is abode in by the heirs thereof;
but if they are slack and negligent in possessing their right,
usurpers will often take it from them, in this sense.
Such who are called to work for God in his church, by holding back more than is fitting,
not only bring poverty and leanness upon their own souls,
but also open a door for the spirit of antichrist to enter.
I have often seen, that when the wise woman neglects to build the house,
the foolish woman, by pretending to build, has pulled it down with her own hands:
this has been no small cause of the waste and desolation in some places.
I have had much labor with that busy, active, forward spirit since,
both in meetings and in private plain dealing;
as also in stirring up and encouraging the right-minded to stand their ground;
which I hope has not been altogether without some good effect.
I could not be easy to proceed without making the above remarks,
as a caution to those into whose hands this may come,
since it is no small thing to be guilty of negligence in the work of God,
nor to engage therein without a proper qualification.

Meetings for worship were held on third and fourth-days,
wherein we were favored with a good degree of that heavenly virtue,
in which there is a renewal of strength and a comfortable fellowship one with another.
From there we proceeded towards Norwich,
taking Brandiston and Layston meetings in our way;
where true religion appeared to be mournfully low.
At Norwich we were favored with considerable openness
and satisfaction in their meetings on first-day.
The Quarterly and Yearly Meetings for the county of Norfolk, were held on second,
third and fourth-days.
Divine goodness was felt assisting in close exercise and labor,
for the help and recovery of a declined people;
and heavenly fellowship was sweetly enjoyed with those who preferred
the prosperity of the city of God to their chiefest joy.
On fifth-day we had a meeting at Wymondham, wherein we were opened in Gospel service,
to our comfort and relief in a good degree.
Next day we had a meeting at Tasborough, which was a very painful trying time;
my duty therein was to set an example of silence.
Here my agreeable companion and I parted.
He had been with me ever since I left London.
I was now alone, as to any constant companion,
and on the first-day following attended Norwich meeting to pretty good satisfaction;
and had the following meetings appointed in my way to Lynn: Lammas, North Walsam,
Holt and Wells; in most of which I had close laborious service: being led,
as was often my lot, to stir up and awaken, if possible,
the careless lukewarm professors.
Our friend Edmund Peckover, accompanied me to Lynn,
where we had two meetings on first-day; they proved very painful and laborious:
I had very little openness as to ministry.
From there we went to Wisbeaeh and to Gedney, where things appeared to be very low;
and at Spalding, had a heavy laborious meeting;
where my friend Edmund Peckover left me and returned home.
The same day was a considerable eclipse of the sun.

The next meeting I had was at Broughton, which was very painful and afflicting.
The great loss which some in that part of Lincolnshire, through which I passed,
have sustained,
by forsaking the Fountain of living water and the commonwealth of our Israel,
that they might embrace this present world, Demas-like, was sorrowfully felt.
Although some of them retain the outward form, yet having lost the dew of their youth,
they are become dry and formal; by whose means,
and the undue liberties indulged in many of the youth,
a thick darkness was raised that might be felt; which eclipsed the beauty of our Zion.
I traveled from there through Newark, and a considerable way by the pleasant river Trent,
to Nottingham.
Being first-day, I was at the meetings there, both fore and afternoon.
Truth greatly favored me in opening doctrine and counsel in the morning;
the afternoon not quite so open, but in a good degree to satisfaction.
From there to Oxon meeting, which was small yet open, and to Mansfield,
and had a painful trying meeting there.
The next was at Chesterfield, where the company was small, yet Truth livingly favored,
opening counsel for our help and encouragement in the way of well doing.
Notice being previously given, I had a large meeting at Matlock on first-day.
There were a few Friends and many others at this meeting,
which proved heavy and laborious for some time;
yet divine goodness afforded ability to work through,
and the holy power of God was in a good degree exalted; praises to his name forever!

The next meeting was at Hansworthwood-house, on the borders of Yorkshire.
There were but few Friends, and of those few,
most seemed to depend much upon the labor of the ministers,
as is sorrowfully the case in many other places.
I had nothing to administer to them but an example of silence,
that appearing best adapted to their states;
for unless the great benefit thereof is experienced,
there can be no real advancement in true religion.
I went from there to Sheffield, which was a large meeting,
and the doctrine of Truth was largely and livingly opened therein;
I believe to general satisfaction, and to the comfort of the upright-hearted.
I went to Highflats, and was at their meeting on first-day, which was very large;
being composed of plain country Friends.
The Lord was pleased to favor us with a precious opportunity together,
in the comfortable enjoyment of his love shed abroad; under which holy influence,
the doctrine of Truth was largely opened;
the glorious powerful name of the Lord was magnified, and his humble,
dependent children were encouraged to serve him
with a perfect heart and with a willing mind.
The next meeting was at Brighouse, which was to pretty good satisfaction;
Truth owning and comforting our spirits therein.

Next day I had a very painful afflicting meeting at Halifax,
having reason to fear but few of the members were rightly acquainted
with the quickening virtue of true religion in themselves:
when this is the sorrowful case, it makes heavy work for the living.
My labor among them was in a close arousing way,
but it did not appear to make much impression.
At Gildersome I had a pretty open comfortable meeting; and next day,
one at Leeds to satisfaction.
This being a large meeting, I stayed over first-day, and am persuaded a sensible,
weighty body of Friends belonged to it; yet there seemed to me a much larger number,
who contented themselves in the profession of Truth,
and in hearing the report of others concerning the heavenly country.
The indifference of these, together with their eagerness after words,
appeared to me a cause of the painful anxiety of spirit
I had to suffer under both morning and afternoon.
Here my friends John Hunt and his wife, from London, met me,
with intent to accompany me to some meetings in that county, of which I was glad,
being alone, often low and much discouraged, in a deep feeling of my own weakness.
I had to wade along from place to place, in a painful sense of a greatly declined people,
among whom I was concerned to labor;
so that had not the Lord at times made me
sensible that his everlasting arm was underneath,
to support my afflicted soul in various probations, I had certainly fainted.
But blessed be his holy name forever,
he was often graciously pleased to open a way for me to hold on when I could see none,
leading me by the hand like a tender merciful Father, one step after another;
and giving me more place in the love and regard of his people than I looked for,
or could, as I thought, reasonably expect.
I was many times greatly abased in my own sight; ready to say,
to what good purpose do I visit the churches?
for I seem to move in an untrodden path,
as under the weight of the hills and mountains of exalted unfruitfulness;
and often as it were, groping in the chambers of death,
with such constant afflicting views, that I was ready to say with the prophet,
"`I am a man of unclean lips, and I dwell among a people of unclean lips.`"
But the live coal from the holy altar,
soon removes all that tincture or seeming defilement,
which does not proceed from our own sins and miscarriages, but from those of others.
You deep wader for the good of souls, this is written principally for your sake,
that you may see others have gone the same way before you,
and be encouraged not to sink under your burden.

I found in the Lord`'s time that tribulation works patience, and patience experience,
and experience hope.
The Lord gave me thereby clearly to see that I must thus feel the wounds, bruises,
and putrefying sores of the sons and daughters of Zion,
or I could not speak to their states and conditions feelingly and effectually,
for their help and recovery.
Our Lord and Savior Jesus Christ, was touched with a feeling of our infirmities.
He bore the weight and painful sense of the sins of the whole world,
tasting death for every man;
whereby he reached forth a merciful hand of help and salvation for the recovery of all,
sufficient for all who believe in him and obey him.
His faithful messengers must know, in degree, a drinking of the same cup,
and being baptized with the same baptism he was baptized with,
not only on their own accounts, but also on the account of others.
He still suffers by his spirit, as under the weight and oppression of sin and iniquity,
in the hearts of the children of men; and all those who are one in spirit with him,
must in measure feel his sufferings, and sympathize with him therein; traveling in pain,
that Christ may be formed in the hearts of mankind, ruling in his kingdom on earth,
as he rules in heaven.
But these things are too mysterious for the wise and prudent of this world to understand,
being only revealed to those who are indeed born of God.

We stayed at Leeds until fifth-day, there being a burial,
attended by a large number of Friends and others.
Truth opened our way in the ministry to good satisfaction.
Next day we had a small meeting at Knaresborough, where we found things very low.
From there we went to Thirsk, and on first-day had a precious open meeting there,
in which the testimony of Truth was greatly exalted,
and the upright-hearted sweetly comforted.
The praise of all belongs to the Giver of every good and perfect gift.
Next day we went to visit our ancient honorable Friend John Richardson,
at his house near Hutton-in-the-hole.
He had scarcely sight enough to distinguish us one from the other.
We were received and entertained by him with true love and brotherly affection.
He was much at liberty in his spirit, and very free in discourse about religious things,
in which his life and great delight appeared to be.
He showed us, in manuscript,
a journal of his life and travels in the service of the Gospel, since published,
wherein are many very useful observations and remarkable occurrences,
which I hope will be of great service in the world.

On third-day we had a meeting at Hutton,
wherein we were favored with some degree of openness;
yet Truth did not arise to any considerable degree of dominion:
but all is best as the Lord is pleased to order,
for from him alone proceed the issues of life.
On fourth-day morning we took leave of our said worthy friend in much affection,
and had a small meeting at Bilsdale, where the life of religion was low;
after which I parted with my friends John Hunt and his wife.
John Scot of Leeds, continued with me,
who was an honest laborer for the arising of life in meetings,
and I thought of considerable help to me.
The next meeting we had was at North Allerton; which was rather low and heavy.
We went from there to Darlington, in the county of Durham.
I had close painful labor there;
earthly mindedness in professors is often the cause of hard work,
as it obstructs the current of life in themselves;
and also frequently in our religious meetings,
like the Philistines stopping up the wells which the
true Seed has opened in the hearts of believers;
so that many times, instead of their having to sing, Spring up, O well,
and we will sing unto you! there is mourning and painful labor in sympathy therewith,
to have the spring opened again,
that the flock of Christ`'s fold may be watered with the refreshing
streams of that river which flows from the presence of God.
I went next to Raby on a first-day; it was a large heavenly meeting,
Truth having great dominion, and Friends were sweetly comforted together.

At Bishop Auckland,
the Lord favored with matter and utterance to a
considerable degree of ease and satisfaction.
From there I went to the city of Durham, and had a hard painful meeting in silence:
at New-Castle we had a close, trying, laborious time, of this work occasioned,
as I apprehended, by undue liberties in thinking and acting,
which had raised darkness to be felt in that meeting.
We had an open comfortable meeting the next day at Shields.
We went to Sunderland, and attended their meetings on first-day:
that in the morning was very open and satisfactory,
the testimony of Truth going forth freely to the several states of those present,
who were much affected therewith.
In the afternoon it was a heavy afflicting meeting;
little being felt of that which crowned the meeting in the morning.
We often find afternoon meetings are heavy and painful, occasioned,
no doubt in part at least, by answering the cravings of nature to the full;
whereas they should be denied a full gratification, as little sustenance would,
for that short space of time, answer much better, and be no injury to the constitution.
If any think this hint impertinent,
there is reason to fear that they are yet too much strangers to the nature
of true worship and the many impediments in the way of its due performance;
what I have above-mentioned is none of the least.
I was quite shut up as to ministry in the afternoon.
Here I met my valuable friends Jonathan and Margaret Raine of Trawden in Lancashire,
for the first time; concerning whom more hereafter.

On second-day we had another meeting in the city of Durham,
wherein the Lord was graciously pleased to exalt his glorious and
powerful name over all disorderly and corrupt libertine spirits;
there being some such in the meeting, which was evident to me,
from the testimony I had to deliver among them.
It was with remarkable authority and sharpness against such,
who having departed from the divine light, wherewith all mankind are enlightened,
choosing rather to be in darkness,
were so lost in a maze of error as even to call
in question the truths of the Christian religion.
I was afterwards informed that there were some such in that meeting,
who had imbibed the dark and wicked principle of deism, or free-thinking, so called;
but I had no outward information concerning the state of any there before the meeting,
which I always carefully shunned.
The next meeting I had was at Stockton, to pretty good satisfaction,
as Truth opened my way to discharge the service required; yet the meeting was small,
and the life of religion appeared to be at a low ebb.
I went from there to Yarum in Yorkshire; had a meeting there, and at Yatten,
and Moorsham, to a good degree of satisfaction.
The next meeting I had was at Castleton.
The two last named were on the Moors, among a very plain people,
who appeared to be in a low station of life,
but I found the savor and virtue of Truth among them, especially at the latter;
to which that substantial minister of the Gospel Luke Cock, in his life-time, belonged;
the remembrance of whom, although I did not personally know him,
was very fresh and livingly before me in meeting, as if his spirit had been present.
I could, as I thought,
perceive the good effects of that worthy man`'s Christian labors among those people,
and a precious meeting the Lord favored us with; to whom,
for the multitude of his mercies bestowed upon us poor unworthy helpless creatures,
be humble thanksgiving and praise, now and forevermore.

Whitby was the next meeting I attended, being on first-day,
where I had very close laborious work.
An earthly lofty spirit had taken place in some of the professors;
the tendency whereof is, by darkening the understanding and blinding the judgment,
to account various weighty branches of our Christian testimony small trifling things.
Here the flesh, that wars against the spirit, having the ascendency,
its language is quite opposite thereto.
The flesh says, there is little in dross; religion does not consist in apparel;
there is little in language; there is little in paying tithes, etc. to the priests;
there is little in carrying guns in our ships,
to defend ourselves in case we are attacked by an enemy.
To which, I think, it may be safely added,
there is little or nothing in people who plead thus, pretending to be of our Society;
for if they can easily let fall those branches of our Christian testimony,
I am fully persuaded they will maintain the others no longer
than they apprehend it will suit their temporal interest.
I have often wondered why such continue to profess with us at all.
They are not really of us,
who are not concerned to maintain those principles and
testimonies which the Lord has given us to bear.
I was, through mercy, enabled to discharge the service required of me,
and went from there to Scarborough, where the Lord in gracious condescension,
was pleased to open doctrine and counsel for their help;
who appeared to me mostly low and weak, as to a real growth in true religion.
From there I went to Pickering,
where the Lord gave us a very precious opportunity together,
in the comfortable enjoyment of his power and refreshing presence;
to the exaltation and renown of his great name, who is`" worthy forever.

Next day I had a meeting at Malton, being a close searching time;
Truth seemed at a low ebb there.
At Cransick the meeting was very small,
but the Lord was pleased to own and comfort us together,
affording counsel for their help and encouragement.
I attended the meeting at Bridlington on first-day;
it was small and the life of religion very low.
Oh how greatly is that, and many other meetings declined,
both as to number and a lively experience of true religion:
some Friends informed me as I remember, that they knew the time,
when fourteen or fifteen ministers belonged to it; and now perhaps,
there is not a much greater number of members of all sorts.
Once there was a wonderful time of gathering into the vineyard of Christ; but since,
with sorrow and lamentation it may be said, there has been a losing, scattering,
and dwindling away in many places; the principal occasion whereof seems to have been,
an inordinate love for transitory enjoyments, lawful in themselves and in their places,
but not to have the chief possession of the mind.
When this becomes the sorrowful state of any,
they cannot savor the things that be of God, but the things which be of men;
and are of consequence deprived of that all-sufficient help, so to live and walk,
as to answer the witness of God in others;
to train up their children in the nurture and admonition of the Lord;
and to maintain the testimonies of Truth with a convincing strength and efficacy.
So that although the form is retained in a considerable degree by such,
and they may also be fortified with arguments,
to maintain the consistency of our profession
with the primitive plan laid down in Holy Writ,
yet wanting the salt of the kingdom in themselves,
all their pretensions without it will prove nothing; yes worse than nothing;
seeing that by how much they have had the opportunity of knowing more than others,
by so much their condemnation will be greater.

Next day we had a small meeting at Hornsey, and from there went to Oustwick,
and had a large meeting, wherein Truth favored in opening doctrine largely,
and to a considerable degree of satisfaction.
The next meeting we had was at Hull,
which was indeed a very painfully exercising time of silence,
in a mournful sense of great declension.
We find it recorded in the holy Scriptures,
that we must enter the kingdom of heaven through many tribulations.
It is indeed a very wonderful mercy,
that such unworthy creatures as we are should be so highly favored,
as to be admitted therein on any terms.
I have considered that our afflictions in this day, both in the manner and cause,
differ much from the trials of our worthy predecessors.
Their bodies were frequently imprisoned and grossly
abused by people of different religious persuasions;
but our spirits, when engaged in the work of the Gospel, are often imprisoned, depressed,
and greatly afflicted,
by means of the great unfaithfulness of many under the same profession with ourselves;
being at times, on account of such,
so closed up in a painful sense of death and darkness,
as to be somewhat like the prophet of old, quite shut up and dumb with silence.
This may be occasioned by those who are so far alienated from the
sensible reaches of the measure of grace in their own minds,
as not to be opened thereby to receive to advantage the word preached;
for the word goes not forth in vain; but will accomplish that for which it is sent.
Silence may also be necessary,
on account of those who have often been comfortably
refreshed by sitting under a living ministry,
yet neglecting their own duty in a spiritual labor for heavenly bread,
look too much for food from the labor of others;
which unjustifiable dependence and expectation, are often disappointed and mortified.
The main design of Gospel ministry is to turn the
children of men to the grace of God in themselves,
which will teach them to work out their own salvation,
and diligently to seek the Lord for themselves, and their strength being renewed in him,
their spirits would unite with, and greatly help and relieve,
the ministers in their Gospel labors.

From Hull I went to North Cave, where I had an open comfortable meeting.
From there to Howden, where the meeting was small and things very low;
it was held in silence.
I went next to Selby, and attended their meetings on first-day.
I had some strength and openness for service in the morning.
In the afternoon I had to sit in silence,
and could find but very little of the life of religion there.
Next day I had an open comfortable meeting at Rawcliff; then one at Pontefract,
where things were low and painful.
The next meeting was a small one at Wakefield, wherein I was quite closed up in silence;
the state of the people, as I apprehended, requiring it.
I went from there to Leeds, and next day to the house of my esteemed friend William Hird,
intending for Bradford Monthly Meeting, which was held on sixth-day,
wherein I had thorough service, and the blessed Truth had dominion,
to the joy and comfort of many hearts.
I returned to Leeds, and attended their meetings on first-day,
which were low and rather painful; my service therein was close and searching;
but those who are at ease in Zion like smooth things best,
and are almost ready to say now, as some did formerly to the seers, see not,
and to the prophets, prophecy unto us smooth things.

I went from Leeds to the Quarterly Meeting at York,
wherein I had considerable openness in service;
yet my spirit was secretly pained most of the time; the cause whereof, as I apprehended,
was the numbness and earthly mindedness of many members of that large assembly;
in which there was, notwithstanding,
a substantial body of wise and lively spirited Friends; which, by account,
has continued in a succession from the early times of our Society.
When this meeting was over, I set out in company with several Friends in their way home,
in order to visit some meetings in the Dales, on my way to Kendal Quarterly Meeting;
John Scott being with me.

The first meeting we had was at Bainbridge in Wensley-dale, which was large,
being on a first-day.
It was a very trying laborious time.
I had very little to say by way of ministry, but suffered deeply in spirit,
under a sorrowful sense of carnality prevailing.
Next day I had a very comfortable reviving
meeting among a few plain Friends in Grisdale.
After which I went home with that plain faithful minister of the Gospel,
Alice Thistlethwaite, who had borne me company from York, to her house in Dent-dale,
where we had a meeting next day, which I hope was serviceable,
although things were but low.
After this we went to the house of that worthy elder and minister of the Gospel,
James Wilson, near Brigflats, where, next day,
the Lord was pleased to favor us with a powerful glorious meeting;
so that we could thankfully witness Truth was over all.
Such thorough open meetings but seldom fall to our lot in this declined state of things.
Yet the Lord is all-sufficient for the help and support of his faithful servants,
in all times and dispensations of his providence to mankind; so that we not only can say,
sufficient to the day is the evil thereof; but also,
sufficient to the day is the strength and wisdom
afforded for our assistance in the Lord`'s work.

Next day I went to Kendal, being accompanied by the before mentioned worthy Friend,
who entertained me on the road with pleasing accounts
concerning the spreading of Truth in those parts,
and the wonderful convincements thereabouts, by that memorable servant of the Lord,
George Fox, which the said Friend had heard related by eye witnesses,
who were themselves convinced at that time.
This made the journey exceedingly pleasant to me, nothing disagreeable therein,
but its being too soon over, as that put an end to this delightful conversation.

There appeared to me a valuable body of Friends yet left in and about Kendal,
although many had been removed by death but a little time before;
the loss of whom was much lamented by the survivors,
as they had been useful members in their day.
It also appeared that good order was well maintained,
and the excellent discipline established among us in the wisdom of Truth,
seemed to be as duly put in practice, as in most places I have observed among Friends;
yet my way was much closed up in suffering, during the Quarterly Meeting.
I stayed their meetings on first-day, and was largely opened in the morning,
Truth having great dominion; but in the afternoon was shut up in silence.

On third-day I went to Windermere general meeting.
Truth greatly overshadowed that large assembly,
and the testimony thereof was much exalted,
to the edification and sweet refreshment of the upright in heart,
as well as deeply affecting the minds of many
who had taken more liberty than Truth allows of;
I hope it may be to their lasting advantage.
Next day I had a small meeting at Grayrig, where things were low.
At Preston the Lord was pleased to favor us with an open comfortable meeting,
and Truth`'s testimony was exalted; after which I went to Kendal,
and had a very comfortable meeting among Friends there.
From there I went to Swarthmore, and was at their meeting on a first-day,
in a meetinghouse built near the hall by George Fox.
I could not discover much lively sense of true religion there,
it being a time of painful suffering silence.
The Hight meeting was to pretty good satisfaction;
but that at Hawkshead was low and afflicting.
My principal service was to give an example of silence, which frequently fell to my lot;
the Lord favoring with resignation to his divine will.
Next day I had a small open satisfactory meeting at Keswick; and went to Isel meeting,
but had nothing to deliver by way of testimony.

From there to Pardshaw, which I think is the largest country meeting in England,
and Friends generally made a plain becoming appearance,
much resembling many meetings in Pennsylvania, both for largeness and otherwise;
the view whereof gave me singular pleasure, and abundantly the more,
as the great Master of our assemblies was graciously pleased
to honor and comfort us with his living presence,
in which there is fulness of joy.
Matter and utterance were given by him for the discharge of duty,
in which there was peace.
I had an open satisfactory meeting in the evening,
at my friend and old companion Christopher
Wilson`'s. Next day I had a meeting at Whitehaven,
and then went to Broughton, where I had a meeting.
I endeavored to lean upon the Lord alone, for guidance in my service,
and by him was frequently much opened to see the states of meetings and individuals.
The meeting at Cockermouth, was to satisfaction, and at Allonby,
Truth favored with a good degree of openness and peace.
From there I went to Holme, a meeting remarkable for having been, I suppose,
more than sixty years interrupted and grievously
disturbed by a wicked unruly company of Ranters.
It began in some of the Pearsons, and when they were removed,
others succeeded in the same spirit.
Some of them were at the meeting when I was there.
A woman of the party spoke several times in such rancor,
that I do not remember ever to have taken notice of a
voice so much tinctured with a dark diabolical spirit.
But Friends in the blessed enjoyment of the powerful Truth, were quite over it and them,
and I believe, had been in a good degree preserved;
as that meeting appeared to me the liveliest of any thereabouts, having, as I remember,
five or six public Friends belonging to it.

The next meeting I had was a small one at Bolton;
where Truth favored with a comfortable degree of openness.
I went to Wigton, and attended both their meetings on first-day;
which were exceedingly painful and exercising.
My mouth was closed up in mournful silence,
yet not without a pretty clear view and sense of the sorrowful states of those
among them who had been the principal cause of the death and misery which I felt.
I saw what they were doing in the dark, as it were, through the hole in the wall.
O! what a great snare bright genius and extensive natural abilities are,
to such as are deluded by Satan to trust in them,
and presumptuously to imagine they are sufficient to
answer every purpose for guidance and help,
not only in temporal but spiritual things, without divine aid immediately communicated.
I have met with no state more at enmity, or in greater opposition, to the Truth;
nor from whose spirits more pain and distress are to be met with,
than from these worldly wise and self-sufficient people, who no doubt,
would deride this observation, or any thing that asserts an inward sense of things.
They are very much out of the way of being reached unto and helped;
therefore they are in great danger of being left alone, that they may wonder and perish.
I sincerely wish that the tender-hearted, both youth and others,
may be preserved from the infection of the poison of asps which is under their tongues.

Next day I had a poor small meeting at Kirkbright,
where my business was to set an example of silence.
From there we went to Moor-house, where I had some openness and satisfaction,
though things were but low as to religion.
The next meeting was in the city of Carlisle;
where my way was closed up in painful silence.
I had a small open meeting next day at Scotby; then went to a meeting at Sowport,
where there were but few Friends, and things were very low among them,
as to the life and sensible understanding of religion; but many of the neighbors came in,
towards whom I found great openness to declare the Truth, and it was a good meeting.
I went next to Kirklington, or the border meeting, being on a first-day.
Friends having, without my knowledge, given notice to their neighbors,
and to several people of account in the world,
it is likely they expected great things from one come so far to visit them;
and some perhaps hoped to get credit by that day`'s work;
but we see sometimes when man appoints, the Lord disappoints; which in the end result,
seems to have been the case here.
I sat the meeting, which was very large, in silence,
to the great mortification of many present, some of whom,
one might have expected from their appearance and pretensions,
understood the nature of spiritual worship better,
than to have been so anxious after words.
It proved, I think, as painful and exercising a meeting as ever I knew,
to which the expectations of Friends and others did not a little contribute.
At the conclusion I was fully satisfied that I had
discharged the service required of me that day,
in an example of silence, in which I had peace.
I could perceive great uneasiness in many under our name, at the silence of the meeting.
This evidently discovers a mournful degeneracy,
seeing silent worship is so directly consistent with our Christian
profession of the inward teachings of the grace of God that brings salvation,
which has appeared to all men, and teaches all who diligently hearken thereunto,
that no time is more suitable than when assembled together,
unitedly to wait for this blessed teaching,
and thereby receive a renewal of our strength.
How absurd is it for those who profess this teaching,
and access to the Fountain of all good, to depart therefrom and gaze at the clouds,
or depend on the conduits and water spouts,
as if it was in their power to fill themselves, and so to supply their wants?
For although the servants have at times, by the Lord of all,
been used as a means for our help and edification,
yet such means or helps are not so essentially necessary to
the spiritual worship professed by us as a people,
but that it may be as effectually and as acceptably performed without them,
in an awful solemn silence:
than which nothing can be more reaching and convincing
to those in whom the divine witness is regarded,
and it may also tend greatly to raise that in the minds of such where it is depressed.

Some have remarked, that those who have been convinced in the silence of our meetings,
have generally stood their ground in religion best.
The reason is plain,
because they have at the very first laid hold of
and embraced the very substance of religion;
whereas, the understanding may be, in a great measure convinced by testimony,
and the mind much tendered and affected with lively declarations of the truth;
but all this goes off sooner, and will leave such minds destitute,
unless they happily come to be fixed under the
teachings of the grace of God in themselves,
and have to sit under their own vine and under their own fig-tree,
where none can make them afraid.
None need be ashamed of a solemn awful silence before God, and in the sight of men;
seeking the Lord, who will be found of all such, and will, by his secret invisible power,
vindicate that sort of silence in the hearts of all who allow his pure witness to arise.
All who reject the voice of this holy witness, may justly be disregarded by God`'s people,
so as not to be discouraged by what they say on that account.
But on the other hand,
when any thing of this nature is done in the form and by way of imitation only,
there being nothing supernatural to support and defend the same,
it must necessarily fall under contempt, and like the salt that has lost its savor,
will be trodden under the feet of men.
That Scripture passage is very observable,
where some undertook to cast out devils in the name of Jesus, whom Paul preached.
It is plain the evil spirits knew, notwithstanding their pretenses,
that they wanted power to subject them;
and therefore answered these imitators and pretenders,
"`Jesus I know, and Paul I know, but who are you?
and the man in whom the evil spirit was, leaped upon them, and prevailed against them,
so that they fled out of the house naked and wounded.`"
I instance this passage to show how inefficacious imitation is:
those would do well to consider this, who, upon a serious examination,
do not find the Lord with them in their religious performances;
for assuredly nothing can stand approved in his sight,
nor maintain a dignity worthy of him, in this state of probation,
but the product of his own spirit in us.
Therefore, let all who profess spiritual worship,
greatly dread being found in senseless stupid silence,
although it be in the very same form which the people of God have been,
and are still led into; knowing,
that the best and most consistent form is of little avail, without the heavenly power.
I perceived that some were much offended with me,
for abiding in the station in which the Lord placed me that day,
which they did not altogether forbear letting me know by words;
neither did I let them pass without some close remarks
on their sorrowful state and great blindness.
In about a week after, I received a long letter upon the subject,
setting forth among other things, how great a mystery it was to the writer,
that a person in my station, traveling from one nation to another,
should disappoint people, Friends and others, by such unaccountable silence.
Had not I discovered sufficient cause to believe
that this Friend was not then what he had been,
his letter would have been as great a mystery to
me as my silence in that meeting was to him.
When I had perused the letter, I was most easy to let it pass without answering.

This was a time of great anxiety to me, and I have made the above remarks,
as I felt my mind opened thereto; for no other reason,
than as a caution or warning to all professors of the
blessed Truth into whose hands this may come,
that they may watch and pray continually; lest,
by departing from the pure leadings of Truth in themselves,
they fall into the like absurdities; manifesting to others,
that they are but mere pretenders to spiritual worship;
and also for encouragement to painful travelers in the work of the Gospel, whose lot,
in the course of their service, may fall among such,
to whom they may be as signs and gazing-stocks, because their time is not always ready.
What makes such examples more necessary in some places,
is the busy forwardness of unskillful ministers among themselves,
who may be too apt to feed the people with a multitude of words;
perhaps frequently recommending silence in words, but not sufficiently by example.
I have seen it much my place, especially at home, to show Friends by my example,
the benefit and necessity of silence, and as it were, to lead them into it.
And as may be seen by this account,
I often found it my duty to sit meetings appointed for me in silence;
(being at times greatly distressed in a sense of
the states of the people,) like a sign unto them,
of what they ought to be more in the practice of.
This indeed was no easy task to the flesh,
as the expectation of people was greatly towards me, being come from far to visit them;
yet there was no remedy but patience and resignation to the divine will,
without whose assistance, I knew it was in vain to attempt any thing by way of ministry.
My way of traveling as above hinted, often silent, was looked upon then by many,
as a strange and unusual thing;
but some others have been led pretty much in the same track;
however I had mostly great peace and inward strength, to stand my ground therein,
as all will who follow the Lord whithersoever he shall be pleased to lead them.

I had a meeting on third-day at the house of Cuthbert Wigham in Northumberland,
which was a sweet refreshing time,
and tended much to strengthen and revive my drooping spirit.
Next day I had a pretty open serviceable meeting at Allondale.
From there I went to Alstonmoor,
where the Lord was pleased to favor me with a thorough arousing opportunity,
and God`'s everlasting Truth was exalted.
The next meeting I had was at Penrith, where things appeared to me but low.
I went from there to Coldbeck, and was at their meeting on first-day.
It was a very hard distressing time.
There I felt, as I thought, some of those hard dark spirits,
who had occasioned great anxiety at sundry places in that county, who might,
as I apprehended, be compared to the bulls of Bashan that compassed David about.
It is likely they would scoff at the expression of their spirits being felt,
but the time will soon overtake them, wherein their spirits will feel,
though now perhaps in a great measure past feeling.
Next day I had a small but pretty open meeting at Massdale.

From there to Terril, where I had a good open meeting,
Truth being exalted and Friends comforted.
The next meeting was Strickland, which was but small, yet to good satisfaction.
I went from there to Kendal, and attended their meetings on sixth-day,
first-day and third-day.
Most of them were to me trying and laborious.
I was not much opened as to ministry.
Friends in many places had need to be brought from words,
to the one eternal in-speaking Word.
On fourth-day at Yelland in Lancashire, I had a close searching meeting.
The next day I was favored with an open comfortable time at Wray,
and from there went to Bentham, where Truth assisted to discharge what I had before me,
to a good degree of satisfaction.
At Settle on first-day we were favored with a precious open time;
the testimony of Truth went forth freely and affectingly, tendering many hearts:
praises and thanksgiving to the Lord for the same.
Next day I had a small but a very open meeting at Monybent.
From there to Soly meeting, which appeared to me in a very weak, low condition,
as little of the life of religion was to be found therein.
After meeting I went to the house of my kind friends Jonathan and Margaret Raine;
and from there to Marsden-Height meeting, in which the Lord`'s power was livingly felt,
whereby the testimony of Truth was delivered with clearness and good demonstration.
Next day had a meeting at Trawden.
On first-day I went again to Marsden meeting, which was a thorough good opportunity,
and we were sweetly comforted together.

Being fatigued with constant traveling and close labor,
I rested at Jonathan Raine`'s about a week,
and then went to a large meeting of Friends in Lothersdale, where I was much favored,
and largely opened to deliver the doctrines of Truth,
with good demonstration and to my own peace.
The next day had a comfortable open meeting at Airton;
my friend Jonathan Raine bearing me company, and then to Skipton meeting,
where things were low.
I had that evening a good open opportunity
among our worthy friend David Hall`'s scholars.
Then I had a meeting at Fairfield, which was small,
but pretty open and I hope serviceable.
The next meeting was at Nethersdale, where I had very laborious searching work;
the testimony was close and sharp against formal professors, yet, through divine favor,
I was enabled to get through to very good satisfaction,
and the meeting ended comfortably.
At Asquith, I had a small open meeting, and then at Rodan, which being on first-day,
was very large; a plain solid body of Friends belonging thereto.
We were favored with an open meeting, and the testimony of Truth was exalted.
Next day I had a very comfortable open meeting at Bradford, and went to Keighley,
which was also satisfactory.
There I received from my worthy friend David Hall, an encouraging letter,
and as it contains matter of weighty instruction, I give it a place here,
not doubting but it will be agreeable to my readers.

[.embedded-content-document.letter]
--

[.salutation]
Esteemed and well-beloved friend,

In the sweet spirit and fellowship of the everlasting and glorious Gospel of peace,
I hereby kindly salute you,
and your dear companion and fellow-laborer in the acceptable work you are now engaged in;
not forgetting his worthy consort Margaret, when you see her.
Be not at all discouraged on any account, for I trust, your good Lord and Master,
whom you serve, has made you willing to leave your outward habitation and little ones,
and to traverse the ocean with your life in your hand,
as an ambassador in Christ`'s stead, to preach glad tidings of good things to the meek;
to call upon and arouse the indolent and careless;
to direct the straying sheep to the fold of rest;
to raise the drooping ones that are too low,
and endeavor to bring down the lofty who are too high, to the true centre,
even the midst of the path of judgment: in short,
to bring unto us the pledges of your Master`'s love and yours, and to receive ours He who,
after he had in his wisdom and counsel,
allowed you to be taken captive for the trial of your faith,
and in mercy ransomed you as an evidence of his power,
will never leave you nor forsake you.
I have unity with your spirit, gift, and with the manner of the administration thereof.
I entreat you, dear brother, keep to your steady bottom way.
The present state of the church loudly calls for entire resignation, faith, hope,
charity and patience, in the ministers of the Gospel.

The diversities of gifts, operations and administrations, from the one Spirit,
are beautiful and serviceable;
as the stars in the firmament are not all of one magnitude,
have not all one station or degree of luster,
but each is ornamental and serviceable in its respective places and season.
The Lord bless you,
and be your shield and exceeding great reward in time here and in eternity hereafter.
Now as the apostle, in a paternal way, advised his son Timothy to drink no longer water,
but use a little wine for his stomach`'s sake and his often infirmities; I desire,
as you serve not an austere man or hard master,
but the most merciful and bountiful King of kings and Lord of lords,
you will take due care of yourself, and rightly consider your constitution.
Do not drive on too fast in this cold climate and season of the year; consider,
nets are not always to be spread and cast into the sea,
but sometimes to be mended and repaired.
You finds the good Seed lies low in many bosoms and many meetings.
Experience teaches, that where and when our Master suffers; who said, where I am,
there shall my servant be; we ought to be content to suffer with him;
that when he reigns, we may also reign with him.
Shall the servant think to reign, when and where his Lord and Master suffers?
There are, my dear friend, you know, times of sitting at the King`'s gate; a safe,
honorable and profitable situation, previous to advancement.
They that are faithful in this low, safe sitting,
in due time receive a call from the King to put on his royal robes,
mount his horse and ride around, which is a high dignity and a high day;
yet those so favored, must not expect always to sit in that saddle,
nor always to be clothed with that royal apparel, but as certainly to dismount,
as ever they mounted; and must by no means forget the road to the King`'s gate,
and their honorable seat there.
We should be glad to see you here once more.
Pray write to us.
My wife joins with me in dear love to you, and those above-mentioned.

[.signed-section-closing]
I am your truly affectionate friend,

[.signed-section-signature]
David Hall

[.signed-section-context-close]
Skipton, the 19th of Tenth month, 1748

--

After this meeting I went home with my companion Jonathan Raine, to Trawden,
and next day to Todmorden, and had a laborious exercising meeting;
yet through the extending of heavenly help,
I was enabled to discharge the service required,
to my own ease and comfort in a good degree.
I had a small poor meeting at Oldham next day;
in which silent labor seemed to me to be my proper business.

On first-day, the 25th of tenth month, I went to Crawshawbooth in Rossendale,
which was a pretty large meeting; but I was in so weak a state of body,
being much spent with traveling and deep close labor,
that my spirits were greatly exhausted.
Finding my mind engaged in that meeting,
I stood up in order to deliver what seemed to be required,
but was obliged soon to sit down again,
being so weak that I could not raise my voice so as to be heard.
I then concluded it was time to take some rest, in order to recover strength,
if it was the Lord`'s will, which I did not then much expect, thinking myself far gone;
nor indeed did I desire it, for my afflictions, several ways, were very heavy,
which made me weary of this world, and had it been the Lord`'s will,
should have been glad to embrace death rather than life
yet I endeavored to be resigned to the divine will.
Great care was taken of me, with affectionate kindness,
by my worthy friends Jonathan Raine, his wife, and her sister Ann,
who then lived with them; having often the company of that valuable family,
the Ecroyds of Edgend.
I was brought very near to these two families, in that love that thinks no evil;
being by illness, or rather weakness, detained there about nine or ten weeks.
It was an exceedingly wet season, being also the middle of winter,
yet I got mostly out to their meeting, which was near;
and went several times to Marsden-Height, about four miles off;
and once to Skipton and Lothersdale, about eight or ten miles off:
in most of which meetings the Lord was with me to my great comfort,
enlarging my heart in service for him and his people,
to my satisfaction and encouragement.

As soon as I was pretty well recovered and the weather more fit to travel,
I set out for Lancashire, my kind friend Jonathan Raine bearing me company;
and attended both their meetings on first-day; which were painful and laborious.
I had nothing given me to deliver by way of public testimony;
many Friends there appeared to me then, and more since,
lively and sensible of the work of true religion;
yet I apprehend the expectations of too many were after words that day,
which were to be disappointed.
O that all were really turned to the divine Word, that they might never be disappointed!
I was next day at their Monthly Meeting of business, which was low,
Truth not having much dominion therein.
I went to Wyersdale, and had a pretty open meeting, and returned to Lancaster, where,
through divine goodness, we were favored with a heavenly baptizing meeting,
to our great joy in reverent thankfulness.
Friends were sweetly united in the precious
enjoyment of the pure love and goodness of God;
having an additional confirmation, that when the Lord is pleased to shut, none can open,
and when he is pleased to open, none can shut.
As there had been very little openness at some meetings there before,
and at this the Lord opened places of broad rivers and streams,
to the unspeakable pleasure and refreshment of thirsty souls;
in a sense thereof I took leave of Friends,
being accompanied by my esteemed friends William Backhouse and Jonathan Raine.
We had a pretty open comfortable meeting at the Fylde.

Next day had a thorough awakening opportunity at Freckleton,
being enabled to divide the word with great plainness to their states;
wherein I had ease and peace.
We then went to Preston, where the number of Friends was exceedingly small,
and but little to be felt of a spiritual travail
or lively sense of religion among those few,
there having been a mournful declension;
yet I found the Lord`'s merciful lovingkindness graciously
extended towards them for their help and recovery.
From Preston I went to the following meetings, namely, Capel, Ashton,
Bickerstaff and Liverpool:
in all which the Lord was graciously pleased to afford wisdom and strength,
to open doctrine and counsel, stirring up careless luke-warm professors,
as well as to the encouragement and edification of the sincere-hearted,
also to my own ease and peace.

I went from Liverpool to the house of Gilbert Thompson,
and was at Penketh meeting on first-day; where my spirit was deeply afflicted,
under a sense of many professors sitting down at ease,
seeking to be fed with words and outward declarations concerning the things of God.
I have found this much the case at some places where eminent instruments have dwelt.
Friends have allowed their minds to be too much drawn from a diligent spiritual labor,
to receive the bread and water of life immediately from the fountain thereof;
and depended upon the labor of such instruments, who are but as clouds or water-spouts;
having no power to fill themselves or to feed the flock profitably,
until furnished for that purpose,
by the bounty of the inexhaustible treasury of wisdom and all-sufficiency.
Here the fountain is forsaken for the stream`'s sake;
the eye being more to the gift than the giver, which is an abuse of the gift,
and provokes the Lord to jealousy;
giving him just cause to withhold such instrumental means.
The reason of such a dangerous mistake, to me is obvious, namely,
because it is found easier for flesh to receive by such a medium;
"`Let not God speak unto us, lest we die, said the people of Israel,
but let Moses +++[+++the instrument] speak unto us.`"
There is a life that ought to die on the cross,
which is easier saved alive under testimonies, be they ever so substantial and excellent,
than under the immediate teachings of Christ;
whose voice is as a fire against evil of every kind,
and affords no peace after it is discovered, until it be given up for destruction,
and to be purged away by the spirit of judgment and burning.
This pure voice speaks to us in such a manner,
that we can by no means turn it off from
ourselves by applying it to the states of others;
which may be done under the most searching testimonies;
there being a partiality to ourselves, which, through the deceitfulness of the heart,
we are apt to fall into; and also to flatter ourselves,
by supposing the pleasure we take in hearing the doctrines of Truth delivered,
arises from the good in us,
when it may be no other than the state of those to whom the prophet Ezekiel`'s words
and declarations were as a lovely song of one that has a pleasant voice:
for they heard his words, it seems, with pleasure, but did them not;
their heart going still after their covetousness.

I have made these remarks,
because of the very hurtful consequences I have often seen and felt,
by an over-anxiousness in people after outward declarations;
even to the neglect of that great and necessary work,
of drawing near to God with true hearts, in full assurance of faith;
wherein is our only safety and help.
May this consideration deeply engage all minds
to return unto the great Shepherd of Israel,
who puts his own sheep forth and goes before them, leading into green pastures,
bringing them up from the washingpool, bearing twins, none being barren among them.
I found it my place to give that meeting an example of silence.

From there I went to the Monthly Meeting at Hardshaw,
wherein I sat a considerable time in silent waiting upon and seeking the Lord,
who was pleased in his own time to open a living spring of ministry,
and truth greatly prevailed, to the comfort and edification of Friends.
There were also several not of our Society present during the meeting for worship,
one of whom expressed the sense he had of an awful solemnity
to be felt in the meeting before any words.were uttered,
which to him exceeded words, or to that effect, as a Friend told me afterwards.
This, doubtless, would be much more the case with many who at times come among us,
were our religious meetings held in the sensible feeling of the divine power.

From there I went to Manchester, and had a meeting, which was low and afflicting.
Some who should have been way-marks and leaders of the flock,
not keeping their own spirits in due subjection to the peaceable spirit of Truth,
had not maintained the unity thereof, which is the bond of peace;
whereby that meeting was hurt, and the pernicious effects thereof were painfully felt.
I stayed until their first-day meetings were over,
where the Lord was pleased to afford sufficient
ability to discharge the service required,
to my own ease and comfort, in a good degree.
I went from there to Stockport in Cheshire, and had an open comfortable meeting,
to the reviving of the few who labored to keep their habitations in the Truth,
and to the warning of careless professors.
I had next day a small poor meeting at Macclesfield, and from there to Morley, where,
although the appearance of professors was large,
yet very little was to be felt of the life of religion among them; but instead thereof,
a sense of death and darkness, occasioned by wrong things.
I had no openness at that time to administer any thing, but an example of silence.

I had a meeting next day at Frandley, where Truth favored with a degree of openness,
and went from there to Sutton, where things appeared low.
I found it my place to sit the whole meeting in silence.
The next meeting was at Newton, being on first-day,
where I was favored with a pretty thorough opportunity to clear myself.
Then went to West-Chester; had a small meeting there in silence,
and things appeared very low.
The next day had a good satisfactory meeting at Namptwich; and went to Middlewich,
where I met our worthy friend, Joshua Toft.
The meeting was, through divine goodness extended for our help,
to pretty good satisfaction.
I went home with the above-mentioned Friend,
and had a meeting next day at Leek in Staffordshire: I sat the whole time in silence;
Friends appeared to me, in too general a way, at ease in an empty form of religion,
depending on the labor of others.

Next day in company with Joshua Toft, went to the burial of a Friend at Stafford;
where there are but few of our Society, but many others came,
some of whom were very rude and noisy in the meeting.
Our way was quite blocked up as to ministry.
I returned with Joshua Toft and went to Leek meeting on first-day,
where I had a thorough arousing opportunity; Truth being exalted,
and the great name of God magnified, who alone is worthy forever.
I went from there in company with my dear friend to the Quarterly Meeting for Cheshire,
to be held at Middlewich: Infinite kindness was greatly manifested at that meeting,
for the benefit of Friends in general and the
encouragement of the upright-hearted in particular.
Things respecting Truth and Friends were very low in that county; yet the Lord,
in condescending kindness, extended his love for their revival and recovery.
Here I found my mind engaged to visit Morley meeting again,
the aforesaid Friend joining me therein;
and sending notice by some Friends returning from the Quarterly Meeting,
we had a very large meeting, composed of Friends and others.
I had thorough service; yet near the conclusion,
not finding my mind clear of those under our profession, others were desired to withdraw,
which they immediately did.
Our labor was very close and searching among those under the profession of Truth,
things being much out of order and undue liberties having crept in.
The Lord favored me with wisdom and strength,
so to discharge myself of the service required, as to go away with a peaceful easy mind.
