== Chapter 5

[.chapter-synopsis]
* Goes to Yorkshire again
* Attends the circular Yearly Meeting in the North of England
* Visit to Ireland
* Returns to England and proceeds in his religious visit there
* Goes to London and embarks for home
* Lands at Chester in Pennsylvania.

I have now to give an account of an unexpected turn I found in my mind,
respecting the course I was to steer in my travels.
When I left Lancaster I had no other view than to visit
meetings agreeably to the foregoing account,
and to proceed in a pretty direct course through the midland counties towards London.
But, very contrary to my expectation,
I found my way quite blocked up as to what is before hinted,
and another way opened before me, namely, to turn into Yorkshire again,
and take meetings in my way to the Quarterly Meeting there;
from there to Lancaster Quarterly Meeting;
and to the circular Yearly Meeting for the Northern counties,
to be held that year at Kendal; after which, to cross the sea for Ireland.
This unlooked-for turn brought close exercise upon my mind;
not so much out of reluctance to obey the Lord`'s requiring,
provided I was favored with clear certainty thereof, as from a fear of being mistaken;
and great reasonings I had in my weakness; yet through divine favor, I was enabled,
in a good degree to get over them,
and to yield obedience to what I believed was required.
I acquainted my friend William Backhouse with the time I purposed going for Ireland,
as he, when with me in the Fylde county of Lancashire,
had signified his desire of bearing me company therein,
when I found it my duty to undertake it.
Neither he nor I thought then it would be so soon; however, I received his answer,
that he intended to prepare against the time proposed, in order to bear me company.
We went from this meeting to Lowlayton in Derbyshire,
and were favored with a good open meeting,
and proceeded over the mountains of Derbyshire-Peak, to Sheffield in Yorkshire;
where the Lord was pleased to give us a very gracious confirming meeting,
Truth and its testimony being greatly exalted.
This blessed opportunity removed all my reasonings and fears;
for which my soul was humbly thankful to the Lord, my only helper.

After this meeting, my much esteemed friend Joshua Toft and I took leave of each other,
he returning home.
I went with our worthy friend John Haslam, to his house at Handsworth Woodhouse,
and the next day had a very open satisfactory meeting;
the Lord affording doctrine and counsel suitable to the
states of the few belonging to that meeting.
When at the house of this Friend,
my mind had some view of his bearing me company to York,
and from there to Kendal Yearly Meeting, of which I informed him;
but he made very light of it,
perhaps thinking my motive was only for the sake of having his company.
I advised him to take with him such things as he might think necessary,
in case he was to go; and if, when at York, he found no such concern,
he might return home.
We set out together for York, taking meetings in our way at Newel-Grange and Barton,
which were precious open times;
the life and power of Truth attending to our great comfort.
We traveled on to Leeds, and lodged at our worthy friend Christiana Home`'s,
who had been a succorer of many of the Lord`'s messengers,
being a truly open-hearted woman, a mother in Israel.
She did not continue a great while in mutability after this.

Next day we proceeded to York, attended the Quarterly Meeting,
and stayed over their first-day meetings, which were hard and painful;
I had nothing by way of testimony, save a little at one of them.
My truly valuable friend John Haslam acquainted me,
that what I had said to him of bearing me company to Lancaster
Quarterly Meeting and the Yearly Meeting at Kendal,
had laid such close hold of his mind, that he could not find freedom to leave me.
He said, that although he did not much regard them at first,
the few expressions I used had cast such a mantle over him, or to that effect,
that he found he must go with me,
though not so well provided for the journey as he could desire.

We went from York to the Monthly Meeting at Settle, and in the afternoon of the same day,
were at the burial of a Friend there, which was an open satisfactory time.
Truth overshadowed the meeting,
and the testimony thereof was greatly exalted to our solid comfort.
Next day we had a pretty open comfortable meeting at Bentham,
and went from there to the house of our friend William Backhouse,
whom I expected to find prepared to go with me into Ireland; but to my surprise,
I found he had reasoned it away,
under an apprehension that his proposal of accompanying
me proceeded more from love to me than any real concern.
I was fully persuaded his concern was right,
as he informed me that it had remained on his mind for some years,
to visit Ireland again; I therefore had a great travail in my mind for him,
that he might be brought to a right sense and discerning of the Lord`'s requirings;
being fully satisfied he was a man of sincerity, who would not willfully transgress.

I took an opportunity with him next morning and his concern returning,
and he abiding steadily under the weight thereof,
afterwards performed the journey to his own peace,
and was to me an agreeable friend and fellow-laborer.
Having appointed to meet me at Whitehaven; we went from his house to Lancaster,
and attended their meeting on first-day,
in both which I found it my business to set an example of silence.
That night after all were in bed,
I was taken suddenly with an uncommon swelling in my throat, not much unlike a quinsy.
I could scarcely swallow liquids for some time,
so that it seemed very probable to those about me, that it would soon be over with me,
as to this world; concerning which, I was very easy in my mind.
A doctor was quickly sent for; by whose care, under divine favor, I soon recovered,
so as to attend the Yearly Meeting at Kendal.
It was very large, there being a great collection of Friends from many parts,
and large numbers of people of other societies.
It was divinely favored, especially at the concluding meeting,
wherein God`'s everlasting Truth triumphed gloriously, and my poor depressed spirit,
that had long waded under the weight of wrong things,
was raised into comfortable dominion, and obtained, through the Captain of our salvation,
complete victory over those hard unmortified spirits, undue liberties,
and carnal lifeless professors, under a painful sense whereof,
I had long mourned in my northern travels.
Now I was set over them all, for I sensibly perceived,
and livingly felt his eternal power set over wrong spirits,
and clearly saw that the Lamb and his followers will obtain the victory:
and although it has been, and will be, through great sufferings,
yet those who patiently suffer with Christ, shall also reign with him.
This meeting crowned my service in those parts;
after which I found my mind at liberty to embark for Ireland.

I set out next day for Whitehaven, in company with my good friend Christopher Wilson;
a very pleasant journey we had, in that sweet innocent freedom which clothed our spirits,
feeling the consoling streams of that river which makes glad the city of God.
We, in degree, enjoyed the new heavens and the new earth, wherein dwells righteousness,
the fruit and effect whereof is quietness and assurance forever.
I was at Pardshaw meeting on a first-day, which was a precious opportunity;
Truth being greatly in dominion and its testimony exalted,
the sincere-hearted were sweetly comforted and united one to another.
Next day I went to their Monthly Meeting,
and had good service both in the meeting of worship and
that for transacting the affairs of the church.
The weighty service of visiting families was before it,
and I understood had been sometime obstructed by some of the members,
to the concern and uneasiness of others.
It was clear to me, when it came to be weightily considered,
that the power and virtue of Truth was livingly with the promoter off so good a work,
and I did fully believe the Lord would bless it in their hands.
I therefore endeavored to sift the opposite side as well as I could, to the bottom,
and found very little or no weight in what they had to offer against it.
Upon which they were earnestly desired not to hinder the service of others,
in that important work that had so often and so evidently been blessed,
although they might be unwilling to put their own hands to it.
Truth arose and came over them,
so that Friends appointed fifteen or sixteen men and women,
to go in several companies on the service,
as that Monthly Meeting is large in its extent.
This afforded great relief and satisfaction to
the sincere travelers for Zion`'s prosperity.
I went from there accompanied by several Friends, to Whitehaven,
where I met my intended companion William Backhouse; and a ship belonging to a Friend,
whose name was James Nicholson, being ready to sail for Dublin, we went on board of her,
the 19th of the second month, 1749, in the evening, and were soon under sail.
We met with contrary winds, and a very rough uneasy passage as to our bodies;
being five days and as many nights before we landed.
What made it much harder for William and me to bear was,
that we had given up the beds prepared for us to two
women Friends who came on board and were unprovided,
they being very sea-sick most of the time;
so we were under a necessity of lying down on the cabin floor or upon some of the chests,
in our clothes, which we did not take off all the while, that I remember.
This proved very trying to us,
and we were greatly spent and fatigued when we landed at Dublin.
We were received and entertained with affectionate
kindness by our friend Samuel Judd and family,
at whose house we lodged while in that city.
The Half-year`'s Meeting began in the morning of the day we landed,
it being afternoon when we got on shore.

The next day we attended two meetings for the affairs of the church;
and I was fully persuaded, there was a faithful exercised remnant,
painfully laboring for the restoration of ancient beauty and comeliness,
and the affairs of the church were transacted with considerable order and decency;
yet my spirit was clothed with deep mourning, and much closed up in painful anxiety.
The cause thereof I did not then distinctly understand;
but when I had traveled through the nation, visiting the churches,
and sorrowfully viewing the desolations thereof,
my sufferings in spirit at the Half-year`'s Meeting were no longer a mystery to me.
The next morning was held a general large concluding meeting for
worship and in the afternoon a meeting of ministers and elders;
at both which, especially the latter, I had open thorough service;
as also in their week-day meeting at Sycamore-alley on sixth-day.
We stayed at Dublin over first-day:
at Meath-street in the morning the Lord was pleased to
furnish largely with matter and utterance,
to a good degree of satisfaction.
In the afternoon at Sycamore-alley, I found it my duty to be silent.

On second-day we set out from Dublin, accompanied by James Evans and wife,
in order to visit the following meetings in our way towards Cork, namely, Ballycane,
Wicklow, Errats, Wrights, Cooladine, Wexford, Lambston, Ross, Waterford, Clonmel,
Kilcomon, Youghal, and so to Cork.
We found things very low indeed in most of the said meetings;
my service in them was generally searching, painful and laborious;
Truth seldom having that comfortable dominion,
(by reason of the prevalence of wrong things) which was earnestly labored for,
both by us, and also by a few mourners scattered up and down in those parts,
who waited for and ardently sought the prosperity of Zion.
Such can only rejoice when the righteous Seed bears rule.
We had several meetings in the city of Cork,
where there is a considerable body of Friends.
But the love of this world and other undue liberties, have prevailed,
to the great hurt of the Society there also.
Our labor was for the most part, painful and exercising among them.
From there we went to Kilcomon again; so to Cashel, Limerick, Jonathan Barns`'s and Birr.
At several of these meetings I found it my place to example the people with silence,
which was the case at Birr, having, as it was said,
all the people called Methodists residing there, and their preacher at the meeting;
than whom, I think no people are more at a loss what to do with silence in worship.
I am persuaded there have been awakenings of merciful kindness to them,
and they have seen the necessity of the new-birth;
but their notions about it have been for the most part, in airy visions,
and flightiness of their own imaginations; not coming lo cease from man,
nor from their own willings and runnings.
Oh that they were so happy as to be emptied, that God might be all in all,
working in them the will and the deed;
then would they come really to experience true poverty of spirit,
and to abhor forward active self, whose time is always ready.
In this safe, self-denying situation,
they would really feel an absolute necessity to wait,
as with their mouths in the dust before the Lord,
until he shall be pleased to arise in their hearts;
whereby all his and their enemies would be scattered.
Then would true worship be performed,
and they established upon the immovable Rock
that the gates of hell cannot prevail against.
After Birr, we had meetings at the Moat, Old-Castle, Ballyhaise,
Coothill and Castleshane; which meetings were mostly small and painful.
Truth favored with a degree of strength, to labor for their help and recovery; but,
alas! the life of religion appeared to be at a very low ebb.
The next meetings we had were at Ballyhagan and Charlemont, which were large,
yet but little to be felt of the life of religion stirring in them,
neither did there appear to be much soundness among some of the foremost rank;
several of whom having administered cause of stumbling and discouragement to others,
it had a bad savor and influence; instead of gathering,
it had tended to scatter from the fold of Christ`'s flock.
I had very close searching work among them,
in order to bring the judgment of Truth over such,
as the Lord was pleased to open my way and to discover their states to me,
being altogether without any outward information thereof.
I understood afterwards some of them resented it,
though they said nothing to me about it; but as some had before,
so I understood one or more of them did soon after, manifest a base ungodly foundation.

We proceeded to take the meetings round Lough Neagh, namely, Toberhead, Colraine,
Ballinacre, Grange and Antrim;
which meetings appeared indeed almost a desolation with
respect to the sensible possession of Truth,
although it was professed by some.
A time of deep mourning and distress it was to my soul, to view their captivity and loss,
of which themselves did not seem to have much sense.
The next meeting was Ballinderry, being very large, but heavy and painful;
yet the blessed power of Truth prevailed in a good degree.
From there we went to the following places and had meetings, namely, Lisburn,
Hilsborough, Lurgan and Moyallan; where,
although we found some true mourners in and for Zion,
yet the bulk of the Society seemed to love the world and the things that are therein,
to that degree, as to have very little taste or relish for the things of God.
Even some of those, who, by their stations in the church,
ought to have been lively examples of self-denial in this respect,
appeared to be as deeply plunged into this mournful cause of desolation as any.
Alas! what account will they have to give of their stewardship,
when the chief Shepherd shall appear.
From this place we crossed the country to Edenderry; once remarkable for a brave,
lively body of Friends: there are now a large number of professors belonging to it; but,
alas! the glory is much departed, and the fountain of living water forsaken by many.
Oh, how are they gone into captivity by the muddy waters of Babylon!
We attended their meeting on a first-day, but could hear no melody or song of Zion;
all being closed up, and our harps hung, as it were, upon the willows.
It was a time of deep silent mourning.
About the time of breaking up that meeting, it livingly sprung in my mind,
that as they had rejected abundant favors bestowed upon them,
that they might be gathered to God, so the Lord would reject many of them.

The next meetings we had, were at Timahoe, Rathangan, Mount-melick, Montrath,
Ballinakill, at James Hutchinson`'s, Carlow, Kilconner,
and the province meeting at Castledermot.
Pain, distress and close labor, either in testimony, or an example of silence,
attended in the last-mentioned meetings; yet the Lord was a gracious support through all.
I hope our deep wadings and painful service, were not without some good effects,
both in stirring up the careless, and comforting the mourners in Zion.
I had very close service at the province meeting; yet, by divine favor,
was carried through to pretty good satisfaction,
and I believe it was a serviceable meeting to many.
From there, in our way to Dublin, we had meetings at Alby, Ballitore and Baltybois,
which were small, and true religion very low.
From there we went lo Dublin, intending shortly to embark for England.
We attended the meetings in the city,
both on first and other days of the week during our stay,
but I had very little openness therein;
being made to the professors as a sign and example of silence from meeting to meeting.
Great indeed were my inward distresses,
on account of the mournful declension of the church in Ireland: the Lord knows,
and was my only support under it.
Blessed be his name forever!
Many there were among themselves, who greatly lamented it;
the travail of whose pained souls,
I hope the Lord of sabbaths will regard in his own time,
so as to turn his hand again upon a greatly declined church, that,
by the spirit of judgment and burning, he may purely purge away her dross,
take away her tin and reprobate silver; that her judges may be restored as at the first,
and her counsellors as at the beginning.

It may by some be looked upon rather imprudent,
to lay open the defection and spiritual condition of our Society,
which depends so much upon my own testimony of
an inward sense given me thereof in my travels.
In the first place, no other person can do it for me,
and I cannot find my mind easy that it should be wholly omitted.
It has been so repeatedly, and confirmed with such clear evidence to my understanding,
that I have not the least doubt of what I write in that respect.
Although it be with a considerable degree of reluctance, yet it seems my way,
and I am not easy to go out of it; intending no other by those close remarks,
than as lessons of instruction, caution and warning, to succeeding generations; if,
when I am removed hence, this be looked upon worth printing.
So far I may add, that the laying open the mournful declension of the Society,
and pointing out some of the causes thereof,
as my understanding might be opened thereinto,
was one of the principal things that engaged me to write a journal:
it never entered into my thought, that my travels and little services, singly considered,
were of such consequence as to merit the regard of my friends, so as to be published;
but thinking the account of my travels and the observations of
the state of things are necessarily connected together,
so that in doing the first, I could not well avoid the last.
I have further to add, that I think myself also warranted herein,
by the example of God`'s faithful witnesses in ages past,
with whom it was usual to lay open the states of the people,
both in an individual manner and in a more collective body, that is, as nations,
societies or churches; also setting forth, for a warning to all succeeding generations,
those particular evils which caused the Lord`'s displeasure, and would,
if not turned from, bring down his judgments upon them.
We also find, that, even these warnings and heavy denunciations of judgment,
were preserved in writing, as a testimony for God and against themselves,
even by those against whom they were really given forth; yes,
the particular evils and frailties which, through inadvertency,
the Lord`'s choice servants fell into and deeply repented of, are recorded;
not only as warnings to all,
but also to excite charity and tenderness towards those who have fallen into evil,
in case they repent and forsake; considering that we may also be tempted,
and therefore never dare to upbraid those, who, through their own imprudence,
have fallen among thieves and are naked and wounded,
provided they return again to the Father`'s house.

I have further to remark,
that I have observed a prevailing disposition in
some of considerable eminence in the Society,
and in a great many others, to cry up for peace and charity,
and the maintenance of unity, and not to press any thing very closely,
lest the peace of the Society should thereby be endangered; although,
perhaps the things urged cannot well be objected to upon any other principle
than groundless fears and a faint heart not yet quite upright to God,
nor wholly redeemed from the praise of men:
as there is an unwillingness to displease them, though in maintaining the Lord`'s cause:
"`for if I yet pleased men,`" said Paul, "`I should not be the servant of Christ.`"
What makes me take notice of this, is, that I have seen a great snare in it,
wrong things being allowed to remain and prevail under it,
and the fire of primitive zeal against undue liberty, much quenched.
We have no such examples in the prophets, or in Christ and his apostles,
of indulgence and winking at wrong things and false ease.
They, in their concern to testify against such things,
had no fear of breaking unity nor disturbing the quiet and peace of any people,
let their rank or station be what it may.
Had this noble spirit of ancient zeal been more generally exercised
in plain dealing and speaking the truth one to another,
the mournful declension justly complained of among us as a people,
would not so generally prevail.

It is but about a century since the Lord by an outstretched arm,
gathered our Society as from the barren mountains and desolate hills of empty profession;
choosing them for his own peculiar flock and family;
as by many evident tokens of his love and mighty protection, does fully appear;
even when the powers of the earth like the raging waves of the sea, rose up against them,
with full purpose to scatter and lay waste.
The remarkable evidences of his regard, must, I think,
gain the assent of considerate persons,
who yet may not have a capacity of understanding
clearly the Lord`'s gracious dealings with his people,
in a more spiritual and mysterious relation.
When I view the multitude of his favors and blessings to them in this respect,
I am afraid to attempt the recounting and setting forth
of so copious and amazing a subject,
which can better be admired, and the bountiful Author adored for the same.
It may be justly queried, What could the Lord have done for us that he has not done?
Notwithstanding which, what indifference,
lukewarmness and insensibility as to the life of religion,
are now to be found among numbers under our name; no, in some places,
this painful lethargy is become almost general; although I hope a few may be excepted,
who are much afflicted on that account, and burdened with an earthly, carnal spirit.
Oh! how does covetousness, which is idolatry,
and an inordinate love of things lawful in themselves and places,
cloak and shelter themselves under a plain appearance in some;
yet plainness is no more to blame for that than
the name disciple or apostle was to blame,
because Judas once bore it.
I could write much more on this mournful subject,
having suffered deeply in my travels on account of the grievous declension;
but hope to ease my mind by dropping here and there a remark,
as I proceed in giving an account of my travels.

We embarked at Dublin the 18th of the fifth month, in the morning, and landed at Peel,
near Swarthmore-hall, next day.
One thing I am not quite free to omit,
as I could not well help looking upon it a providential preservation of my life, namely,
the sands being very extensive thereabout, and we happening rather too late,
as to the time of tide-serving, to be set on shore, could not,
owing to the waters leaving us, bring the boat up so as to land in time.
We were thus set fast, about half a mile from firm land.
We could, therefore, think of no better way in this difficulty,
than accepting the poor sailors`' assistance, which they kindly offered,
to carry us to land on their backs, which was no small undertaking, as we were,
especially myself, none of the lightest.
I was the first, and believe the sailor, who was a strong man,
would have carried me to land, had not both of us, in our journey there,
fallen into a large quick-sand.
The sailor immediately left me, his burden, to shift for myself, while he did the same;
but he had greatly the advantage of me, as he could swim, which I had never learned.
However, I was some how or other, buoyed up in a wonderful manner,
so that I never was plunged over head; to which, perhaps,
my great coat buttoned about me, might in some measure contribute.
I well remember that I could feel nothing under my feet but water or soft mud,
which could not bear me up, my head being all the while above water;
I knew which way we tumbled in, and being near the bank,
I made some shift to scramble to it, and to climb up of myself.
I then waded to the shore, being exceedingly wet and dirty.
We went to a cottage where the accommodations were very mean;
but the poor people`'s kindness and hospitality were very noble,
which we did not let pass unrewarded.
We got that night to my affectionate companion`'s house;
having traveled the before mentioned journey with great diligence,
in much love and harmony one with another,
and were not quite three months out of England.
The first meeting I went to after we landed was Yelland, which was a good open time;
Truth being exalted over wrong things; and from there to Lancaster,
where I had a satisfactory meeting; the Lord`'s power in a good degree having dominion,
to our comfort.
I was at Penketh meeting in the forenoon, on first-day;
where the Lord was pleased to favor us with a precious opportunity,
Truth being exalted over all,
and the sincere travelers Zionward greatly comforted in
the sweet enjoyment of the Lord`'s presence,
which was livingly felt among us.
Praises to his holy name forever!
In the afternoon we had a large meeting at Warrington,
where it appeared my duty to sit in silence; the lack of which, properly employed,
proves a great loss to our Society in many places.
Next day accompanied by my worthy friends Samuel Fothergill and William Dilworth,
I set out in order to be at Marsden-height Yearly Meeting,
and to visit Friends thereabout.
Marsden week-day meeting on fifth-day, was satisfactory.

On the first-day following the Yearly Meeting was held,
to which came a large collection of Friends from parts adjacent,
and many people of other persuasions.
The Lord was pleased to exalt his glorious Truth and the testimony thereof,
in a free and open manner, to the comfort of many hearts.
I went from there to Manchester,
accompanied by my affectionate friends Jonathan Raine and his wife,
and had an open comfortable meeting, Truth having dominion;
wherein alone the upright-hearted can rejoice, with joy unspeakable and full of glory.
Oldham meeting on first-day, was in a good degree open, and I hope serviceable.
The next day I traveled to my worthy friend Joshua Toft`'s, near Leek,
and had a meeting there, in which I found it my place to sit in silence.
Having my said friend with me,
we attended both their meetings at Birmingham on first-day;
which were very heavy and laborious,
through the prevalence of lukewarmness in some and undue liberty in others;
so that I had but very little openness at either of them,
and in one was quite shut up in silence.

The next meetings we had were at Wigansal and Atherstone;
but found the life of religion very low in them.
The Yearly Meetings for the westerly counties being to be held at Coventry,
we went there in order to attend them.
They began on first-day, the 6th of the sixth month, 1749,
and were held in a large town-hall; conveniency being made therein for the purpose;
so that one room which was called the hall, would contain by computation,
not less than a thousand people; and another under the same roof,
it was supposed would contain about five hundred.
We had a pretty large meetinghouse besides.
These, I think, once or more, were all filled at one time.
There was a great collection of Friends from many parts,
and a very great flocking in of others, among whom there was considerable openness,
and their behavior in general was becoming.
The Gospel was preached with power, clearness and demonstration.
I found myself much excused from public service, which I accounted a favor;
having greatly to rejoice in the exaltation of Truth`'s
testimony through well qualified instruments;
a considerable number being present whom I greatly preferred,
and was glad the public service fell chiefly upon them.
I have ever accounted it a concern of great importance,
to appear by way of public testimony in those large assemblies,
and have earnestly prayed they might be conducted in best wisdom; which,
doubtless would be the case,
if the spirits of all who undertake the great and awful work of the ministry,
were truly subjected to the alone source or fountain thereof; who is,
to his humble dependent ones, wisdom and utterance.
The meeting ended on third-day to the comfort of Friends, and as far as appeared,
to the general satisfaction of others; whose attention to what was delivered,
and behavior to Friends in general, were to their honor,
and the reputation of the city of Coventry.

On fourth-day there was a meeting appointed at my request in Warwick, to which I went;
but when I saw the great company of people, many of whom by their appearance,
seemed to be of the principal inhabitants, I was intimidated,
and fell under discouragement for a time, knowing my own great weakness.
My fear was, lest through my means or that of some others present, Truth might suffer.
I cried with earnest concern to the Lord who sees in secret,
and he was graciously pleased to hear and to furnish with might,
by his spirit in the inward man;
so that the everlasting Truth and its testimony were exalted that day,
and the people appeared to be much affected therewith.

I have many times seen it very profitable to be deeply humbled and
awfully prostrated before the almighty Helper of his people;
that so what we are in the ministry may be by his grace only;
having observed that where the creaturely part is not wholly abased,
but some sufficiency or treasure belonging thereto is saved or reserved,
it being very close work to be stripped of all, there has been a mixture brought forth,
like the linen and woollen garment, or sowing the field with two sorts of grain;
and when any by custom, their own unwatchfulness,
or the neglect of others whose care should have been over them,
become as it were established in this mixture, they seldom get out of it the right way,
by the bad being removed and the good preserved.
Oh, it is a great thing to stand fully approved in this
solemn service! to speak as the oracles of God,
and to minister of the ability immediately given by him.
Blessed will that servant be, who when his Lord comes, is found dividing the word aright,
giving the flock and family of Christ their proper portion of meat,
and that in due season.

Having a desire to take some meetings in my way into Wales,
where I intended in order to visit my dear ancient mother, I look the following, namely,
Henley, Broomsgrove and Worcester.
I had close laborious service in them, as was often my lot where I traveled.
I spent about a week at my mother`'s,
having several large serviceable meetings among Friends,
my old neighbors and acquaintance; their hearts being tendered, and some much affected.
But alas! things are at a low ebb with our Society in those parts,
and the conduct of some rather administers cause
of stumbling than convincement to others.
I traveled to Bewdly, Stourbridge and Dudley; my brother Benjamin bearing me company,
and had good service at the said meetings, and then to Birmingham,
where I had a hard trying meeting as before.
From there to Hartshill general meeting on a first-day, which was, through divine favor,
an open good meeting.
My kind friend John Bradford bore me company to Hinkley in Leicestershire,
where we had a pretty open meeting, and then to Leicester,
where the Lord was pleased to favor us with a satisfactory meeting.
Next day I had a small meeting at Soilby, things being very low;
and at Castle-Donnington, I had two meetings on first-day;
to which many Friends from Nottingham came; they were, I believe, serviceable to many.

Next day I had a small poor meeting at Wimes-wood, then to Longclawson,
where I could perceive very little of the life of religion;
and from there to Oakham in Rutlandshire, and had a comfortable meeting;
Truth and its testimony had considerable dominion.
At Leicester Quarterly Meeting and Kettering in Northamptonshire,
I had a good degree of openness, and Truth prevailed.
At Wellingborough I attended their fore and afternoon meetings on first-day;
the first was a close exercising time in a painful silence,
and a sorrowful sense of the indifference and insensibility of many.
It was a large meeting,
and to me the greater part of those present appeared very ignorant of the
importance of that worship and service they professed to meet about.
In the afternoon I was favored with wisdom and strength to discharge my mind,
in a close searching testimony.
The next day I had a meeting to pretty good satisfaction at Ranee,
and the day following went to the Monthly Meeting at Ramsay in Huntingdonshire,
where I had good service.
Then had meetings at Ives, Godmanchester, Erith and Hadenham;
most of which were pretty open and serviceable, through divine help,
for without the Lord`'s blessing on our labors, they prove altogether fruitless,
the increase being from him alone.
I went next to Mildenhall in Suffolk,
where on a first-day I had a large meeting to good satisfaction;
then at Burry and Haverill; the last of which, being mostly people of other societies,
was open, and the testimonies of Truth appeared to be well received.
At Saffron Walden in Essex, we had a very painful afflicting meeting:
very little to be felt of the life of religion therein.
Oh! what pity it is, so many up and down,
satisfy themselves with a mere profession of Truth; only having a name to live,
when they are really dead, as to the quickenings of heavenly virtue.
At Stebbing we were favored with the opening of the living fountain;
yet there appeared to me to be some obdurate unfaithful spirits under our profession,
who seemed sorrowfully out of reach and very hard to be made sensible
of the weight and importance of our religious testimonies;
especially in some branches thereof.
Such cause a secret pain and anguish,
which covers the minds of poor travelers in the work of the Gospel,
like the sackcloth underneath.
I seldom found room and opportunity to put it wholly off,
though I was frequently favored with a comfortable evidence that the Lord was with me,
graciously owning my service for him and his people.

At Coggeshall on first-day, I had close, searching, laborious service,
and found something exceedingly heavy in that meeting; yet by divine favor,
I was carried through to a good degree of satisfaction.
The next meetings were at Kelvedon and Witham, in both which,
my testimony was very close and arousing; in order, if possible,
to awaken and stir up lukewarm, unfaithful professors;
and by the blessed efficacy of the word of life,
the wholesome doctrine of Truth was set over them,
and the few upright-hearted had relief.
I went from there to Chelmsford, where I had good open service at their week-day meeting,
and also on the first-day following: notwithstanding which,
a secret pain accompanied my mind,
occasioned by those unfaithful professors before hinted at,
who have neither courage nor fidelity to maintain any branch of our Christian testimony,
when there appears a probability of outward losses or suffering thereby:
dealing with our principles in a very lax, indifferent manner,
taking what they please and sacrificing the rest to their own selfish views;
such are as spots in our feasts of charity,
and a mournful load to the living in religion: but the Lord Almighty,
who hears the groanings of these, will in his own time grant relief;
and the others shall bear their own burdens.
At Royston in Hertfordshire, the life of religion appeared very low;
and I had nothing to minister to the people but an example of silence.
Next I had a meeting at Baldock, which was low and rather painful, then to Hitchin,
and was at their first-day meetings, which were pretty open and satisfactory;
and to Ampthill, where things appeared low.
At Hogstyend, I had some openness and satisfaction;
but the meeting at Sherington was low and painful.
The next meeting I had was at Northampton, which was a very trying time;
but the Lord by his powerful word, gave me dominion in a good degree, over dark,
libertine spirits: true religion seemed almost lost there.
At Bugrbrook I had some openness, got through my service to pretty good satisfaction,
and was at their meetings on first-day at Coventry; in one whereof,
I had close searching labor, and was silent in the other.
The meeting at Edington was small, and things but low.
I went from there to a marriage at South Newton,
and found it my place to sit the meeting in silence.
The earnest expectation of people, especially on such occasions,
I believe often obstructs the current of right ministry.
Silence, if duly considered,
may be the best lesson of instruction for those
whose life is in words or outward declarations.

I have thought some among us are so void of a right understanding,
as to suppose there is a kind of necessity for something to be done by way of ministry,
at marriages, and funerals especially;
it being hard for them to apprehend that they can be so honorably conducted without.
I have observed some who, though but little concerned,
to maintain our testimonies by a uniform, consistent deportment,
yet appear very zealous on these occasions; taking a deal of pains,
and riding many miles, and sometimes from one preacher to another,
to make themselves sure of having one;
and when they have been so successful as to prevail upon any to come,
it would no doubt be a great disappointment, were they to be wholly silent.
In this situation, the minister himself may, unless well-grounded,
be exposed to temptation to gratify such.
My principal view in this remark is,
to show how remote such are from the truth they profess,
and how nearly allied to some other professors of Christianity,
who make religion chiefly consist in outward performances,
and think it not like a Christian burial,
when a corpse is committed to the earth without something said over it.
If that over-anxiousness in the people should prevail on the preachers among us,
to answer their cravings and expectations, either in attending, or when there,
in gratifying them with words,
without a due regard to the holy weight and impressions of the Word of life,
as the alone moving cause to public service,
they would be in danger of being lost as to the living body in the Society;
and although such might continue in a consistent form of sound words and sound doctrine,
as to the external appearance, yet the substance being lost,
their performances would be no more than as sounding brass, or a tinkling cymbal.
Some, to our sorrow, have been observed to lose ground by such means:
what can we imagine more offensive to the gracious, bountiful Giver,
than to prostitute such a precious divine gift,
by making it subservient to the carnal unsanctified
desires of those who are strangers to God,
yet love to hear of him and his glorious acts, by the hearing of the ear?

From this place I went to Hooknorton, and had a meeting;
wherein my business was to example with silence; then to Sibford, where I had a meeting,
and some openness; yet things were but low.
I had open thorough service in the meetings at Banbury on first-day,
and the testimony of Truth was in a good degree exalted.
Next day I went to South Newton again, where I had great openness,
and Truth was comfortably in dominion.
Much satisfaction is received by following the
safe guidance and conduct of our holy Leader,
whether in heights or depths, sufferings or rejoicings.
I had a good meeting next day; and then went to Adderbury, where things are low.
At Bicester I had a small poor meeting; there being but very few under our profession,
and but little to be felt of the life of religion among them.

My face being now turned towards the city of London, I had a small meeting at Alesbury,
and some open service therein to my satisfaction.
There are but few Friends thereabout.
I went to their first-day meeting at Jordans, which was large:
my service was to example the people, Friends and others, with silence;
which I believe was a considerable disappointment to many;
but I hope it was profitable to some.
Several Friends from London met me there, and we got to the city next day.
I continued there about three weeks, visiting meetings diligently every day in the week,
except the last, and one more.
It was a very painful time of deep suffering in spirit, even beyond expression.
I was as a sign of silence from place to place,
especially at Grace-church street meeting; which, doubtless, was a great mystery to many.
But it was my way to peace, and I sought after contentment,
though it might occasion me to be accounted a fool,
by the lofty towering spirits in that city,
who may justly be compared to the tall cedars of Lebanon.

I left London the 19th of the tenth month, 1749,
to visit meetings at Hertford and St. Albans, where our friend Benjamin Kidd met me,
and accompanied me to Hempstead, Wickham, and the Quarterly Meeting at Oxford.
The meeting there for worship was exceedingly
disturbed and hurt by a company of rude students,
who came in like a flood, and allowed little or no stillness,
till by breaking up the meeting they dispersed; by which means,
we held the meeting for discipline and good order, in a quiet peaceable manner.
At Whitney I had a very painful exercising time,
not only under a sense of undue liberties prevailing,
but also of an exalted self-righteous, self-sufficient state; than which,
none is harder to be reached to, or made any impression upon:
my business was to sit in silent suffering with the oppressed seed.
I went next to Burford, where there seemed to me very little of the life of religion,
and to Cirencester, where my spirit was deeply distressed,
under a painful sense of wrong things and wrong spirits.
The next meeting was Nailsworth, where I had close searching labor,
in testimony against luke-warmness and undue liberties.

At the Quarterly Meeting for Wiltshire,
being a stranger and altogether unexpected by Friends there,
the close searching testimony given me to bear,
especially relating to the state of some active members, might be better received,
and have more effect,
than if the same had come from one better acquainted with their states.
I always coveted,
to be wholly unacquainted with the states of meetings by outward information,
in all my travels; and when, by the discourse of Friends previous to my attending them,
there appeared any probability of their inadvertently opening in my hearing,
any thing of that kind, I have generally either stopped them,
or walked away out of hearing.
But in general, Friends who entertain us in our travels,
have more prudence and a better guard in these respects; as indeed all ought:
for it straitens, and may give much uneasiness to right spirited ministers,
who have a sure infallible guide within,
and therefore have no need of any outward guide or information in their services.
I visited meetings in that county, at the house of John Fry, in Sutton, Cain, Chippenham,
Melkshara, Corsham, Bradford, Lavington and Salisbury, and found things mostly low,
painful and laborious to work through.
Those under our profession appeared to me, in too general a way,
to be satisfying themselves with the religion of their education only;
without much experience of the life and virtue thereof, operating upon their hearts.
Some, it is to be feared,
undertake to rule and act in the church without a proper qualification,
and so do not therein seek the honor that comes from God only.
Here the equal balance and standard is not kept to; partiality gets place;
men and women`'s persons are respected because of riches or outward substance:
true judgment is perverted, and wickedness escapes censure,
to the affecting of the whole community, as in the case of Achan.
Such things provoke the Lord to withdraw,
who is the only strength and defense of his people.
They then become languid; their hearts become as water,
and the inhabitants of the land prevail against them,
till they are in the end made desolate.

The next meetings I had were at Andover, Whitchurch, Basingstoke and Alton; having,
through divine help, some profitable service,
tending to warn and excite Friends to a more diligent and careful
discharge of the several duties their stations required:
but I could not help viewing, with some painful reflections,
the lukewarmness and declension which sorrowfully prevail in many places.
At Alton, which is a large meeting, I found some solid, weighty Friends,
to whom my spirit was nearly united; having, in the main,
good satisfaction and openness among them;
with searching close service to the unfaithful;
in which I was favored with the comfortable help of upright spirits,
whose sincere travail is maintained for an increase of faithful
laborers in the Lord`'s vineyard and the restoring of ancient beauty.

Now did my deep and painful labors in this visit begin to wear off,
and to draw towards a close, as far as related to my travels at this time,
in Great Britain and Ireland.
I therefore soon expected a full discharge, as I saw little before me,
save the city of London.
I had meetings at Godalming, Guilford and Esher, in my way there;
in which I had some service to my own satisfaction, and I hope to the help of Friends.

I continued in the city some time, visiting meetings with diligence.
My mind was deeply exercised as usual in a painful travail,
with and for the suffering Seed of God in the hearts of professors, who to me appeared,
in a general way, living, moving, acting and breathing,
in an airy exalted region above it.
I have often been ready to say, By whom shall Jacob, the true Seed, arise?
for he is very small in the esteem and regard of professors of most ranks.
Yet I could see an afflicted, suffering remnant, lie very low, as under the ruins,
and panting as it were, struggling for life.
And although we could see and knew one another,
and traveled together under a degree of the same painful sense of things; yet,
not having it in our power to relieve one another,
our proper business was to travail under our respective burdens,
until the Almighty Deliverer was pleased to appear,
calling his suffering ones to dominion and rule with him,
who is Lord of lords and King of kings:
for the Lamb and his followers shall have the victory;
though they are permitted sometimes to suffer long.
I had then, at times, faith to believe he would raise the dry bones,
and they should stand upon, their feet; an army to fight the Lord`'s battles;
to bring the mighty from their seats, and to take the crowns of some from them,
who seemed to reign as kings, making their nakedness appear.

Surely the complaint of the Lord, by the mouth of his prophet concerning Israel,
was mournfully verified in the city of London, respecting a great part of the Society,
namely, "`My people have committed two great evils;
they have forsaken me the fountain of living waters, and hewn them out cisterns,
broken cisterns, that can hold no water.`"
Such is a mere profession, though of the Truth itself, without the real possession.
This is holding the Truth in notion, speculation and imitation only.
The same may be said of whatever is done in religion, without the immediate influence,
direction and leadings of the holy Author`'s spirit and power.
Sound doctrine may be preached, as to words and the main scope thereof,
and true principles imbibed from education, tuition, or other outward means;
yet the man`'s part being alive, active and always ready; the child`'s and fool`'s state,
that knows its sufficiency for every good word and work
to be immediately received from God alone,
is neither experienced nor abode in.
"`For it is not you that speak, but the Spirit of your Father that speaks in you, or by you.`"
I say, without this living sense of things, all is but a broken cistern;
it will hold none of the water of life; which is the real cause,
that the endeavors and seeming zeal of some for the promotion of religion, are so dry,
insipid, and inefficacious.
Truth will carry its own evidence.
The spring of action being the holy Spirit of Christ,
it will gain the assent of all his children,
and answer his pure witness in the hearts of the rebellious,
far beyond what many conceive or imagine.
Upon which I would just observe, that the only way to preserve the strength, glory,
and dignity of a religious society, is for all who undertake to be active in it,
certainly to feel the Lord leading and directing them in all their services;
and on the other hand, the sure way to desolation is,
when the active members in religious things move
therein by the strength of human abilities only.
A great deal depends on that, more than some are aware of: it is observable,
that the preservation of the Jewish church in purity,
much depended upon the governors and rulers thereof; and so do and will,
the prosperity and purity of the Christian church.

I had very little openness in respect to ministry, but was silent as usual,
from meeting to meeting.
Indeed, my sufferings in spirit were great and deep, day and night, in that city,
so that I was weary of this life, and as it were, sought for death;
being at times ready to say, it is better for me to die than to live.
I much wondered why it should be so;
but have since seen it was in order for the filling up
that measure of the sufferings of Christ allotted to me,
of which I have seen the great advantage,
with respect to giving dominion over those things and spirits,
that were the cause of those great sufferings,
which could not be stood against nor overcome any other way.
For, as says the apostle,
"`If so be we suffer with Christ, we shall also reign with him.`"
And our Lord also said, "`Verily I say unto you,
that you which have followed me in the regeneration;
when the Son of man shall sit in the throne of his glory,
you also shall sit upon twelve thrones, judging the twelve tribes of Israel.`"

I have sometimes thought, as I believe it may, by the foregoing account,
appear to others that I was led in a manner somewhat uncommon,
to see and feel the sorrowful declension of our Society,
in my travels through these nations; though I am very sensible,
several faithful brethren have shared in the like painful travail; which, in some degree,
may be compared with that of Nehemiah; who, under great anxiety and distress of mind,
entered upon a long and hazardous journey,
and went in the night to view the breaches and
desolations made in the city of the great king,
before he and the people arose in the name of the Lord,
to build the walls of that city and to set up the gates thereof.
He found the hand of the Lord upon him,
moving and strengthening him to seek the good and prosperity of his own people.

These things are written for encouragement and
instruction to the painful laborers in the Lord`'s work;
that they faint not under the weight and exercise thereof;
nor think strange concerning such fiery baptisms and trials as
they may meet with in the course of their travels.
They may be well assured, that such things are all directed in wisdom; which,
in the Lord`'s time, will appear to their full satisfaction and comfort.
For it is far from the Fountain of infinite kindness,
to permit such heavy affliction to fall upon his servants unnecessarily.

I went from London into Essex, in order to visit some meetings in that county,
which I had not been at before, and was at Chelmsford week-day meeting on fifth-day,
where I had good satisfaction; the virtue of Truth being shed abroad,
to the joy and comfort of the living.
On the first-day following, I was at Colchester meetings.
My mind was painfully depressed,
under a sense that Truth suffered much in that place by wrong things.
Where evil is winked at,
and undue liberties in a religious society are allowed to escape judgment or censure,
weakness, and as it were a cloud of darkness come over meetings as well as individuals.
The Lord was graciously pleased for his blessed name`'s-sake, to arise,
and in some good degree, to dispel the darkness; whereby Truth and the testimony thereof,
was exalted over all corrupt unsanctified spirits;
and the few upright-hearted were sweetly comforted;
it being a time of relief to their spirits, in a good degree.

I went from there to meetings at Copford, Coin, Halstead and Braintree,
wherein I had thorough service, in plain dealing and close labor with the unfaithful,
of which number there seemed to be many;
and but few who had really bought the blessed Truth.
It is such only, who know how precious and valuable it is,
and who cannot easily be prevailed upon to sell it for a thing of naught,
nor for any consideration whatever.
But it is not so with those who have their religion, if it may be so called,
by education only, or derived by way of inheritance like their outward possessions,
from their ancestors.
The principles of religion only thus received and held,
are often subjected to temporal conveniency and worldly interest.
Where the world and true religion stand in competition with each other,
such professors will soon give place to the world;
wherein they do really deny Christ before men, and will as certainly, unless they repent,
be denied by him before the Father and his holy angels.

I returned out of Essex to London;
for though I had had but little openness as to ministry there,
yet I found my mind engaged to attend their meetings, as I apprehended,
in order to suffer and travail with the true Seed, for its enlargement,
as well as to be a sign and example of the important duty of silence,
to the professors of Truth.
They had been long and greatly favored with living testimonies, even line upon line,
and precept upon precept; under all which,
for lack of a proper application and improvement thereby, the Society declined,
and the ancient beauty thereof greatly faded away; I mean,
in what relates to the life and spirit of religion in the practical part thereof;
for the body of the Society everywhere, as far as ever appeared to me,
are remarkably one in faith and profession,
the same which has been held and professed by us as a people, from the beginning.
This wonderful oneness and agreement among us everywhere, which I have not observed,
neither do I believe it is to be found among any other set of Christians,
to that degree, is to me a clear evidence, that the original foundation thereof,
was the one infallible Spirit of Jesus Christ our Lord, who prayed the Father,
that his followers might be one, as the Father and the Son are one.
And notwithstanding great numbers in our Society
are resting satisfied with an empty profession,
and by their unfaithfulness,
fall greatly short of the dignity our worthy predecessors attained unto; which,
considering the abundant favors bestowed from time to time,
for the help and preservation of the Society,
is cause of deep mourning and sore lamentation; yet there has been,
through the kind providence of God, from the beginning down to this time, a living body,
preserved the same in faith and practice with our ancients.
These are scattered and interspersed throughout the whole Society, like the salt thereof,
in order, if possible, that all may be seasoned.
I think there are very few, if any meetings, wholly destitute of some of that sort;
so that I would not have it understood, by the foregoing mournful complaints,
although there may be just cause for them, that I think the Society is become desolate,
or that the glory is departed therefrom: far be that from me;
I am fully convinced to the contrary, and at times have faith to believe,
the glory will never wholly depart, nor shall we cease to be a living people:
yet I believe, numbers under our profession,
for their great unfaithfulness and unfruitfulness, will be blowed upon by the Lord,
and rejected, and others called into the vineyard,
who will be more diligent and faithful.

After I had continued some time in the city,
I apprehended myself nearly clear of further service at this time in these nations,
and that I might with safety look out for an opportunity of
returning to my outward habitation in America.
I therefore applied to the brethren for a certificate of my travels, etc.,
which they readily granted;
setting forth their unity with my services and demeanor under this weighty engagement.
But as no suitable opportunity appeared likely to present for some time,
I had leisure to look into and carefully to weigh an affair of great importance,
which had by this time so far prevailed on my attention,
that I was afraid wholly to reject it,
as I had done for a considerable time after it first came into my thoughts;
looking upon it almost impracticable.
This was, entering into a married state with my endeared friend Frances Wyatt,
before mentioned.
I never had any other objection to it, than our both being,
as far as appeared then to me, settled in oar places;
from which I thought it would be very unsafe, without the best counsel, to remove.
But that objection was wholly removed, by my way opening, as I thought,
with great clearness, to settle in England on account of my future service.
I was deeply concerned in my mind to be rightly guided herein;
which was answered so indisputably clear to my understanding,
that I could no longer hesitate about it.

The next thing was, settling matters relative thereto with my said friend; that so,
if she found no objection, our marriage might be accomplished, if Providence permitted,
after my returning home, settling my affairs there,
and removing in order to settle in this nation.
I therefore laid the whole before her, desiring her solid consideration and an answer,
when she was prepared to return me one.
I found the same powerful hand which had removed my objections,
was at work in her mind to remove hers also;
so that she could not be easy to put a negative upon the proposal,
as believing the thing was right, which was still confirming to me.
We therefore in the fear, and as we had cause to believe, in the counsel of God,
engaged with each other to accomplish our marriage,
when way should be made by divine Providence for the same.
We had no views on either side for worldly advancement;
as I was fully persuaded we were directed in our said engagement,
by the wisdom and counsel of Him,
who can give or take away outward blessings at his pleasure.
I therefore had not freedom, previous to my engaging with her therein,
to make any inquiry into her circumstances in the world.
All which, however,
with the superior blessing of an affectionate wife and true help-mate,
I afterwards found agreeable and comfortable.

Having as above, paved the way to remove and settle in England,
and a good opportunity presenting of a ship,
in which several valuable Friends intended to embark, I went on board the Speedwell,
John Stevenson master, at Gravesend, the 8th of the third month, 1750,
in company with our friends Jonah Thompson and Mary Weston,
who were going on a religious visit to the churches in America.
We had fourteen or fifteen passengers belonging to the cabin and state rooms;
some of whom were bad people, whose conversation proved very disagreeable to us;
so that we spent much of our time on the deck, night and day,
except when we took our rest in sleep.
Our departure was from the Start Point, the 11th in the evening,
being the last land seen by us until we discovered America.
We had a fine gale of wind down the English channel,
and a good set off to sea by the same;
but we often had scant and sometimes contrary winds afterwards,
which made it rather a slow passage, though much quicker than some have gone.
The 17th of the fourth month, we found ourselves on the banks of Newfoundland,
and in the midst of nearly twenty sail of French ships, who were fishing for cod.
We spoke with one of them, who told us we had about twenty-five fathom water;
whereupon the captain ordered the ship to be brought to,
that we might take some fresh cod.
This was very agreeable to us all; and succeeded so well, that in about two hours,
there lay upon the deck twenty-four of the finest cod fish I ever saw.
This proved an agreeable feast to us for about one week; and although through mercy,
we had very great plenty of provisions, yet this was an acceptable change.

It was the 5th of fifth month, about three o`'clock in the afternoon,
when to our great joy we saw the land of America; and by sounding,
found ourselves in about twenty-five fathom water,
and entered the capes of Delaware that night.
We had a prosperous gale up the bay and river,
so that I landed at Chester in Pennsylvania, about eight miles from my own house,
on the 7th of the fifth month, about three o`'clock in the afternoon,
and got home that night; having been on board two months lacking one day,
and from home in the whole journey, two years, seven months and eight days;
having traveled in that time by sea and land, I think on a moderate calculation,
eleven thousand eight hundred and seventy-five miles,
and was at about five hundred and sixty meetings.
