== Chapter 6

[.chapter-synopsis]
* Returns to England to settle second marriage
* Labors for a reformation in discipline
* Attends the circular Yearly Meeting at Broomsgrove, and meetings in Wales, etc.
* Visits Friends in Yorkshire, Lancashire, Westmoreland, etc.

I had before concluded, with divine permission, to return in the same ship,
and left a large chest of stores on board.
When discharged of her loading, she was to sail for Maryland,
there to take in a cargo of tobacco, where I intended meeting her;
it being about seventy miles from my house.

In a day or two after my arrival I went to Philadelphia,
where I found my friends generally much alarmed,
with news brought by letters in the ship I came over in,
(for they had not heard it before) of my intention to return,
to marry and settle in England.
Many, I believe, being ignorant of the grounds and motives upon which I acted therein,
judged concerning the same from the outward appearance only;
supposing that having found one I liked, I had let my mind out towards marrying,
and made that the principal inducement of my removing.
Had this been the case, I freely acknowledge that I should have deserved blame;
as acting upon a very dangerous bottom to myself,
and setting an unsafe example for others to follow;
believing some have sustained great loss, by inadvertent steps of this kind,
in their travels on Truth`'s account.
This was what I greatly feared in relation to myself, and therefore, as before hinted,
dared not give way to the thoughts of entangling myself therein, until I had repeatedly,
as I thought at least,
received clear evidence in my mind of its being my duty
to remove into this nation for future service.
I do therefore earnestly caution all,
to be aware of taking any encouragement from my example herein,
unless they have the same evidence, and act upon the same bottom that I did,
agreeably to what is above mentioned, and are well assured of divine direction.
That I was rightly guided in my removal,
has not only been fully confirmed to myself since, but I am persuaded also,
to many others: and even at that time,
those who were free enough to confer with me thereon, appeared to be well satisfied,
whom for their freedom and openness to me on that account,
I looked upon to be some of my best friends; and as to others,
I thought it my duty to bear with patience and meekness
all they were pleased to say and conjecture,
until time made manifest who were in the right.

I attended the Yearly Meeting held at Burlington, for Pennsylvania and the Jerseys,
in the seventh month,
wherein the Lord was graciously pleased to overshadow our
large assemblies with his heavenly power and presence,
to our great comfort and edification;
having with joy to draw water out of the wells of salvation,
and to offer the praise and humble thanksgiving to the alone fountain thereof,
who is forever worthy.

Having settled my affairs,
and obtained a certificate of removal from the Monthly Meeting of Darby,
in Chester county, in Pennsylvania, to which I belonged,
directed to the Monthly Meeting of Witham in Essex, old England;
myself and daughter set out from my house in Darby, accompanied by my sister Mary,
(who since my wife`'s decease, had been my careful house-keeper)
together with several Friends, the 12th of the eighth month, 1750.
We traveled to East Nottingham,
being about sixteen miles from the place where
the ship lay in which I intended to embark.
My sister and one of the Friends stayed with us about a week,
and then took their solemn leave.
My daughter and I stayed there until the 2nd of the ninth month.
I visited some meetings in the neighborhood to good satisfaction,
and was at many in East Nottingham, it being a very large meeting,
and a zealous body of Friends then belonged thereto;
among whom I had good service and great openness;
the precious unity of the one spirit being livingly enjoyed,
in which we took a solemn farewell of one another.
The 2nd of the ninth month we set out, accompanied by several of our worthy friends,
and crossed the Susquehanna,
taking our quarters at Jacob Giles`'s house within sight of the ship;
but were not ordered on board until the 8th. We did not sail until the 11th at noon.
The unskillful pilot ran us aground twice that afternoon,
and caused the poor sailors hard labor and much fatigue, for which I was sorry.
It was the 18th, about two o`'clock in the afternoon,
before we got clear of Chesapeak bay; and having then a fine wind,
we soon lost sight of land.

We had been at sea but about four days, when he espied a sail or two, who,
by their motions, appeared very desirous to speak with us, which, at length,
one of them belonging to Rhode Island effected, informing us,
they were reduced to a very small quantity of provisions,
and earnestly intreated the master to afford them some assistance.
To my grief and surprise, he gave them a very short denial;
alledging we were but newly come out to sea,
and did not yet know what we might lack ourselves.
I was much troubled in my mind at the hardness of his heart,
and immediately stepped up to him, and in as moving language as I was capable of,
interceded for the poor sufferers.
The first mate being a man of a good disposition, joined with me,
and we at length so prevailed on the master,
that he gave them liberty to hoist out their boat, and come on board;
telling them he would see what could be done for them.
The poor creatures gladly complied with this;
the master of the ship and four of his sailors, being quickly on board of us.
It was very affecting, to behold the need so conspicuous in their faces,
and to see how greatly they rejoiced, with thankfulness, that kind Providence had,
in mercy, cast us in their way, for their relief;
in which I could heartily join with them;
rejoicing that we had not inhumanly turned them off without help.
The master, to give him his due, handed to them pretty liberally;
for which he charged what he thought proper, and took the master`'s draft for the money,
on his owner in London, I spared them some out of my private stores,
for which I wanted no other pay, than the satisfaction of relieving their wants;
being very glad I had been instrumental thereto.

The next day we had a great storm, and an exceedingly high sea,
so that we could carry no sail,
but fastened the helm and let the ship drive
whithersoever the wind and waves would carry her:
we were indeed mightily tossed; but through divine favor,
my mind was sweetly calm and comfortable, feeling his living presence to be near,
who is God of the seas and of the dry land.
My heart was filled with the joy of his salvation,
so that I could sing and make melody therein to him; in which I had confirming evidence,
as I many times had under the same precious enjoyment,
both by sea and land after I left England,
that my way and undertaking was approved of the Lord,
and would be blessed and prospered by him; which yielded more comfort to my mind,
than any thing in this world could do.
The severest part of the storm lasted about twelve hours;
and although we had two considerable storms afterwards, yet for the most part,
it was a good passage.

On the 17th of the tenth month, in the morning, we sounded,
and in sixty-nine fathom water we found ground.
The same morning, about ten o`'clock, we had the very agreeable sight of England.
Next day, the wind being against us, we made but little advantage of sailing.
The 19th, about eight o`'clock at night, we came to an anchor in Falmouth harbor.
Going on shore next day, we went to an inn in the town.
Our kind hospitable friend, Joseph Tregelles, came and invited us to his house,
where we had generous entertainment while we where at that place.
I was several times at their meetings, both at Falmouth and Penryn,
and had openness and good satisfaction.
My worthy friends of that town, Andrew Hingeston and his wife and daughter,
were affectionately kind to me, which I cannot well avoid mentioning,
out of a grateful sense I retain thereof, as we were entire strangers;
for I had not been that way when in England before.

Having been detained there about a week, we put out to sea again,
in order to proceed to London, where we were bound.
The second day of our being out, towards evening,
as we were sailing within about a league and a half of Dover,
a boat came on board for letters.
The wind then not being fair to go up the river Thames, we went with them to Dover,
and next day to Gravesend, where crossing the water at Grays in Essex,
I proceeded to Chelmsford.

My dear friend Frances Wyatt and I,
after proceeding according to the good order of Friends,
accomplished our marriage with each other,
at a large meeting of Friends and others in Chelmsford meeting-house,
the 14th day of the then first month, 1750-1,
in the sweet and sensible enjoyment of his presence, who saw in the beginning,
it was not good for man to be alone; and therefore, in great kindness,
provided a help-mate to be with him, who was bone of his bone, and flesh of his flesh.
It is therefore said, they shall be no more twain, but one flesh.
The Lord then joined the man and his wife together.
Happy would it have been for mankind, had they never sought,
nor found out any other way of joining in that relation since.
But as the sons, or worshippers of the true God,
formerly looked upon the daughters of men,
with an eye that tends to pervert this ordinance,
following the dictates of their own evil heart, instead of the counsel of God,
in this great undertaking; so it is evidently the case at this day with many.
It is also often not so much what the woman or man is,
as what worldly substance they have.
Where there is plenty of that, many real defects,
with respect to those qualifications and endowments
essential to real happiness in a married state,
are over-looked.
Thus, by man`'s ignorantly and presumptuously taking
upon him the guidance and government of himself,
instigated thereto by the subtlety of Satan; those outward accommodations,
which were by divine providence intended as blessings, become quite the reverse.
To prevent such unhappy consequences to young people and others,
I know of no advice better adapted for their safety and preservation,
than that of our Lord`'s, namely, "`Seek you first the kingdom of God,
and his righteousness, and all these things shall be added unto you.`"
Those who have happily, by seeking, found this kingdom, and live therein,
which consists in righteousness, peace and joy in the Holy Ghost, have great advantage,
even in outward things, above all others; as the blessing of God, which makes truly rich,
attends all their worldly affairs.
They enjoy what appertains to this life with a proper relish.
"`Blessed are the meek, for they shall inherit the earth.`"

As it is man`'s duty and safety to seek the Lord`'s counsel and blessing,
so it is truly honorable among men; for this,
Jabez was said to be more honorable than his brethren;
for he called on the God of Israel, saying, "`O that you would bless me indeed,
and enlarge my coast, and that your hand might be with me,
and that you would keep me from evil, that it may not grieve me!`"
And God granted him that which he requested.
Let me conclude this observation with tender
advice and caution to all whom it may concern,
into whose hands this may come,
to be aware they do not fall into that dangerous snare of supposing,
as marriage is an outward affair,
they need consult nothing further therein than their own inclination and reason;
it is said,
"`Woe to the rebellious children, that ask counsel, but not of me, says the Lord.`"
And Christ is called Wonderful, Counsellor, as well as Mighty God.
Now as marriage is allowed to be the most important affair in this life,
and may tend greatly either to promote our happiness or misery in the next;
if we have no occasion to seek the Lord`'s counsel herein,
in what are we to expect or desire it?
Abraham`'s servant,
when he was only engaged about procuring a wife for his younger master Isaac,
with great earnestness sought the Lord`'s guidance and blessing therein,
and obtained it in a remarkable manner.
What, say some, are we to look for, or to expect a revelation in such cases?
We must desire the Lord to guide and direct our steps in this,
and all other affairs of consequence in relation to this life,
or we shall certainly miss our way.
But this we cannot clearly understand, until the man`'s part is reduced in us,
and we see what we are without God, that we may find occasion to pray without ceasing,
and in everything to give thanks.
Then the constant cry will be, Guide me with your counsel.
When this is, with great sincerity, the state of the mind, we cannot miss our way;
because divine protection is ever present, although we do not always see it,
no more than the prophet`'s servant did, until his eyes were opened.
The great thing is, to have a single eye, that whatever we do,
may be done to the glory of God.
When this is the case, we say, if this or that be not agreeable to your will, O God,
you have all power in your hand; do you, by your overruling providence,
direct me according to your blessed will.
The Lord will keep such in all their ways, and be their sure defense.

We settled together after marriage, at Chelmsford, in the county of Essex,
where I enjoyed great satisfaction and comfort in an affectionate wife.
Yet such I found the low and almost desolate situation of our Society in the said county;
especially in relation to good order and that discipline established among us,
by the power and in the wisdom of Truth,
as a hedge to defend and preserve from hurtful things,
that it gave me much painful concern of mind.
The difference appearing so very great,
as I had before resided where discipline in the general was well maintained.
I could not discover, either by their books or inquiry,
that the unfaithful or disorderly walkers had, a few instances excepted,
been for many years regularly dealt with, and their misconduct censured,
either by Monthly or Quarterly Meetings.
I diligently attended those meetings, but my spirit was greatly distressed therein,
as the members seemed to move and act in another element, as I may say,
than that I had been accustomed to, in managing the weighty affairs of the church.

The first thing of importance that laid hold of my mind, as wanting to be reformed,
was relating to women`'s meetings; there being no such held quarterly,
and at but few of the Monthly Meetings;
and where there was any thing of that nature it was of little or no service,
in the manner then held.
Having therefore the advices and directions of the Yearly Meeting,
relating to women`'s meetings,
I requested liberty of the Quarterly Meeting to read the same therein, which I did,
making such remarks thereon, as appeared to me then necessary.
At the same time, I proposed that the meeting should take that weighty affair,
of establishing women`'s Quarterly and Monthly Meetings,
agreeably to the repeated pressing advices of the Yearly Meeting,
into solid consideration; and if it was thought proper,
that a few Friends might be appointed to form some general
directions for the assistance of our women Friends,
pointing out to them, as for lack of opportunity,
they were pretty much strangers thereunto, how such meetings are to be conducted,
and the part of church discipline that properly comes under their notice,
and requires the management of the women.
All which was agreed to and minuted.
The proposed directions were prepared by the Friends appointed,
brought to the next Quarterly Meeting, and there agreed to.
The women having previous notice,
withdrew at the close of the meeting of worship into an apartment,
to receive what we had to lay before them, and unanimously agreed thereunto.

A Quarterly Meeting of women Friends being then established,
pressing advice was sent by minute, to Monthly Meetings,
that they should encourage and establish women`'s meetings among them also,
which was complied with.
And although our women Friends,
for lack of being brought up by their ancestors in the management of the discipline,
might be rather inexperienced at first, yet I am well assured,
this step tended much to enlarge our meetings and to make them more lively;
opening the way of sincere travelers to a fuller enjoyment of spiritual good,
wherein alone is our ability for every good word and work.
Some few, from a right sense of the importance of the work,
joined me in an earnest labor for a general reformation,
and as we felt the weight of things upon our minds, we gave up to visit Monthly Meetings,
to help the weak and to move forward the wheels of discipline, which,
especially at the first, moved very heavily;
for although we had many in the county under our profession,
yet few of them had their hands clean enough to handle the affairs of the church;
many being, as it were, crippled with unfaithfulness,
especially in their mean and cowardly compliance with the
anti-christian demand of tithes and things of that nature,
which of itself unfits for service among us; for I never saw much, if any,
true living zeal for the cause of God, in those who have fallen into this defection.
Oh! the darkness and cause of stumbling it has occasioned in this poor county,
and in other places where it has prevailed.
We found ourselves concerned, repeatedly to visit such in their families,
laboring in Christian love,
to bring them into a sense of the inconsistency
of their conduct with their profession therein;
which labor, though prevalent with some, has been no otherwise successful in general,
than the discharge of that duty which one member
of a religious community owes to another;
and by bringing the judgment of Truth in some degree over them,
they became more distinguished from the faithful.

We had great peace in this labor, though hard and unpleasant,
as we found them dark and difficult to be reached to, a few excepted.
However, these endeavors greatly tended to exalt Truth`'s testimony,
for which our worthy predecessors deeply suffered.
In process of time, through the blessed assistance of our holy Head,
engaging a small remnant to labor in the Monthly
and Quarterly Meetings for a reformation,
good order has been much promoted, and our Christian discipline in its several branches,
has been in a good degree put in practice;
and some came to understand that it is necessary to receive wisdom and strength from God,
for maintaining that work.
So that, although things in that respect,
through the unsoundness and lukewarmness of many professors, are now low,
yet the Lord continues to be gracious,
in affording us the blessed assistance of his holy Spirit,
both in our meetings for divine worship and those for discipline;
whereby some are enabled in meekness to labor for maintaining his cause,
notwithstanding the discouragement they meet with,
not only from a view of the languid state of the Society in general,
but also from the brittle jealous spirits of some.

Having labored in our own county, according to ability received of God,
for without his divine assistance, I have, by long experience, known I could do nothing,
I attended the sittings of the Yearly Meeting in London as they fell in course,
therein to join with the sincere travelers for Zion`'s prosperity,
in the important care of Truth`'s affairs throughout the world;
this weighty engagement coming more upon some of us than heretofore,
as many of the elders and faithful laborers were removed to their rest.
Our valuable friends John Churchman and William Brown from Pennsylvania,
were at several of the first Yearly Meetings after my settling in this nation.
They labored in these nations in the service of Truth nearly four years,
having left affectionate wives and children for Truth`'s sake.
Such noble disinterested endeavors, without any view towards temporal interest,
are a very great mystery to the worldly wise.
The above named Friends were great and good instruments in the Lord`'s hand,
not only at the Yearly Meetings, but also in their travels up and down,
for the promotion of discipline and good order in the churches;
though not without considerable opposition from some, who,
under pretense of acting for the good of the Society,
were in reality advocates for undue liberty.

Notwithstanding some such difficulties,
the Lord has greatly strengthened the hands of his pained ones for Zion`'s welfare,
and blessed his work to the promoting of good order,
as the likeliest means of reviving ancient beauty and comeliness;
there having been great stirrings and much labor of late years,
to bring the several members of the Society into the holy order of the Gospel.
May the Lord yet continue the blessing of wisdom and strength,
that the work may be carried on,
to the praise of his worthy name and the preservation of his people,
is the earnest prayer of my soul.

I set out the 16th of the sixth month, 1751,
intending to take some meetings in my way to the
circular Yearly Meeting for the western counties,
to be held at Broomsgrove in Worcestershire,
and from there to visit the meetings of Friends in Wales.
I first went to the burial of a Friend at Stebbing, and proceeded through Walden,
Cambridge and Huntington, to Wellingborough in Northamptonshire;
and attended both their meetings on a first-day; having close earnest labor,
in a sense of great dulness, and much insensibility prevailing on many professors.
My spirit was greatly burdened therewith;
but the Lord was pleased to arise and dispel the darkness in a good degree,
giving me thorough service, especially in the afternoon;
I hope not easily to be forgotten.
I went away greatly relieved, and had a meeting at Coventry,
which was heavy and laborious, though I was, through divine favor,
enabled to wade through to my own ease, in a good degree.

I had a good open meeting that evening at Nun-Eaton;
there being but one family of Friends in the town,
but a large number of others were at the meeting;
several of whom seemed affected with the testimony of Truth.
I had a close exercising meeting the next day at Atherstone, where things were very low,
yet Truth arose and opened doctrine for their help; and that evening one at Polesworth,
which was open and comfortable.

From there I went to Woolverhampton, where I had a small meeting, things being very low.
At Colebrookdale meeting, I had close thorough service,
tending to stir up Friends to diligence, as well as to encourage the upright-hearted;
then to Shrewsbury, where the number of professors was very small,
and the life of religion very much depressed, not only by the lukewarmness of some,
but also by a blasting, lifeless ministry, which they had long sat under; doubtless,
to the great uneasiness of the few sensible among them.
I had a painful sense of the great hurt thereof in that meeting,
being concerned to sit the meeting in silence, I believe, as an example to Friends,
and rebuke to that forward unsanctified spirit:
the same soon after was made manifest both to Friends and others to be very corrupt,
and was deservedly testified against by the Monthly Meeting.

I have several times, in my travels, perceived great hurt to the prosperity of Truth,
by such unsanctified pretenders to a divine commission,
intruding themselves into the ministry;
but always have apprehended them a bad sort of people to deal with by advice and caution,
as they are commonly very positive and self-willed; being seldom,
in this declined state of the church, without a party,
who had rather have almost any kind of ministry than silence.
This makes it much more difficult for those, who have a right sense of their spirits,
to bring the judgment of Truth over such;
as those above-mentioned are apt to screen them, and cover their heads,
unless they manifest themselves, which has frequently happened,
by their being guilty of some immoral conduct.

I went after meeting to visit two Friends,
who had been imprisoned a considerable time for refusing to pay tithes.
As soon as I had entered the place of their confinement,
I sensibly felt that the Son of peace was there.
My mind was brought into great nearness, unity,
and Christian sympathy with them in their suffering state,
which they appeared to bear with cheerfulness and resignation to the divine will.
The sense of the great importance of the testimony they were concerned to maintain,
by suffering for it, and what our worthy predecessors went through,
in nasty stinking prisons and dungeons,
where many of them ended their days in support thereof,
who may be very justly numbered among the faithful martyrs of Jesus Christ,
overcame my mind with tenderness to that degree,
that I could not presently discourse with them about their sufferings.
We had a blessed opportunity together, and took our leave of each other,
in the sweet enjoyment of the pure love of God.
Oh, how much more joyous and refreshing it is to visit such faithful sufferers,
than to visit carnal professors of the same Truth, who violate that precious testimony,
by voluntarily putting into the priests`' mouths,
lest they should prepare war against them,
making religion bow down to their supposed temporal interest,
thereby not only declaring themselves mere pretenders thereto,
but also increasing the sufferings of those
under the same profession who dare not temporize!

I returned to Colebrookdale, where I had a hard trying meeting held in silence;
and went to Birmingham, where I had been several times before,
and generally had painful laborious meetings;
but now it pleased divine Goodness to favor with openness and good authority,
to declare the Truth largely, I believe to the stirring up of the careless,
at least to a present sense of their duties;
as well as to the comfort and edification of the honest-hearted,
and to my own peace and relief.

From this place I went to Broomsgrove, in order to attend the Yearly Meeting,
which began on first-day, the 1st of the seventh month, being held in a barn,
fitted up by Friends for that purpose: it ended the third day following;
many ministering Friends attended it,
some of whom were largely opened by the power and wisdom of Truth,
to publish the Gospel tidings with clearness and good demonstration.
The people, though numerous, being generally very still and attentive,
appeared to receive the testimony of Truth with pleasure,
and things were in the main well conducted.
Here my friend John Bradford joined me as a companion.
We had a large meeting at Worcester on fourth-day,
in which Truth had comfortable dominion, especially near the conclusion,
to the great satisfaction and joy of many hearts.
Blessed be the Lord our God, for his continued favors to his people!
On fifth-day we had a small poor meeting at Broomyard in Herefordshire;
things being very low in that place, as respects Truth and Friends.
On sixth-day we had a meeting at Leominster; the forepart was very cloudy and painful,
yet by the gracious springing up of light and life,
I got through my service therein to good satisfaction.
The next day, being the seventh of the week, I went to my dear mother`'s in Radnorshire.
On first-day, the neighbors being apprized of my being come,
flocked to the Pales meeting in abundance.
The Lord was pleased to favor me with a large open time,
to declare his everlasting Truth among them,
with which they appeared to be much affected.
I had another such opportunity with Friends and many others, at Talcoyd,
near my mother`'s house.
They seemed greatly affected with the virtue of Truth;
but I fear they stumble at the cross.
On second-day we had a meeting at a place called the Coom,
about six miles from my mother`'s, pretty open and comfortable.
On fourth-day, the 11th, I took leave of my worthy affectionate mother,
relations and Friends thereabout,
having my brother Benjamin for our guide over the bleak mountains into Cardiganshire.
The wind blew hard and it rained, but through mercy we received very little harm.

Next day we had a small poor meeting at one Evans`'s.
Religion was at a very low ebb in that place,
and my chief business, as far as I could see, was to detect a vile impostor, who had,
by a feigned and hypocritical show,
got the advantage of the weakness and credulity of Friends there.
I never had seen him before, that I know of,
but my spirit was exceedingly burdened with his deceitful
groanings and feigned agitation in the meeting,
and was satisfied his spirit was very foul and corrupt,
as it was like a nuisance to me all the time.
I warned Friends to be aware of him, and to keep him at a distance;
but they seemed willing to hope that there was some good in him,
as he appeared so much concerned in meetings.
I saw whereabout they were who pleaded thus, as they seemed taken with,
and rather to approve of, what was so very offensive and even odious to me, namely,
his pretended exercise in that meeting.
But if people will lay hold suddenly on such, they must partake with them in their sins;
for this man afterward discovered himself to be very bad,
by being guilty of gross wickedness.
I think the meeting was held in silence.

We went to a place called Penbank in Carmarthenshire,
where a meeting was held next day to pretty good satisfaction,
being favored with matter and utterance for their help, though things appeared low;
in the evening I had a very poor afflicting meeting at Penplace;
where great slackness and weakness appeared in the few professors.
We were quite silent as to public ministry.
We went from there to Carmarthen, and attended their meetings on first-day;
and had good open service therein, especially in the afternoon,
many of the neighbors coming in:
the testimony of Truth went forth freely and largely among them,
with which they appeared to be much reached and affected; and might, I hope,
tend to remove a prejudice they had imbibed, from the misconduct of one or more,
of high pretensions lately in that place, but then removed.

We had a meeting on second-day in the evening, at Laugharn, where very few,
if any properly of our Society, resided; many of the neighbors came in,
and we had a good opportunity among them, in the free extendings of Gospel love;
the doctrine whereof seemed to have a considerable reach upon them.
On third-day we had a meeting among a few professors at Jamestown.
It being their harvest time, they seemed more concerned about their corn than religion;
several rushing out in a disorderly manner, to take care of that,
as there was some appearance of rain.

It was with much difficulty we procured a guide to Haverfordwest.
At length we prevailed on a young woman to go,
who seemed to have the most lively sense of religion of any among them.
Having a large ferry to cross over Milford Haven, we were so hindered,
as not to reach the place, until about an hour after the time appointed for the meeting,
to our great uneasiness.
This meeting was, for the most part, held in silence; yet near the conclusion,
I had some things given me to deliver, with considerable weight and Gospel authority.
I went next to Redstone, where the meeting was small, yet open and comfortable;
then to Carmarthen, and next day to Swansey, about thirty miles,
being a very rough open road; and the day very stormy, so that we were exceedingly wet.
Great care was taken of us, when we got to our friend Paul Bevan`'s house, so that,
through mercy, we received but very little harm.

On first-day, being the 22nd, we attended their meetings;
that in the forenoon was held in silent labor.
In the afternoon I had a close searching testimony to bear,
tending to stir up and arouse Friends to more zeal and fervour of mind;
and was favored to get through to satisfaction.

On third-day we had a poor small meeting among a few Friends at Freeveraque.
I had nothing to administer, but an example of silence.
We went after meeting to Pontypool, and next day had a precious open meeting;
the testimony of Truth went forth with good authority and clearness,
and the upright in heart were sweetly comforted in the enjoyment of the Lord`'s presence,
returning him the praise, who is worthy forever!

On sixth-day, the 27th, we crossed the Severn at the New-Passage,
and went that night to the widow Young`'s at Earthcott;
had a hard trying meeting there next day; after which we went to Bristol,
and on first-day, the 29th, attended three meetings there;
the first two were held in painful distressing silence, and the last also,
except a few words near the breaking up of it.
This was the first of my visiting that city, and a time not easily to be forgotten by me.
It was indeed a season of sore mourning and lamentation,
in a sense of their great declension.
There was very little to be seen or felt of that plainness, pure simplicity,
humility and contempt of the world, so conspicuous in their worthy predecessors,
who trampled upon the glory of this world, counting it as dross and dung,
in comparison of the smiles of the Lord`'s countenance and
being clothed with the beautiful garment of his salvation.
Oh, how was the choicest vine planted, made to spread and mightily to prosper,
through great suffering and persecution, in that city, in early times; sufficiently,
one would think, to have deeply established the permanency thereof,
and to have recommended its superior dignity and excellency to many generations!
May not that of the apostle to the Galatians, be justly applied to them?
"`O foolish Galatians! who has bewitched you, that you should not obey the Truth;
before whose eyes Jesus Christ has been evidently set forth, crucified among you?
Are you so foolish, having begun in the spirit, are you now made perfect by the flesh?`"

I parted with my companion at Bristol, and turned my face homewards,
taking meetings in my way to London, at Frenchay, Corsham, Chippenham, Cain and Reading;
in all which I had considerable openness, largely and with good authority,
to publish the doctrine of Truth, to my own peace,
and I hope to the comfort and help of many;
though in some places my spirit was much pained with a
sense of the prevailing indifference and lukewarmness,
in this day of ease and outward plenty.

On seventh-day, the 5th of the eighth month, I got to London,
and stayed their meetings on first-day.
After which I returned home, and found my dear wife and family well,
to our mutual comfort; being thankful to the kind hand of Providence,
whose goodness attends those who trust in him, both in heights and depths;
taking care of their bodies,
souls and those outward benefits he has bountifully favored them with;
affording real comfort therein, with his blessing, which makes truly rich,
and adds no sorrow with it.
I was out on this journey about eight weeks,
and traveled about seven hundred and forty miles, having been at about forty meetings.

I have preserved very little or no account of short
journeys and services in this and the adjacent counties;
in which, however, I was several times engaged to labor,
both at Quarterly and other meetings, for reviving ancient zeal and diligence.
But alas! the inordinate love of worldly enjoyments, good in themselves,
covers the minds of many professors, like thick clay,
who are exceedingly hard to be made sensible of the chiefest good,
so that I have often feared some of them will not hear,
until the Lord is provoked to speak with a louder voice in judgment,
from which they will not be able to turn aside or in any way to shun.
Many in our Society, as in others, having departed from the life,
rest satisfied in a profession of religion:
some also have departed from the power and form too, in a great degree;
appearing neither one thing nor another.
Could they see themselves as judicious persons see them,
shame and confusion of face would cover them.

The next considerable journey I have any account of,
was entered upon the 27th of the eighth month, 1753,
in order to visit Friends in some parts of Yorkshire, Lancashire, Westmoreland, etc.
I met some Friends at Walden,
who with myself were appointed by the Quarterly Meeting
to visit that Monthly Meeting for its help.
I was largely opened in the meeting of worship, to set forth the beauty,
order and excellent harmony of the several members in the church of Christ;
and Truth had considerable dominion therein, to our great comfort.
This prepared our minds for close and painful labor
with wrong spirits in the meeting of business,
who had the boldness to plead that the payment of tithes was justifiable,
because required by the laws of the land;
not considering the gross absurdity of making human
laws to be preferred before the laws of Christ,
however contrary thereto, and enjoined as an absolute rule for Christians;
unless they suppose it impossible that any human
laws can be made contrary to Christ`'s laws,
which is equally absurd.
Such an opinion tends to invalidate the great sufferings and martyrdom of all those,
who gave up everything they had in this world, and even their lives,
rather than actively comply with the laws of the land,
when they believed them inconsistent with the nature of Christianity,
and therefore a transgression of God`'s law.
But the ground of the misapprehension, which such reasoners fall into,
appears to be a presumption that the source of property is in the law,
and that the laws of the land can alienate the right of one,
without rendering him any equivalent, and give it to another,
who had no right therein before.
But right and wrong are immutable, and cannot be altered by human laws,
which only grant people aid to preserve and recover
that which of right appears to belong to them;
so that human laws cannot bind the conscience,
any further than they are consistent with the laws of God.

When a sincere Christian is persuaded they enjoin any thing
contrary to the perfect law of liberty in his own mind,
he may not actively resist, but passively suffer the penalty thereof,
whereby he faithfully bears his testimony against the iniquity of such a law,
and so far contributes to have it removed.
Tithes under the Gospel, being an anti-christian, popish error,
and the laws enjoining their payment being grounded upon a supposition,
that they are due to God and holy church,
how can any clearly enlightened person pay them in any shape,
as he thereby assents to that great error and contributes to support it,
to the great scandal and abuse of the Christian religion, and that noble, free,
disinterested ministry, instituted by our Lord and Savior Jesus Christ;
whose direction in that case is, "`Freely you have received, freely give?`"
Much more might be said to manifest the absurdity of
such a plea for the payment of tithes;
but I would hope there are not many among us so blinded by the god of this world,
as to adopt such an argument.
Truth prevailed in the meeting,
and the testimony thereof was exalted over all such spirits.
Praises to our God for his gracious assistance,
mercifully afforded to all those who put their trust in him alone!

I proceeded on my journey and had meetings at Godmanchester, Oakham and Leicester;
and had close searching labor, in order that careless,
lukewarm professors might be stirred up and awakened to a sense of their states.
The testimony of Truth also flowed forth at times,
as a refreshing stream of encouragement to the mourners
in Zion and sincere travelers thitherward.
From there I went to Nottingham, and had a meeting;
the Lord graciously favoring with wisdom and utterance,
to divide the word aright to the several states of those present.
Truth greatly prevailed, overshadowing the meeting to the rejoicing of many hearts.

Next day I had a small meeting at Furness in Derbyshire,
wherein I had close labor with indolent professors, who,
neglecting their own proper business, were too much depending upon the labors of others,
to their great loss; besides which,
such unwarrantable dependence greatly tends to
load and depress the life in those concerned,
making their exercises much greater.
The next meeting I had was at Matlock, which was large;
the greater part being people of other persuasions.
It was, through the blessed efficacy of the Word of life, an open good time,
and the doctrines of Truth were largely declared;
showing that the world by wisdom knows not God,
as well as how and to whom he is pleased to make himself known.
The meeting was much affected with the virtue of Truth,
which was eminently extended that day, and I hope would not be easily forgotten by many.
I went from there to Sheffield, and attended their meetings on first-day,
which were large.
In the morning my spirit was deeply baptized into a
painful sense of the empty formal state of some,
and also of the undue liberties of many others.
I was made willing and resigned to go down into suffering on their account;
that if it pleased the Lord,
I might be the better qualified to administer effectually to their several states,
as experience has taught me repeatedly,
that I could not speak feelingly to mankind for their help and recovery,
in any other way.
At the afternoon meeting I was concerned to lay their several states open before them.
It was a blessed and seasonable opportunity,
tending much to their awakening to a sense of duty,
and I think it may with thankfulness be said, Truth was over all.

The next meeting I had was at Highflats, which was large,
there being a numerous body of plain Friends, as to the outward appearance,
belonging thereto.
It was a laborious meeting, but through divine favor,
there was strength afforded to lay before them in a close pressing manner,
the great danger of resting contented in a decent form
of religion without the life and power thereof.
I hope it was a profitable time to many.

I went from there to Brighouse meeting, wherein matter and utterance were given,
tending to arouse the indolent and to encourage those
who were truly concerned for Truth`'s prosperity.
The meeting at Rawden was very large and open, and the testimony of Truth had dominion.
I had a pretty open meeting next day at Bradford;
after which I went to visit a friend who was very low and weak in body,
few expecting her recovery.
I felt the pure virtue of the holy anointing to be with her,
and had it given me to signify,
that I did believe the Lord would raise her up for further service,
which accordingly came to pass.

I went from there to Leeds, and attended their meetings on first-day.
In the forenoon the testimony of Truth was greatly exalted,
in setting forth the power and efficacy of living faith: it was a glorious time,
Truth being over all.
In the afternoon, it was thought several hundreds attended,
mostly of the people called Methodists.
I was quite shut up as to ministry, I thought,
in order to set an example of the important duty of silence to Friends and others.
The meeting concluded with an awful solemnity, which I hope was profitable to many.
I went to Skipton, where the meeting was large,
and the power of God`'s eternal Truth went forth in a searching, awakening testimony,
as well as in a refreshing stream of consolation to those who stood
in need of encouragement in their travels towards the city of God.
The meeting next day at Airton was a heavy painful time of silence in the forepart;
but the Lord was pleased to appear and afford ability to search some barren professors,
by opening their states to them, with which they seemed somewhat affected;
but alas! how hard it is to reach effectually
unto those who are settled as upon their lees,
living in a state of mind that can rest satisfied in an empty profession.

Next day I had a pretty large meeting at Settle:
there I found the life of religion much depressed with an earthly formal spirit;
but through divine goodness, Truth arose and prevailed over it for the present,
and was exalted, as being the one thing needful.
I went from there to Lothersdale, where I had a very large meeting; the Lord enabling me,
who am otherwise a poor helpless creature, to bear a thorough testimony,
suited to the various states of those present;
and his glorious name was exalted above every name.
From there I went to the house of my beloved friends Jonathan and Margaret Raine,
at Trawden; whom,
for their tender regard to me when I wanted succour both for body and mind,
I have heretofore had occasion to mention; as likewise the Ecroyd family.
We greatly rejoiced in the opportunity of one another`'s
company once mot their Quarterly Meeting,
being accompanied by my friend Jonathan Raine.
I was at the Monthly re; Truth having nearly united us in our former acquaintance.
I stayed there something more than a week,
attending several meetings there and at Marsden-height;
at some of which the Lord was eminently with us, opening the wells of salvation,
that we might drink together and sing praises to him the Fountain of all good.
I had great openness in my service among them;
and we took our leave of one another in a sweet sense
of God`'s love uniting our hearts one to another.

On second-day, the 1st of the tenth month, I set out for Lancaster,
in order to be at Meeting there on third-day, where I had considerable service.
Fourth-day in the morning, was held their meeting of ministers and elders;
which was to comfort and edification.
I found myself concerned to set forth the nature of true Gospel ministry;
as also to point out some dangers which, without a steady care and watchfulness,
might attend those exercised therein.
I hope it was a profitable opportunity to some present.
The same day was held the Quarterly Meeting, wherein the Lord was graciously pleased,
according to his customary goodness,
to appear for the help of his sincerely concerned laborers.
Blessed be his worthy name, he is found of those that truly seek him,
and does not fail those who lean upon him, and not to their own understanding,
nor to former experience of his assisting power and wisdom.
Truth was greatly in dominion and Friends much edified,
the unity of the one spirit being livingly enjoyed.

I went next day, accompanied by Samuel Fothergill,
William Backhouse and William Dilworth, to the Quarterly Meeting at Kendal.
The select meeting for ministers and elders was held that afternoon;
and I had some good open service therein,
on the nature of Gospel ministry and the mysterious
workings of Satan in his transformations.
It was a time of edification and comfort.
Next day was held the Quarterly Meeting; the forepart for worship,
and afterward for the discipline of the church, wherein I had some service.
Things were low: we had a large meeting in the evening, both of Friends and others;
it was, through the pure efficacy of divine virtue, a blessed opportunity.
I was largely opened in testimony concerning Christ, the divine light,
who enlightens every man that comes into the world.
It ended in solemn prayer and praises to Almighty God;
our friend Samuel Fothergill being engaged therein,
in a very powerful and affecting manner.
I stayed at Kendal to attend their first-day meetings; at both which,
especially the latter, I was very largely opened to declare the Truth with power,
which affected and tendered many hearts, there being a great number of Friends,
mostly of a younger sort, in that meeting; it having been stripped,
like many other places of late, of several substantial elders.
My labor was very earnest,
that the rising youth might come rightly under the yoke of Christ,
that they might be really prepared and fitted to succeed those who are removed hence,
having finished their day`'s work.

Accompanied by several Friends, I had a meeting at Grayrigg, to good satisfaction.
The testimony of Truth went forth with clearness and demonstration,
tending to awaken the careless,
as well as to strengthen and encourage the honest-hearted.
I returned to Kendal, and went next day to a general meeting at Windermoor.
The Lord`'s blessed power was livingly felt in that meeting, whereby I was enabled,
from the expressions of our Lord to Nicodemus,
to show the necessity of regeneration or the new birth;
a doctrine highly necessary to be pressingly recommended to
the youth in our Society and carefully weighed by them,
lest any should vainly hope for an entrance into the kingdom of God,
by succeeding their ancestors in the profession and confession of the Truth.
A lamentable error! which many I fear have fallen into, imagining they are God`'s people,
without his nature being brought forth in them; or, as says the apostle,
being made partakers of the divine nature,
and escaping the corruptions that are in the world through lust.
Great opportunity have such by education, the writings of our predecessors,
and also by the Gospel ministry with which the
Lord has been pleased to bless our Society,
to collect and treasure up a great deal of
knowledge in the speculative understanding part,
even to profess and confess the Truth in the same words or language made use of,
by those who really learned it in the school of Christ.
This is no more than an image or picture of the thing itself, without life or savor;
and where it is trusted to is an abomination to God and his people.

I have touched the more closely on this head,
being apprehensive the danger is very great to which the rising youth are exposed,
by dwelling securely and at ease, as it were, in houses they have not built,
and enjoying vineyards they never planted; for great are their advantages above others,
if rightly improved`'; otherwise they must increase the weight of their condemnation.
I have often looked upon the mournful condition of
those who trust in the religion of their education,
to be aptly set forth in the holy Scriptures, by a hungry man dreaming that he eats,
and behold when he awakes, his soul is empty.
Oh, that all may deeply and carefully ponder in their hearts,
what they have known in deed and in truth, of the new birth,
with the sore labor and pangs thereof!
I cannot but believe, if they are serious and consider the importance of the case,
that they will soon discover how it is with them in this respect,
by observing which way their minds are bent and thoughts employed,
whether towards earthly or heavenly things.
To those who are born from above or risen with Christ, which is the same thing,
it is natural to seek those things which are above; their affections being fixed thereon.
So on the other hand, that which is born of the flesh is but flesh,
and can rise no higher than what appertains to this transitory world;
for flesh and blood cannot inherit God`'s kingdom; and it is said,
those who are in the flesh cannot please God.
The apostolic advice therefore, is to walk in the Spirit; that is,
let the Spirit of Christ be your guide and director,
how to order your lives and conduct in all things;
for the children of God are led by his Spirit.
I have often greatly feared, lest the descendants of the Lord`'s worthies,
who were full of faith and good works, should take their rest in the outside of things,
valuing themselves on being the offspring of such:
a sorrowful mistake which the Jews fell into!
May all duly consider that it is impossible to be the children of Abraham,
unless they do the works of Abraham.

Truth was greatly in dominion that day,
and many hearts were much tendered and contrited before the Lord;
to whom be everlasting praises, Amen!
The next meeting was at the Height, where I had close arousing service,
in order to awaken careless formal professors.
The day following I had a large meeting at Coltis, near Hawkshead,
where I was favored with great openness upon the nature of true faith,
and that it must be evidenced by good works; for faith,
when only an assent or consent of the mind to principles of religion true in themselves,
being alone, is dead, as a body is, without the spirit.
The power of Truth had great dominion, it being a time not easily to be forgotten.
The next day I had a meeting at Swarthmore;
where also I was led to speak largely of faith, of historical and implicit faith,
and to set forth the nature of that faith which was once delivered to the saints,
and was their victory over the world and all the corruptions thereof.
It works by love, to the purifying of the heart, and when the heart is made pure,
we can see God.
"`Blessed are the pure in heart, said Christ, for they shall see God.`"
And his apostle said, "`By faith we come to see him that is invisible.`"
It is plain from the holy Scripture, that it proceeds from the Holy Spirit in man;
for it is the evidence of things not seen, and the substance of things hoped for.
No man can possibly please God without it.
O that mankind would carefully examine themselves, whether or no they be in this faith!
If they be in it, they cannot be strangers to Christ, inwardly revealed;
for he dwells in the hearts of true believers by faith; his kingdom being within,
where all his laws and ordinances are discovered,
clearly understood and willingly obeyed.
When this faith is received and held in a pure conscience,
there is no complaint of hard things being required, or his commandments being grievous;
but a soul endued with this powerful principle, can say with sincerity,
the Lord`'s ways are ways of pleasantness, and his paths are paths of peace.
It was a good time, and I hope profitable to many.

The next meeting I had was at Preston, near Kendal;
there I was earnestly concerned to stir up Friends to
more faithfulness and a closer union one with another.
It was a laborious time, but the blessed Truth prevailed and carried through,
to my own ease in a good degree.
The meeting at Brigflats, near Sedburg, was large,
and for some time heavy and afflicting;
but it pleased the great Master of our assemblies to arise,
without whose gracious help his poor instruments can do nothing to any good purpose.
It was a solemn awakening time, I hope to be remembered by many.
I had a meeting next day at Ravenstondale, which was a laborious trying time:
my way was shut up as to ministry, and Friends seemed at ease in a profession.
When this is the case, the life of religion is exceedingly depressed;
so that those who feel its state, must suffer therewith,
until it please the Lord to raise his pure Seed,
in judgment against evil in people`'s minds: then man falls under for the present,
and confesses to that name or power given under heaven for his salvation.
But alas! he soon denies it again, by giving way to a contrary power;
an enemy to God and his own soul.
In such ups and downs, changes and conflicts,
by the working of contrary powers in their minds, many weary out their days in vain,
because they will not resolve to choose the good and to eschew the evil,
that they might be established upon the Rock of ages forever.

The next day I had another meeting at Preston; it was a time of close labor,
yet through gracious help, I hope it was serviceable.
I went from there to Yeoland; this was a suffering time,
much of the testimony given me to bear,
went forth sharply against such who were strong and confident in profession,
without real experience of the living virtue and holy efficacy of God`'s eternal Truth,
to quicken and season their spirits.
We find it very hard to gain any entrance on such.
The testimony is often felt to rebound,
which in low times is a great discouragement to the poor instrument.
Here the faith and patience of the Gospel must be exercised.
I understood after meeting,
that the state of some present had been remarkably spoken to that day,
which tended to humble my mind in thankfulness before the Lord,
for his gracious help and guidance.

After these exercising painful times,
doubts are apt to enter and fears to possess the mind,
lest we have been mistaken in what we apprehended the Lord required of us to deliver.
I say us,
as I do not doubt that it has been the experience of many others as well as mine.
This ought to be carefully guarded against,
lest the poor instrument sink below its service,
by giving away its strength and sure defense.
The soul`'s armor and weapons being thus imprudently given away or cast off,
our spirits are weaker than those of others, and consequently fall under them.
Here that dominion, in which there is ability to teach, may be lost.

There is great danger also, on the other hand, of being too confident and secure.
I have observed some,
after they have darkened counsel by a multitude of words without right knowledge,
and exceedingly burdened the living, appear quite cheerful and full of satisfaction,
seeming as if thoroughly pleased themselves.
This is a lamentable blindness,
and discovers them to be at a great distance
from the dictates and holy impressions of Truth.
This is what all ought earnestly to pray they may be preserved from,
walking carefully in the middle path, retaining a jealousy over themselves,
with a single eye to God`'s honor and the promotion of his Truth.
Then will their feet be shod with the preparation of the Gospel of peace,
and will appear beautiful upon the mountains.

I went from Yeoland to Lancaster, and attended their meetings on first-day,
where I had good open service, Truth being comfortably in dominion,
and Friends thereby nearly united one to another.
From Lancaster I went to meetings at Fylde, Frekleston, Preston, Langtree and Ashton.
They were generally small, and the life of religion at a very low ebb.
I was favored with strength to discharge the service required,
in a close painful labor for their help and recovery.
But alas! great is the declension in those parts,
and I fear it is but little laid to heart.
The next was Hardshaw general meeting, which was very large,
and although heavy and painful in the forepart, yet, through divine goodness,
it proved a solemn, serviceable meeting, and by strength and wisdom received from above,
several weighty Gospel truths were delivered, to the comfort and edification of many.
That evening I had a large meeting at Warrington; but as heretofore in the same place,
I felt their life and dependence was too much upon and after declarations.
I found it my duty to disappoint that spirit, by sitting in silence.
I went from there to my valuable friends John and Joshua Toft`'s,
near Leek in Staffordshire, having Samuel Fothergill for company and guide.
I had a serviceable meeting at Leek; my labor was close in plain dealing with some,
who appeared to me exalted in their own wisdom and conceit of themselves,
so that the simplicity of the Truth was overlooked by them.

On fifth-day, the 1st of the eleventh month, accompanied by Joshua Toft,
I went to Stafford, and had a small poor meeting there.
Next day in the evening we had a meeting at Tamworth, which was large,
being chiefly made up with the considerable inhabitants of the town.
The public service thereof fell upon my companion, with which I was well pleased,
but found my mind not clear of Friends belonging to that meeting,
and therefore desired to have a meeting with them next day, at a Friend`'s house,
as I was desirous to have Friends only.
I had close searching service among them, to my comfort and great relief in the end.

On first-day, the 4th, I was at Birmingham meetings; the forenoon was a good open time,
wherein the testimony of Truth was exalted;
but the afternoon proved a heavy painful meeting;
and my way was quite shut up as to ministry.

Apprehending myself discharged from further service in this journey,
on second-day morning I set my face homewards, and got to Northampton that night,
next day to Hitchin, and home on fourth-day, the 7th of the eleventh month,
finding my dear wife and family well; being thankful, as we had great cause,
to the Fountain of all our mercies, for his providential care over us,
when outwardly separated for his service sake.

I was from home on this journey, about ten weeks and three days,
in which time I traveled, by account, about seven hundred and sixty miles,
and was at about fifty-five meetings.`'
