== Chapter 7

[.chapter-synopsis]
* Travels with John Churchman
* Visits London in company with Peter Andrews
* Severe illness
* Visits the meetings in Kent, Sussex and Hampshire
* Remarks on the state of Christendom and of the Society of Friends
* Journey into Lincolnshire, York, Lancaster, etc.

In the year 1754, I traveled with my esteemed friend John Churchman, through Hampshire,
the Isle of Wight, and part of Surry; the particulars whereof I cannot at present find;
but I remember it was the last of his travels in this nation,
and that we were nearly united in the service;
the power and wisdom of Truth being livingly and comfortably with us,
enabling us to labor with diligence for the promotion of Truth and our own peace.

In the forepart of the year 1756,
being in company with my esteemed friend Peter Andrews from America,
visiting meetings in the city of London, I was seized with a violent disorder,
and it was with considerable difficulty I got home, and soon took my chamber,
where I continued many weeks under great affliction of body, and also of mind at times,
which I have several times experienced as a further trial of my faith and patience.
The Lord has been pleased to withdraw his comforting enlivening presence,
I have thought rather more so in those times of bodily afflictions, than at others,
for wise ends, best known to himself.
Oh! who can understand or conceive the anxiety of the mind when this is the case,
except those who have felt the same?
But through divine favor, it was not so with me always,
especially in the last of my great illnesses, which was the latter end of 1758,
when the joys of heaven so opened upon my soul, as I had never known before,
which made me willing to hope that I was near entering into the full fruition thereof.
How strong were my desires then to be dissolved, and to be with Christ forever!
I was ready to say, now let your servant depart in peace,
for my eyes have seen your salvation!
But I was not then accepted herein,
neither was my mind afterwards free from some fears and doubts,
that I had offended a gracious God,
by an over-anxious desire to be removed from a militant to a triumphant state.
The example of our Lord, though he was the only begotten Son, in addressing the Father,
is highly worthy to be ever remembered by us, in all our desires and prayers, namely,
"`Nevertheless, not my will, but yours be done!`"

The above hints may fall into the hands of some poor afflicted persons,
to whom they may afford comfort, by observing that they are not singular in their trials,
and from there, through the divine blessings, they may receive encouragement;
which is my reason for penning them,
as well as many other remarks in the course of this journal;
even of my most inward and hidden trials.
I have had great cause to bless and praise the Lord, many times since,
when I have observed the great advantage of those pinching seasons of affliction,
how much they tend to refine, and to establish the soul upon the Rock of ages,
yielding the peaceable fruits of righteousness
to those who are properly exercised thereby.

I had very little health from the time that I was taken before-mentioned,
for about two years; yet was enabled, in 1757, to visit Friends`' meetings in Kent,
Sussex and some few meetings in Hampshire, etc.

I set out from home the 12th of the seventh month,
and crossed the river Thames at Gravesend,
where by appointment I met my friend Joseph Taylor, and with him,
Joseph Wood and Stephen Jackson, all from London.
We went that afternoon to Rochester,
where about six o`'clock in the evening we had a meeting, there being a meetinghouse;
though I think but one person, a young woman, who made profession with us.
Many others came,
and there was an openness to declare the doctrines of Truth largely among them,
which I hope was not altogether in vain.

From there we all went to Canterbury, except Stephen Jackson, who returned home.
We had a meeting there, made up chiefly of professors with us.
The testimony of Truth went forth in a close searching manner, and through mercy,
it was exalted over all of a contrary nature.
The Lord had the praise, and his sincere followers, satisfaction and comfort.

We had a meeting next at a place called Burchington, where there was a meetinghouse,
but none of our Society living in that place.
The people filled the house, and many were out of doors;
they appeared in general ignorant, yet the Lord,
with whom there is no respect of persons, opened the doctrines of the Gospel largely,
and in a reaching affecting manner, by which many seemed to be tendered.

Next day we had a meeting at Drapers, near Margate, which was small,
and things low as to the life of religion.
In a very small meeting in the evening at Deal, I had some close service; after which,
one person gave me sufficient cause to see that there was need of it.

The next meeting was at Dover, being on seventh-day in the evening,
as I was desirous of being at Folkstone on the day following.
Truth opened doctrine and counsel for their help and edification,
there being some lately convinced of our principles, who appeared tender and hopeful.
I had good satisfaction among the few Friends in that place.
At Folkstone the meetings were large,
but the life of religion mournfully low and borne down,
not only with those things commonly called undue liberties in many,
but also with the form of religion, without the power of it in others.
I had, as it were, a threshing instrument put into my hands,
and was enabled to discharge the service required, to my great ease and relief;
for my spirit was exceedingly loaded and bowed down at that place.
Oh! what a pity it is, that old professors,
instead of being as pillars in the house of God, and as Aarons and Hurs,
bearing part of the Lord`'s great work, so happily and gloriously begun in the earth,
should be a means of obstructing the same, and by the carnality of their spirits,
burden and greatly depress the Word of life in the messengers of Christ,
sent in order to carry it on among mankind;
thereby rendering themselves altogether unworthy to be named by his name,
to taste of his dainties,
or to live under this glorious manifestation of evangelical light and truth, to mankind!

Is not the great design of the Almighty obvious,
in gathering us as a people into his fold, to sit under his teachings,
and consequently under his glorious manifestation,
showering upon us great plenty of rain from above,
and heavenly dew as upon Hermon`'s hills, that we might be as the garden of the Lord,
full of fruitful plants and fragrant flowers, sending forth a sweet smell, yes,
to be as a fountain of gardens, and wells of living water,
and streams from the goodly beautiful mountains of Lebanon.
It is written,
"`Out of the belly of him that believes, shall flow rivers of living water.`"
By this it plainly appears, that the Lord`'s chosen people are like conduits, channels,
or waterspouts, to convey the water of life into the wilderness,
that it may become a fruitful field, and that the desert land may come to rejoice,
and blossom as a rose; also into the sea, that is, among the nations, languages,
tongues and people, to heal the fishes that are in this sea,
the backsliders and distempered of mankind.

But oh, how slowly does this work go on! and what a little progress it has yet made,
to what was expected by those valiants,
who first engaged against Babylon in the morning of our day, and made that kingdom shake!
Many under the same profession in this day, are turned against the Truth,
and at the same time that they pretend to maintain its cause,
are supporting and strengthening the kingdom of Babylon all in their power,
which is exceedingly strange,
and perhaps would not be believed by hundreds that really are doing it.
The reason is, they first of all have taken some draughts of the wine,
out of Babylon`'s golden cup, whereby they are so intoxicated,
as not to know what they are doing; so that, when they think they are serving God,
they are serving Satan.
Were not the Jews drunk with this cup, when they dreamed that God was their father,
and at the same time were in reality of their father the devil, doing his works,
when they thought they were doing God`'s works?
This, woful mistake has been, and is almost general among mankind.
When they suppress the measure of grace in themselves,
and drink a few draughts as above said,
they are then fit to follow antichrist whithersoever he will lead them.
But he will take care, not to have much cross to the will of the flesh in his religion,
lest they should be tempted to leave him;
that being the very reason of the violence they have offered to the divine Witness,
which formerly rose up against them in their minds, that is,
because they saw if they followed that, the cross must be taken up,
and self must be denied.
At this they have stumbled; and although little sense is at present retained thereof,
by reason of their intoxication,
yet when they are summoned before the judgment seat of Christ,
and the books come to be opened, all will then see things as they really are,
which do not at all change their natures, though, by the defect in the capacity before,
described, they be not seen or understood.

It is worthy to be remembered, and deeply pondered by great numbers in our Society,
that it was the rebellion and unfaithfulness of the children of Israel,
that was the cause of their being turned back again into a barren, doleful,
howling wilderness, when near the borders of the land of promise.
They doubtless might have then entered, subdued the idolatrous inhabitants,
and taken full possession thereof, had they believed in and obeyed the mighty Jehovah,
who with an outstretched arm had brought them out of the land of Egypt,
dividing the Red Sea in mercy to them, and for the destruction of their enemies.
But what a long wilderness travel they had afterwards,
for about the space of thirty-eight years, until all that people had fallen,
except Caleb and Joshua,
men of upright hearts whom the Lord honored with being the
leaders of an entirely new people to possess the land.
Cannot the empty formal professors among us, who, under great pretensions,
have allowed a heart of unbelief, a rebellious heart,
that has departed from the living God, and embraced this present world,
read their own condemnation in this account?
Shall they ever enter into the heavenly Canaan,
or be accounted worthy to carry on his glorious work in the earth?
No, verily; but they must fall into great condemnation,
except they repent and redeem their misspent time,
and another people be raised to maintain this glorious cause,
to whom the Calebs and Joshuas in our Society will be as leaders and directors;
like Priscillas and Aquilas, to expound unto them, who inquire the way to Zion,
the way of the Lord more perfectly; for I am fully persuaded,
our Society will not cease to be a people, nor the glory ever depart therefrom wholly,
as it did from the Jewish, and in a great degree the lapsed Christian church.

I have no doubt but that a people will be preserved from generation to generation,
to contend earnestly for the faith once delivered to the saints,
and to maintain the same with the doctrine and principles resulting therefrom,
so eminently revived in our predecessors, and most surely believed by us.
So that when it shall please the Lord to awaken the nations,
there will be no occasion to expect new discoveries or other manifestations,
but the Lord will show where he feeds his flock, and where they lie down at noon.

I do not expect the present lethargy and almost universal indifference of
all denominations of Christians about religion is to continue very long,
for the Lord`'s soul abhors it.
I am fully persuaded he will arise in dreadful majesty, to shake terribly the earth;
the power, wisdom, policy and splendor thereof, and not only the earth,
but the heavens also, that he may remove those things which can be shaken,
that those things that cannot be shaken may remain.
Then shall people see how empty and fruitless their religious pretensions have been.
Then will their eyes and cries be to the Lord,
to show them the pasture of the flock of his companions.
Then will mankind receive a kingdom which cannot be shaken.
But, oh! the bitter cups that must be drank,
and the vials of God`'s wrath that must be poured upon nations and kingdoms,
before mankind in general, will be humbled enough to submit to the yoke of Christ,
and to learn of him who is meek and lowly in heart.
But he is Lord of lords and King of kings, and can turn and overturn,
until the inhabitants of the earth are willing that he should reign whose right it is;
"`for when the judgments of the Lord are in the earth,
the inhabitants of the world will learn righteousness.`"

Great and marvelous have been the Lord`'s condescension and goodness,
manifested for our help and preservation many ways;
upon one whereof I cannot well omit a short remark, namely,
the reviving of ancient zeal for the promotion of discipline and good order,
which I find is almost general throughout the Society.
That spirit of sound judgment, and the burning of that holy fire,
which the Lord does kindle in the hearts of the faithful,
has never been wholly extinguished since we have been a people; though in some places,
through the neglect of many, it has burned faintly and languidly.
This zeal has of late been much augmented,
and the number of those who will not take bribes, that is,
through favor and affection pervert judgment, is increased.
I pray God, for his great name`'s sake and his people`'s preservation,
that this good work may prosper!
Public ministry, though a great blessing, help and comfort to God`'s people,
may be shunned, evaded, and turned off by individuals:
but the church cannot easily lose ground under a godly,
impartial administration of sound judgment,
and dealing in the way of good order and discipline, as this brings judgment home;
you are the man.
Here individuals must condemn the evil, or be disunited from the body,
that it may not be infected or endangered by their defection.
I went from Folkstone to Maizam, where I had a meeting and some close searching labor,
in order to awaken drowsy lukewarm professors.
I had meetings also at Ashford, Tenterden and Cranbrooke,
where I found things exceedingly low as to Truth and Friends,
and but very little of the substance, or even form, to be met with.
My spirit was much affected with sorrow and mourning,
in viewing the deplorable state of the Society in this county;
yet I endeavored with patience to wade along in my service,
and to discharge the duty required of me.

I then proceeded to visit Sussex.
The first meeting I had in that county, was Gardnerstreet.
I could find but very few, if any, truly alive in religion there.
I had hard close work with the unfaithful in some
important branches of our Christian testimony,
to which I was immediately led; for I knew nothing of their state by outward information.
I had meetings also at Lewes, Brighthelmstone and Arundel; at all which places,
I found the life of religion much depressed.
My service was close and searching;
but alas! carnal professors are very hard to be
made sensible of their deplorable condition.
From Arundel I went to Chichester, where I had a meeting and good open service,
not only to stir up the careless to more fervent labor,
but also to encourage and strengthen some tender-hearted travelers Zion wards.
It was through the holy efficacy of Truth, a blessed time.
I went from there to Alton, in Hampshire, and attended their first-day meeting.
There is a large body of Friends, among whom the great Master of our assemblies,
opened doctrine and counsel suited to their several states,
and the blessed Truth was in great dominion that day.

The next meeting was at Godalming, where I had very close heavy service,
being made sensible of much indifference and lukewarmness in some professors.
It was often my lot to labor for the stirring up and reviving of such:
but alas! it is hard work,
yet sufficiently rewarded by the comfortable returns of true peace,
in a faithful discharge of duty.
The meeting at Staines was pretty open and satisfactory;
being livingly engaged to administer suitably to the several states of those present.
I went from there to Uxbridge, where I had open thorough service, to good satisfaction;
after which I went to High Wickham, and had a heavy laborious meeting.
The same day I had an evening meeting at Amersham, in which I had some service,
though things were very low.
Next day I had a meeting at Jordans, where the blessed Truth had great dominion,
and the testimony thereof flowed forth freely, in doctrine and counsel,
for the help and comfort of those present.
After this I went to London, where I stayed the first-day meetings.
I attended Grace-church street in the morning, where I had good service,
and the testimony of Truth had great dominion.
I went to Devonshire-house in the afternoon,
where I had also a good open time to declare the Truth;
finding much ease and peace of mind.
The service of this small journey being over, I returned home the next day,
having been out about four weeks, at twenty-eight meetings,
and traveled about three hundred and fifty miles.

The next journey I have any account of,
was chiefly in order to visit the Quarterly Meetings of Lincoln, York,
Lancaster and Kendal.
I set out the 16th of the sixth month, 1758, and by appointment,
met Joseph Taylor at Cambridge, who was to be my companion as far as York.
It being first-day, we went to their meeting in the morning, which was very small,
and things exceedingly low as to the life of religion.
We went in the afternoon about ten miles to a general meeting at a place called Over,
and I was largely opened therein, in close awakening service,
tending to arouse careless professors, of whom there seemed to be many at that meeting.
We proceeded as far as Erith, and next day got to Spalding, in Lincolnshire,
where we met our worthy friend Mordecai Yarnall, from America,
who was then on a religious visit in this nation, and Samuel Neale from Ireland.
The 20th in the morning, we set out for Lincoln Quarterly Meeting,
which began the next day about noon, and ended the day following.
Truth is at a low ebb in this county, and the discipline in the main but poorly managed,
and the conduct of several professors administers cause of offense; yet we were,
through the extendings of merciful goodness,
favored with considerable openness and pretty thorough service for their help,
and to our own ease in a good degree.
My companion and I proceeded on our journey towards York,
taking Leeds`' first-day meetings in our way, which were large, very heavy and laborious.
My proper business was to wade under a great weight,
occasioned by the indolent spirits of those who were
unwilling to labor and bear their own burdens,
in an example of silence.
Next morning was held their Monthly Meeting of ministers and elders,
where I had close service; and the same day that for discipline,
which was exceedingly large, our Society being very numerous thereabout.
The testimony of Truth was greatly exalted therein, in treating concerning Christ,
the everlasting rock upon which the church is built, whereupon only it can stand firm,
against all the attempts of a potent adversary and his emissaries.
Next day we went to York,
where the same evening was held the Quarterly Meeting of ministers and elders.
I had some open service therein, particularly to ministers.
We were divinely favored in the succeeding meetings, both for worship and discipline,
to our edification and comfort.

From York I went towards Kendal, and was, in my way,
at a Yearly Meeting held on a first-day, in a large barn near Bingley; where,
it was thought, were very nearly a thousand people of other religious persuasions,
besides many of our own Society.
I was largely opened therein to preach the everlasting Gospel,
in the authority and demonstration thereof.
The people generally behaved in a sober becoming manner, appearing well satisfied,
which is too often the most we can say in our
day concerning such memorable opportunities;
whereas, our predecessors might have added, perhaps,
that several hundreds were convinced.
However,
we must content ourselves with the state or condition of the fields of the world,
in our day: and although we cannot lift up our eyes as they could,
to behold the fields white unto harvest,
yet let there be honest endeavors to contribute all in our power,
for the bringing them forward in this respect, and leave the rest to the Lord,
in whose hands alone are times and seasons.
I had a meeting at Skipton that evening to good satisfaction; then to Settle,
and was at their Monthly Meeting, where I had good service, and so proceeded to Kendal,
accompanied by several Friends.
The same day was held the meeting of ministers and elders,
wherein our ancient worthy friend James Wilson had excellent service,
to our great comfort and edification.
Their Quarterly Meeting of business was held next day, wherein I had good service,
in the opening of Gospel life and power.
A blessed meeting it was.
The Lord alone had the praise, who is forever worthy thereof!
I attended Kendal meetings the first-day following, which were very large and precious;
the everlasting Truth and its testimony being exalted over all of a contrary nature,
to the great comfort of the upright in heart.

I went, accompanied by our friend James Wilson and many others,
to their general meeting at Preston-patrick, which was very large.
My service therein, was searching and laborious;
not only in a sense of great lukewarmness in some, but also the heart-burnings, disunion,
and secret smitings one against another, of others.
It seemed to me,
that spirit had subtilely prevailed on some accounted of the foremost rank,
to their own hurt and the wounding of the innocent life.
My spirit had been painfully affected with the same sense of the state of that meeting,
in degree, in my former visits to it;
but never had so much power and comfortable dominion over it, as at this time,
wherein Truth mightily prevailed, to the subduing, at least for the present,
all that was of a contrary nature.
Near the conclusion of the said meeting, our worthy ancient friend, before mentioned,
publicly testified, that the eternal Truth of God was over all,
exhorting Friends highly to prize such blessed opportunities,
and carefully to improve thereby.

In relating what has been done, in marvelous kindness and condescension,
through me a poor weak instrument, towards the help and restoration of my fellow-mortals,
I do sincerely desire, if any good is done, the Lord only may have the praise,
honor and glory; for he alone is worthy, and nothing belongs to the creature,
but humility, reverence, obedience, and laying the mouth as in the dust.
I would be so understood throughout the whole narrative,
though not always expressed in words.

I went from Kendal to Lancaster.
The quarterly select meeting for ministers and elders was first held;
wherein our ancient friend James Wilson, bore a noble, evangelical testimony,
to the instruction, edification, and great comfort of Friends.
Next day was held their Quarterly Meeting for discipline, in which,
through the efficacy of divine power, I had some open weighty service.
I cannot well forbear remarking the great
satisfaction and pleasure I had at this meeting,
in beholding and having the acceptable company of three honorable, worthy,
ancient Friends, namely, James Wilson, Lydia Lancaster and Grace Chambers; who, I think,
all bore living and powerful testimonies therein, in a very affecting manner,
to the holy efficacy of that everlasting Truth,
which had been with them all their life long.
Oh! it was a time of much humbling encouragement,
to see their greenness and fruitfulness in old age.
I looked upon them as patterns of primitive times and Friends.
There is something wonderfully great and excellent,
seen only by those eyes which the Lord has opened, in the native simplicity of the Truth,
and that estate into which it gradually brings a man, who, in a total denial of self,
has fully given up to be formed by it.
This I take to have been very much the case with Friends in the beginning,
which rendered them so very obnoxious to the spirit of the world; than which,
there is nothing more opposite to a redeemed state:
so that the more any are drawn out of the corrupt ways and spirit of the world,
the more they are hated by it.
This is obvious, when we consider the treatment which Christ our Lord,
in whom the Godhead dwelt bodily, met with.
If many in profession with us, are nearer in unity and peace with the world now,
than our Friends were formerly,
let it not be understood as a token of their
advancement in the nature and spirit of true religion;
but the contrary, that is, that they are fallen nearer thereunto,
and become more like it in spirit,
though somewhat different as to the exterior part of religion,
which the world cares not much for, when it finds that in the main,
we are making advances towards them.

Our Friends formerly delivered themselves in ministry and writing, in a plain,
simple style and language, becoming the cause they were sincerely engaged to promote;
chiefly aiming to speak and write,
so as to convey the power and efficacy of the pure Truth,
to that of God in the consciences of men.
It is no small glory to the righteous cause we are engaged to promote,
that it has made such a mighty progress in the world,
upon a better foundation than that of human helps and learned accomplishments.
The very first and most eminent instruments, raised to propagate the same,
were illiterate men, agreeably to what Paul delivers, 1 Cor. 1:26-29.

May these things be weightily considered by all those
who seem to aim at seeking credit to the Society,
by means of those outward embellishments,
from which our worthy ancients were wholly turned,
to seek and wait for that living power and holy authority,
which alone is able to carry on the work of man`'s redemption to the end of time.
The departure from that opened the door effectually for the apostasy to overspread;
then human wisdom and learning became, in the estimation of degenerate Christians,
essentially necessary to make ministers of the Gospel.
But the early ministers and writers in the Christian church, became eminent another way,
as we have great reason to believe most of them were illiterate men;
and such of them who had attained human learning,
when the power of the Gospel was inwardly revealed,
laid all such accomplishments down at the feet of Him, to whom every knee must bow,
and every tongue must confess; so that we find them counting all that as dross and dung,
to which men, in their corrupt wills and wisdom, give the highest place for usefulness,
as above-hinted.
And I think some among us fall very little short of the same disposition of mind,
though they do not care to own it in words; for I have many times observed,
that some have but little relish or taste for the substantial truths of the Gospel,
in a plain, simple dress; nor to read books, holding forth the same,
unless they find some delicacy in the style and composition.

An honest substantial minister may wade into the several states of people,
in order to bring forth suitably thereunto, in the native simplicity of the Truth,
and his labor herein be seen, gladly owned and received,
by the circumcised in heart and ears, where his lot is cast;
yet the sort of people among us above-mentioned, of whom I fear there are many,
do not know, nor much regard him,
scarcely thinking it worth their while to attend
the meetings such a one is engaged to visit.
But if they hear of one coming who is noted for learning and eloquence,
though perhaps far short of the other in depth of experience,
what following after him from meeting to meeting!
Enough, if the instrument is not pretty well grounded,
to puff it up with a vain conceit of itself, and to exalt it above measure.
With sorrow it may be said, that much hurt has been done among us,
by such great imprudence.
I have often seen reason to conclude,
that popularity and common applause are no safe
rule to judge of the real worth of a minister.
Therefore, when I have heard much crying up of any instrument,
I have been apt to doubt its safe standing, and holding out to the end;
which it cannot possibly do, if the same desire prevails to speak,
as there is in such people to hear.
I am persuaded, if such keep upon a right bottom, they will, at times,
find it their duty to starve and disappoint such cravings after words.

I had an open satisfactory meeting at Lancaster the day after the Quarterly Meeting,
in which the holy virtue of Truth greatly united Friends in the bond of love and peace.
The 14th of the seventh month,
I set out in company with my kind friends Jonathan Raine and wife, William Dilworth,
and Tabitha Ecroyd, and lodged that night at Watton, near Preston.
Next morning I took my leave of the above said Friends in much near affection,
except William Dilworth, who accompanied me to Warrington that day.
The next, being the first of the week, I attended Penketh meeting in the morning,
and Warrington in the afternoon.
At both which, my labor in the ministry was heavy and painful, on account of the formal,
lifeless state of too many, who, by their age and long profession,
might have been as pillars in the church;
as well as the chaffiness and lack of solid experience
by their not yielding to the visitation of Truth,
in many of a younger rank.
Thus it is, when heavenly blessings have been showered down upon people,
not duly improving thereby,
they become more insensible than others who have not been so highly favored.
I was enabled to discharge the service required, in a searching, awakening manner,
to my own relief in a good degree.

I went the next day to my worthy friend Joshua Toft`'s, near Leek,
who had then lost his sight, but seemed fresh and lively in his spirit.
We had great satisfaction in company and conversation with each other.
I stayed one day with him and his brother, and then proceeded towards Worcester,
taking meetings at Dudley and Stourbridge.
I had some open satisfactory service at the first,
and a very laborious painful time in silence, at the other,
where Truth seemed to me much depressed by wrong things.
On seventh-day I went from there to Worcester, and attended their first-day meetings,
and was mournfully affected therein with a sense of lukewarmness in many professors,
finding it very hard for the life and power of Truth to arise into dominion,
so as to make them sensible of their states.
My labor was for the most part in silence, though I had some close public service.
I went after the last meeting as far as Evesham, on my way to London, and from there,
the next day home to my dear wife, and found her well; which, together with other favors,
I was, through infinite kindness, made a partaker of in this journey,
bowed my mind in humble thankfulness to the bountiful author of all blessings,
who is alone worthy of dominion and worship forevermore.
I was from home about five weeks and five days, and traveled, by account,
six hundred and sixty-four miles, and was at thirty-seven meetings.
