== Chapter 9

[.chapter-synopsis]
* Joins with the committee of the Yearly Meeting in a visit to the meetings for discipline in Essex, Suffolk, Norfolk, Cambridgeshire, Huntingdon, the Isle of Ely, Hertfordshire, Bedfordshire, etc.
* Remarks on the low state of the discipline in many places, and their labors for a revival
* Their manner of proceeding in the service
* Importance of a right qualification for managing the affairs of the church
* Report to the Yearly Meeting in 1762
* His visit to London and adjacent meetings.

Pursuant to the direction and appointment of the Yearly Meeting of 1760,
for visiting the Monthly and Quarterly Meetings of Friends in this nation;
on the 11th day of the first month, 1761, my esteemed friends, John Emms, Matthew Mellor,
Thomas Corbyn and Joseph Taylor, joined me at Chelmsford, we having before agreed,
by divine permission, to visit the Monthly and Quarterly Meetings of Friends in Essex,
Suffolk, Norfolk, Cambridgeshire, Huntingdonshire, the Isle of Ely,
Hertfordshire and Bedfordshire.
The next day, being the 12th, our Monthly Meeting was held,
wherein the above-named Friends had good service,
tending to promote discipline and good order amongst us.
The blessed efficacy of the living Word accompanied their honest labors,
which rendered the same very acceptable to some,
and I hope of general advantage for the promotion of truth.

The 14th we visited Felsted Monthly Meeting, held at Stebbing;
the state of which appeared very low and weak,
through the defection and lukewarmness of many members,
whereby the life of religion was greatly depressed;
yet the Lord was graciously pleased to arise, for his great name and people`'s sake,
in whose living power and wisdom much labor was bestowed for their help and recovery;
a few sincere-hearted members amongst themselves, joining with us herein.
The 16th we visited Thaxsted Monthly Meeting, and it appeared, by inquiry,
that many of their members were very slack and defective in
several branches of our Christian testimony;
and most of the active members had but little experience in the
essential qualifications for effectual service in the church,
which must all proceed immediately from the great Father of lights and spirits.
It would be very absurd to imagine that a less or inferior
ability to administer justice and sound judgment,
was necessary under this higher and more glorious dispensation,
than was received by those who judged and ruled for God in the Israelitish church;
it being evident the Lord was pleased to put his spirit upon those
who had the weight of the affairs of that church upon them,
both in their wilderness state of probation,
and after they quietly possessed the promised land.
But the supernatural endowment, which is so essential, is not within our reach as men,
neither is it given to us,
until we are emptied of our own wisdom and divested of
all dependence upon human accomplishments.

Our holy Head was pleased to furnish us with wisdom and strength,
suitable to the state of that meeting, for their information and help;
and the blessed virtue of Truth prevailed, to the tendering of their spirits.
The next Monthly Meeting visited was Coggeshall, on second-day the 19th,
but as I did not attend it, I cannot say further,
than that I understood it was a serviceable time;
much weighty advice and counsel being administered, to mutual satisfaction and comfort.
The 21st we visited Colchester Monthly Meeting, where,
though the life of religion appeared low, and several disorders had crept in,
yet divine goodness was extended in a powerful manner for their help,
enlightening the spirits of some to search the camp,
and to point out how to proceed in restoring that which had been turned out of the way.
The 22nd, Manningtree Monthly Meeting was held at Colchester, in which,
through the pure efficacy of heavenly love and wisdom, much fervent labor was bestowed,
for the awakening and stirring up the members to
a faithful discharge of their respective duties.
But, alas! through the great unfaithfulness of many,
discipline was but little maintained, in a manner agreeable to its dignity and worth;
consequently the life of religion was very low.

From Colchester we went to Edmundsbury, in Suffolk,
and visited their Monthly Meeting the 24th. It was a time of remarkable favor,
Truth bowing the spirits of Friends into a humble, teachable state, and at the same time,
affording plenty of suitable counsel,
which was kindly received by several members of that meeting,
with whom we had near union and great satisfaction;
several being willing to engage in the work of reformation, which appeared necessary.
The 26th we visited Woodbridge Monthly Meeting, in which the Lord,
according to his customary merciful kindness,
appeared not only in spreading the awful canopy of his divine power over the meeting,
but also in graciously condescending to be a spirit of judgment and counsel,
for the help and recovery of a declining people;
under the enjoyment of which divine favor, much labor was bestowed,
and as far as appeared, was well received.
The 28th we visited Beccles Monthly Meeting,
where things appeared very low and much out of order;
the spirit and wisdom of man appeared much to rule and act amongst them,
which is fond of smoothing over and daubing with untempered mortar,
crying peace when there is no peace.
In this difficult mournful state of things, the divine helper,
in whom our only dependence remained, was near,
giving judgment to assign the living child to the proper mother,
and to judge down wrong things, in whatever stations they appeared.

The 29th we visited Tivetshall Monthly Meeting in Norfolk, in which, though large,
being composed of many members,
yet very great slackness and unfaithfulness appeared in several important respects.
Notwithstanding this, we had, with thankful acknowledgments,
to experience the awful presence of the Lord,
who is the only strength and sufficiency of his little ones;
under the blessed influence whereof, great and deep labors were bestowed,
for reviving our Christian discipline, and promoting the good order of the Gospel;
the testimony of Truth being maintained against wrong things in that meeting,
with authority and clearness; the power thereof subjecting, for the present at least,
all of a contrary nature to itself.
On the 2nd of the second month, we visited the Monthly Meeting of Wymondham, wherein,
on the usual inquiries, things appeared very afflicting,
through the great defection of many; the few who were concerned for good order,
were weak and much discouraged,
so that very little was done to maintain our wholesome discipline,
by visiting and laboring with the unfaithful and disorderly walkers: yet the Lord,
in great condescension, appeared wonderfully for their and our help,
extending much advice and counsel,
and giving us wisdom and strength to contend earnestly
for the faith once delivered to the saints;
which faith is to be demonstrated by works consistent therewith.
The testimony of Truth was greatly exalted over all such,
as through a mean compliance with wrong things, had mournfully deviated therefrom.

The 3rd we visited their meeting of ministers and elders at Norwich,
where the slate of the members was inquired into,
by means of queries proper to such meetings; and solid and weighty advice was given,
where any deficiency appeared.
Although I have not before now, distinctly mentioned our visits to select meetings,
yet we had such opportunities in most or all the
Monthly Meetings where such meetings were settled.
On the 4th of the second month, we visited the Monthly Meeting of Norwich,
which was very large, consisting both of the men and women Friends; it being our method,
in our labors at the Monthly Meetings, to have the company of both sexes.
Through the overshadowing of divine power, it was a solemn awful time,
of which Friends in general appeared to be sensible,
as a remarkable stillness and patience was abode in,
for the space of about six hours and a half, being the time of the meeting`'s continuance.
Though a motion was made sooner for our women Friends to withdraw,
lest some weak constitutions might be injured by long sitting, etc.,
yet their spirits being stayed and bowed down under a sense of heavenly good,
they did not accept the liberty given, but continued to the breaking up of the meeting.
We found a valuable body of Friends in that city, and discipline in the main,
well supported;
yet there appeared great danger of the prevalence of earthly mindedness in some,
and grandeur and wisdom above the simplicity of the Truth in others; which,
if not guarded against, might intrude itself to act and govern in the church;
of which Friends were warned,
and through the effectual opening of the fountain of wisdom and knowledge,
much caution and counsel were administered, to mutual edification and comfort.

On the 6th of the second month we visited the Monthly Meeting of North-Walsham,
where we found an honest sincere remnant concerned to maintain the principles of truth,
by a conduct consistent therewith;
yet a great defection appeared in some important branches of our Christian testimony;
the Monthly Meeting not having discharged its incumbent duty,
by way of admonition and dealing with such members.
Truth opened our way in much plainness and close labor,
in order to bring the unfaithful to a right sense of their states,
and to revive and promote our Christian discipline, as a means to restore ancient beauty,
and a good savor amongst men.
The path of the just, in which our worthy predecessors carefully walked,
was clearly opened before Friends in that meeting;
the judgment of Truth being set over those who had erred and strayed therefrom,
in this day of outward ease and liberty.

The 9th we visited Wells Monthly Meeting, in which humbling goodness prevailed,
to the great comfort and strength of the upright-hearted;
in a living sense of the free extendings whereof,
much labor was bestowed to restore good order and discipline in every part,
by first endeavoring to remove those impediments which appeared in the way.
It was a time of sweet comfort in a faithful discharge of duty.
The 11th we visited Lynn Monthly Meeting,
wherein our spirits were deeply afflicted under a cloud of darkness,
which seemed to overshadow that meeting,
occasioned by the prevalence of wrong things in many of the members,
and their great neglect of the due execution of wholesome discipline.
Much labor was bestowed in order for a regulation, but,
alas! great weakness and unskillfulness appeared;
neither was there that openness to receive help,
which we could have desired in the general.
I may also add, we had fresh occasion to say,
that nothing but an understanding renewed from above,
is capable of laboring successfully for maintaining our Christian discipline.
Oh! that this important point was duly considered by all active members.

The 13th we visited the Monthly Meeting of Wisbeach, in the isle of Ely;
it was a small meeting, as but few members belong thereto.
By inquiry, it appeared that slackness and disorder had prevailed on some,
and things in general were but low;
yet an openness was felt to receive proper advice and counsel, which,
through the gracious extendings of heavenly help, were freely and largely communicated.
We had cause to believe Truth was at work in the hearts of a few,
in order to prepare them for service;
having ease and satisfaction in our labor amongst them,
and hoping this visit would prove of considerable help to that meeting.
The 17th we visited the Monthly Meeting at Ives, wherein we had painful labor,
and found things much out of order, which caused darkness to be felt, and an ill savor;
some of the active members did not appear to us rightly to know what spirit they were of.
We found they were not one with us in our service,
which was indeed very close and searching to all stations in the church,
as it appeared all had need of help, and to look more narrowly to their standing.
Divine goodness was graciously with us, and carried us through,
to our ease and satisfaction in a good degree.
But alas! we have cause to see,
that our discipline does not prosper when managed with unsanctified hands.

The 18th we visited Hadingham Monthly Meeting, and found things very low,
as to the life of religion, consequently as to good order and discipline;
yet some appeared hopeful, tender,
and desirous of a proper regulation in the affairs of the church,
with whom we had good satisfaction in our labor for their improvement,
which I hope was not in vain.
The 20th of the second month, we visited the Monthly Meeting of Royston,
in Hertfordshire; the state of which appeared much out of order;
discipline was in the main neglected.
Very deep and painful was our labor,
under a mournful sense of that gross darkness which had prevailed,
by reason of unfaithfulness; yet the Lord was graciously with us,
and the testimony of Truth was exalted over the heads of disorderly walkers,
and all those, who, by a mean temporizing spirit,
had violated some principal branches of our Christian testimony.
We were unanimously of opinion, that the Monthly Meeting of Royston,
in its present state,
was too weak to manage the weighty affairs proper to a Monthly Meeting,
and therefore proposed its being joined to Baldock and Hitchin; which,
upon a solid deliberation, was agreed to, and has been since effected,
to the great satisfaction of Friends who have the prosperity of Truth at heart.
The 28d we visited Hertford Monthly Meeting, in which heavenly wisdom and merciful help,
as at other places were largely extended,
to the encouragement of a few sincere laborers amongst them,
as well as to the warning and stirring up of careless, unfaithful professors;
for there appeared much slackness in many,
in not improving those talents God had given them.

The 24th, we visited those under our profession at Coterhill-head,
called a Monthly Meeting; but, alas! upon inquiry,
we found very little was done of the business proper to a Monthly Meeting;
neither was it held in due course, but rather occasionally, for some particular purposes.
When the state of the members appeared, we did not marvel thereat,
seeing most of them were unfaithful in regard to that important testimony
against tithes and other anti-christian demands of that nature:
other great disorders also had crept in, nor can any other be reasonably expected;
for where persons are so void of a right zeal, as to sacrifice that noble testimony,
they have not strength to maintain other branches in a consistent efficacious manner;
so that where this defection has prevailed,
we have observed the most essential part in religion, amongst us as a people,
has fallen with it: meetings for worship and discipline are neglected,
and if sometimes held by such, they are to little good purpose,
and plainness and self-denial are departed from.
This hard, dark, tithe-paying spirit is so blind,
as to see but little in any branch of our testimony,
wherein there is a cross to the carnal mind.

Upon solid consideration we did not think, that using endeavors to regulate the meeting,
in its situation at that time, would answer any good purpose;
but the thing pointed out to us in the light of Truth, was its being dissolved,
and the members thereof joined to Hertford Monthly Meeting.
This had been endeavored for several years, both by their Quarterly Meeting,
and also several committees of the Yearly Meeting,
which had not till now proved successful,
as the consent of most of the members could not be obtained.
But this meeting, through divine favor,
was wonderfully overshadowed with a solemn weight of heavenly power,
which awed and tendered their spirits,
and at the same time mercifully enabled us clearly to demonstrate,
that they contended only for the name of a Monthly Meeting;
seeing the service of such a meeting was not answered, scarcely in any instance.
They at length generally yielded,
and a minute was made to propose a junction with Hertford, which is since effected,
to the great ease and satisfaction of Friends.
I cannot well avoid remarking here,
the very great hurt and obstruction to the progress of Truth, which I have many times,
with sorrow of heart, observed to arise by some active members, from private views,
strenuously withstanding the pointings of divine wisdom,
for the help and preservation of the body, which doubtless is in the Lord`'s sight,
a crime of a very offensive nature;
therefore all should greatly dread being in any degree guilty thereof.
Let us, at all times, carefully examine what ground we act upon in the church of God,
whether we always preserve the single eye,
being clothed with that pure charity which seeks not her own,
and filled with that universal spirit, that carefully promotes the good of the whole,
without respect of persons.

The 25th we visited Hitchin Monthly Meeting,
where we found a valuable solid body of Friends,
and discipline well maintained in most of its branches.
Heavenly goodness overshadowed that meeting,
whereby understanding was given to administer suitable caution and counsel;
particularly to point out the great danger of sitting down at ease,
in a becoming decent form, even after being eminently favored,
both with the dew of heaven and the fatness of the earth; notwithstanding which,
there must be a persevering in an earnest labor for daily bread,
seeing nothing beyond this can be attained by us, while in a militant state.
At the Monthly Meeting of Ampthill in Bedfordshire, on the 27th,
the Lord`'s awful presence being near, as, through infinite mercy, was generally the case,
opened the way for a close and diligent inquiry into the state of that meeting.
Things appeared low and pretty much out of order; the active members here,
as in many other places,
having neglected a deep and painful labor for a better regulation.
Endeavors were used, in order to stir up and provoke to love and good works,
by diligently extending a care over the whole flock,
that so all might be brought into the comely order of the Gospel.

On the 28th we visited Luton Monthly Meeting; it was small,
slackness and the lack of right zeal appeared; also some disorders had crept in,
yet there seemed openness in the minds of Friends to receive advice and counsel, which,
through divine aid, were largely administered;
and I hope the labor of that day was beneficial to several of the members,
and may prove a lasting advantage to that meeting.

The 2nd of the third month, we were at Alban`'s Monthly Meeting, held at Charleywood,
where, on the usual inquiries, things appeared very low and much out of order;
yet divine favor was largely and livingly extended for their help and recovery;
in a humble sense whereof, endeavors were used to promote a better regulation; first,
by the active members taking heed to themselves,
that they might be endued with ancient zeal and fervor of mind;
then they would take the oversight of the flock, not by constraint, but willingly.
This willingness,
through a neglect of seeking that divine power which
alone can bring it forth in the mind of man,
has been much lost or departed from by many,
and appears to be greatly wanting in most places; which, without doubt,
is one principal cause that so general a defection has prevailed.
Had the foremost rank stood faithful in the authority of Truth,
they would have been as a bulwark against undue liberties,
and happy instruments to preserve the body healthy and in beautiful order.
But oh! how shall I set forth and sufficiently admire,
the marvelous condescension of infinite goodness,
which so eminently manifested itself in all the meetings we were concerned to visit,
in order to bring back again the captivity of his people, to build up the waste places,
and to beautify the house of his glory.
May such evident tokens of his merciful regard
make deep and lasting impressions on all minds,
lest the Lord be justly provoked to cast many off,
and move such to jealousy by those who are now no people.

One very sorrowful instance of much degeneracy,
being an inlet for many other wrong things to creep into our Society,
is the great neglect of divine worship, especially on weekdays.
Some week-day meetings were wholly dropped, and in many places where they were kept up,
were attended by few; and by what appears,
many do not seem to think it their duty to attend them at all,
nor even first-day meetings, when small difficulties present.
This discovers remarkable ignorance of the great importance of that indispensable duty,
as well as of the great need all have, of a daily supply from the Lord`'s bountiful hand.
These opportunities of inward retirement and humble bowing before God,
have by experience, been found times of unspeakable refreshment,
which flows from the presence of the Lord,
who has graciously promised to be with those who meet in his name,
even where the numbers are but two or three: hereby strength is administered,
which enables us to stand our ground in the Christian warfare.
It is no marvel therefore, that the neglect of so important a duty,
is a cause of much weakness,
depriving people of a necessary defense against the
numerous and potent enemies which war against the soul.
Here he that goes about like a roaring lion, and also as a creeping subtle serpent,
prevails, in order to lay the Society waste;
and while many are asleep in carnal security,
he finds opportunity to sow tares amongst the wheat.
Very deep and fervent were our labors in this visit,
to promote diligence in this most important duty, as a means under the divine blessing,
for the restoring ancient beauty and comeliness throughout the Society.

This opportunity at Charley-wood, finished our present visit to Monthly Meetings;
we having requested the Quarterly Meeting to which they belonged,
to adjourn in such order, as to be visited in course by us at one journey,
to begin in Luton, for Bedfordshire,
which accordingly was held the 8th of the fourth month, 1761.
John Emms, Thomas Corbyn, Samuel Scott, Joseph Row and myself attended the same,
and laid before the Quarterly Meeting in writing, the state of their Monthly Meetings,
as the same appeared to us by their answers to the Quarterly Meeting queries,
and other inquiries made in our late visit, with sundry remarks thereon;
and through the overshadowing of heavenly power,
we were fervently concerned to bring the weight of the
declined state of the Society there upon the meeting,
wherein an engagement of mind was revived for a reformation:
may the same continue and increase.

On the 10th of the fourth month we visited Hertford Quarterly Meeting,
where our friend Joseph Taylor, who had been indisposed, joined us.
Having previously drawn up the state of their Monthly Meetings,
as the same appeared to us in our late visit, with remarks thereon,
we laid it before the meeting, which they took into solid consideration,
and a solemn time it was.
The Lord`'s power being livingly felt, it made a remnant willing to arise,
that the breaches made in that excellent hedge of discipline,
set by divine wisdom about us as a people, might be repaired,
that the heritage be not laid waste.
On the 14th of the fourth month, we visited the Quarterly Meeting at Ives,
for Huntingdonshire, Cambridgeshire, and the isle of Ely; where,
having drawn up the state of their Monthly Meetings,
as the same appeared to us in our late visit, with some remarks thereon,
we laid the same before them,
with earnest labor to awaken the active members to a lively
sense of the sorrowful declension found within their borders.
It was a painful exercising time, great insensibility having prevailed over many;
yet I believe it was a season of comfort and relief to a living remnant,
who travail for the prosperity of Truth amongst them: may their number increase!
We had the return of sweet peace in the discharge of our duty,
and departed with cheerfulness of mind.

On the 21st of the fourth month,
we visited the Quarterly Meeting for the county of Norfolk, held in the city of Norwich;
where, as usual, having drawn up the state of their Monthly Meetings with some remarks,
the same was solidly laid before the meeting.
Divine goodness was manifested;
in the wisdom and strength whereof much earnest labor was bestowed,
in order that all the active members especially,
might be stirred up to an exertion of godly endeavors,
for restoring comely order and discipline in
several very weak meetings within their county;
and not to be at ease in their paneled houses,
while the ark of the testimony of God was exposed to reproach,
by the defection of many under the same profession.
It was a good time, and I hope serviceable to some; yet we could not help lamenting,
that the memorable opportunity we lately had at Norwich Monthly Meeting,
had not made greater impression than appeared by some
not very agreeable instances in this meeting,
relating to their fully uniting for the county`'s help,
as there was apparent necessity for the same.

The 24th of the fourth month,
we visited the Quarterly Meeting of Suffolk held at Woodbridge,
and laid before them in writing, the state of their Monthly Meetings,
as the same appeared to us in our visit, with some remarks thereon.
Much labor was bestowed in the free extendings of divine love,
which was comfortably shed abroad in that meeting,
that Friends might be stirred up to use endeavors for a general reformation.
Fervent labor and close admonition were extended to such as
knew not their own spirits subjected by the spirit of Christ,
but dared to presume to move and act in the affairs of the church of God,
by the strength of their own understandings as men: these not having true zeal,
can wink at wrong things, great disorders and flagrant unfaithfulness,
smoothing all over, and blending all together deceitfully, crying peace, and all is well,
when it is evidently otherwise.
Oh, how does the Lord abhor such unsoundness! surely then his people
should see the weight and authority of his power standing over such.

A principal cause of desolation and waste in the house and heritage of God,
is the lack of more prepared stones for the building, hewn and polished in the mountain.
But great inconvenience arises, when some are made use of as stones for the building,
in their natural state,
which renders them unfit materials to erect a house for the glory of God to abide in;
so that what such build, is nothing but a habitation for anti-christ;
for he will content himself in any form of religion,
while he can keep the power out of it.
His first subtle working in the mystery of iniquity,
is to persuade the mind that there is no need of
any more power and wisdom than they have as men;
that if they will exert their endeavor, they may be useful members;
thus withdrawing gradually from the Fountain of living water,
to hew out cisterns to themselves, which will hold no water.
Oh, how dry and insipid are all the religious performances of such! and what they do,
is only to beget in their own image, carnal lifeless professors like themselves.
These are very apt to be doing, being always furnished; but the true laborers must,
in every meeting, and upon all occasions that offer for service,
receive supernatural aid and the renewed understanding,
by the immediate descendings of heavenly wisdom and power, or they dare not meddle.
Where there are but two or three in each Monthly Meeting,
carefully abiding in a holy dependance upon God to be furnished for his work,
great things may be done by his mighty power, in and through them.
This is evident, by observing the state of meetings where such dwell,
though all is not done which they ardently desire; but praised be the Lord,
there are many yet up and down,
who know and experimentally feel their sufficiency for
every service in the church to be of God.

The 28th of the fourth month, we attended the Quarterly Meeting I belong to,
held at Coggeshall, for the county of Essex.
Having drawn up the state of the several Monthly Meetings in writing,
with remarks thereon, it was laid before this meeting,
and solid and weighty endeavors used for a general reformation,
by the earnest labor of our friends on the visit,
which was very edifying and comfortable to the honest hearted amongst us.
We drew up a summary account of the state of the
Society in the counties before mentioned,
and our satisfaction in that solemn undertaking;
with thankful acknowledgment of the Lord`'s gracious assistance through the whole,
which was read in the Yearly Meeting, 1761.
Before I close this account, it may not be amiss to say,
that such was the effect of our labors in most or all the Monthly Meetings,
that committees were appointed of their own members,
to visit particular meetings and also individual members, for their help,
as occasion might require.
The Quarterly Meetings also appointed large committees
to visit their Monthly Meetings and others,
as they found freedom, for their assistance.

A few days after the Yearly Meeting in London, 1761, Thomas Corbyn,
Joseph Row and myself, set out in company with several other Friends,
on their return from the Yearly Meeting,
in order to visit the Monthly and Quarterly Meetings of Friends in Yorkshire,
Lincolnshire, Nottinghamshire, Derbyshire, and Leicestershire.
Matthew Mellor joined us at Oatby, near Leicester;
Joseph Taylor having concluded to meet us in Yorkshire.
On the 24th of the fifth month, we visited Balby Monthly Meeting, held at Sheffield,
and found to our comfort, a living body of Friends therein;
yet much slackness and defection appeared in many members of most ranks.
Truth opened and largely furnished with wisdom and strength,
to lay before them the dangerous consequences of some prevailing and undue liberties.
Those advanced in age and profession,
were entreated and labored with in much earnestness, to be more zealous and diligent,
in a godly care over themselves and the flock,
as those that must shortly give an account to the great Shepherd.

The 25th we visited Pontefract Monthly Meeting, held at Highflats.
Here was a very numerous body of Friends,
whose outward appearance was very becoming our self-denying profession;
and I really believe this plainness, in a considerable number amongst them,
was the genuine product of a well regulated mind; yet I fear, in many,
it was more the effect of education, which, however, I would not condemn,
where people are not prevailed upon by the subtlety of satan to take their rest therein;
since the form must follow the power, and not the power follow the form.
We had close labor, in order to arouse those who had settled down in a false rest,
and also to promote a better regulation in some respects;
yet I think it might be said that discipline, in most of its branches,
was pretty well maintained in that meeting.
It was a time of high favor; and counsel and admonition were plentifully extended.
The 27th we visited Brighouse Monthly Meeting, held at Bradford:
here Jonathan Raine and William Hird joined us.
This meeting was exceedingly large; some slackness and defection appeared,
yet in the main, discipline and good order were well supported in several branches.
It was indeed a time of signal favor,
as the canopy of divine power and love overshadowed this large assembly,
wherein much fervent labor was extended, that all might be brought into and preserved in,
that humble self-denying way which leads to lasting peace and happiness;
and that none might rest satisfied in a form of religion,
without the daily quickenings of heavenly life,
whereby only the daily sacrifice can be offered, and the abomination that makes desolate,
kept out of the holy places.
The heart of man is only made and preserved holy by the powerful presence of God;
no longer can it be so, than his presence is there.

The 29th we visited Knaresborough Monthly Meeting, held at Rawden.
This was also very large, perhaps nearly five hundred of both sexes attended,
and nearly as many at each of the before mentioned meetings.
Here we found a weighty, solid body of Friends,
who were zealously concerned to preserve discipline and good order on its ancient bottom;
yet there was also a very heavy, clogging, lifeless body, at rest in a profession,
in whom little or no living concern appeared to
keep undue liberties out of their families,
and to show exemplary diligence in religious duties.
Divine goodness, as at other times, was eminently manifested, in which,
abundance of sound advice, caution and counsel, was freely administered,
wherewith many hearts were deeply affected, being made willing to arise,
in order to promote a reformation where things appeared out of order.
The 1st of the sixth month we attended Settle Monthly Meeting,
which was a laborious exercising time,
in a deep and painful sense of the numbness and formality of too many members,
and the great decay of primitive zeal;
yet through the merciful arising of heavenly power and wisdom,
ability was received to administer suitable advice, warning and counsel,
in order to awaken the careless, lukewarm professors,
as well as to extend comfort and relief for the encouragement
of a sincerely concerned remnant amongst them;
that so, what appeared out of the holy order of the Gospel, might be regulated.

The 3rd of the sixth month, we visited Richmond Monthly Meeting, held at Aisgarth;
the number of members here was very considerable,
yet the life of religion seemed at a low ebb.
That sorrowful mistake,
of imagining themselves God`'s people without the
real sense of the indwelling of his holy Spirit,
and of being the children of Abraham without the faith and good works of Abraham, has,
I fear,
very much prevailed upon the posterity of faithful worthies who are gone to their rest.
In those parts,
great slackness and defection in some very important respects appeared in many, who,
through the powerful efficacy of the everlasting Word,
were closely and very pressingly admonished to more care and diligence.
Great endeavors were used,
that our Christian discipline might be more duly put in practice;
a living remnant amongst themselves,
heartily joining with us in our deep labors for promoting that salutary end.
The 5th, Thirsk Monthly Meeting was visited; Joseph Taylor joining us here.
We were now seven in number, which we did not find too many,
the work we were engaged in being very weighty and laborious.
In this meeting,
a remnant were sincerely concerned to maintain discipline and good order,
in the spirit and life thereof; yet great lukewarmness and many deficiencies appeared;
an earthly carnal spirit having much the ascendency in parents, and rawness,
insensibility, and a deviation from plainness, in many of the youth;
which caused us deep and painful labor; yet, through the descending of heavenly virtue,
we were enabled to speak closely to their states, which, I hope,
had a good effect on some of them.
This opportunity afforded much relief to our spirits, and we went away with peace.

The 8th we were at Gisborough Monthly Meeting, held at Kirbymoorside;
where a very large number of members attended,
with an outward appearance becoming our holy profession,
and we found a truly concerned remnant amongst them.
But at this, as well as at other places, we had, with sorrow of heart,
to view the great desolation that an enemy had
made in the time of outward ease and liberty.
He could not prevail upon our worthy predecessors, by depriving them of their liberty,
in jails and stinking dungeons; separation, by banishment and otherwise,
of those in the nearest ties and connexion of life.
No, the loss of all their outward substance, and the lives of many,
could not deter them from maintaining their testimony
for God in public worship and other things;
yet he has mightily prevailed on many of their inconsiderate offspring,
who seem to have very little besides the husk left to feed upon.
Divine goodness was wonderfully extended, in which much fervent labor was bestowed,
and it was an awakening time.
The foundation of the builders upon the sand was shaken, and Jesus Christ,
the everlasting rock and sure foundation, was exalted,
as the only safe rest and defense of his people.

The 11th we visited Malton Monthly Meeting; the state whereof appeared very low,
and things relating to our discipline much out of order.
Divine goodness being near, our minds were strengthened and our mouths opened,
in earnest endeavors for their help and recovery;
a small remnant amongst themselves joining with us herein.
I hope it was a profitable time to some.
The 13th we visited Scarborough Monthly Meeting, held at Whitby, where,
although we found a sincere remnant with whom we had unity in spirit,
and they had a satisfactory sense of our close and earnest labors in that meeting;
yet many under the same profession were greatly backslidden and revolted
from the primitive power and purity of that undefiled religion,
which the faithful amongst us have been and are led into.
Divine help was eminently manifested, in order to heal their backsliding,
and to bring them into a due sense of the weight and great
importance of those testimonies to the blessed Truth,
given to us as a people to bear, which made good impression on some;
but others seemed at so great a distance,
that it was hard to make them rightly sensible of their true interest.
We departed from there with ease and peace of mind.

The 14th, Bridlington Monthly Meeting was held, which was very small,
and the life of religion very low;
but little ability and judgment to manage the affairs of the church appeared.
It was our opinion, they were too weak to subsist honorably as a Monthly Meeting,
and that it would promote the general good, to join them to some other Monthly Meeting.
The 17th, Oustwick Monthly Meeting was held at Hull.
Upon the usual inquiries, it appeared that much lukewarmness and defection had crept in;
and for lack of a godly zeal in most of the active members,
discipline had not been strictly and impartially maintained,
so that darkness and weakness had prevailed.
In this mournful state of things, our labors were painful and exercising; yet,
through divine assistance, the testimony of Truth in its several branches, was exalted,
and judgment set upon those who had violated the same.
The few sincere-hearted laborers amongst them were earnestly advised and encouraged
to bear the ark of the testimony of the Lord as upon their shoulders,
in the people`'s sight, which I hope had a good effect.
The 19th, we visited the Monthly Meeting of Cave.
The appearance of the members was plain,
yet we found great deadness and insensibility amongst them,
which must be the case where people are contented in an empty form of religion,
without the power of it.
Much Christian labor was bestowed in order to kindle a living zeal; but,
alas! little impression was made on some,
yet I hope this visit was of considerable service to others,
and may tend to general benefit; but all the increase is of the Lord.

The 21st we visited York Monthly Meeting,
wherein appeared much lack of a lively sense of Truth on the minds of active members,
and many deficiencies and some disorders, had crept in and remained,
by a neglect of proper dealing and the exercise of sound judgment.
Here we had cause to see, as well as at many other places,
that a literal knowledge of our discipline,
without heavenly life influencing the minds of those exercised therein,
brings nothing effectually to pass, to God`'s glory,
and the edification of his church and people.
Great and deep was our labor, under a weighty sense of the divine power,
and also of the low, languid state of the church in this city,
desiring she might be favored to arise and shake herself from the dust of the earth,
strengthening the things which remain.
This finished our visits to the Monthly Meetings in this county;
and though I have not particularly mentioned the opportunities
taken by us in select meetings of ministers and elders,
yet we had such opportunities in most or all the Monthly Meetings;
where the queries were read and answered, advice, caution, counsel and reproof also,
were administered, as we found ourselves led and influenced thereunto.

The 24th of the sixth month, the Quarterly Meeting was held in York.
We had drawn up the state of their Monthly Meetings, being fourteen in number,
as the same appeared to us from their answers to the usual queries,
and other inquiries made by us in our late visit to them, with remarks thereon,
particularly on the great and mournful slackness in, and neglect of, divine worship;
especially on week-days,
which discovers an indifference and lukewarmness much to be lamented.
Earnest labor was bestowed in that great meeting,
to fasten on the minds of Friends the weight and great
importance of qualified members coming more earnestly and
feelingly under a deep sense of the care of the churches;
that so an increase of zeal and diligence may be exercised throughout,
in warning the unruly, comforting the feeble-minded, and in supporting the weak.
It was a solemn time,
the members being sensibly affected with the great need
of a better regulation in several respects;
and a large committee was appointed to visit and
assist the Monthly and Particular Meetings,
as they saw cause, in order to help forward the necessary work of reformation.
The Monthly Meetings also, except one,
in consequence of our visit appointed committees
to visit Particular Meetings and individuals,
as their way might open,
to promote the better putting in practice of our Christian discipline.
In this city, our friend John Hunt of London joined us;
and here we parted with Jonathan Raine, Matthew Mellor and William Hird.

We went next into Lincolnshire, and en the 29th of the sixth month,
visited their Monthly Meeting, held at Gainsborough, where John Oxley of Norwich met us.
Things appeared very low and defective,
as to the discipline and good order of the church in this place;
many of the members being, through indifference and weakness,
insensible of its great worth and usefulness.
Our spirits were deeply baptized into a sense of their states, and we received ability,
with great plainness, to lay before them the dangerous consequence of such an unsavory,
unfruitful condition, and the great duty which the members of society owed to God,
themselves and to one another, in a religious capacity,
which for the present seemed to affect their minds; may the impression be lasting!
We had also some things to offer by way of encouragement, to a few sincere,
though weak ones amongst them.
The 2nd of the seventh month, we visited Wainfleet Monthly Meeting,
finding things distressingly low and much out of order;
and but few who had the cause of Truth at heart,
so as to mourn because of the great desolation and waste made in the Society there,
by earthly-mindedness and other fleshly liberties.
Our minds were deeply engaged that Truth might break through,
and soften the minds of those dry, carnal professors, who,
instead of helping forward the necessary work of discipline,
were great clogs and hindrances thereto,
being as dead weights on the more lively part of the body.
Through the holy efficacy of that pure life,
which graciously attended us from place to place,
we were enabled to discharge our consciences at that meeting, in much plain dealing,
to our own peace and the comfort and relief of the few upright-hearted amongst them.

The 4th we visited Spalding Monthly Meeting,
where also much disorder and slackness appeared in some; others,
who would seem to be something in religion,
were but too much like the unfruitful fig tree, on which,
when it came to be nearly examined, nothing was to be found but leaves; having,
like Ephraim and Demas, forsaken the dew and tenderness of their youth,
and embraced this present world.
Such, though they retain something of the outward resemblance,
cannot prosper in religion, as they are dry and insipid.
In this low, mournful state of things, Truth arose,
and furnished with suitable matter and utterance,
in plain dealing with formal professors,
and proper encouragement to some hopeful youth and others,
to come up in a more lively zeal and concern for God`'s cause,
than had been maintained of late at that meeting, which I hope was of good service.
The 6th we visited Lincoln Monthly Meeting, held at Broughton.
This meeting appeared in a very low condition, as to a lively sense of Truth;
the discipline thereof was not rightly managed, being done much in the will, wisdom,
and temper of man.
Some appeared hopeful and tender, especially of a younger rank, to whom, I hope,
our deep and earnest labor amongst them was profitable.

The 8th of the seventh month, the Quarterly Meeting was held at Lincoln;
before which we laid in writing,
the languid and disorderly state of the Society in that county,
with close remarks thereon, pointing out, in some measure,
the cause of the great declension found amongst them.
This was accompanied with our joint and earnest endeavors,
to bring the weight of those things upon the members,
that they might feel a proper engagement of mind to arise and repair the breaches made,
which had a good effect on some minds,
and a committee was appointed in order to promote the work of reformation;
which was also done at most, or all their Monthly Meetings.
From Lincoln, John Hunt and Joseph Row returned home to London,
and John Oxley to Norwich; Thomas Corbyn, Joseph Taylor and myself,
went into Nottinghamshire.

The 13th of the seventh month we visited Retford Monthly Meeting, as it was called,
wherein we found a few tender and hopeful,
and had some openness to administer counsel and advice,
tending to their help and improvement, which appeared to be well received,
and some minds were affected therewith;
yet very little was discovered by us of discipline being put in practice,
but almost every thing relating thereto was neglected.
It was our judgment they ought to be joined to some other Monthly Meeting,
yet their situation rendered that somewhat difficult; however,
we concluded to lay the case before their ensuing Quarterly Meeting.
The 14th we visited Mansfield Monthly Meeting, which also appeared very low and weak;
but very little of the business of a Monthly Meeting being properly done,
as the number was very small that generally attended,
and in most of them the essential qualification for
service in the church of Christ was much wanting.
It was therefore our judgment, that it would be for the general good,
that Mansfield Monthly Meeting should be joined to that of Chesterfield,
except Oxon Particular Meeting;
which from its situation might better be joined to Nottingham.
The 15th we visited Chesterfield Monthly Meeting,
wherein divine goodness was livingly manifested,
in order to administer proper assistance, by way of advice, counsel, and encouragement,
to this small, weak meeting, wherein discipline, in several of its branches,
was much neglected;
yet there appeared an openness in the members to be
instructed and helped forward in that weighty work,
which, through the strength and efficacy of divine love, was largely extended to them,
in which we had satisfaction of mind.

The 16th we went to Breach, called a Monthly Meeting, but we found it in that respect,
almost desolate.
The testimony of Truth, so precious to their ancestors in that place,
was by them allowed to fall, in most of its branches;
but few of those who were active members, appearing clear in its support.
Darkness had greatly prevailed over their minds, yet our deep labor,
under the influence of heavenly good, had a tendering effect upon some of them.
One thing aimed at by us was,
that the members of that meeting might be joined to the Monthly Meeting of Nottingham,
they being unfit to remain in their present condition, which was consented to by them,
a minute made,
and some of their members appointed to propose the same to Nottingham meeting.
The 17th we visited Nottingham Monthly Meeting; the number here was pretty large,
but the pure virtue of heavenly goodness,
without the sensible experience whereof there can be no prosperity in the Truth,
seemed to be much depressed and obstructed by earthly-mindedness,
covered over with a form of religion in some heads of families,
by whom undue liberties were winked at in their offspring:
such not having zeal enough to suppress wrong things in their own families,
are not likely to promote good order and discipline in the church.
We found some who united with us in a deep and earnest labor for a better regulation,
and much sound admonition, caution and counsel, were administered, which seemed,
at least for the present, to have an awakening effect on some.

On the 20th of the seventh month, the Quarterly Meeting was held at Nottingham,
and as we understood, a junction of that and the Quarterly Meeting of Derbyshire,
was agreed on between them, and shortly to be completed,
we drew up the state of the Monthly Meetings in both the said counties,
as the same appeared to us in our late visit,
with remarks on the mournful declension found amongst them,
pointing out to them in some measure, what we apprehended to be the cause thereof,
that those concerned might both examine themselves and be more watchful,
in order to prevent such consequences for the future.
This was read in this meeting, and endeavors used verbally also,
that the meeting might come under a solid sense of the state of their Monthly Meetings,
that proper assistance might be extended for a general reformation.
But, alas! there were but few amongst them enough devoted,
heartily to engage in so good and necessary a work; however,
we were enabled to clear ourselves, by leaving the weight of things upon them,
and to depart with ease and sweet peace of mind.
All praises and humble thanksgivings to our holy Head,
for his gracious and comfortable support,
in our deep exercises and labor from place to place.
For, alas! we should soon have fainted under the weight of that painful service,
had he been pleased to withdraw, even but for a little time;
but we found him a never-failing Fountain of all we stood in need of,
and when our service for this time was over, we could not say we lacked any thing.

The 21st of the seventh month we visited Castle-
Donnington Monthly Meeting in Leicestershire,
wherein divine favor was largely extended,
in which we received strength to labor earnestly,
for the reviving of a living concern in the members,
that discipline and good order might be better maintained, which,
through the indifference of some, and the backward, cowardly disposition of others,
was but poorly supported in sundry respects.
This opportunity seemed to have a good effect,
by a considerable reach upon many of their minds,
and I hope may prove of great advantage to that meeting,
as the members thereof seemed rather weak than willful.
The 24th we visited Hinkley Monthly Meeting, which,
as to the support of discipline and Gospel order, appeared almost desolate.
Our earnest labor for their help and recovery had
little visible impression on some of their members,
the insensibility was so great;
though others were awakened to a degree of feeling and tenderness, who, I hope,
received some benefit thereby.
The best expedient that appeared to us,
was their being joined to Leicester Monthly Meeting, which was accordingly recommended.
The 25th we visited Dalby Monthly Meeting;
and as it appeared in the same state as that last mentioned,
I shall refer to that account, and only say,
we advised it should be joined to the Monthly Meeting of Castle-Donnington,
except a small branch thereof, which lay contiguous to Leicester.

The 27th we were at Oakham Monthly Meeting,
where much slackness and indifference appeared,
too many of the active members being at ease in a profession,
while wrong things prevailed, and death instead of life, overshadowed their meetings.
The Lord engaged us in a deep and fervent labor, to stir them up,
that they might arise and shake themselves from
the dust and clogging things of the earth,
to receive the eye-salve of God`'s kingdom,
whereby they might come to see their own state as individual members,
and also the general state of the church.
Oh, how ashamed would some then be, of their poverty and nakedness!
We found a few amongst them in a humble, teachable frame of mind,
with whom we had good satisfaction,
hoping this opportunity might tend to their help and improvement in the best things.
The 28th we visited Leicester Monthly Meeting,
in which we found some honest laborers for Zion`'s prosperity, and Truth opened our way,
as at other places, to look carefully into the state of things,
and to apply suitable counsel and advice, as the same immediately opened,
for restoring good order and wholesome discipline, which appeared much neglected;
and I hope the opportunity was of good service to that meeting.

On the 29th of the seventh month,
the Quarterly Meeting for the county was held at Leicester, before which,
we laid in writing the state of their Monthly Meetings, as it appeared to us,
with such remarks as seemed proper and necessary; and were deeply concerned,
to bring a weighty sense of their great declension upon
the spirits of the active members,
and the great necessity of a speedy exertion of
their Christian endeavors for a regulation,
lest a general desolation should ensue.
But, alas! the stupefaction was so great in this as well as other places,
that it was hard laborious work; yet not without hope of a revival,
as some concerned members were, by the overshadowing of divine power,
made willing to give up their names,
to contribute their endeavors for carrying on the necessary work of reformation,
so happily begun in the Yearly Meeting.

Here ended our visit to Monthly and Quarterly Meetings for the present; and I have,
with deep reverence, humbly to acknowledge,
that a remarkable evidence of divine approbation attended us throughout;
making us of one heart by the baptism of his unerring Spirit,
so that scarcely a difference of sentiment from
one another appeared during the whole journey.
Another thing which appeared to me a token of divine favor attending,
was the open reception we met with, notwithstanding the plainness used by us,
in very close searching inquiries and remarks upon many disorders.
I hope my usual freedom, in laying open the states of the Monthly Meetings,
will give no just cause of offense to any who wish well to Zion,
since nothing is more likely to strike the minds
of succeeding generations with fear and care,
than to have the lukewarmness and defection of many,
who have been so wonderfully favored, set in a true light before them,
together with such a remarkable account of the
Lord`'s compassion and condescending kindness,
in seeking their restoration, and offering his mercy to heal all their backslidings.
How can any, without being somewhat affected with fear,
read the sorrowful degeneracy of some Christian churches, even in the apostles days;
like the first fruits in the Gospel vineyard;
particularly that of the seven churches in Asia Minor, discovered to the beloved John,
in his state of banishment for the word of God and the testimony of Jesus Christ,
and by him with great plainness committed to writing,
as a call and warning from God to them, and to remain, for the same end,
to all succeeding generations?
I have no other end in what I have written concerning the state of our Society;
for whose help and preservation I have been freely given up in body, soul and spirit,
as well as in what outward substance the Lord has bountifully favored me with,
to contribute my small endeavors, that her light may go forth as brightness,
and her salvation as a lamp that burns.

A summary account of this visit and service was drawn up by us,
and read in the Yearly Meeting of 1762, as had been done the year before,
when engaged in a service of the like nature.
A similar visit was also performed by other Friends, who had, since the Yearly Meeting,
1761, engaged therein in different parts, and all the Monthly and Quarterly Meetings,
in that part of Great Britain properly called England, had then been visited; which,
as far as appeared, had been performed to general satisfaction.
The Yearly Meeting then recommended to the Friends appointed in 1760,
the care of extending the same brotherly assistance to
the meetings of our friends in Wales,
Scotland and Ireland, as their way might open in Gospel freedom.
Neither did the Yearly Meeting omit sending a warm,
lively epistle to those already visited, to corroborate,
revive and strengthen the great labor bestowed, that the same might be made effectual.
I shall now close this narrative with just adding, that I have found by solid experience,
it was a blessed work, and greatly blessed in carrying on.
May it be so in the fruits arising therefrom, is the sincere desire of my soul.

The 21st of the eighth month, 1762, I set out,
in order to visit London and some other parts, and on first-day the 22nd,
I went to Ratcliff meeting in the morning, where I had close, thorough service;
Truth and its testimony having considerable dominion.
It was an awakening time to careless professors,
and of refreshing consolation to Zion`'s travelers,
of whom I believe there was a considerable number there;
I had with satisfaction to believe that meeting was on the improving hand.
I went in the afternoon to Horslydown; this was a time of deep travail and painful labor,
as the life of religion seemed to be greatly depressed,
by much indifference of mind in many, and the prevalence of fleshly liberties in others;
yet through infinite condescension, at length the power and virtue of Truth arose,
whereby the testimony thereof was exalted over wrong things.
On the second-day following I attended the morning meeting,
and went on fourth-day to their Monthly Meeting at the Peel, in which,
through the extending of heavenly good, I had open, edifying service;
Friends being favored with a degree of that holy leaven, which, as it is abode in,
preserves the several members of one heart and one mind.
Oh, then the work goes sweetly on, the body edifying itself in love,
as well as with one voice giving forth sound judgment against wrong things.

On first-day, the 29th, I went in the morning to Westminster,
which was a very open good meeting, the testimony of Truth went forth freely and largely,
wisdom being given to divide the word aright, so that the disobedient were warned,
and the mourners in Zion comforted.
I went in the afternoon to the Peel meeting, which was large and very laborious,
in suffering silence throughout; which,
in sympathy with the depressed Seed of God`'s kingdom,
and for an example to the professors thereof,
appeared to be my proper business at that time.
I attended the morning meeting on second-day,
and went on third-day to Plaistow week-day meeting, in which I had some close service;
but the life of religion appeared to me low there,
the professors of Truth neglecting a constant labor for daily bread.
I spent that afternoon and the next day,
chiefly on a visit to our worthy friend John Hayward, who appeared green in old age.
On fifth-day, the 2nd of the ninth month, I went to Tottenham;
there being two considerable Friends`' schools, one for boys, and the other for girls.
By the free opening of the living fountain, it was a very precious, comfortable meeting,
doctrine and counsel being plentifully handed forth,
suitably adapted to the children`'s weak capacities, as well as to those of riper age:
through the divine blessing,
it was a time of favor and refreshment to the upright in heart.
That afternoon I had a very comfortable reviving
time with our friend Josiah Forster and family,
he being in a very poor state of health,
in appearance not likely to continue long in this world; with much tenderness,
he expressed great satisfaction in that opportunity.

On sixth-day, the 3rd, I went to Gracechurch street meeting, which was low and laborious;
it appeared my proper business to sit in silence.
On first-day, the 5th, I went to Grace-church street in the morning,
where the meeting was exceedingly large, and for a time, very trying and painful;
yet in the latter part, it pleased the Lord to arise and his enemies were scattered;
then was Truth exalted, and its testimony went forth freely, having great dominion.
In the afternoon, I went to the Peel meeting, where I had large, open service,
and Truth was over all;
it being a time of much comfort and relief to the sincere-hearted.
Next day I was at the Monthly Morning meeting of ministers and elders, so called,
because the members more generally attend, especially the women.
It was a blessed time, wherein I had open good service,
showing the great difference between the ministers of the letter and those of the Spirit:
that the letter without the Spirit,
kills that which is begotten of God in the hearts of people;
and that it is the holy power, efficacy and demonstration of the eternal Spirit,
which render the Holy Scripture, outward ministry, and all other means ordained of God,
for the comfort, help and preservation of his people, effectual.
I had to observe,
that the ministers of the letter were most of all
concerned for the external appearance of their ministry,
that is, that the words and doctrine may be curiously adapted, not to disgust,
but rather to please those who have itching ears; on the contrary,
the ministers of the Spirit are least of all concerned
about the outward appearance of their ministry;
having no doubt, if they are careful in the spring, ground, and moving cause,
which they know should be the constraining power of the holy Spirit,
the other will be agreeable thereunto;
seeing that power is able to render the most low and simple expression, in man`'s account,
exceedingly efficacious.

On third-day, the 7th, I set out, accompanied by several Friends,
in order to have a meeting that afternoon at Charley-wood;
it was a time of awakening labor, I hope not easily to be forgotten.
On fourth-day, the 8th, I had a precious, open,
serviceable meeting at Jordan`'s in the morning; it was a time of general awakening,
at least to a present sense of duty:
the afternoon meeting at Uxbridge was painful and laborious,
and what made it more afflicting was,
that the Gospel endeavors used for the help and recovery of lukewarm professors,
seemed to take very little effect upon their minds.
On fourth-day, the 8th, I went to Staines meeting, which, in the fore-part,
was a time of very heavy, painful, silent labor; in which,
as at many other times on the like occasion,
I fully expected the cloud and distress would remain, till we separated one from another;
yet near the conclusion, through infinite condescension,
Truth arose and obtained a complete victory over wrong things;
their states being spoken to with great plainness; but,
alas! the life of religion seemed low amongst most of all ranks there.
I went next day to a meeting at Godalming, which proved a time of much favor,
in the sweet and precious enjoyment of the consolating streams of that river,
which makes glad the whole city of God; in the blessed efficacy whereof,
the doctrines of Truth were largely opened, setting forth the nature of faith,
hope and charity; that the greatest of all is charity,
as faith will be swallowed up in open vision, and hope in the full enjoyment;
but charity never fails nor changes its nature, being the same in time and in eternity.

On first-day, the 12th, I was at Alton in Hampshire,
where we had a very large precious and baptizing meeting; in the morning,
the testimony of Truth had great dominion,
and the living members were sweetly comforted together.
The afternoon meeting was very heavy and laborious, and held in silence.
I had a very open satisfactory meeting at Esher, on third-day the 14th,
and another at Wandsworth the next day; after which I went to London, and the next day,
being the 16th of the ninth month, I returned home, finding my dear wife and family well:
having, through infinite kindness, been much favored in my service this small journey,
and found more openness in the city of London than heretofore.
It was with great comfort I saw a growing hidden remnant in that city,
who will be exalted in Israel in the Lord`'s time; who has,
and will yet open a way more and more,
for his pained traveling children to exalt his name and Truth,
by removing the stumbling-blocks and other impediments which remain in their way,
and hinder them, in some measure, from taking the rule and government,
which is their due and right in the kingdom of Christ; and usurpers shall see,
that none can sit with Christ upon thrones,
but those who faithfully follow him in the regeneration,
agreeably to his gracious promise, namely, Matt. 19:28, and Luke 22:30.

To this period of time, being now in the fiftieth year of my age,
I have continued an account of divers occurrences of my life, labors and experiences,
with observations on the state of the Christian Society of which I am a member;
and though done in a way of plain dealing, yet in truth and sincerity,
as my mind has been immediately led and opened thereunto.
Let none take any undue advantages thereby to reproach the Truth;
for no society of Christians, that I have had any knowledge of,
has any advantage of this people, either in principle or practice.
Here I intend to lay aside my pen for the present,
not knowing that time or ability will be given to add any more,
which is all in the Lord`'s hand; to whom I humbly commit this, with my soul and body,
for preservation,
during the short space of time he may be pleased yet to lengthen my days;
beseeching that his blessing may attend what is done; without which,
our endeavors are fruitless, for all the increase is in him and by him,
who is glorious in holiness, and fearful in praise.
To whom be dominion and glory, through all ages and generations.
Amen.
