== Chapter 10

[.chapter-synopsis]
* Prospect of a religious visit to America and his proceedings preparatory thereto
* Embarks at Gravesend arrival in Philadelphia labors within the limits of that Yearly Meeting
* Visits Virginia and Carolina
* Returns to Philadelphia
* Sets out for New England and proceeds as far as Boston and Salem then to Oblong and New-York
* Attends meetings in Bucks County, Pennsylvania, and in Delaware and Maryland
* Returns home.

From the year 1762, to the seventh month, 1765,
I have preserved no particular memorandum of my travels and service that I can find,
and although I traveled no considerable journeys, yet,
as I always thought it my incumbent duty,
from my first acquaintance with God`'s everlasting Truth,
I diligently attended meetings when at home and well, both first and week-days,
also the Quarterly and Yearly Meetings, as they fell in course;
as well as some adjacent Quarterly and other meetings, In the year 1764,
I attended the Yearly Meetings of Colchester, Woodbridge and Norwich,
to good satisfaction and comfort, being favored with free open service therein,
especially the two last.
In the same year, having an inclination to visit London and some parts adjacent,
as my way might open; and likewise having a manuscript by me,
which I had written about two years before,
containing brief remarks upon sundry important subjects, several Friends,
whose judgment I valued, having perused it, expressed their unity therewith,
generally apprehending there might be a service in making the same public.
Being thus encouraged, I laid it before the Second-day morning meeting of London,
as is usual in such cases, and attended the revising of it for the most part:
Friends agreed it should be printed, which was accordingly done.
It was afterwards reprinted here, in Ireland, and in America.

Having had a view, for several years, of visiting Friends in the American colonies,
as I waited with earnest desires to be rightly
directed in so solemn and weighty an undertaking,
both as to the thing itself and the proper time to enter thereupon,
I was favored with clear and full satisfaction, in both respects; and had seen,
for a considerable time,
that I should embark for that service soon after our Yearly Meeting, 1765.
This I esteemed a particular favor,
as I had thereby the better opportunity to order my outward affairs timely,
so that I might, with more freedom and ease, leave them so long a time; yet,
except to my wife and two or three Friends, who were enjoined secrecy,
I kept all to myself,
till about the time it became necessary to lay my concern before the Monthly Meeting.
I readily obtained its concurrence, and a certificate very fully expressive of unity;
which I carried to our Quarterly Meeting, laying the same, with my concern,
before that meeting; and obtained its concurrence,
signified by an endorsement on the Monthly Meeting certificate.
This I laid before the Yearly Meeting of ministers and elders in London,
and after a time of weighty consideration,
Friends drew up and signed a certificate of their full
unity with me and my intended undertaking.
The ready and unanimous concurrence of my much esteemed friends,
was a great strength and comfort to me in entering upon
and throughout this solemn engagement.
I was very sensible it was of such a nature,
that the whole body of Friends were interested in the right and proper performance of it;
and therefore found my mind much resigned to the divine will,
and to the determination of his people.

I returned home from the Yearly Meeting,
to complete the settlement of my outward affairs, having partly concluded,
with divine permission, to embark in a ship likely to sail in two or three weeks,
I went to our Quarterly and Yearly Meeting at Colchester; where,
being taken very ill of a fever, I returned home with my wife in a post-chaise,
being unable to ride on horse-back, and was confined to my chamber about ten days.
This put a stop to all preparations for my intended voyage; and on account of my illness,
I had wholly given up the expectation of going in the before-mentioned ship;
but when I recovered, so as to be able to move a little about,
my mind did not seem easy to let that ship go away without me.
I therefore wrote to the merchants or owners, who were desirous I should go in her,
to know what time they could allow me to get ready; their answer was, about ten days.
The time was short, and I was very weak in body,
and had some affairs of consequence to settle, which would take time; however,
the will being good, I set about them in earnest, and beyond expectation succeeded,
recovered strength apace, and got through my affairs in time to satisfaction.
I could not help looking upon this as a providential success,
far beyond human probability:
the Lord in his dealing with us his poor dependent creatures,
sometimes brings us very low, baffling all our skill and contrivance,
that he may clearly show us, that our success in spiritual things,
and even in temporals also, is by his providence.

On the 9th day of the seventh month, 1765, I took leave of my dear wife and family,
and accompanied by several friends, went to meet the ship at Gravesend,
where we were met by about fifteen or sixteen Friends from London; we dined together,
and lodged there that night.
Next day being the 10th of the seventh month,
I took leave of Friends in much tender affection, and went on board the Carolina,
James Friend master, bound for Philadelphia.
We got under sail about eleven o`'clock,
but it was nearly a week before we took our departure from the Land`'s-end of England.
We had for a few days, a pretty fair wind and a good set-off from the land;
yet on our passage we had a great deal of contrary winds, and often a head sea.
About the 9th and 10th of the eighth month, and for some time before,
things had a very discouraging aspect,
having got but a little on our way for about twenty days;
and most of the company seeming to be affected with sadness on that account.
At the same time I had a strong persuasion of mind,
that the wind would turn in our favor before night,
and had an inclination to tell them so, in order to cheer their spirits,
but was fearful of presuming too much upon the certainty of what presented to my view,
lest I should prove a false prophet, and thereby bring dishonor to the good cause;
however, it proved true, and held favorable to us a considerable time,
so that we sailed next day seven or eight miles an hour the right way.

The 21st of the eighth month, we found ourselves upon the banks of Newfoundland,
having about twenty-eight fathom water.
It was some satisfaction to find ourselves so far on our way;
I was favored with very good health, and a good appetite all the time,
and through divine favor, generally with a quiet resigned mind,
having full satisfaction that I was in my place.
The captain was very steady and well qualified for his station, and very kind to me;
the passengers also were generally civil in their behavior,
though they often burdened and wearied my spirit with their trifling, vain,
empty discourses, in which I could not join,
but was rather a reprover and a weight against them,
which I am persuaded they frequently felt,
and I am sensible I was a considerable awe upon them; yet I thought it was prudent,
as we were confined in one another`'s company, to uphold a family respect.
I often reproved their vanity and corrupt conversation, and was enabled,
in a good degree, to bring judgment over them, so that some would own I was right.
Alas, I had sorrowfully to observe how empty, vain, trifling, and even corrupt,
the conduct of those esteemed the genteel and polite part of mankind, in our day,
is become; little or nothing to be found therein, that conveys solid,
profitable instruction, either in things relating to this life or the next,
but in general it tends to deprave and corrupt.
Yet many thus void of self-denial and the government of their tongues, pretend,
with great assurance, to lay claim to the holy and undefiled religion of Jesus Christ;
surely,
they do not give themselves time to think seriously about the nature of that religion,
and must conclude that the name and profession without the spirit and life,
is all they are to look for, except adhering to a few exterior observations:
such gross darkness and stupefaction is much to be lamented,
but very hard to be helped when they are so ignorant of their own states.

It was the 10th of the ninth month, early in the morning, that we first saw land,
which proved to be Cape Henlopen; about six o`'clock we got a pilot on board,
who was a native Indian; about nine we entered the capes of the Delaware,
with the tide beginning to make in our favor;
about eleven our ship struck the ground three times, but soon got off.
We had fine wind and weather, which made it pleasant sailing up the bay and river;
we got up with that tide, within about six leagues of the city.
Next day, about eleven o`'clock, we came to anchor before the city of Philadelphia.
I soon landed and went directly to my old quarters,
being very kindly received as formerly, by my much esteemed friends Isaac and Sarah Zane.
I was about nine weeks on board the ship in all, and about eight from land to land.
I attended their week-day meeting on fifth-day, and had some good open service therein.
I went on first-day to the great meeting, where perhaps, nearly, if not quite,
fifteen hundred Friends, or those under our profession, were present;
my business among them at that time seemed to be to set them an example of silence.
I had, with secret lamentation,
to view the remarkable declension from a true spiritual exercise,
which appeared to me very general, looking for words to feed upon;
and found that craving was to be disappointed and famished,
and therefore was often shut up from public service amongst them,
especially at the great house, though I had some very clear, open, powerful times,
in the blessed light and life of the everlasting Gospel, there also.

On sixth-day, the 20th of the ninth month, I crossed the river Delaware,
and went to Haddonfield Quarterly Meeting, which was very large,
and I was opened to declare the Truth amongst them with good authority.
I returned next day to the city, and attended the Yearly Meeting of ministers and elders,
where things seemed low: this Yearly Meeting, which was very large,
concluded on sixth-day.
It was in a good degree favored with divine wisdom and strength,
wherein Friends were enabled to consider and conclude
some weighty affairs with unanimity and brotherly love.
The Lord was graciously with me,
affording wisdom and strength to be serviceable at this meeting,
both in ministry and discipline, wherein I had sweet peace and comfort.
I went the first-day following to Springfield meeting, in Chester county,
where I had very open weighty service, and the blessed Truth prevailed.
In the evening I had a comfortable meeting with a sick friend at Darby,
who soon after departed this life.
I then returned to Philadelphia, and attended both their week-day meetings,
which were painfully laborious in silent travail.
On sixth-day went to their Monthly Meeting, and was livingly opened therein,
to show the reason why the church of Christ is compared to a human body,
consisting of many and various members;
I had good service also in the meeting of business.
Their number is very large,
but many appeared to me weak and unskilful as to the
proper qualifications of active members in the church,
and some did not appear to be redeemed from fear, favor, and affection in judgment.
I had great comfort in the labor of this day.

On third-day, the 1st of the tenth month, I had a very large meeting at Haddonfield,
in West Jersey; the word was given with clearness and Gospel authority,
and I had to show the power and efficacy of true faith,
and the weakness and insufficiency of a historical faith: it was a good time,
and the glorious Truth was exalted.
I then went to Chester; the meeting was very large, and I had close,
thorough service therein, on the subject of self-denial and taking up the daily cross.
On fifth-day, had a very large meeting at Evesham, and had weighty service therein,
on the nature of that new birth, without which no man can see the kingdom of God;
most of the auditory seemed much strangers thereto, which made the labor heavier,
yet wisdom was mercifully given to divide the word to this numerous assembly,
for about the space of two hours.
Next day I had a very thronged meeting at Mount-holly, in New-Jersey;
my labor in the ministry was very close and searching, to good satisfaction.
On first-day, the 6th of the tenth month, was at Burlington meeting,
and had an open time; also at their Monthly Meeting on the second-day following,
which was very large; I was livingly opened upon these words, "`Pray without ceasing,
and in every thing give thanks;`" also showing,
that the power of the word of life ought to be
the spring of action in the church of Christ.

On third-day, accompanied by several friends, I crossed the river Delaware,
and had a small poor meeting at Bristol, in Pennsylvania.
I labored according to ability received, to stir up the members to a more lively concern,
but things appeared very low.
On fourth-day I had a large meeting at the Falls; it was very laborious,
under a sense of a dry, lifeless state in too many,
and the inconsistent conduct of others; especially in excessive drinking,
which I felt to cause a very ill savor: I was informed afterward,
that it had greatly prevailed upon many, and that several who were there that day,
had been disowned on that account.
Next day I had a large meeting at Wright`'s-town; and was opened therein,
to show the similarity between the travels of the soul towards spiritual Canaan,
and those of the Israelites towards the outward Canaan.
It was a close awakening time to dry, formal professors.
On sixth-day, I had a large meeting at Buckingham;
to this great gathering the everlasting Gospel was powerfully preached,
and the end and design of true ministry set forth.
This was a blessed time of divine refreshment, to the rejoicing of many hearts,
and arousing, I hope, of the lukewarm, in a good degree.
After this meeting, I felt it in my mind to speak to Thomas Ross,
a Friend in the ministry, of that county, to bear me company to the southern provinces,
which he, after due consideration and obtaining his friends`' concurrence and certificate,
complied with; and not only that journey, but also to New England, etc.,
so that I was favored with the agreeable company of this valuable Friend,
through most of my American travels, which was to my great comfort.

On first-day, the 13th of the tenth month, I was at North Wales meeting,
which was very large, and was favored with a thorough open time,
to the tendering of many hearts.
The day following had a large meeting at Plymouth.
I was opened upon that passage,
"`Believe not every spirit;`" and had close work with libertines,
such as are commonly called free-thinkers, and was carried over them:
Truth and its testimony was greatly exalted,
and triumphed over that spirit and other wrong things.
On third-day, had a large meeting at Horsham,
and was powerfully opened on the words of the prophet Joel:
"`I will pour out my spirit upon all flesh,`" etc.,
with some close remarks to those who rest satisfied with a mere profession.
After meeting, came a seventh-day Baptist to the Friend`'s house where I was;
and if I had allowed it, would have led me out into a wide field of argument,
for which I had neither time nor inclination.
He advanced several points,
but I kept him so close to some of them that he was soon foiled;
he found my method of arguing different from his;
he being for a multitude of words and a great deal of ramble,
and I was for few words close to the point, backed with clear Scripture proof,
so we had quickly done.
He seemed willing to drop it, and so was I,
for such are so full of notion and so fixed therein,
that the clearest reasoning seems thrown away upon them.

On fourth-day had a very large meeting at Abington,
the place which I belonged to in my youthful days, and where I was first,
through infinite mercy, brought to the knowledge of the ever blessed Truth;
and where my mouth was first opened above thirty years before, in a public testimony.
A dark cloud seemed painfully over the meeting in the fore part,
yet at length Truth prevailed,
and utterance was largely given to declare the doctrine thereof,
showing that the children of Israel feared the Lord all the days of Joshua,
and of the elders that, out-lived him.
It was a very awakening time, and many appeared to be pretty much affected.
Next day I had a small meeting at Frankford,
things appeared very low and dark for a time, yet at length,
wisdom and utterance were given upon these words, "`Man being in honor, abides not:
he is like the beasts that perish.`"
There seemed a lack of a living concern in the general.
Next day had a large meeting at Germantown; this was a dark,
painful time in the fore part; Truth measurably arose, and the word was given:
"`Let God arise; let his enemies be scattered.`"

Went after meeting to Philadelphia, and on first-day, the 20th of the tenth month,
over Schuylkill, to Merion meeting; things appeared low, as to the life of religion:
I was concerned to call them to work while it is day, and it was a close searching time.
On second-day I went to the burial of a valuable Friend at Darby,
the same with whom I had a meeting before mentioned; the meeting was very large,
and there was great openness to declare the Truth with clearness and divine authority,
even to the confounding libertines and gainsayers,
of whom I fear there is a considerable number in that place:
this seemed to me the most favored time I had had since I landed,
and being also at the meeting I formerly belonged to for many years,
it was a precious renewal of that sweet unity some of us had
enjoyed together many times formerly in that place.
Next day I went to Philadelphia; and the first-day following to Newtown meeting,
in Chester county, where I had very searching laborious service;
things appeared to me mournfully low, as to the life of religion,
many being at ease in a profession thereof.
I went next day to the Monthly Meeting at Providence,
and had some good edifying service to the poor in spirit;
things appeared very low and heavy in the meeting for business.
On third-day I had a large meeting at Radnor,
and labored to convince them that there is something in
religion besides the form and outward profession,
but few seemed to me alive therein.
On fourth-day went to Haverford meeting; I was opened upon the words of the apostle:
"`Great is the mystery of godliness; God manifested in the flesh.`"
It was a good time, though the professors are but few and in a weak state.

I went on fifth-day to the Monthly Meeting at Darby,
the life of religion seemed very much depressed.
I was silent as to ministry, but had some service in the meeting of business,
and returned to the city that night.
I had been indisposed some days past, and in much pain with a kind of flux;
took some medicine on sixth-day, and was soon better.
Next day I went to their Quarterly Meeting of ministers and elders,
where I was livingly opened on that passage, "`Him that overcomes,
I will make a pillar in the house of my God,`" etc.;
showing that the beast and the false prophet must be overcome,
before we can stand with safety and approbation in the great work of the ministry.
This Quarterly Meeting ended on third-day,
at the several sittings of which I had good open service,
particularly at the Bank meeting on first-day afternoon,
showing that those who are more willing to receive than to make suitable returns,
are neither so honest nor grateful as they ought to be; and on third-day,
at the great house, being the Youths`' meeting, which was very large,
concerning the nature and necessity of Christ`'s baptism with the Holy Ghost and fire;
there was great flowing of love and enlargement of heart to the young people that way.
On fourth-day I was at a meeting appointed for the poor negroes,
and had open good service amongst them, in the free flowing of universal love,
wherein I was enabled to open unto them the way of life and salvation;
several of them appeared to be affected and tendered; it was a comfortable time.
On fifth-day I was at a marriage in the city, and largely opened upon these words,
"`The blessing of God makes truly rich,`" etc.;
showing there is no real happiness in any station of life without it.
It was a good time, for Truth prevailed.

I set out on sixth-day, the 8th of the tenth month,
on my intended journey towards Maryland, Virginia and Carolina;
and went that night to my brother-in-law, Micajah Speakman`'s, at Concord.
Next day began their Quarterly Meeting: through divine favor,
I had thorough service at the three meetings held there: on seventh-day,
at the meeting of ministers and elders, I was livingly opened upon these words of Christ,
"`The disciple is not above his master, nor the servant above his Lord;`" also,
concerning what was declared of Christ,
"`That in his humiliation, his judgment was taken away,`" etc.
It is not to be wondered at, if our judgment in the Truth is taken away at times,
that we may see who is the giver of it; it was an effectual reaching time.
On first-day I was mournfully affected with a distressing
sense of the apostasy of many in that meeting,
from the life and power of religion; I had a very close awakening time,
and Truth mercifully prevailed.
On second-day I was largely opened with good authority, on these and.other words,
"`He that comes after me, must first deny himself.`"
Great weakness and lack of living concern was felt in that large meeting,
and too much leaning to their own understanding, yet a faithful remnant is preserved;
I was favored to be serviceable in the meeting of business.
I took Birmingham and Kennet meetings,
in my way to the Quarterly Meeting at London-grove; these were very large,
and I had deep searching service at them;
but alas! the life and power of religion is mournfully
departed from by great numbers in that highly favored land.

On seventh-day, the 16th of the eleventh month,
I went to the Quarterly Meeting of ministers and elders at London-grove;
it was a very painful distressing time;
great barrenness and carnality appeared to have prevailed in many in those stations,
which was cause of sore lamentation:
my public service amongst them was in much close plain dealing, showing,
"`that to be carnally minded is death;
and that the natural man understands not the things of the spirit of God.`"
Here my intended companion, Thomas Ross, met me.
On first-day the meeting was very large; I had a close searching time,
particularly to some who stood in the foremost rank;
my spirit was much distressed in viewing the great
desolation made by the prevalence of many evils.
On second-day I had large thorough service to the various states of the members,
and also in the meeting of business, which appeared to be well conducted;
some skillful members being principally engaged therein.
On third-day the meeting was very large, and through divine favor,
I was raised in much strength and clearness to divide the word amongst them; showing,
"`That the children of Israel feared the Lord all the days of Joshua,
and of the elders that out-lived Joshua, who had seen the wonders of the Lord.`"
I was opened largely upon the degeneracy of our Society, and with great weight and dread,
had to signify, that the judgments of the Lord would be poured out upon them,
and that what they had yet seen, was but like the beginning of sorrows,
that the stroke would fall upon their idols, their worldly enjoyments.
It came before me many times, that the fruits of the earth would be smitten,
whereby there would be a sore famine in the land, and that judgments,
much heavier than they had yet known, would fall upon them;
it seemed to me in various ways, of which the sword would be one.
It was an awful deep searching time as ever I knew; I hope not easily to be forgotten.

Next day I went to Sadsbury Monthly Meeting, where I had satisfactory service,
both in the ministry and discipline.
On sixth-day we had a meeting at Lancaster; many not under our name came to it;
and my concern therein was to endeavor to open to the understanding of the people,
what true religion is: we had a pretty satisfactory meeting at Isaac Whitelock`'s,
in the evening.
On seventh-day, we crossed Susquehanna, at Wright`'s ferry,
and next day went to Newbury meeting; second-day to Warrington; third-day to Huntington:
fourth-day to Monallen; at all which places, I had close thorough service;
found the life of religion very low amongst Friends;
yet a remnant was preserved sensible from which good comes.
We went from there into Maryland, and had small meetings at Pipe-creek and Bush-creek;
Friends were few in number, and seemed low in religious experience.
from there, fording the great river Potomac, we entered the province of Virginia,
and on third-day, the 3rd of the twelfth month, we had a very large meeting at Fairfax:
Truth opened doctrine and counsel largely,
showing that two things are essential to the very being of a true Christian, namely,
The saving experimental knowledge of God, and the knowledge of ourselves;
the last being the natural consequence of the first: it was a highly favored time,
and the living were sweetly comforted.

Next day I had a large meeting at Goosecreek; it was a dark afflicting time;
my mind was deeply impressed with a sense of a corrupt,
blasting ministry being amongst them; and the people having itching ears,
loved to have it so; this was so strong upon my mind,
that I feared for some time I should have been under a
necessity of declaring it publicly in the meeting.
I was an entire stranger, and did not know by any outward information,
that they had any who appeared in public.
After meeting, I took some of the elderly Friends aside,
and told them how it had been with me, as above, for I was silent the whole meeting;
I was informed afterwards, that there was a forward unruly man,
who had given sensible Friends much trouble in several places,
and had been much labored with by way of advice, to refrain from his public appearance,
that he had for some time settled within the compass of that remote meeting,
and was encouraged by many of the members, to the great uneasiness of some others.
That afternoon I put what was upon my mind in relation thereto,
with a few remarks thereon, in writing, and sent it to some Friends of that meeting.

In our way to Opeckan, we had a small meeting at a place called the Gap,
where Gospel doctrine, showing the way and means of salvation by Jesus Christ,
was freely and largely preached.
On first-day, the 8th of the twelfth month, we went to Hopewell meeting; it was a dark,
afflicting time; great insensibility and lukewarmness appearing in almost a general way;
I was led in as close, plain dealing, and searching a manner, as ever I remember.
The third-day following we had a large meeting at Crooked-run,
both Friends and many others attended.
My mind was exceedingly low the morning of that day,
being lately set out on a great journey, and my horse was fallen very lame,
and it seemed unlikely that I could be supplied with a suitable one in those back parts:
what to do I could not tell; the more I thought about my distressed condition,
the more I sunk and was perplexed.
In this disconsolate state, I went to the meeting:
to see such a number of other societies,
and some of them of high rank by their appearance,
still added to my distress in this weak state,
greatly fearing the blessed Truth should be dishonored through me;
yet as I endeavored to look singly to the Lord,
he was graciously pleased to be a present help in the needful time,
and appeared to my soul, as it were in an instant, as a clear morning without clouds.
A heavenly time I had, upon these words; "`Trust in the Lord,
and lean not to your own understanding;`" showing clearly,
that the soul`'s salvation was of God and not by human ability:
the oil of gladness ran sweetly.
Next day, my horse being unexpectedly recovered of his lameness,
we set out on our long journey towards Carolina, and he continued well all the time.
I write this for the encouragement of some poor travelers into whose hands this may fall.
After three days traveling, we had two poor small meetings,
where the life of religion seemed to be almost, if not wholly lost, namely,
Camp-creek and Fork-creek; we had but little satisfaction in our Gospel labors,
and endeavors to revive true religion in these poor places.

From Fork-creek, to the first meeting we had in the back settlements of North-Carolina,
was about two hundred and thirty-five miles.
In our way there, we had four small poor meetings, namely, Genito, Amelia and Bannister,
and a meeting at Kirby`'s, on the banks of Dan river: to some of them,
many of other societies came,
and Gospel doctrine was opened largely for their help and information;
in which labor there was good satisfaction; but, alas! few under our name in those parts,
let the true light shine before men,
but were most of them as stumbling blocks in the way of serious inquirers:
we were enabled to clear our minds to them, and proceeded on our journey.
On the 29th of the twelfth month, we went to New-Garden meeting, in North-Carolina,
which was very large, and mostly of professors with us: a thick,
dark cloud overshadowed the fore part of that meeting, and it was a painful,
distressing time; most of them seemed as asleep, 1 Thess. 5:6-7, in the night;
yet at length, through merciful kindness, Truth prevailed in a good degree.
It was a close awakening time,
and many seemed to be reached and tendered by the virtue of Truth,
and I found great ease and liberty of spirit after meeting.
On second-day we had a large meeting at Deep-river, mostly of professors with us,
but they appeared so generally void of a spiritual concern,
that there appeared to me no room for Truth to arise into dominion.
I found it my place to sit the whole time in silence, which, I believe,
was no small disappointment.
On fourth-day, there being a marriage, we went to New-Garden again;
wisdom and utterance were given to speak largely and with good demonstration,
in a very searching manner to their states.
On fifth-day we had a meeting at Centre; it was extremely cold, and as some observed,
the like had not been known there in the memory of man;
and being quite an open meeting-house,
and very little of any thing to be felt amongst them of religious warmth,
it was really a distressing time inwardly and outwardly; yet, through divine favor,
I was preserved in a good degree of resignation.

Next day we had a small meeting at Rocky river.
I could find little evidence of the wrestling seed there;
we sat the whole meeting silently,,
yet a Friend had something to offer very suitable to their states.
On seventh-day we went to the Monthly Meeting at Cane-creek, which was large,
but most of the members seemed void of a solid sense and solemnity;
a spirit of self-righteousness and contention was painfully felt;
the leaven of the pharisee seemed to prevail,
and the few living sensible members were borne down and discouraged.
Most of the meeting of worship was held in silence; yet towards the conclusion,
some very close remarks were delivered to their states,
and very plain dealing in the meeting of business.
It seems to me, that when affairs of importance come before such a meeting,
they are very likely to be perplexed and made worse by ill management,
which I have reason to believe has been much the case in that meeting.
I am persuaded many of those under our name have removed out
of Pennsylvania and other places to these parts,
in their own wills, having taken counsel of their own depraved hearts,
and when they have got there, have set up for something in the church;
but it seemed to me most of them were very unfit for the spiritual building,
not having been hewn in the mount.
We went to their meeting on first-day, but there was much darkness and death over them;
I found it my duty to sit the whole meeting in silence.
On second-day we went to the Spring meetingI was led therein
to speak largely upon the subject of water baptism,
which I wondered much at, not knowing of any being there who did not profess with us;
for as people in general in those parts clothe in a mean way,
the difference is not great in their dress and appearance.
After meeting I understood that the Baptists gained ground much that way,
and even had prevailed on some of our Society to join with them,
and that their teacher was there; and also a woman brought up amongst us,
who thought it was her duty to be baptized, but her husband opposed it;
and that the Baptist preacher took her and her husband into the meeting-house,
when the people were gone, to undo, as it was supposed, that day`'s work,
or to prevent its having effect upon the woman: it was a time of great favor,
and the one saving baptism was exalted above all types, signs and shadows.
Next day we had a small, poor meeting at the Hawfield`'s;
and on fourth-day we had one at Eno, which was the last we had in the upper settlement:
this was a laborious meeting, in close, plain dealing with wrong spirits, for which,
we understood afterwards, there was a cause.

On the 9th of the first month, 1766, we set out, having two guides,
for the lower settlements of North Carolina, being about two hundred miles,
and had but two small meetings in the way, namely, Richsquare, and at one Stephens`'s;
at the first, many of other societies came in;
and the Gospel was freely declared with good authority and clearness,
to the reaching of several present: at the other place there seemed to be very little,
either of form or substance; we were quite shut up as to ministry.
We got to our friend Thomas Newby`'s at Piney-woods, on third-day the 14th,
being pretty much fatigued, and rested a few days there.
On seventh-day we went to the funeral of a woman Friend, and had a meeting;
after a time of deep wading,
the word was given in counsel and searching doctrine to their states,
who seemed mostly to be settled in a mere form and profession:
after meeting we went to our friend Thomas Nicholson`'s.
The first-day following we were at Little-river meeting,
which was large, but very low and dark in the fore part;
the professors we felt were much at ease and in a state of indifference; yet at length,
in great mercy, the blessed power of Truth arose,
and afforded counsel and doctrine suited to their state.
It was a searching time, I hope not easily to be forgotten.
On third-day had a large meeting at Simon`'s-creek;
through divine favor Gospel truths were opened with clearness and good demonstration,
to the affecting of many hearts.
Next day had a meeting at Newbegun, which was pretty large and open.
On fifth-day we had a very large meeting at Oldneck,
near the centre of Friends in this settlement, and others came together in abundance.
I was shut up the whole time in silence,
which I apprehended they had not been much used to.
Next day we had a large meeting at Wells, in which I had a close searching time;
but alas! it seemed to me that many of the professors of Truth hereabout,
are far gone from a lively sense of true religion,
and are become harder to reach than people of other societies.

On first-day the 26th of the first month, we had a very large meeting at Ringwood`'s,
it being the last we were to have in Carolina; some Friends came to it, I believe,
from all the other meetings, with many of other societies:
at first it was a time of painful travail,
but at length the great Master was pleased to
give wisdom and strength in Gospel authority,
to open the state of the Society in those parts, and to divide to each of them;
also to show that in every dispensation of God to man,
he was pleased to give to those who are sincerely attentive,
clear evidence of his will and approbation of their obedience;
it was a highly favored time, which I hope, will not soon be forgotten.
Next day we traveled into Virginia, and on third-day had a meeting at Summerton;
the doctrine of Truth was largely opened,
and some close remarks made on the state of our Society; many others also being present:
the testimony had a considerable reach.
Next day we had a large meeting at the Western Branch of Nansemond:
those under our profession appeared too generally unacquainted
with the work of religion upon their hearts;
many weighty truths were closely delivered,
but did not seem to take so much effect upon the minds of many,
as could have been desired.

On fifth-day we had a large meeting at Black-water:
the greatest number of negroes were at it that I ever
saw in a meeting not appointed on purpose for them.
This was a highly favored time;
the everlasting Gospel was preached with clearness and good demonstration,
showing that the inward and spiritual knowledge of God,
is the substance of true religion; and that according to the prophet,
this knowledge is to cover the earth as the waters cover the sea.
I had great satisfaction and comfort in the labor of that day.
We went from hence to the Quarterly Meeting at Blackcreek; the number here was large,
but alas! great deadness, insensibility and darkness were felt to prevail amongst them;
close labor, in great plainness was used, showing the cause thereof:
amongst other things,
that which appeared none of the least was their keeping the negroes in perpetual slavery.
I was often concerned to use plainness in families where I went,
in respect to this matter, and am satisfied Truth will never prosper amongst them,
nor any others, who are in the practice of keeping this race of mankind in bondage.
It is too manifest to be denied,
that the life of religion is almost lost where slaves are very numerous;
and it is impossible it should be otherwise,
the practice being as contrary to the spirit of Christianity as light is to darkness.
Through divine favor,
the testimony of Truth prevails against it in most of the American colonies,
especially in Pennsylvania and the Jerseys.

We took meetings from this place at Burleigh, Petersburg, at Curl`'s, over James`'-river,
Wain-oak, John Crew`'s, Black-creek and the Swamp; most of which were very laborious,
in a sorrowful sense that the life of religion was too generally departed from;
yet in all of them, except Wain-oak, a degree of wisdom and utterance was given,
to labor in the love of the Gospel for their help and recovery;
which I hope was not altogether in vain.
The next meetings we went to were Cedar-creek and Caroline,
being the last we had in Virginia: they were large,
not only those under our profession attending, but also many others,
as was often the case in these parts.
I think it may be truly said, these were memorable meetings:
the Gospel was preached in the demonstration of the spirit and with power,
which appeared to reach and tender many, if not most present,
and my mind was comfortably relieved from that painful weight of death and
darkness which mostly attended it in these greatly corrupted colonies.
On fifth-day the 13th of the second month, we set out for Maryland,
crossing Rappahanock-river at Portroyal, and the Potomac, about three miles over,
at How`'s ferry.
We got to West-river meeting on first-day, the 16th of the second month.
We found very little if any thing in that meeting,
of that simplicity and self-denial so conspicuous in our ancients;
but a conformity to the fashions and corrupt customs of a vain world.
The Gospel power arose, giving ability to set forth the nature of Christianity,
and how far the professors had deviated therefrom in life and practice.
The judgment of Truth was set over libertines and unfaithful professors thereof.
The next meetings we had, were at Indian-spring, Sandy-spring, Elkridge, Patapsco,
Gun Powder, Little-falls, Bush-river and Deer-creek;
we were also at Deer-creek Monthly Meeting next day: in all which meetings,
ability was mercifully given, to divide the word suitably to the various states,
which seemed in a general way, much out of the order,
and from under the government of Truth;
yet the labor tended to solid satisfaction and peace;
I hope it may be remembered by some to advantage.

Thus having visited the western shore of Maryland,
we crossed the great river Susquehanna,
and went to the house of our friend John Churchman, near East Nottingham.
On first-day the 2nd of the third month, we went to that meeting, which was very large,
the professors of Truth being numerous hereabout.
To this great assembly the Gospel of life and salvation was powerfully preached,
showing the force of Truth, how it gained the general assent of people,
yet few were concerned to know the same in experience or practice.
It was a highly favored time, and the meeting seemed to be generally affected.
From Nottingham we went to the following meetings: New-garden, Hockesson,
Center and Kennet, which were mostly large,
abundance flocking to them from adjacent meetings.
The travail of spirit in these meetings was very deep and painful;
much distressing flatness and insensibility were felt; yet, through merciful help,
Truth prevailed and largely opened doctrine and counsel suitable to their states;
showing, there is not the least ground to hope for happiness in a future slate,
unless true religion becomes the principal concern of the mind; and much more,
in the free extendings of Gospel life and power, to the reaching of many hearts:
everlastingly adored, reverenced and worshipped, be infinite condescending love.
Amen.

From Kennet I went home with my sister Speakman, to Concord, and staid there one night,
and next day to Goshen Monthly Meeting, which was very large.
There was a great body of Friends, generally under a plain appearance;
but alas! it proved a painful, gloomy time of silent travail to me,
the whole time of worship; and through the meeting of business,
though in a good degree regularly and decently conducted, the cloud still remained.
This I am persuaded was occasioned by the lukewarm careless state of many members;
there being a great lack of that living concern and holy ardor of soul,
which the Lord is often pleased to own in our religious meetings.
The members engaging in his work,
without his presence to animate and endue with heavenly wisdom,
cannot fail to cause thick darkness,
which may be felt by those who are truly alive and have their spiritual senses exercised.
After meeting, my valuable companion Thomas Ross and I parted for the present,
he returning home, and I staid Goshen meeting, on first-day the 9th of the third month.
It was very large, and in the fore part low and cloudy;
yet at length I was favored with a degree of faith, which enabled me to stand up,
and as I continued in patience, I found an increase,
with considerable enlargement to speak closely to their several states, from these words,
"`Trust in the Lord with all your heart, and lean not to your own understanding.`"
But alas! very many of of them seemed to be far gone into the
spirit of the world and at ease in a profession;
so thai instead of Goshen being a land of light,
darkness has prevailed in a sorrowful degree,
and many are not sensible of it to lament it.
I went from there to Philadelphia, taking Darby meeting in my way;
and got there on sixth-day the 14th of the third month,
having been on this journey about four months.
I was received with affectionate kindness by my friends in that city,
and attended three meetings on the first-day following; at two of which I was silent,
as was often my lot there,
I believe to disappoint and famish the unsanctified
desires and cravings of many after words.
I attended their week-day meetings, and had considerable service therein.

On seventh-day began the general Spring meeting, which ended on third-day following;
some of those large meetings were held mostly in silence.
I had then as has often been the case, a deep travail upon my spirit,
that the people might be led by the example of ministers and elders,
to find the comfort and advantage of true silent worship,
all coming to sit under their own vines and under their own fig-trees,
where none could make them afraid.
I had, notwithstanding, at some of them, good open public service.
I staid in the city till their Monthly Meeting was over on sixth-day,
where I had some close service, and then went to the Yearly Meeting at Wilmington,
and was at four meetings in two days.
At three of them, the truths of the Gospel were largely and with clearness declared,
to much satisfaction and comfort.
I returned towards the city, attending Darby Monthly Meeting in my way,
where things appeared mournfully low;
some of the active members seeming very unskilful in the management of the discipline:
earnest labor was bestowed, but I thought it had very little effect.
On sixth-day I went to the children`'s meeting in the city;
I suppose there were about two hundred in all, of both sexes.

On first-day the 6th of the fourth month, in company with several Friends,
I crossed the Delaware at Gloucester point: the wind blowing very hard,
it appeared dangerous; yet, the boatmen being very careful,
through mercy we got well over, and went to Woodbury meeting, which was very large,
and the Gospel power livingly arose, wherein many weighty truths were delivered,
showing the great use of that propensity in man of seeking after happiness,
if rightly directed; also, wherein true happiness consists, and how to attain the same.
It was a good time, through the gracious extendings of merciful regard.
I went home with my near friend Isaac Andrews, who bore me company in this journey,
three or four weeks in the Jerseys.
We had meetings that week at Upper Greenwich, Pilesgrove, at the head of Alloway`'s-creek,
Salem, and Alloway`'s-creek, which were mostly large;
great lukewarmness and insensibility were painfully felt,
many seeming to rest in only professing the religion of their education;
for these I had a deep concern and travail of mind,
that they might come to know Christ formed in them.
The Lord was graciously pleased, in great condescension,
to furnish with matter and utterance in an awakening manner,
in order to make them sensible of the nature and importance of true religion and worship:
may it not be in vain!

On first-day the 13th of the fourth month, we went to Greenwich meeting;
the glorious Gospel power eminently manifested itself that day,
by clearly opening several weighty points of doctrine,
suitable to the various states of that large auditory; among other things,
showing that the true and saving knowledge of God,
whereby we obtain the right knowledge of ourselves,
is essential to the very being of a real Christian;
and by what means that knowledge is obtained.
It was a highly favored time, for the Lord`'s heavenly power was over all,
and the people appeared to be generally affected.
Next day we had a large meeting among the Presbyterians,
at a place called New England Town;
their minister having given notice the day before from the pulpit, of a meeting for us;
he attended it himself, with, I suppose, most of his hearers,
who behaved solidly and respectfully.
The universal love of God, through Christ, to mankind, was largely set forth,
and people directed from outward observations, to the substance,
whereby victory might be obtained over sin: it was a favored time,
and the people seemed generally well affected and very loving,
though several things were delivered which are
usually controverted between us and those people;
there was no visible opposition, but all passed off in quiet and peaceably.

On fourth-day we traveled a day`'s journey through the pine-barren wilderness, to CapeMay;
had one meeting there, and two at Great Egg-harbour.
We found the number of professors small, and the life of religion low;
yet we were enabled to minister suitably to their states for their help and recovery,
and had a good degree of satisfaction and peace therein.
On third-day, the 22nd of the fourth month, we had a large meeting at Little Egg-harbour.
After a time of trying poverty and deep travail, Gospel-life and power mercifully arose,
in which, doctrine and counsel flowed forth freely to several states,
particularly to a libertine youth.
Next day we had a meeting in a new Presbyterian meeting-house, near Barnegat;
it was large, and held more than an hour in silence,
which the people were not accustomed to.
At length the word was given with authority and clearness,
showing the necessity and advantage of silence in worship,
and distinguishing Christians of the letter from Christians of the Spirit,
as also ministers of the letter from ministers of the Spirit;
and that those who are always ready to preach, must either have the Spirit at command,
or act without it.
It was a great and good time; the people appeared to be generally affected,
and all passed off quietly, without any opposition.
We traveled on by the sea-side, to a place called Good-luck,
where we found a large meeting-house erected, though not quite finished,
by one Thomas Potter, intended by him, it seems,
for all preachers to make use of who would preach freely, except papists,
who would not be admitted even on those terms.
We had a meeting in it, but notice not coming timely,
and Thomas Potter not being at home, it was small and to little satisfaction.
We met him that afternoon on his return,
he seemed sorry he happened to be out at that time; he sees beyond hireling ministry,
and I understand, inclines most to Friends of any, but joins to none.
On sixth-day we had a poor, low meeting at Manesquan;
but very few therein seemed alive in religion;
yet some Gospel labors were bestowed for their help.
We went after meeting to Shrewsbury, intending to be at their Quarterly Meeting,
which began on first-day, the 27th of the fourth month.
It was very large; some solid Friends were present, also many loose,
libertine people under our name, and of other societies.
In that sad mixture, the life of religion was exceedingly depressed,
and my mind in sympathy with it:
I could not wade through so as to get ease and satisfaction, though I labored very hard.
In the meeting next day, the power of Truth in marvellous kindness arose,
and the Gospel was preached with good authority and clearness,
to the various states of that great auditory.
The meeting of business followed;
there seemed but little judgment to maintain good order and discipline;
and unity appeared not so general as could have been desired.
On third-day abundance of people flocked to meeting, perhaps with much expectation;
but my way was shut up as to ministry, and but very little from any other;
I found peace and satisfaction by abiding in my place.

On fifth-day I went to Chesterfield Monthly Meeting; it was very large,
and I had deep and painful wading therein, in my public service,
showing what man is by nature,
with whatever mode or form of religion he decks and adorns himself;
for that which is born of the flesh is but flesh, and cannot see the kingdom of God.
I got through at last to pretty good satisfaction,
but found much close labor in the meeting of business,
and saw great deviation from the right thing, in some high ruling members,
who had carried an affair through that meeting against the most lively part of the body,
which they themselves had sufficient cause to repent.
On sixth and seventh-days, I had meetings at Upper-Freehold and New-Springfield;
and on first-day, the 4th of the fifth month,
had a very large meeting at Mansfield in the morning,
and another at Bordentown in the evening.
The people seemed full of expectation from one come so far;
but it pleased the great Master,
without whose gracious aid the poor servant can do nothing to advantage,
to shut me wholly up as to ministry, in both places, to the great disappointment of many;
but there was no remedy; I dared not contrive or form any thing for them, and,
I have no doubt, that silence was the most profitable lesson for those meetings.
I went next day to Burlington Monthly Meeting, it was large and divinely favored;
the doctrine of Truth flowed forth freely,
showing what it is to be a fellow-citizen with the saints and of the household of faith.
On third-day I had a laborious meeting at Ancocas,
yet had some good open service towards the latter-end,
which seemed to fasten on several minds.

I got to Philadelphia next day, and on fifth-day, the 8th of the fifth month,
went to the marriage of John Pemberton and Hannah,
the daughter of my worthy friends Isaac and Sarah Zane.
It was at the great meetinghouse, the assembly was large,
and there appeared much desire and expectation after words,
which often hurts meetings and blocks up the way of ministers,
which was the case now for a while; yet at length some, I hope,
profitable labor was bestowed, from the words of our Lord,
"`Blessed are they that hunger and thirst after righteousness.`"
On first-day, the 11th of the fifth month, I attended three large meetings in the city,
in all which, I thought it my duty to set an example of silence.
Near the close of the evening meeting, it was a sweet refreshing time;
the thirsty soul had to drink of that river that makes glad the whole city of God;
in the enjoyment whereof,
there was comfortable solacing rest from the painful labor of that day, and,
full satisfaction, with thankfulness that I had been preserved in my place.
I staid their meeting on third-day, which was large;
the power and wisdom of Truth opened deep counsel and doctrine,
pointing out the different states of professors in that city,
that some of the true wrestling seed dare not choose or contrive for themselves,
which way to be fed; whether immediately by the great Shepherd`'s own hand,
or instrumentally by his servants;
and that there were many others anxiously choosing to
be fed with testimonies and outward declarations,
which state ought to be famished; also, that the time would come,
when the word of the Lord, by way of ministry, would be very precious,
and he would command the clouds to rain no rain upon such;
that it was already a time of parching drought, because of idolatry;
yet the Lord would open springs to the seed of Jacob, in the midst of the valleys,
and in his own time bring them to Rehoboth.
It was a great and good time, and the meeting was much affected.
I set out next day for New England, and had meetings in my way to Long-Island,
at Byberry, Middletown and Stonybrook, where my old companion, Thomas Ross, met me:
my service was very close and searching at these meetings.
Alas! how has an indolent spirit prevailed on the professors of Truth,
a small remnant excepted, who are preserved in most places,
to rejoice in the painful labors, in great mercy yet continued to the churches.

In company with several other Friends we proceeded on our journey,
in order to attend Flushing Yearly Meeting, on Long-Island,
for the government of New-York.
On fifth-day, the 22nd of the fifth month,
we attended the Monthly and Quarterly Meetings of ministers and elders at Flushing;
in the latter I had comfortable open service,
upon the blessing pronounced by our gracious Redeemer to the poor in spirit,
showing the necessity and usefulness of that state;
and also setting forth the essential qualifications of a Gospel minister.
It was a blessed time, and the upright-hearted were sweetly comforted.
Next day was held the Quarterly Meeting, which was small,
and the life of religion was felt to be very low;
a painful gloominess having spread itself,
through a lack of living concern in many of the members,
and from some presuming to act in the church, too much in their own will and wisdom;
yet the Lord who waits to be gracious,
afforded doctrine and counsel suitable to their states; showing,
there is one body and one spirit, and that all the members who act profitably,
must know a being baptized by that one spirit into the one mystical body.
I found great numbness in the meeting of business;
my spirit was deeply baptized into suffering therein,
and constrained to lay their condition before them by very close searching observations,
which appeared to take some impression, and my mind was much relieved thereby.
On seventh-day morning the Yearly Meeting of ministers and elders was held,
which was small, and the vital part of religion seemed to be much obstructed;
some close remarks were delivered, which afforded considerable relief:
at eleven o`'clock came on the first public meeting for worship,
the time of which was taken up very unprofitably by an unskilful appearance; after which,
the business was entered upon, and it was a painful, distressing time; the forward, busy,
active spirit of man was let loose in a few elderly persons,
who had placed themselves at the helm of government there,
and who seemed to have got such an ascendency over the meeting,
as to bear down whatever appeared in the right line of tenderness and Truth`'s simplicity,
when they did not see fit to promote it.
The attempt was to lay aside the necessary queries to be answered by inferior,
to superior meetings.
I was favored with a degree of wisdom and strength to withstand that spirit,
and to show the necessity of proper queries,
in order that the state of the Society might be better understood;
how else could suitable advice be administered?
But through the cowardice of many present, I was left to engage much alone;
yet have cause to believe,
that the weapons given both in the meeting and afterwards in private conference,
wounded that spirit deeply,
and gave honest Friends a clearer sight of it than they had before.
In the succeeding meetings, business was managed with more harmony and peace,
and the meetings for worship were very large;
wherein the everlasting Gospel was preached with clearness and demonstration:
many were deeply affected, and the great Author was humbly worshipped and adored,
who is worthy forever!

We went from Flushing, and had a large meeting at Cow-Neck,
in which Truth opened Gospel doctrine largely, to the tendering of many hearts.
Next day we had an exceedingly large meeting at Westbury: as there was general notice,
abundance of people came from several parts of the island,
so that there was nearly as large a concourse as at the Yearly Meeting;
their expectations were much after words, but they had none from me,
being shut up in silence the whole time:
the Monthly Meeting of business was held at the close thereof.
We had very large meetings afterwards, on this island at Matinicock, OysterBay,
Bethpage and Sequetague; and notwithstanding the low, languid state of the Society,
Gospel truths were largely delivered, and livingly opened in them.

We then traveled towards the east end of the island, on our way to Rhode-Island,
and on third-day, the 3rd of the sixth month,
went on board a vessel about eight o`'clock in the morning, taking our horses with us,
and landed safe at Gratten, opposite to New London in the colony of Connecticut,
about one o`'clock the same day.
We got that night to our friend Peter Davis`'s, in Rhode-Island government,
about twenty-two miles.
We had a meeting next day at Westerly:
the governor of the province was at it and behaved kindly, inviting us to his house;
but it did not suit us to go.

In order to fill up our time before the Yearly Meeting,
we had meetings at a new meeting-house near James Perry`'s, South Kingston, Greenwich,
Neshantecut and Providence;
and though we found some honest travelers for Zion`'s prosperity, yet, for the most part,
the life of religion appeared mournfully low, indifferency prevailing in many,
and several undue liberties in others.
I was much afflicted at some of the meetings with the dark principles of deism,
and was favored with ability to lay open the wickedness
and gross absurdity of such principles,
warning Friends and others to shun the conduct of those tinctured therewith,
as they would a poisonous serpent.
On fifth-day, the 12th of the sixth month,
the Yearly Meeting for New England began at Portsmouth on RhodeIsland:
this meeting was very large as to number;
but it was a dark gloomy time of deep suffering:
the glory and diadem of our religious assemblies seems
to be sorrowfully removed from these people,
and instead of the meeting being covered therewith, it was overspread with darkness.
Here I met our friend Thomas Gawthrop,
who was upon his third visit to Friends in America;
we both sat the whole meeting in silence.

The meetings following, both for worship and discipline, were held at Newport,
and continued till second-day was over.
The public meetings were exceedingly large, both Friends,
and abundance of other people attending most of them;
it was supposed there were two thousand people.
To these great assemblies, it pleased the gracious fountain of all good,
to open much Gospel doctrine in the demonstration of the Spirit and with power,
which appeared to be generally well received,
and was to the great comfort and relief of those engaged therein.
But the meetings of ministers and elders, and those for discipline,
were for the most part very heavy and distressing;
great weakness and lack of living concern, were painfully felt, therein;
that divine wisdom which alone can build the house, was little attended to,
and formality prevailed.
Ability was graciously afforded to use plainness of speech,
endeavoring to make them sensible of the loss they sustained,
by forsaking the fountain of living waters, and hewing to themselves cisterns,
broken cisterns, that would hold no water:
yet we found a few sincere laborers amongst them,
whose hands I hope were in some degree strengthened; but things in general were very low.
On third-day we had a large satisfactory meeting on Conanicut Island,
to which many from Newport went; and next day another at Newport,
which was the last we had there.
In this meeting wisdom and utterance were given
to declare the Truth to their several states,
in much plain dealing, endeavoring to show them from where they had fallen,
and how vain it was to imagine they were God`'s
people in the state most of them were then in:
there was also encouragement to the few sincere hearted.
On fifth-day we had a very large meeting at Portsmouth,
to which came great numbers from Newport.
It was a time of great darkness and deep suffering with the oppressed Seed:
the young people are mostly gone into the air and undue liberties;
and those more advanced, a few excepted, are gone into the earth;
having much to do in government affairs, and many of them had got into the offices,
friendships and parties, as well as into the profits, of this world.

Next day we had meetings in our way to Nantucket Yearly Meeting, at Tiverton,
Little-Compton and Accoakeset.
The last two were very large, especially Accoakeset;
the Gospel was largely and with good authority declared
in them to much satisfaction and comfort,
there being considerable openness, many of other persuasions attending.
On second-day, being their Monthly Meeting at Aponyganset,
and notice having been given of our intention of being there, it was exceedingly large;
it was supposed there were two thousand people present.
In this large assembly the everlasting Gospel was preached in
the demonstration of the Spirit and with power;
wisdom being mercifully given to divide the word suitably to the various states:
the meeting appeared to be generally affected, and the minds of those engaged,
greatly relieved.
Early next morning we embarked for Nantucket, in company with about twenty Friends,
and landed about five o`'clock in the afternoon of the same day.
On sixth-day the Yearly Meeting began, and was very large:
a becoming plainness appeared in the general; but,
alas! the life of religion was very much departed from by numbers in that place,
once so much noted for a family of love.
I went on the island a stranger to their present state,
though I had been there twice before, a witness of better times:
much distressing anguish was felt in this meeting,
and for some time I expected the current of life would have been wholly obstructed.
But at length, through divine mercy, Truth arose with Gospel authority,
setting forth what a great manifestation of evangelical light and Truth
sprung up in the last century after a dark night of apostasy and error;
when the heavenly power being embraced, brought forth the nature and spirit of religion;
but endeavors now are too often used to support the same principles in a formal way,
by the strength and wisdom of man; and the Lord will not own a people in that state.
Many things were delivered upon this subject with great dread,
and I felt the Lord`'s power go forth as a fire amongst the briars and thorns;
many were struck with sadness and fear, and the everlasting name was exalted.
Thomas Gawthrop was there and had good service.
The meeting ended on second-day,
much Gospel labor having been bestowed in the several sittings thereof.
Notwithstanding the general state of Friends on that island appeared deplorable,
yet I believe a remnant are and will be preserved fresh and lively in religion.
May their number increase!

We left the island on third-day, the 1st of the seventh month,
and landed that evening at Seconesset, on the continent, being about fifty in number.
We had a small meeting on fifth-day, at a meeting-house near the place of our landing,
and went forward to be at Sandwich Quarterly Meeting.
On sixth-day we went to their Monthly Meeting,
where was a burial of a Friend who had died suddenly.
There were many Presbyterians present:
the Gospel power arose with considerable strength and clearness,
with the words of the apostle;
"`Give diligence to make your calling and election sure;`"
with remarks on the great importance of the work,
how necessary to be assured of its going forward,
and that a certainty thereof may be obtained,
by the spirit of God bearing witness with our spirit,
according to the apostolic testimony.
This exhortation contradicts the dark opinion of
absolute and unconditional election and reprobation;
seeing this pressing advice to make it sure, implies something to be done on man`'s part,
which may be omitted, and he thereby may miss the election of God`'s grace; whereas,
according to that, the election is made so certain,
even from the foundation of the world, by an immutable decree,
that all man`'s endeavors will make no alteration,
seeing one cannot possibly be added to the number of the elect, nor one diminished.
The great absurdity of this doctrine was exposed,
showing how it reflected much dishonor on infinite mercy and goodness;
and some of their strongest arguments in favor of that doctrine were answered.

I was also opened upon infant baptism, so called,
setting forth how unreasonable it is to uphold types, signs and shadows,
unless We expect another and higher dispensation:
that types always pointed to the anti-type or substance,
and seeing most acknowledge the substance is come, how weak to keep up the sign.
It was a good time, for Truth was exalted and the meeting pretty generally affected;
and though these disputable points were closely handled, yet there was no opposition,
nor the least objection appeared.
On seventh-day the Quarterly Meeting was held, in which we had some profitable service,
in a close, searching way; things appeared very low, yet there were some sincere,
honest laborers.
We went after meeting about twenty miles to Plymouth,
where it is said the first colony of English landed and settled.
The next day, being the first of the week, we went to Pembroke meeting,
which was but small of Friends, but a pretty many of other societies came in,
considering the short notice;
the truths of the Gospel were largely delivered amongst them,
and seemed to be well received.
We set out after meeting, intending to pass through Boston,
and as far to the eastward as we proposed to visit Friends, leaving notice as we went,
at the several meetings, to take them in our return.
We had very large meetings at Cachechy and Dover;
and although we found but little living concern amongst Friends,
yet the blessed Truth favored and opened the way
for much Gospel labor suited to their states,
in order to revive ancient zeal and ardor.
The weather was extremely hot and the meetings crowded,
so that at times it seemed as if I should have been overcome and faint;
but by divine favor, I was mercifully carried through,
to a considerable degree of satisfaction and peace.
We returned to their Quarterly Meeting at Hampton, which began for ministers and elders,
on seventh-day the 12th of the seventh month.
We were sorrowfully affected to find so little
living concern amongst the leaders of the people.

Next day being the first of the week,
we had two large meetings composed of Friends and others.
A religious labor for heavenly bread seemed almost lost,
even amongst those advanced in age and profession of the Truth;
yet in marvelous condescension,
the Gospel power and life sprung up and extended to their various states,
with great strength and clearness, even as a flame of fire against the wood,
hay and stubble.
It was showed what a great and glorious thing Christianity is;
how complete victory and dominion may be obtained by it over sin,
and the soul of man be endued with sublime virtues;
but that to view the notion of Christianity which
people in general appear now to be contented with,
it would seem as if little real religion remained on the earth.
In the afternoon I was led to set forth that there is one body, one spirit, one Lord,
one faith and one baptism; that by this only,
people come to be truly initiated into the church,
being buried with Christ by his saving baptism into his death,
and thereby witnessing with the apostle,
the measure of the sufferings of Christ which are yet behind, fulfilled in us;
if so be that we suffer with him, we also may be glorified together:
the deep mystery of man`'s redemption through Christ, was largely opened,
it being a time of great favor, and the people were generally affected.
Next day forenoon was held their meeting of business; but as the power of Truth,
the main spring of action in the weighty affairs of the church,
appeared to me sorrowfully wanting, little could be done to good purpose;
some close remarks were made upon the declining state of that meeting,
wherein we had very little satisfaction.
In the afternoon we had a very large concluding meeting,
wherein Christ was freely set forth as the true light,
who enlightens every man that comes into the world;
and that as the light of the outward sun is necessary
for transacting the affairs of this life,
so the light of the Sun of righteousness,
is no less necessary to show us how to perform the great work of our soul`'s salvation:
it was a good time.
We then had meetings at Amesbury, Newbury, Salem, Lynn and Boston.
At Lynn in the afternoon, being first-day,
I found it my place to set an example of silence;
at the other meetings I was largely opened in the service of the Gospel,
to good satisfaction and comfort.
From Boston we traveled to Dighton, and dined on the way at Taunton.
Our guide being acquainted with a shopkeeper in that town,
we were invited to dine with him:
after dinner we entered upon much reasoning about religious principles,
and a close dispute ensued.
I was, through divine assistance,
enabled to stand my ground and to maintain our principles,
to the comfort and satisfaction of my own mind, and I believe in a good degree to his;
who I understood had been accounted a very zealous Presbyterian,
and had entertained an unfavorable opinion of our principles:
he confessed they never had been cleared up so much to his satisfaction before,
and seemed to be a good deal affected; we parted in love and friendship.

We then had meetings at Free-town, Longplain, Rochester and Acushnet;
in these we found things very low and languid,
as appeared generally the case in New England; our Society, like others,
having too much dwindled into form and profession.
The last meeting was very large, but my way was quite shut up as to ministry;
in the others I had close searching service.
On first-day the 27th of the seventh month, we had a very large meeting at Swanzey,
to which came Friends from many parts, some even from Newport.
The power of the everlasting Gospel arose in this large assembly,
and wisdom and utterance were given to declare the Truth from these words;
"`To know you the only true God, and Jesus Christ whom you have sent, is life eternal.`"
The meeting was much affected;
the Lord`'s heart melting goodness was sweetly enjoyed by a remnant.
Next day we had a large meeting at Smithfield; the nature of true religion,
from the apostle James`'s definition of it, was copiously treated of:
it was a favored time, and the people were generally affected.
On third-day we had a meeting at Wainsoket: great numbers of loose, libertine people,
who, I suppose, rarely attended any place of worship, came out of curiosity;
and indeed those, for the most part, who profess with us there,
seem as if they knew little of the nature and importance of religious worship;
but it was my duty to sit in silence.

Next day we had a very large meeting at Mendham, to which came many of our profession,
and a great number of such as being dissatisfied with
the established worship and a hireling ministry,
had separated and held meetings in one another`'s houses,
having such as thought it their duty to preach freely amongst them:
to this meeting the Gospel was largely preached, which seemed to have a general reach.
After meeting came a predestinarian, and a young man,
a preacher among those separatists before mentioned,
who are quite averse to that dark opinion: these two it seems,
had been engaged in a dispute in the meeting-house when all were gone,
upon some points of doctrine delivered that day concerning
original sin and the opinion before mentioned;
and as they could not settle the points, at length they agreed to come to my quarters,
to ask me a few sober questions, by way of further explanation of some things delivered.
When they informed me of the reason of their coming,
I told them I was very willing to afford them all the satisfaction in my power,
but was not very fond of disputes,
which seldom tended much to edification as they were generally managed.
The old man signified he had no intention of entering into any dispute; however,
one thing brought, on another, till we got very closely engaged: the young man,
the preacher, was on my side, and I think,
had as remarkable a memory in the Scriptures as I ever knew,
and was favored with a considerable understanding in the mystery of them.
The poor old man, though I suppose as well furnished as most upon such a bad subject,
was entirely vanquished and confounded to that degree,
that his spirits appeared to be sunk with sorrow,
because he could not support his principles better.
The young man and I, with other friends, withdrew into another room,
and had a religious conference,
particularly upon the nature of Gospel ministry and worship;
he appeared to be much enlightened and not far from the kingdom;
but I fear he had entered into the ministry too soon.
This opportunity afforded my mind a good deal of satisfaction.
I found many of those high professors in New England, in rather an unsettled state,
and fond of flocking to our meetings;
they seemed to hear the doctrines of Truth with satisfaction,
and there was great openness amongst them in many places.
But what sorrowfully affected my mind was,
that there is so little of the life of religion held up as a standard to these,
by our Society in those parts; yet I believe there will be a gathering to Shiloh,
in the New England colonies.
Their esteem and regard to Friends, is very different from what it was formerly,
though perhaps that in part may be owing to some in our Society being more like them,
than our Friends were in early times; yet I believe the case is otherwise with many,
and that it arises from their good opinion of most of our principles.

On fifth-day the 31st of the seventh month, we set out, accompanied by two guides,
through the back parts of Connecticut, towards Oblong, in the government of New-York,
being about one hundred and forty miles through a Presbyterian country;
they generally carried themselves civilly,
and we had some religious conferences to good satisfaction.
The weather was very hot and the roads stony, rough and mountainous,
and the entertainment but mean in many places,
so that the journey was attended with fatigue to our bodies and horses.
We went to New Milford meeting on first-day, the 3rd of the eighth month.
I had nothing to offer by way of ministry, yet in my quiet waiting,
I was favored with the first clear satisfactory glance of my
being at liberty towards the latter end of this year,
to return home, which I fully believed, but kept it to myself.
After meeting we ascended to the Oblong, and a long ascent it was,
of nearly a mile to the summit of that called Quaker hill;
the weather being extremely hot, I feared it would have killed my horse,
and I was not able to relieve him by walking.
On third-day we had a very large meeting at a
commodious house built by Friends on that hill.
They who attended were generally professors of the Truth as held by us,
and mostly plain and becoming in their outward garb;
yet alas! when they came to be viewed in the true light, they appeared dry and formal;
many, I fear, having clothed corrupted nature with a form of religion,
and in a plain dress sit in their religious meetings like dead images.
After a time of deep suffering in spirit with the oppressed Seed,
the word was given with good authority,
and went forth like a flame of fire against the wood, hay and stubble, to the arousing,
I believe, and awakening of many for the present.
The condition of man in the transgression, as set forth by the inspired writers,
was opened; that he is in a state of enmity to, and separation from God,
and consequently must experience a very great change,
before he can be acceptable to his Maker: showing how this change is to be effected,
and that the operation necessary thereunto,
makes indelible impressions on the minds of all
who are so happy as to experience the same,
without which none can be true Christians.
Truth had great dominion that day.

We had a very large meeting next day at the Nine Partners, and had close service therein.
Next day we had a very painful afflicting meeting at Oswego;
I was quite a stranger to them, and did not know by any outward information,
that they had any one who usually appeared in public among them;
yet my mind was strongly impressed with a sense that
the meeting had been much hurt by a wrong ministry,
and for that reason chiefly, my mouth was shut up there in that respect:
it seemed as if the very person was shown to me in the meeting,
though I had never seen him before that I know of; but I found afterwards,
it was a true sense, and I told Friends in his hearing,
how things appeared to me in that meeting, which seemed to strike him,
and he struggled a little, but I left it upon him:
may the great and gracious helper of his people, have the praise of his own works,
says my soul, now and for evermore!
On first-day, the 10th of the eighth month, we were at the Oblong again;
and my travail during the whole meeting was in suffering silence.
From hence, in our way to New-York, we had the following meetings: Peach-Pond,
North-Castle, the Monthly Meeting at the Purchase, Mamaroneck, and Westchester;
at most of which, the Gospel power was largely manifested,
by opening doctrine and counsel, in a close, searching manner,
to the various states of the people.

On first-day, the 17th of eighth month, we were at two meetings in the city of NewYork;
in the morning I was silent; in the afternoon, Truth opened the way to public service,
showing the beautiful order and economy of human life; all seeking for some mansion,
possession or settlement, and agreeably to the laws of prudence and justice,
endeavoring to increase their store,
that they may have something of their own against the time of need:
if prudence requires to provide the necessaries for this short and uncertain life,
how much more incumbent is it upon us, in regard to the immortal part;
and that our eyes should be turned to view the order, harmony and beauty,
of the new creation, and to seek an inheritance in the holy city?
It was a blessed time, and many hearts were tendered.
I had a good deal of satisfaction among Friends in that city,
and hope there is a growth in the best things experienced by many.

On second-day we crossed the bay and Staten-Island;
ferried from there at Elizabeth-town Point, and went to Rahway.
On third and fourth-day we went to the Quarterly and Monthly Meetings at Woodbridge;
and I was enabled to labor largely in a searching way,
with much plainness and Gospel authority, for their help and recovery from a weak,
languid, unconcerned state; yet we found some solid, valuable Friends amongst them.
from there we proceeded on our way to my companion`'s house in Pennsylvania,
and had large meetings at Plainfield and Kingwood,
wherein the Gospel was preached with great openness, to good satisfaction.
On seventh-day evening, the 23rd of the eighth month,
having crossed the Delaware at Howell`'s Ferry, we got to my companion`'s house,
and attended two meetings at Wright`'s-Town, where he belongs.
Next day there was a considerable number of professors assembled at meeting,
but spiritual idleness was felt sorrowfully to prevail over many,
craving to be fed with words; I found it my duty to be silent at both the meetings.
Having taken a cold after some of the late large and hot meetings, I was much indisposed,
and staid at my companion`'s till fifth-day,
and then went to the Quarterly Meeting for the county of Bucks, held at the Falls,
which was exceedingly large.
Truth greatly favored that meeting} in opening doctrine and counsel, for the help,
reproof and encouragement of many, beginning with these words,
It is especially worthy to be noted, that the inspired writers,
both in relating their own experience, and in administering advice and counsel to others,
on a religious account, lay the whole stress of religion upon the inward,
saving and spiritual knowledge of God.
It was a great time, and many hearts were tendered.
The Youths`' meeting was held next day at Bristol; it was a low, poor time,
and I had nothing to offer by way of ministry.

On first-day, the 31st of the eighth month, I went to Makefield meeting,
which was an exercising time; a careless, earthly spirit was felt to be very prevalent;
I had some service there, in a very close, searching manner.
In the afternoon I had a very large meeting at John Beaumont`'s,
wherein much Gospel doctrine flowed to the people,
upon the nature of self-denial and bearing the yoke of Christ; many, not of our Society,
were present and pretty much affected; it was a favored time.
Next day I went to Buckingham Monthly Meeting, which was very large,
a numerous body of Friends living in those parts;
I had great openness for public service therein, showing,
that the promises of God in him, are yes and amen forever;
yet we are not entitled to them but upon certain conditions, that is,
being in those states to which they are applied.
It was a good time, Truth being exalted.
On third-day I had a large meeting at Plumstead,
many attending from Buckingham and other places.
The word was given with authority and clearness, to declare to this numerous auditory,
upon the nature of true religion and worship, showing,
that it principally consisted in an inward exercise of the soul towards God,
and especially depended on a spiritual acquaintance with him; it was a favored time,
and many hearts were tendered.
For some time past I had been indisposed, being, through the extremity of the heat,
much afflicted with a rash, called the prickly heat; and having taken a great cold,
my asthmatic disorder was much increased; yet,
through merciful help supporting soul and body in the great work to which I was called,
I was enabled to proceed on my journey,
having a strong desire to visit some meetings in the back parts of Bucks,
Philadelphia and Chester counties,
before the approaching Yearly Meeting for Pennsylvania and the Jerseys,
to be held in Philadelphia towards the latter end of the ninth month:
apprehending if I could accomplish that, I should have little to do after,
except on the eastern shore of Maryland and in the lower counties upon Delaware.

Here my valuable friend Zebulon Heston, joined me for a companion to the back parts.
We traveled next day to Richland, and the day following had a large meeting there,
mostly consisting of those under our name:
great lukewarmness and lack of a living concern was felt;
yet it pleased divine goodness to favor with
ability to labor in the Gospel with plainness,
in a very awakening manner, which seemed to have some tendering effect,
at least for the present.
We traveled next day to Oley, called also Exeter, and went to their meeting on first-day,
the 7th of the ninth month.
They appeared to me mostly ignorant of the importance of that
worship and service which they pretended to meet about,
and as if the chief waiting was to hear what the poor servants had to say:
they were disappointed in respect to me,
finding it my place to sit the meeting in silence.
We afterwards went to Maiden-creek, and had a large meeting the next day.
I believe there were some valuable Friends there,
but many appeared in a state of indolence as to religion, looking for words.
There was a considerable space of silence; at length Truth arose and obtained dominion,
and the Gospel was freely preached;
showing the nature of the work of man`'s salvation by Christ,
and the great danger of a neglect thereof.
On third-day we had a meeting in Reading Court-house, to which many came,
not of our Society, mostly Germans, who behaved in a solid, becoming manner;
the word of theGospel was given,
and ability to declare it with good authority and clearness for a considerable time,
to the tendering of many hearts.
Next day we crossed Schuylkill, and had meetings at the Forest, Nantmill,
Providence and Pikeland, in all which, ability was given to labor in the Gospel,
for stirring up professors to a more lively sense of religion,
which was felt to be at a low ebb amongst them, as in many other places.
There is cause of mournful complaint,
where people go no deeper into religion than
what comes by education or outward conformity:
many in these parts have entered into the outward
possessions and profession of their worthy ancestors,
at a very easy rate; yet the Lord, in great mercy,
is causing his trumpets to sound very loud, to awaken such to a sense of their danger.

On first-day, the 14th of the ninth month, we went to Uwchlan,
which was a very large meeting of itself,
and Friends came to it from most of the adjacent meetings.
The fore part was a time of deep travail and silent labor,
in a painful sense that many present were at ease in a bare profession of the Truth.
At length the word was given with considerable weight and Gospel authority,
showing what a powerful efficacious thing Christianity was,
when it made its first entrance into the world, and so continued for a considerable time,
mightily prevailing by its own force and efficacy,
against all opposition and worldly interest, until the world smiled upon its professors;
the name then spread, but they gradually loosing the power and life, many disorders,
great corruptions and desolating contentions about trifles, got in.
Close application of these things was made to the states of
the inhabitants of this highly favored province,
earnestly pressing the auditory to seek after the substance of religion.
The afternoon meeting was solid and comfortable in silence.
On third-day we had a large meeting at EastCain, in which I had thorough service,
to good satisfaction; and next day we had a very large meeting at Bradford,
in the Forks of Brandy wine; things were felt to be much out of order,
and religion to be at a very low ebb amongst them, yet, through infinite condescension,
Gospel authority was given, with much clearness in doctrine, showing,
that in order to possess a valuable religion,
man should be feelingly and experimentally convinced, that in matters of religion,
he must wholly resign his will to God,
and give himself up to be guided by the holy Spirit; until then, he cannot say,
with acceptance to his Maker,
"`Your will be done in earth, as it is done in heaven.`"
It was, through divine mercy, a highly favored baptizing time,
and the blessed Truth was in dominion over hard, unmortified spirits.
I went home with my brother-in-law, Micajah Speakman, to Concord,
where I rested quietly three days, after long fatigue of traveling and hard labor;
yet all was made easy through the efficacy of that heavenly
power which mercifully attended from place to place,
filling my soul, at times,
with true contentment and perfect resignation to the Lord`'s will, either to do or suffer;
in which happy state, my peace flowed as a river.

On first-day, the 21st of the ninth month, I went to Middletown meeting,
but had no public service therein, and on second-day proceeded to Philadelphia;
attended their weekday meeting next day, and on fifth-day I went to Haddonfield,
in West-Jersey, to the burial of Thomas Redman, a public Friend in good esteem,
who formerly told me he was first reached or convinced through my ministry,
in the Bank meeting at Philadelphia, about thirty years ago.
The meeting was very large, consisting both of Friends and those of other societies;
the truths of the Gospel were largely declared, with clearness and good demonstration;
the auditory being very solid and attentive,
Truth had good dominion to the comfort of many.
In the afternoon was held their Quarterly Meeting of ministers and elders;
it was a low time.
Next day was held their Quarterly Meeting, which was very large;
there seemed to be great expectations and looking after words,
as is sorrowfully the case with many in these parts,
especially if the poor instrument had been favored before, and it pleased them:
this sometimes tends to deprive them of that which they so anxiously seek after,
which I believe was now the case, for I was quite shut up as to public service,
but had some good service in the meeting of business.
On seventh-day, the 27th of the ninth month,
I went to the Yearly Meeting of ministers and elders at Philadelphia,
for Pennsylvania and the Jerseys.
It was large, and I had some service therein.
I informed Friends that I expected liberty to return home that fall,
requesting a few lines by way of certificate, to my friends in England,
according to the good order used amongst us;
this was the only one I requested on the continent of America, yet Friends,
of their own accord, sent certificates from most or all the parts I visited.
A certificate was readily granted, and signed by a great number of ministers and elders,
testifying their unity with my Gospel labors and conduct while among them.
I diligently attended the several sittings of this Yearly Meeting,
both for worship and discipline, and had some weighty service in them.

On first-day, the 5th of the tenth month, I went to Fair-hill meeting,
and returned to the evening meeting in the city.
On third-day, the 7th of the tenth month,
I set out in order to attend the Yearly Meeting on the eastern shore of Maryland,
being accompanied by Samuel Eastburn.
We had meetings in our way at George`'s-creek, and the head of Sassafras;
Truth made way for close, weighty service, to the states of those present.
We went, the 11th of the tenth month, to a small poor meeting for ministers and elders,
at Cecil, in Maryland; and next day being the first of the week,
the Yearly Meeting began there, to which came many people of various sorts,
most of whom seemed loose, and void of a solid, religious concern.
Death and darkness were felt to reign in the general, yet the Gospel power,
in great mercy, broke through, and opened suitable doctrine to their states,
showing the general consent of all ages and nations,
to the immortality of the soul and future rewards and punishments;
and although the professors of Christianity were
favored with more clear apprehensions thereof,
than others, yet numbers of them live as if they had no such belief,
or as if they did not look upon themselves to be accountable creatures.
The succeeding meetings, both for worship and discipline, were, I hope,
through divine assistance, profitable to many.
The Yearly Meeting at Choptank began on seventh-day, the 18th of the tenth month,
and ended on fourth-day afternoon; many of the meetings were very large,
and the truths of the Gospel powerfully declared in them,
and the everlasting unchangeable Truth was
exalted over all of a contrary nature to itself:
this Yearly Meeting afforded great relief and satisfaction to my mind.
We set out on fifth-day,
in order to attend the Yearly Meeting to be held at Little-creek,
in Kent county, on Delaware.
It began on first-day, the 26th of tenth month, and held two days;
I had very open service therein.
After this meeting I found myself at liberty to seek a
proper opportunity to return to my native land,
and so went from hence directly toward Philadelphia,
and attended the Monthly and Quarterly Meeting there, wherein I had good open service.

I found a vessel bound for London,
the captain intending to sail about the middle of the eleventh month.
I went on board, accompanied by several Friends;
we sat a while in the cabin in solemn silence;
my mind deeply engaged to be rightly directed; and finding, as I thought,
rather a freedom to go in that ship, I signified to the captain and owners,
that I intended to embark in her, which they appeared to be well pleased with.
I then went to Chester county, to take leave of my relations and friends,
and to attend the Quarterly Meeting at Concord; which I did,
and had large open service in the several meetings, to great satisfaction and comfort.
On third-day I went to a large meeting at Chester;
over which death and darkness seemed to reign, so that I had no power to move,
as to ministry.
I got to Philadelphia next morning, the ship being to sail from there the next day.
On sixth-day, about nine o`'clock,
I took a solemn leave of sundry valuable Friends in the city,
and set out for Chester to meet the ship;
many Friends from there and Darby accompanying me, after dinner,
in near affection we took leave, never expecting to see each other again.
I embarked on board the ship Phebe, captain Mungo Davidson;
we got under sail about two o`'clock next morning, and on first-day,
the 16th of the eleventh month, about four o`'clock in the afternoon, we got to sea.

I find this remark amongst my memorandums, written, I suppose,
after I had been some time at sea:
"`It is fit to be remembered, in humble and awful acknowledgment,
that the Lord has been with me ever since I came on board this ship,
in love and mercy unspeakable, causing sweet peace to flow as a river in my soul,
so as to make me forget all my former anguish.
For the former things are all passed away, so that through infinite condescending love,
I have learned to sing the song of Moses and the song of the Lamb,
and even upon the mighty foaming unstable ocean, to speak in myself in psalms and hymns,
and spiritual songs, making melody in my heart to the Lord.
He has been pleased to preserve me through many, oh! very many heights and depths;
heights in my service and in the affections of my friends and others,
I hope from being lifted up or exalted above measure,
by the revelation I have been favored with;
and through the deep baptisms I have experienced, in sympathy with the precious Seed,
borne down and pressed by the sins of mankind, as a cart is pressed with sheaves;
the Lord enabling me to be resignedly contented in that state.
Whether in suffering or rejoicing, in silence or in words,
he mercifully gave me this support by the power of his own Spirit,
and now is so gracious as to reward my mind with sweet peace
for abiding in that station wherein he alone preserved me.
I was, through unspeakable kindness, when I sat down in a meeting, mostly enabled to say,
"`Your will be done,
whether in making use of me as your instrument to sound an alarm to the people,
or to set them an example of silent waiting upon you.`"
What shall I say or return to the Lord of everlasting loving kindness,
for preservation by sea and by land, in many perils;
I am at a loss for expressions to set forth his bountiful goodness,
and the greatness of his love and mercy to those who trust in him.
I therefore humbly desire with silent reverence, or otherwise as ability is afforded,
to magnify, worship and adore him, who is glorious in holiness and fearful in praises,
working wonders, who alone is worthy now and evermore!
Amen!`"

We had a strong new ship which had been at sea but one voyage before,
and was very tight in the river and bay,
but we had not been a week at sea before she sprung a leak,
so as to require much labor to clear her of water.
This seemed to affect the captain and the passengers pretty much,
not knowing but the leak would increase, and we were but poorly manned,
the captain having been deceived in some whom he had taken for good hands,
and who proved of little use, no, one of them rather a burden.
In this gloomy time, through merciful help, I found a blessed support to my mind,
in humble confidence that he who is Lord of all,
in whose counsel I apprehended I was there,
would conduct me safely to my outward habitation.
Yet I was sorry for such an addition to the work of the sailors,
as we were obliged to keep one hand at least, at the pump night and day all the passage,
which was stormy and rough, and very unpleasant to the body.
The "`captain and passengers were very civil and obliging to me.
It was the 19th of the twelfth month,
before we found ourselves in soundings on the English coast.
After we had sailed a considerable way up the channel, the wind came ahead of us,
so that we beat about there for several days,
and were once in great danger of being shipwrecked upon the island of Alderney.
On the 25th of the twelfth month, in the evening, we put into the safe port of Dartmouth.
I then resolved to leave the ship, being about two hundred and thirty miles from home,
where I arrived the last day of the year 1766,
having been upon this journey one year and a half, lacking a few days.
I understood it was six or seven weeks before the ship arrived at London,
after I left her.

As I have already far exceeded in what I intended to
leave behind me in the way of journal,
I must forbear adding much more; yet may just hint, that in the year 1768,
I went to the Quarterly Meetings of York, Kendal and Lancaster.
I had several other meetings in the north,
and accompanied by my worthy friend Samuel Fothergill,
had several meetings in North Wales, in town-halls, where none under our name resided.
I passed afterwards through a part of England, into South Wales, and so to Bristol;
from there I returned home; having passed through, in England and Wales,
about twenty-five counties, and attended sixty-three meetings,
and traveled about one thousand and sixteen miles.

In the fourth month, 1770, I set out, accompanied by my wife,
intending to be at the Circular Yearly Meeting, to be held this year at Ormskirk,
in Lancashire.
We were at Manchester meetings on first-day,
and attended a very large Monthly Meeting on the second-day following, at Warrington.
Truth and its testimony was exalted, and had great dominion over libertine spirits,
to the joy of the upright in heart.
The Yearly Meeting before mentioned, began the 17th of the same month,
and held three days: there was a very convenient booth erected for the purpose,
which it was thought, would accommodate two thousand people;
yet it was not sufficient to contain the numbers who came,
so that other meetings were held out in the open air at the same time.
The people in general behaved with civility and respect; there was considerable openness,
and the meetings were well conducted.
We returned from there homewards, taking Warrington meeting on first-day:
the journey was very satisfactory,
the whole being about four hundred and eighty-eight miles.

In the year 1772,
I went in company with my friends Sarah and Deborah Morris of Philadelphia,
to the Yearly Meeting at Bristol; it was large and divinely favored.
I attended, this year, four other Yearly Meetings, to very good satisfaction and comfort,
namely, London, Colchesler, Woodbridge and Norwich,
accompanied by my wife to the last four, as well as by the two Friends before mentioned,
who were in this nation upon a religious visit.

Being now in the sixtieth year of my age,
and having labored for twelve or fourteen years, at times, under an asthmatic complaint,
which has caused riding to be frequently painful to the body,
which difficulty age is likely to increase,
I expect that my traveling any considerable journeys will of course cease,
and having written so much already, I here intend to lay down my pen, committing myself,
and what is done, to the providence and blessing of God,
in whose power alone it is to grant patience, resignation and perseverance, to his poor,
helpless servants, and an increase of their Gospel labors: So be it!
