== Chapter VIII.

[.chapter-synopsis]
* Second Visit to Ireland--Remarks on Holding Meetings for Discipline on First-Days
* Returns to England and Attends the Yearly Meeting in London
* Proposal by Joseph White of Pennsylvania for Appointing a Committee to Visit the Meetings for Discipline Throughout the Nation
* Journey Into the West of England

I have preserved no account in writing, of my travelling in the service of Truth,
after I returned from the last-mentioned journey, until the forepart of the year 1760,
when I entered upon a visit to the meetings of Friends
in the nation of Ireland a second time;
having had it weightily upon my mind, at times, for some years.
But when it drew near, I clearly saw the time fixed to set out,
which I did the 1st of the third month, in the aforesaid year, and went to London.
The 2nd being on first-day, I went to Grace-church street meeting in the morning.
My business therein was to set an example of silence.
In the afternoon I had good open service at Devonshire-house meeting.
On second-day morning the 3rd, I went in the Westchester stage coach,
and arrived at that city on fifth-day night, the 6th. I went next day to Parkgate,
to inquire for a passage, where I found divers vessels ready to sail;
yet the wind being contrary, it was uncertain when;
some having already waited nearly a month for a fair wind.
I returned to Chester that night, and next day was poorly of a cold, having,
since my great illness, been very tender in my lungs,
and apt to be afflicted with an asthmatic disorder; so that travelling,
especially in cold foggy weather, was very unpleasant for me to bear,
having endured considerable hardship in my journey from London,
by such weather and the motion of the coach.

But all was made up, in the sweet enjoyment of that pure love,
which makes hard things easy and bitter things sweet.
The 9th, being first-day, I was at Chester meeting,
where the number of Friends was small, and the life of religion very low;
yet it pleased divine Goodness to extend merciful help,
giving me openness in the springing up of life,
to administer suitably for their advantage, I hope, if rightly improved.
The 10th in the morning, having hired a guide and two horses, I set out for Holyhead,
in order to take a passage for Dublin in one of the packets,
and got thither about six o`'clock next evening.
Here I found one of the packets was to sail early next morning.
I went on board the 12th, about six o`'clock in the morning,
and landed at Dublin about six in the evening, the same day,
having had an easy passage and civil usage on board,
and was kindly received by my open-hearted friends Samuel Judd and family.
I was pretty much fatigued with travelling,
being also afflicted with a cold upon my lungs,
which was aggravated by the thick sulphurous air of Dublin.
Yet the pure virtue and holy anointing of the precious Truth,
carried through and over all weakness, both of body and mind.

My soul being enabled to extol and magnify the God of my salvation,
for his gracious support every way; for indeed, humanly looking and judging of things,
it might not have appeared prudent, considering my weak and infirm state of body,
especially alone, to have undertaken such a journey;
but the power of Gospel love gaining the ascendency over
all reasonings and consultations with flesh and blood,
made me willing to give up life and all, in answering the Lord`'s requirings,
and to pursue what he was pleased to call me to, as far as ability of body would admit.
This is a great mystery to the carnal man,
but it has as real an existence in a redeemed mind,
as that a principle of self-love is the spring of action to an unredeemed mind.
On sixth-day, the 13th, I went to the weekday meeting at Sycamore-alley,
where humbling goodness was refreshingly near,
and opened the doctrines of Truth largely and livingly, to the comfort of many hearts.
On first-day, the 16th, I went to Meath-street in the morning,
where I had thorough service, to my own great comfort and ease;
though my spirit was much grieved,
to view the havoc made amongst Friends in that great city, by undue liberties;
but most of all under a mournful sense,
that the dragon`'s tail had drawn some of the stars down again into earthly pollutions,
and caused a bad savour.

This was offensive to my soul, even as a nuisance in that meeting.
May others`' harm and miscarriages cause all the Lord`'s anointed to be very watchful.
I went to Sycamorealley in the afternoon, where the meeting was very large.
Silent waiting upon God was my service therein, in which I had peace and comfort;
and towards the conclusion, there was an awful solemnity, in a remarkable manner,
over the meeting, wherein the excellency of silent worship appeared.
On second-day, the 17th, I went to Baltibois and had a meeting there next day.
I had close arousing service therein;
the testimony of Truth went forth very sharply against haughty libertine spirits.
There I met my good friend Abraham Shackleton,
who travelled with me most of the time I was in that nation.
Of him, I think, it may be said, as was of Nathaniel, "`Behold an Israelite indeed,
in whom there is no guile!`"
He was a great comfort and help to me,
and though he did not appear publicly as a minister;
yet he would drop tender advice at times, in families, in a very affecting manner.
His whole conversation, looks and deportment, were so leavened and tempered with good,
that I looked upon him as a preacher of righteousness wherever he came.
I went with him after the above-said meeting, to his house at Ballytore,
where next day I had a precious open meeting, and good thorough service therein;
the blessed unchangeable Truth being in dominion over all.

The 20th I had a good meeting at Athy, and the next day another at Rathangan,
in which there was a wonderful manifestation of the divine power,
and much clearness in opening the doctrines of Truth; so that I believe there were few,
if any, but were sensibly affected therewith.
I hope such great extendings of favour will not be easily forgotten.
From thence I went to Edenderry, and was at their meeting on first-day, the 23rd,
which was a very large meeting,
and the power and wisdom of Truth was eminently manifested, in furnishing with ability,
to divide the word aright to the several states in that great meeting.
It was in much dread and weight, not sparing any rank or station in the Society.
All there, I believe, through divine favour, had some share of that day`'s work;
I hope not easily to be forgotten.
May the Lord alone have the praise, for he is the author of all the good that is,
or can be done.
The 25th I had a large meeting at Mountmellick, in which I had thorough service.
The labour was somewhat painful, in a sense of indifference,
and the insipid formal state of many, as well as the pride and undue liberties of others;
both which have sorrowfully prevailed in that nation;
yet I found great ease and peace of mind,
in the discharge of that weighty concern which was upon me for their help and recovery,
and which I hope had a good effect on many.

Next day I had a large meeting at Mountrath.
I was enabled to discharge the service required, in a searching manner,
that careless professors might be stirred up to their respective duties;
and ancient zeal, ardour and beauty, restored to the churches.
From thence I went to James Huchinson`'s, where I had an open serviceable meeting;
I hope to the comfort and help of many.
The 28th I had a meeting at Ballinakill, where I had a good degree of openness,
for the help and encouragement of Friends in the way of well-doing;
but things were very low there, as to the life of religion.
I went after meeting to Carlow, in order to attend the province six weeks meeting.
Many Friends, from the several parts of the province, came to it.
It was a large meeting, and considering the low declined state of things,
we were favoured with wonderful extendings of heavenly power, wisdom and living virtue,
in order to heal and restore backsliding Israel.
Great and marvellous is, and hath been, the condescension of the Almighty to his people,
through all ages!
The doctrine of the Gospel flowed forth freely to the several states of those present,
and many were much humbled, in an awful sense of the divine presence,
which is the life and strength of God`'s people.
I had a large meeting at the same place on first-day, the 30th,
it was a blessed opportunity of favour and saving help extended to those present; surely,
if these high benefits are not duly improved,
great will be the condemnation of those upon whom they are bestowed.

I went from thence home, with my kind friends Robert Leckey and wife,
and had the next day a precious open meeting and good service therein,
at the house of our worthy ancient friend Samuel Watson, of Killconner.
I went from thence to Ross, where, at the house of Samuel Ely,
I had a low afflicting meeting, but little to be felt of the life of religion.
I was quite shut up as to ministry.
From thence I went to Waterford, where, on the 3rd of the fourth month,
I had a large meeting; it proved a time of close labour;
yet I waded through to my own ease, in a good degree.
On the 4th, I had an open precious meeting at Clonmel.
Oh, how the heavenly virtue streamed forth in doctrine and counsel, for the help,
encouragement, and stirring up of Friends and others, to their religious duty!
The great name of our God was adored and magnified.

The 5th I went to Cork and attended their meetings on first-day.
They were large,
and although the declension from the life and simplicity of Truth
is very great and obvious amongst Friends in that city,
and many under our name are much defiled with the love of earthly gratifications,
preferring their outward interest to that of religion;
yet great was the extending of divine love and favour for their help and recovery.
The doctrines of the Gospel were thereby largely and livingly opened,
I hope to the comfort and help of many, causing the hearts of a sincere,
upright-minded remnant amongst them greatly to rejoice with thankfulness.
On third-day, the 8th, I attended a very large meeting there,
both of Friends and people of other religious persuasions;
it being appointed for the marriage of our friend Samuel Neale,
to a daughter of Joshua Beale, and grand-daughter of our worthy Friend Joseph Pike,
deceased.

The forepart of this meeting was very cloudy and painful,
but the sincere travail of the upright in heart prevailed with the Lord to arise;
then his enemies were scattered,
and the glorious powerful Truth shone forth in its beauty,
whereby the poor had the Gospel to preach, in the blessed demonstration thereof.
It was a time not to be easily forgotten; made so by his refreshing presence,
who turned our water of affliction into the reviving wine of his kingdom; to whom,
for the multitude of his mercies to his church and people, be humble thanksgiving,
sincere obedience, and praises forevermore, Amen!
I went from Cork directly to Limerick, where on the 11th I had a thorough open meeting,
and the testimony of Truth was greatly exalted, I hope to the comfort and help of many.
I often much admired the divine condescension,
in the open visitations of his unmerited love and long suffering kindness,
to a greatly revolted and backsliding people.
But what we finite creatures cannot comprehend,
of his unfathomable regard to the workmanship of his hands,
we ought to adore and worship him for, with reverence and awful fear.
So be it, saith my soul, both in time and eternity.
I went from thence to Killconner-moor, where on first-day, the 13th,
I attended their meeting, which was but small, and my service therein was very laborious.

The testimony given to bear went forth very sharply against wrong liberties.
I was much afflicted, in a sense of the almost desolate state of that meeting,
which that worthy man John Ashton, being first himself convinced in that remote place,
was the instrument in the Lord`'s hand,
by his savoury circumspect life and labour to gather.
I had a meeting in the afternoon at Birr, where there are but few of our Society,
but many of the people called Methodists and soldiers came in.
The Gospel of life and salvation was largely preached unto them,
and the necessity of the new birth pressingly enforced.
The nature whereof, from a degree of experience being set forth,
the meeting appeared to be generally affected, and I hope it was a serviceable time.
Some of the Methodists expressed their great satisfaction after meeting,
beyond what I choose to mention.

On the 15th I had a very painful exercising meeting at the Moat.
Great indeed, was the distress of my mind,
viewing the general hardness and insensibility,
as well as the vain frothy light spirits of some.
I had very little openness and scarcely any thing to deliver,
but under a sense of the Lord`'s anger being kindled against them, by whom,
if they do not repent, they will be rejected.
Though I hope there were some few had a degree of tenderness and good desires;
but alas! it is a hard lot for such who have a sense of feeling,
to be incorporated with a people generally so insensible of the life of religion;
but the Lord is all-sufficient for those who put their trust in him.
On the 18th in the morning, I had a meeting held at Freeman`'s, near Old-castle,
for our Friends only,
in which I had matter and utterance given suitable to the states of the few present,
who were pretty much affected with the testimony of Truth.

In the afternoon I had a large meeting in Friends`' meetinghouse at Old-castle.
I understood after meeting, they were mostly Papists.
I had a large opportunity to publish the truths of the Gospel with considerable clearness;
showing the necessity of obtaining victory over sin,
through the power and efficacy of living faith in Christ; by whom only,
full remission of sin is to be obtained upon sincere repentance; showing in some measure,
the great danger of supposing the Almighty hath delegated
the power of forgiving sins to any man,
or set of men whatever; that all who were desirous to be freed therefrom,
must know the work of God`'s spirit in their hearts, to work that change,
or to bring forth that new birth our Lord taught Nicodemus the necessity of.
The auditory were generally quiet and attentive, appearing to depart well satisfied.
One of the Papists after meeting, expressed much satisfaction with the doctrine delivered.
But I understood one or two priests were much offended therewith,
yet they said nothing to me; so all passed off quietly, as was my mind,
having sweet comfort in the labour of that day.

From thence I went to Coothill, and the 20th was at their first-day meeting,
wherein I was largely concerned in a close arousing testimony.
It was very sharp against the inordinate love of the world, which,
and other undue liberty, seemed to me to have almost laid that meeting waste.
Their Monthly Meeting of business was held that day,
which to me was another token of their little regard
to the great cause of religion and virtue,
that they could not find it in their hearts to bestow another
day for transacting the weighty affairs of the church,
which I have always observed to be the case, where Friends are really alive in religion,
and not narrowed up by the love of the world.
It hath often appeared wonderful to me,
how the professors of Truth dare offer such an indignity to the Infinite Being,
and his awful work, as to put it off until it suits them best,
and when they are likely to suffer the least disadvantage
in that respect to their outward affairs.
What is pointed out by the offerings under the law,
being of the first year and without blemish?
And what is meant by offering the first fruits to the Lord?
Oh, how ungratefully do some act, as if any thing, or any time,
was good enough to offer unto Him!
I have observed in some places, though I can with comfort say, it was but in very few,
that they hold their Monthly and Quarterly Meetings in the afternoon;
and having thus limited themselves for time,
they seem as if they could spare but little of it in silent waiting,
to seek the Lord`'s blessed assistance,
and to look in faith for the pouring forth of the
holy Spirit promised in this Gospel day.

But I have observed them to enter on the business as they have come out of the world;
moving, in these weighty affairs, in man`'s natural abilities, whereby darkness reigns,
and the glorious light and life of Truth is obscured, and they come to be so benighted,
as to see no necessity to wait for it.
Thus all living zeal and every qualification for carrying on the Lord`'s work is lost,
and vain man thinks he can do without it.
I am well assured, by living experience,
as well as the practice Truth hath led Friends into in all places, a few excepted,
that it is the indispensable duty of our Society everywhere, to dedicate a week-day,
viz.,
a day when they are not debarred by the laws of the land to follow their outward business,
for transacting the weighty affairs of discipline and good order;
and to meet in the forepart thereof, men and women together,
then and there to wait upon the Lord, for the virtue of his holy Spirit;
and when they have thus waited a proper time,
then the men and women in their separate apartments,
with awful fear and a weighty care upon all their minds as in the presence of the Lord,
to proceed in their respective parts of this great work; which is the Lord`'s,
and cannot possibly be profitably done but by his immediate assistance.
This I leave upon record, as my well grounded testimony for God and his church.

I attended what they called their Monthly Meeting,
and on looking a little into the state of things, I found them much out of order,
and did not wonder at it, as I found they had dropped their week-day meeting.
At my request the women were desired to be present,
when much labour was bestowed for their help,
particularly to revive their week-day meeting; they agreed to endeavour for it,
and made a minute for that purpose in their Monthly Meeting book.
But alas! the life of religion seemed to be almost lost;
their state being confused and disorderly,
by mixed marriages and the neglect of discipline.
They appeared part one thing and part another; and,
if this was so offensive to God and so distressing to his people under the old covenant,
how can it be less so now?
But when people`'s views are carnal and selfish, they regard none of these things,
although the hazard is so infinitely great.
I had a small poor meeting at Castle-shane next day, where, to my great sorrow and pain,
I could not perceive any alive in religion.
Some labour in testimony was bestowed,
but to outward appearance it took very little effect.

I went to Thomas Greer`'s at Dungannon,
and on the 23rd had a large meeting at Charlemount,
where I was concerned to declare Truth, as utterance was given,
in a very close searching manner; not without sharp rebukes to such, who,
by defiling liberties,
had brought an ill savour and caused the way of Truth to be evil spoken of.
My mind was comfortably relieved after the service of this meeting was over,
being discharged of a heavy load.
The next day I had a very painful and exercising meeting at Ballyhagan.
The appearance of the professors was in general plain;
but alas! with respect to the life of religion, they seemed in my view,
for the most part, like pictures or images.
Surely the blindness and stupidity must be exceedingly great,
if it be possible for people in that state,
to imagine or dream they are the people of God.
I was, through divine favour, enabled to clear myself of them, by a sharp,
searching and close testimony, in the discharge whereof I had peace.
The meeting was very large.

The 25th I went to the province meeting of ministers and elders, held in Lurgan.
My spirit was deeply affected therein,
with a sorrowful sense that some of the leaders of the people had caused them to err,
and by their love for, and eager pursuit after, worldly enjoyments,
had largely contributed to obscure the way of the Lord,
so that the serious inquirers after the paths which led to peace, could not,
by observing their steps, find them out.
Oh, what a deplorable state this is!
I was favoured with living authority and clearness,
to discharge my mind towards such with great plainness,
which seemed to fasten closely on some: may they profit thereby,
and the end will be answered.
The province meeting was held next day, in which I had weighty service.
But alas! they are far gone, a few excepted, from the life and power of religion;
yet I found much good-will extended for their recovery and help,
and the heavenly power wonderfully opened my mouth and enlarged my heart,
to deliver suitable doctrine to their conditions, in which I had peace,
and many were affected and reached therewith.

Oh, how unwilling is the Lord to give up the offspring of his people!
I attended Lurgan meeting on first-day, the 26th, which,
through the divine manifestations of heavenly power,
was indeed a very awakening time to the unfaithful,
as well as of sweet refreshment to the few mourners in and for Zion.
I went after meeting to Lisburn,
and had a very open satisfactory opportunity there next day.
The testimony of Truth went forth in an affecting manner, tendering many hearts,
and it was a time of humbling encouragement to the honest-hearted.
The next day I had a very poor afflicting meeting at Hillsborough,
things being very low there.
The 30th I had a very large meeting at Ballinderry, in which I had thorough service.
The testimony of Truth went forth with much clearness and demonstration, being,
through divine favour, an eminent time, and many states were spoken closely to,
I hope to their advantage.
On fifth-day, the 1st of the fifth month, I had a meeting at Moyallen,
which was a painful cloudy time.
The testimony delivered was very searching, in order to stir up careless professors,
some of whom seemed, in a great measure, to have deserted the cause of religion,
and to have embraced this present world.

The 2nd I set out for Dublin, in order first to attend the province meeting for Leinster,
and then the Half-year`'s Meeting, both to be held there in one week.
I lodged that night at an inn in Dunlere, and next day got to Dublin.
On first-day, the 4th of the fifth month, I went to Meath-street in the morning,
where Truth greatly favoured in opening doctrine and counsel,
to the edification and comfort of many,
as well as in caution and warning to the disobedient and lukewarm professors.
In the afternoon at Sycamore-alley, we had a laborious painful time of silence, to which,
perhaps,
the expectation and desire of the people after words might not a little contribute.
On second-day, the 5th, was held their province meeting of ministers and elders.
It was a painful heavy time, but through divine favour,
some relief was administered towards the conclusion.
Next day was held the Quarterly Meeting for Leinster province,
in which I had open thorough service,
both in ministry and also in relation to good order and the discipline of the church.

On fourth-day the 8th of the fifth month, at the third hour in the afternoon,
began the national meeting of ministers and elders,
wherein the Lord was pleased to open profitable instruction,
to the comfort and edification of many.
Next day we had a meeting for worship in the morning,
wherein divine favour was plentifully extended, and the doctrine of Truth largely opened.
The meeting of business for the whole nation was held in the afternoon,
in which a degree of divine wisdom and strength was administered for our help.
On sixth-day morning was held a large meeting for worship at Sycamore-alley,
which was overshadowed with heavenly goodness,
and the testimony of Truth went forth freely, being much exalted.
In the afternoon the affairs of the church continued; and on seventh-day,
both the fore and afternoon were employed in them.
Divine goodness was comfortably near, for the help and recovery of a declined people,
stirring up the hearts of some, as he did the heart of Nehemiah formerly,
to seek the prosperity and welfare of the city of God.

I found a considerable alteration for the better,
by some revival and growth in the life of religion, amongst Friends in this nation.
That painful flatness and insensibility,
under a sense of which I formerly mourned sorely,
did not appear so generally to overspread the churches now, as then;
though in some places it was rather worse than better; yet I think, upon the whole,
things were mended in a religious sense.
The Lord in merciful kindness to them,
not only sent divers substantial instruments from distant parts to visit them; but also,
as before noted, moved upon the hearts of some amongst themselves,
to labour for restoring ancient comeliness,
by visiting their Monthly and Quarterly or province meetings,
for the promotion of good order and discipline; the reviving whereof,
in the wisdom which is from above,
proves an effectual means to increase and exalt the virtue and power of true religion.
A concern of this nature came weightily upon the national meeting at this time,
in the feeling whereof, under the holy influence of heavenly light,
Friends nominated a certain number to visit the Monthly Meetings in Leinster province.

I cannot well omit making a remark upon appointments, as I apprehend some have,
by the subtlety of Satan, been prevailed upon to reject them:
I believe all such do not design an injury to the Society; but he who deceives them,
intends thereby to obstruct the great and necessary
engagement of maintaining good order and discipline.
I ardently desire, that all who undertake to move and act in the church of God,
may be well informed what is the spring of action to them, and moves them therein.
If it be the spirit of God, they dare do nothing against the Truth,
but all in their power in order to promote it, that being their greatest delight.
But if it be self, it will seek its own honour and be very fond of victory,
and be disgusted when it cannot rule and carry matters in its own way.
On first-day, the 11th, many country Friends being yet in the city, we had,
it was thought, the largest meeting known at such a time for many years,
and by the blessed dominion of the everlasting Truth, it was a time of great favour.
The sincere-hearted were sweetly comforted, the disobedient warned,
and in the free powerful opening of Gospel life,
much doctrine and counsel were administered,
tending to beget faith in the eternal power of God.
The afternoon meeting was, for the most part, held in awful solemn silence.

On second-day was held a meeting of ministers and elders,
wherein divine goodness was pleased to open the free Fountain of life and healing virtue;
in whom we had to rejoice with joy unspeakable and full of glory.
His name was greatly exalted, magnified and adored amongst us.
After this meeting, apprehending myself quite clear of any further service at this time,
having through infinite kindness, been much favoured and enlarged therein,
through most parts of the nation,
but more especially at the late great meetings in Dublin,
I was very earnest in my mind to embark for England,
and so to leave things whilst fresh and well;
always having an aversion to loitering amongst Friends until they flatten.
But though there were several ships ready to sail for Parkgate,
I could not get away till after their week-day meeting on third-day, in Meathstreet;
to which meeting, I must say, I went with considerable reluctance,
for the reason above mentioned.
But we are very short sighted creatures;
for notwithstanding my unwillingness to be at it, this meeting proved a memorable time:
many country Friends being still in the city,
it was a solemn taking leave one of another,
in the precious flowing of the holy unity of the one Spirit.

Next day about noon,
in company with seven Friends intending for the Yearly Meeting in London,
I embarked on board the Kildare, captain M`'Culloch,
and landed at Parkgate about ten o`'clock next morning,
where we hired horses and proceeded towards London.
When we had travelled as far as Coventry, apprehending I might reach home,
so as to have three whole days with my family before the Yearly Meeting;
and it being but about twenty miles more riding, I concluded to do so;
my kind friend Robert Leckey agreeing to bear me company.
This being on seventh-day, the 17th, we got to Northampton that night,
and stayed their meeting next day, which was small,
and the life of religion appeared to me very low there.
The meeting was held in silence.
I got home on third-day, the 20th of the fifth month, 1760,
finding my dear wife and family in good health,
to our mutual joy and thankfulness to the Lord, who leads out, carries through,
and brings home again in peace, those who trust in him.
Blessed and praised be his worthy name forever!
I was indeed largely favoured in the before mentioned journey, of which,
for my encouragement to give up in humble confidence in the Lord`'s power,
I had a clear sight before I entered upon it, which I esteemed a high favour.
I was from home about twelve weeks and three days,
travelled in that time upwards of one thousand three hundred miles,
and was at about fifty-eight meetings.

Our friend Robert Leckey, myself and wife, went to the Yearly Meeting in London,
which began on seventh-day the 24th of the fifth month, for ministers and elders.
These meetings I hope will be of great service throughout the Society in these nations;
as inquiries are there made, by calling for answers from the several parts,
to certain queries agreed on,
relating to the conduct of Friends in the stations above-mentioned;
and advice administered as occasion may require.
Common reason will inform us, that when the main pillars give way,
the building must inevitably fall.
It is therefore prudent to take due care concerning them.
An eminent servant of the Lord wisely observed to this effect,
viz. That there never was an apostasy from the life and purity of religion,
until the ministers and elders gave way.
How important then are their stations, and what great need have they themselves,
and likewise the church, carefully to observe whether or no they stand upright,
seeing so much depends thereon.
On second-day following was opened the Yearly Meeting of business, which continued,
by adjournments, most or all the week; being a solemn weighty meeting,
of very great importance to the Society: careful inquiries are there made,
into the state thereof, in order to communicate such help,
as in the wisdom of Truth may appear proper and necessary.

I am free to give a short account here,
of the beginning of a very important affair which came before this Yearly Meeting,
as I shall have occasion hereafter to make some mention of its progress and success,
viz. A nomination of Friends,
to visit all the Monthly and Quarterly Meetings of Friends in this nation,
for their help, in promoting good order and discipline in the several parts.
Upon reading the answers to the usual queries from the several Quarterly Meetings,
great slackness and unfaithfulness appeared in divers places,
in some weighty branches of our Christian testimony,
notwithstanding the great and earnest endeavours
made by the Yearly Meeting from year to year,
by way of advice, caution and counsel.
The sense of this deeply affected some minds, who, in humble prostration before the Lord,
were ready to say, What wilt thou do for thy great name`'s sake,
to heal the backslidings of thy people?

A Friend under this exercise,
and in an awful sense of the divine presence which was near, stood up,
and taking notice of the apparent defection, remarked,
that as all the means hitherto used by the truly
Christian labour of preceding Yearly Meetings,
had not proved sufficient to stop the declension, which seemed rather to increase;
it now behooved that meeting,
deeply and weightily to consider what remained yet
to be done for the help and recovery of the Society,
to its ancient purity and comely order, or to that import.
This seemed to open the way for our worthy friend Joseph White of Pennsylvania,
who was then upon a religious visit in this nation,
to lay before the meeting what he said had been much
upon his mind most of the time since he landed,
and which seemed to increase in clearness and weight as the Yearly Meeting drew near;
and that he now found it was the proper time to deliver the same, viz.

That the Yearly Meeting should appoint a suitable number of solid, weighty,
judicious Friends, to visit all the Quarterly and Monthly Meetings in England,
to use their Christian endeavours, in the love of God,
for the promotion and revival of wholesome discipline,
and the comely order of the Gospel in the churches.
Great was the solemnity which covered the meeting,
during its deliberation on this very important affair.
The weight of the heavenly power was so exceedingly awful,
that it was very hard for any contrary spirits to appear;
yet objections against appointments for such services were advanced by some.
It was therefore proposed,
that Friends who found a concern on their minds to engage in the undertaking,
would give in their names.
The Lord`'s heavenly power being at work, like leaven, in the meeting,
a wonderful time of divine favour it was,
wherein about fifty-eight offered themselves accordingly.

Before I insert any account of the progress made in the above-mentioned service,
I have to take notice of a journey into the West of England,
in company with my friend Richard Brewster,
which I entered upon the 9th of the ninth month this year.
We went to Plaistow Monthly Meeting, where, unexpectedly, I had some pretty close service.
Next day, being joined at London by my esteemed friend Thomas Corbyn,
we proceeded on our way,
in order to attend the Circular Yearly Meeting for the western counties,
to be held at Wotton-under-edge, in Gloucestershire, which began on first-day,
the 14th of the ninth month, and ended on the third-day following.
Many of our Society from divers parts, attended, and a vast concourse of other people,
who generally behaved in a becoming manner,
carrying themselves very respectfully to Friends, and I hope the meeting was in the main,
serviceable; yet the heavenly power was not exalted to so high a degree, as those,
whose life and all is in it, could have desired.

It is that alone which is able to open peoples`' way rightly to our Zion;
not the finest and most consistent set of principles, curiously set forth and displayed,
without it.
All ministers should therefore upon all occasions,
eye that divine power as the thing we stand in need of,
otherwise the work will be marred.
We went from Wotton to Ann Young`'s at Earthcott,
and had a close searching meeting at Thornbury on fourth-day.
Things were very low there as to the life of religion.
We had a meeting next day at Earthcott,
wherein the testimony of Truth went forth very sharply against dry, formal,
and disorderly professors.
Our friend Isaac Sharpless, was at this meeting.
We attended the meeting at Bristol on sixth-day,
where Truth and its testimony were exalted over wrong things; and unfaithful,
disorderly walkers, were warned in the dominion and authority thereof, and the humble,
sincere traveller Zionward, comforted: it being through the divine blessing,
a good profitable time.
In the afternoon was held their meeting of ministers and elders,
wherein we had some very close work with a troublesome impostor,
who had given Friends there much uneasiness,
by his unsavoury and unsanctified public appearances.

The judgment of Truth was set over him, though he was very unwilling to submit thereto.
On first-day, the 21st, we attended three meetings there;
and notwithstanding the mournful declension so visible amongst Friends in that city,
yet the Lord graciously appeared for their help and recovery;
opening the doctrine of truth in a clear and plentiful manner to their several states,
with which many appeared pretty much affected.
And although there is yet much cause to lament their degeneracy,
yet I hope and believe there has been a considerable reviving in the best sense,
amongst some of them, especially the youth, since I was there before.
On second-day morning we had a thorough arousing meeting at Portshead in Somersetshire,
and in the afternoon a large meeting at Clareham;
the latter was exceedingly cloudy and afflicting for a considerable time;
but at length it pleased the Lord to arise and to give the word,
with understanding to divide the same in a plain, powerful manner,
and a very awakening time it was.
It went forth very sharply against indifferency and empty formality,
which greatly depressed the true Seed in that meeting: I hope it was a profitable time.

On third-day we had a very open, serviceable meeting at Sidcot;
the testimony of Truth flowed forth freely to the several states of those present.
After meeting we went to Bridgewater.
On fourth-day was held the Quarterly Meeting for Somerset.
In the forenoon we had a large meeting for worship, both of Friends and others;
some previous endeavours, I understood had been used, to invite the neighbours,
which I think was not well judged, neither should I have encouraged it at such a time,
had I been consulted.
The leadings and pointings of Truth should be always minded,
in calling or inviting people of other persuasions to our meetings;
for I have sometimes thought them a bar in the way
of dealing suitably with professors of the truth,
and therefore it is my judgment, they should not be called to our meetings,
unless those who travel in the service of Truth signify their desire to have it so,
to those who have the care of appointing meetings.
The power of the Gospel, opening and exalting the doctrine thereof,
was livingly and comfortably extended in that meeting; yet I apprehended,
other people were then rather in the way of our handling
the state of some professors there,
in a manner Truth would have led to, had Friends been by themselves.
The meeting of business followed, and was adjourned till the afternoon,
wherein Truth appeared to the help of those who know their sufficiency to be of God.
We who were strangers, had good service therein.

Next morning we parted with my friend Thomas Corbyn, who returned home,
and my companion and I proceeded on our journey.
We had a meeting at Taunton on fifth-day morning, and at Milverton in the evening.
At both which I had close service,
tending to stir Friends up to more lively zeal and religious concern of mind.
On sixth-day we had a painful laborious meeting at Wellington.
The testimony of Truth went forth very close and sharp against those who,
under the profession thereof, bow down to the world and its perishing enjoyments.
It appeared to me, the life of religion was much depressed in that meeting.
On seventh-day we had a meeting at Collumpton,
which was cloudy and trying most of the time; yet towards the conclusion,
Truth obtained the victory,
and considerable dominion over things of a contrary nature to itself.
We went after meeting to Exeter, and on first-day, the 28th, were at two meetings there;
and although their number appeared considerable,
yet that holy living sense and weight of divine virtue,
which is the crown and diadem of all our religious assemblies, was very low,
and little felt, through the slackness and lukewarmness of professors, consequently,
not much could be done towards exalting Truth`'s testimony amongst them.

On second-day we went to Bovey, and had a poor, laborious meeting, there being very few,
if any, that I could find, truly alive in religion.
When that is felt to be the state of any meeting,
oh! what pain and anxiety cover the hearts of poor
travellers in the service of the Gospel!
The next day we went to King`'s-bridge,
and on fourth and fifth-days attended the Quarterly Meeting for Devonshire held there;
wherein the great Master of our assemblies graciously condescended to their very low,
weak and unskilful state, opening doctrine and counsel for their help;
furnishing with close admonition to such in high stations,
who indulged either themselves or their families in undue liberties,
tending to lay waste a people whom the Lord, by an out-stretched arm,
gathered out of the fashions and changeable customs of a vain world, to himself,
the unchangeable Fountain of good.

On sixth and seventh-days we travelled to Penryn in Cornwall, and had two open,
precious meetings at Falmouth on first-day, the 5th of tenth month.
On second-day we went to Penzance, where, on third-day,
was held the Quarterly Meeting for Cornwall.
Truth wonderfully appeared in that meeting, considering their low,
weak and unfaithful state.
The testimony thereof was exalted,
and went forth with clearness and good demonstration to their states,
and the meeting appeared to be much affected therewith.
There was also something very encouraging to the honest-hearted;
and I hope it was a time of awakening and profit to many.
In the evening we had what was called a select meeting, for ministers and elders;
but it was so far from select, that the service seemed to be wholly obstructed,
by the crowding in of many who were not fit to be admitted into such meetings;
where ministers and elders may, and often are concerned to use such freedom, in advice,
caution and counsel,
as would be altogether unsuitable for those who are raw and inexperienced to be privy to,
as they might be likely to make improper use of it.
I laid before Friends the hurt and disadvantage of such a promiscuous gathering,
upon that occasion,
and advised them to be careful not to lay waste the
service of those meetings for the future;
for I found myself much straitened, as I could not, with prudence,
deliver what seemed to appear before the view of my mind at that time,
for the reason above-mentioned.

On fourth-day, the concluding meeting was held at Market-Jew,
wherein Truth and the testimony thereof were comfortably exalted.
But, alas! sorrowful is the declension of the Society in those parts,
both as to number and a holy living zeal;
yet merciful goodness was largely and affectingly extended for their help and recovery.
From thence we took the following meetings in our return to Plymouth, viz., Auslle,
Liskard and Germains, where I found the life of religion mournfully low and depressed;
yet the Lord was pleased to open the way to some, I hope,
profitable endeavours for their revival, in the exercise whereof I had peace.
I attended Plymouth meetings on first-day, the 12th. This was a very painful,
laborious time,
as but very little of the life and holy efficacy of true religion had place;
most under our profession having made large advances towards the world,
and but few being endued with Christian courage to
make a stand against prevailing undue liberties.
The state of a meeting being thus, oh, how doth death,
darkness and insensibility gain the ascendency!

My spirit was deeply afflicted at that place, yet I was through divine favour,
enabled to clear myself of the service required; whereby I had some relief.
We travelled from thence directly to Exeter,
and on third-day attended a meeting appointed for the accomplishment of a marriage.
Truth mercifully opened the way to some satisfaction,
in the discharge of the service required, to the advantage of the meeting.
From thence we went to Chard, and had a very small poor meeting on fifth-day morning,
and were deeply affected with their low weak state.
I had a pretty thorough serviceable meeting in the afternoon, at Ilminster;
though I felt much pain of mind there also,
in a sense of that which hath almost laid our Society waste in some,
and exceedingly hurt it in most places, viz., the inordinate love of earthly things,
and resting satisfied in a profession of religion only.

We took the following meetings in our way to Bath, viz., Yeovil, Long-Sutton, Grinton,
Shipton-Mallet, Froome, Hallowtrow and Belton; where things,
as to the life and true sense of religion, appear but low in general;
yet merciful kindness was extended, in a lively and powerful manner,
both immediately and instrumentally, in order to quicken,
restore and turn again backsliding Israel.
On first-day, the 26th of the tenth month, we attended two meetings at Bath,
which were painful and very afflicting, as the grandeur, friendship,
and vain customs of this world, seem to have almost erased from most of their minds,
the desire of seeking happiness in another:
yet merciful condescension was remarkably extended,
in some earnest and awakening endeavours, to bring them to a right sense of things.
On second-day morning we set our faces homewards, where,
to my great satisfaction I arrived on fourth-day in the evening,
and found my dear wife and family well;
having been out on this journey seven weeks and two days,
in which time we travelled upwards of eight hundred miles,
and were at about fifty-one meetings.
