[.style-blurb, short="Testimony from Witham Monthly Meeting"]
== A Testimony From the Monthly Meeting of Witham, in Essex, Concerning John Griffith, Deceased.

The character of this our well beloved Friend being so generally known,
we esteem it unnecessary to extend our testimony concerning him,
further than the time of his arrival and residence amongst us.
In the year 1747, being a member of the Monthly Meeting of Darby, Chester county,
in Pennsylvania, he was concerned to visit the churches in Great Britain and Ireland.
During this engagement his mind was impressed with
an apprehension of duty to settle in this nation;
the importance whereof was the occasion of earnest supplication to the Lord,
that he might be rightly directed.
After deliberate consideration, finding the expediency of his removal clearly confirmed,
he returned to America, and having settled his affairs,
with the concurrence of his brethren he removed to England;
and entering into marriage covenant with Frances Wyatt, of Chelmsford,
he became a member of this meeting; wherein, we trust,
the fruits of his labour afford substantial evidence of able talents faithfully applied.
Few were his companions zealously concerned for the restoration of good order,
which rendered the task more arduous; yet in regard to the exercise of the discipline,
compared with the state in which he found it, considerable regulation has been effected.

His gift was eminently adapted to service: in ministry sound, powerful and clear;
in discipline, diligent and judicious;
searching impartially into the causes by which the circulation of life was obstructed.
This care, disturbing the false rest of lukewarm professors, at times,
excited their displeasure; yet being mercifully preserved from the spots of the world,
and endued with authority to speak feelingly to the states of his hearers,
in him that proverb was remarkably verified, "`When a man`'s ways please the Lord,
he maketh even his enemies to be at peace with him.`"
In doubtful cases, he manifested an exemplary tenderness and forbearance,
particularly respecting such as appeared forward in launching
into religious engagements above their qualification,
being disposed to afford full opportunity for trial; observing, upon these occasions,
that it would be most acceptable,
deluded persons should perceive their error by its effects.
But when thoroughly convinced of unsoundness,
he faithfully discharged the duty of an elder, in the application of plain dealing,
which indeed, was his peculiar talent; yet so tempered with discretion,
both in ministry and discipline,
that we believe few have filled these important stations with more general approbation:
nor were his amiable qualities confined to the notice of our Society,
having a large share in the esteem of others, especially those of his neighbourhood.

Much of his time was devoted to public service;
and a foretaste of the reward promised to them who persevere in well doing,
proved his substantial support through a long course of painful infirmity,
being affected with an asthma about fifteen years.
At length the disorder producing a dropsy, indicated that his dissolution was near;
yet in this condition he continued about eight months; during which season of deep trial,
the fruits of faithfulness were conspicuous, being at intervals,
favoured with strength to speak intelligibly.
His mind appeared to be centered in sweet consolation, which, in great measure,
overcame the sense of bodily pain, though evidently hard to bear.
His mental faculties seemed rather enlarged in quickness of sensibility,
having frequently to express thankfulness and admiration,
that during this sharp probation,
Infinite Goodness had not suffered his mind to be clouded,
but continued to lift up the light of his countenance upon him;
under the influence whereof,
his spirit was engaged to encourage those present to faithfulness,
the happy effect of which he experienced at that awful period.
Divers who assisted during his illness, have declared that his patience in suffering,
kind acknowledgment of their care and instructive admonitions,
so far alleviated their anxiety occasioned by the sharpness of his conflict,
that they esteemed it a favour to attend him.
After a laborious winter, gradually declining,
he quietly departed this life the 17th of the sixth month, 1776,
and was interred in Friends`' burial ground at Chelmsford, the 23rd of the same;
aged about sixty-three years; a minister about forty-two years.

Signed in and on behalf of Witham Monthly Meeting, held at Chelmsford,
the 28th of the tenth month, 1776, by twenty-two Friends.

The annexed testimony being read in our Quarterly Meeting, held at Coggeshall,
the 11th of the third month, 1777, was approved and signed in and on behalf thereof, by

[.signed-section-signature]
Joseph Docwra, Clerk.
